### ISSUE TITLE
Missing some Dominican neumes

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#1]
See Salve Regina, for instance...
![salve-op](https://cloud.githubusercontent.com/assets/213117/3530702/3e55bfd6-07a7-11e4-9d56-114f022d145a.png)

**Comment by henryso** [comment]
I'll admit to being confused by this discussion.  Which shapes, exactly are missing?  We have the epiphohus, so is it just the "u"-shaped note over "ten" and the inverted "u"-shaped noted over "Vir" that are missing?

**Comment by eroux** [comment]
Maybe there should be an alternative epiphonus shape that looks more like this one, but I think the new thing is the weird neume above "ten" (we don't see the text because of the red circle)... At first I thought it was like an alternative porrectus deminutus but without the first and last note... but can these bars above the note get higher than this or are they always at the same height?

**Comment by henryso** [comment]
What I'd like to understand is how much variety there is in the new shape.  In addition to your question about height, can there be a line only on one side?  A line going up and a line going down?  I don't have any Dominican liturgical books, so I cannot see for myself.  Are there any ones available on the Internet that I can look through?

**Comment by eroux** [comment]
There are somes PDF sources in [this comment](https://github.com/gregorio-project/gregorio/issues/1#issuecomment-52437198) and [on gregobase](http://gregobase.selapa.net/scores.php) (in the *by source* section).

**Comment by henryso** [comment]
From what I've been reading, it seems that the only liquescents Dominican chant uses are the epiphonus, the cephalicus, the epiphonus-line neume without the final note, and the cephalicus-like neume without the final note.  Should the latter two figures without the final notes just be alternate glyphs for the virga (reversa) auctus ascendens -- which would needed to be added -- and virga (reversa) auctus descendens -- which already exists? If this is the case, the notation would be `gV>` and `gV<`.  If the preference is to add these neumes as regular figures (as opposed to alternates), then how about `g&>` and `g&<` for the epiphonus-line and cephalicus-like figures, respectively?

**Comment by eroux** [comment]
But doesn't the bar before the absent note vary in lenght?

**Comment by henryso** [comment]
As far as I can tell, that line height and whether to vary it within a score is a stylistic decision.  Does anyone know for sure?

**Comment by henryso** [comment]
This really does feel like the (more ancient) Dominican version of the (more modern) Solesmes augmented and diminished liquescents, as the figure can be tacked onto a multi-note neume or can stand by itself, with or without a leading stem, and since Dominican chant doesn't have liquescents besides the deminutus, we already have a language for this in gabc (except that we currently lack augmented punctum and virga glyphs).

This paragraph (from https://github.com/gregorio-project/gregorio/issues/1#issuecomment-52437198) ...

> Pretty much every edition makes the ‘small line’ a single, constant length throughout. Rare exceptions are the neumes in Officium Hebdomadae Sanctae from both Fernandez, 1965 (p. 17, l. 2), and Paredes, 1925 (p. 38, l. 1). It’s only Cormier’s Processonarium that differentiates these lengths on a regular basis. It also appears that Cormier’s is the only edition that adjusts the small line’s length when it touches the staff line, the way it’s usually done with the stem of virga.

... is what leads me to believe that the line height before the absent note is a stylistic (i.e., a house style) decision.  Do we want to be more Cormier-like, or like "pretty much every edition", or like the other exceptional cases?

My only concern is that we would have to draw as many glyphs as have augmented and diminished liquescents, and that's a considerable number of glyphs.

**Comment by eroux** [comment]
That's very interesting, thanks a lot for your research! I'm no gregorianist, so : when you say augmented and diminished liquescents, do you mean what is called *auctus descendens* and *auctus ascendens* in the code? If so, I think a new font could make sense here... Or maybe the alternate glyph mechanism could be extended to alternate fonts? Also, if the same syntax is used i gabc, this means that one cannot simply typeset normal auctus ascendens neumes and dominican auctus ascendens neumes... Well, I don't think it's a strong limitation, but it's just something we should be aware of...

**Comment by henryso** [comment]
I actually misspoke.  I should have said (and I really did *mean*) ascending and descending augmented liquescents, and by that, I do mean auctus ascendens and descendens.

The alternative mechanism already supports alternate fonts and wildcards, giving you everything you need to implement this using that system (except for the ascending punctum and virga, which would need to be added).

I agree about the limitation, but that only extends to one score.  You can switch it out between scores.

**Comment by eroux** [comment]
Well, it might be good to have @grzegorzrolek and @celide 's opinions on this, but otherwise this seems fine to me...

**Comment by grzegorzrolek** [comment]
I don’t have the time at the moment to try and find any actual examples, but as far as the stem lengths and the various 'note-head’ shapes are concerned, my intuition is that the editors of the Dominican editions simply followed what’s in the original manuscripts more closely than the more ‘mainstream’ Solesmes — and those manuscripts could obviously vary with different kinds of notational minutia. It would explain the apparent struggle of the editors over representing the unusual neumes with the pieces of type that were available. See, for example, the ‘rotated’ virga for the neume over _osténde_ in _Salve Regina_, or similarly misused punctum in the same place in Gillet’s Antiphonarium. For what it’s worth, and to add to the argument further, in those few academic titles on the plainchant that I’ve had the opportunity to read, I can’t recall any author ever discussing the length of various liquescent shapes, at least not in any quantitative terms.

Now whether those stemmed shapes indicate some distinct set of liquescent neumes, aside from what you call _puncta_ or _virgae auctae_, and the usual _epiphonus_ and _cephalicus_ — again, I can’t recall any author making such a distinction. I’m basically with Henry in that these are simply _aucta_ neumes.

For those interested, in the notation of the early polyphony of the 13th century, which used the square notation of the contemporary plainchant manuscripts, there’s indeed a distinctive feature known as _plica_, which looks exactly like some of the neumes in question. It’s considered to have more of a rhythmic interpretation, though, and no resemblance to the liquescence as known from plainchant. I’ve once read David Hiley arguing in his article [‘The Plica and Liquescence’](http://epub.uni-regensburg.de/25516/) that the plica as notated in early polyphony indeed carried at least some of the performance details of the liquescents, but this still doesn’t change anything on the plainchant side. In a somewhat different note, Timothy J. McGee in [‘“Ornamental” Neumes and Early Notation’](http://scholarship.claremont.edu/ppr/vol9/iss1/5/), an equally worthy article, surprisingly makes use of the term ‘plica’ for all the single-note liquescents.

**Comment by henryso** [comment]
(a technical question unrelated to the immediately previous comment:)

It's about the same amount of work to generate a complete font (with all glyphs) as it is to create an extension font (with only the changed glyphs).  Either could be used with the substitution mechanism, but the complete font could be enabled with a single statement (which, granted, could be true of the extension font as well, with a supplied macro), at the expense of duplicate glyphs and a larger download/installed size.  Anyone have a preference?

**Comment by henryso** [comment]
How does this look?
![image](https://cloud.githubusercontent.com/assets/421318/8586622/ca511996-25be-11e5-9b9f-cb8a4b1c6e6f.png)

**Comment by henryso** [comment]
First cut work-in-progress implementation is at #542, pending some more testing and/or comments.  Source for the *Salve Regina* above is at https://gist.github.com/henryso/b2f85e223a2f4b9fc946.

**Comment by henryso** [comment]
If there are issues with the implementation, please open a new issue since this one has become rather loaded.

**Comment by eroux** [comment]
@olivierberten what's the reference of the image you posted in the intial description?

**Comment by henryso** [comment]
http://gregobase.selapa.net/chant.php?id=4577

Completorium O.P. (Suarez), Dominican, 1949, p. 119

**Comment by eroux** [comment]
Thanks a lot!
