### ISSUE TITLE
counting clefs in additional bottom/top spaces

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1007]
Working on #883, I realize it never occured to me that clefs on the first and fourth line should have the same effect on additional bottom/top space as `c` and `k`. Not an emergency though...

**Comment by eroux** [comment]
Oh, virgula and divisio minima should be counted like that too, this would allow much more precise settings

**Comment by henryso** [comment]
Virgula and divisio minima are *on* the top line, so shouldn't they count as a punctum on the top line, on `j` rather than `k` (for a 4-line staff)?  If that's the case, they shouldn't really change the additional top space, correct?

**Comment by eroux** [comment]
absolutely yes

**Comment by henryso** [comment]
@eroux Can you give me some samples where a clef on line 1 or 4 should alter something, so that I can see if what I am doing is having any real effect?

**Comment by eroux** [comment]
I think you can take an example similar to the one in https://github.com/gregorio-project/gregorio/issues/960

**Comment by henryso** [comment]
Thanks.  That opens one question (in my head).  Does the clef at the beginning of the line affect these spaces or only clefs within a line?

**Comment by eroux** [comment]
Hmmm, I don't think a clef at the beginning of line should be treated differently...
