### ISSUE TITLE
Version changes and score compiling.

### ISSUE THREAD

**Issue by eschwab** [gregorio-project/gregorio#101]
Since adopting SemVer for gregorio, the user should only be required to recompile scores if the major version changes `x+1.y.z`. All minor and patch releases must be backwards compatible and thus all scores with version `x.y.z` must work when gregoriotex is in version `x.y+1.z`. The user can choose to recompile if there are new features (in `gregorio-write.c`) he wishes to use.

Current behavior is that a score must be recompiled for each version change (major, minor, or patch).

**Comment by eschwab** [comment]
If a user is using the autocompile feature I am inclined to leave the lua script as it is, which is to compile a new gtex file if its version does not match the gregorio version. A new gtex file for any version change: `x+1.y.z` `x.y+1.z` and `x.y.z+1`. My thought is that a user running `autocompile` wants the best version possible. If there are bug fixes in `gregorio-write.c`. hence `x.y.z+1`, no manual intervention will be necessary to apply the fix to the gtex file.

What needs to change is `\gregoriotexapiversion` which is the final version test. This effects users running the default behavior of gregoriotex, `nevercompile`.

Thoughts?

**Comment by eroux** [comment]
If I understand correctly, you would make `nevercompile` output an error only if major version is different, and let `autocompile` recompile at each version change? If so, why not

**Comment by eschwab** [comment]
Yes, that is a simpler way of saying it.

**Comment by eschwab** [comment]
Fixed by #107
