### ISSUE TITLE
Nabc ~ handling broken

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#1015]
Just installed 4.1 and noticed that tilde handling is broken.
...
nabc-lines: 1;
...
Test(g|po~)
displays normal porrectus like Test(g|po) rather than the liquescent diminutive one, something doesn't change the catcode to parse it properly.  The *.gtex file contains correct stuff.

**Comment by eroux** [comment]
Will you have time to look at this or do you need someone else to do it?

**Comment by jakubjelinek** [comment]
I'm afraid I'll need help, this are of TeX I'm constantly struggling with.
Even using
\GreNABCChar{po~}%
somewhere after including a score doesn't show the right glyph.
If I change:
`
--- gregoriotex-nabc.tex	2016-03-05 15:46:56.975569892 +0100
+++ gregoriotex-nabc.tex	2016-03-05 16:49:44.000000000 +0100
@@ -37,14 +37,26 @@
   \gre@nabcfontloadedtrue%
 }
 
-\newcommand{\grenabccharno}[3]{{\directlua{
-  tex.sprint(gregoriotex.parse_nabc("\luatexluaescapestring{#1}", "\luatexluaescapestring{#2}", \luatexluaescapestring{#3}))
-}}}
+\def\grenabccharno{
+  \begingroup %
+    \catcode`\~=12{}%
+    \catcode`\@=11{}%
+    \grenabccharnoX%
+}
 
-\def\GreNABCChar#1{%
+\def\grenabccharnoX#1#2#3{
+    \directlua{tex.sprint(gregoriotex.parse_nabc("\luatexluaescapestring{#1}", "\luatexluaescapestring{#2}", \luatexluaescapestring{#3}))}
+  \endgroup %
+}
+
+\def\GreNABCChar{%
   \begingroup %
     \catcode`\~=12{}%
     \catcode`\@=11{}%
+    \GreNABCCharX%
+}
+
+\def\GreNABCCharX#1{%
     \gre@font@nabc %
     \gre@style@nabc %
     \grenabccharno{#1}{\gre@nabcfontname}{1}%
@@ -52,8 +64,16 @@
   \endgroup %
 }
 
-\def\GreNABCNeumes#1#2{%
-  \GreSetTextAboveLines{\GreNABCChar{#2}}%
+\def\GreNABCNeumes{%
+  \begingroup %
+    \catcode`\~=12{}%
+    \catcode`\@=11{}%
+    \GreNABCNeumesX%
+}
+
+\def\GreNABCNeumesX#1#2{%
+    \GreSetTextAboveLines{\GreNABCChar{#2}}%
+  \endgroup %
 }
 
 \newif\ifgre@nabcfontloaded%
`
(which I believe was roughly what worked at some point), then \GreNABCCHar{po~} already works, but \GreNABCNeumes{1}{po~} as part of the *.gtex still does not.  So I'm lost on where the catcode is needed and why.

**Comment by jakubjelinek** [comment]
And it would be nice to cover this case in the testsuite once it is fixed, so that it doesn't reappear, the ~ parsing in TeX is a nightmare.

**Comment by jakubjelinek** [comment]
Worst case, if nothing else works, we could let gregorio replace the ~ in nabc strings with some other character (one that doesn't appear elsewhere in the nabc grammar, and doesn't have so many catcode issues as ~), and adjust the nabc lua parser to treat ~ the same as the other character (i.e. replace all occurrences of the other character with ~ at the lua level before further parse_nabc processing).
Or use the catcode stuff, but store the argument into some lua variable earlier, and let parse_nabc just pop the argument ouf of that variable.
I've tried to replace the
\GreNABCNeumes{1}{po~}%
in the *.gtex file with
{
\catcode`\~=12{}%
\GreNABCNeumes{1}{po~}%
}
(that could be something gregorio could do if it detects ~ in nabc string), but unfortunately that doesn't work either.

**Comment by jakubjelinek** [comment]
[Untested hack](http://paste.fedoraproject.org/334533/45720154/)
Though of course, it would be cleaner if the ~ could be passed through the GregorioTeX macros instead.  BTW, in the GregorioNabcRef document it seems to work properly, but it uses the two macros approach and doesn't use ~ in the scores, just in other macros.

**Comment by eroux** [comment]
I think you hack is what would work best. I've reduced the catcode problem to:

```tex
\def\mydefmacro#1{#1}

\def\macrowithtild{%
    \begingroup\catcode`\~=11{}%
    \domacrowithtild%
}

\def\domacrowithtild#1{%
    #1\endgroup %
}

\macrowithtild{a~b}

\mydefmacro{\macrowithtild{a~b}}
\bye
```

(to be compiled with `luatex`, not `lualatex`)

The problem is that we're using the second form (which doesn't work): we use `\GreNABCNeumes` inside `\GreSyllable`. If you use `GreNABCNeumes` alone it will work but if you use it inside a macro it won't.

Can you test your hack?

**Comment by henryso** [comment]
Alternately, It might be possible to use a variation of the code I use for sending headers directly into Lua.  I esacpe

**Comment by eroux** [comment]
I'm not really sure about that... I think we would run into the exact same problem

**Comment by eroux** [comment]
oh sorry, you're right, I think that's even better indeed

**Comment by henryso** [comment]
Looking at the code, I also noticed that `gregoriotex-nabc.tex` uses `\newcommand`, and that should be changed to `\def`.

**Comment by eroux** [comment]
the nabc parser just needs to be able to parse `\xyz` strings where `x`, `y` and `z` are numbers

(you're right about the `\newcommand` that should be changed)

**Comment by jakubjelinek** [comment]
FYI, I've tested my patch and it seems to work.
As for \GreSyllable, would it be possible to break it up into the 2 macros (start + body) and change catcode in there?  Does anything in GreSyllable arguments need the normal TeX handling of ~?  If it is in some other GregorioTeX macro, would it work to change catcode of ~ in GreSyllable to make it normal character and then again in whatever macro might need the TeX handling of ~?

For the testsuite, we probably want:
potilde(c|po~) choralsign(e[cn:po~])
to cover both normal nabc and choral signs.

**Comment by henryso** [comment]
@eroux Lua will evaluate \xyz automatically.  If we use my alternative, `\grenabccharno` should simply pass `#1` (without escaping it) after processing (in gregorio) by tex_escape_text.

**Comment by eroux** [comment]
Indeed, I forgot to remove the escaping in my tests. Well, this solution is really good, let's use it!

**Comment by eroux** [comment]
I won't be able to work on this today anymore, I'll come back to this tomorrow if not done already

**Comment by henryso** [comment]
I'll prepare a pull request for this later this evening.
