### ISSUE TITLE
Create penalty changing system

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1021]
Basically something like what I did for the distances: create a system which provides the user with a convenient interface for changing the various penalties without having to redefine commands.

**Comment by henryso** [comment]
From @eroux (on gregorio-devel):

I think the penalties should just be mapped to some
\gre@space@count@xxxpenalty counts (no need to make it macros, they can
be count directly), that's it... about the deprecation, I really don't
think it's necessary, I don't believe many gregorio users know what a
penalty is... and those who know will certainly be the kind of persons
to look at UPGRADE.md.

**Comment by henryso** [comment]
There are some numbers in gsp-default.tex like `\grewidowpenalty` and `\grelooseness` which are not passed to `\gre@penalty` but are set into things `\widowpenalty = \grewidowpenalty` and `\looseness = \grelooseness`.  Should we handle these in the same way?

**Comment by eroux** [comment]
I think so yes. Also, keep in mind that the same kind of system (mapping to count) will be used for protrusion factors too
