### ISSUE TITLE
Error when building  GregorioRef.pdf

### ISSUE THREAD

**Issue by pcouderc12** [gregorio-project/gregorio#1025]
I have tried to build GregorioRef.pdf
For this, I have read README.md in .../gregorio/doc.
(I have not done .../gregorio/configure as I have suposed that it has been done by ../gregorio/.build.sh)
Then I have tried "make doc", but nothing occurs.

I have tried then "make pdf" and i generates a few things but fails with :

Latexmk: Index file 'GregorioRef-4_1_0.idx' was written
Latexmk: Reference `subsec:greextra' on page 24 undefined
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 35584
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Makefile:442: recipe for target 'GregorioRef-4_1_0.pdf' failed

**Comment by eroux** [comment]
The long you pasted doesn't contain the error, can you please paste the complete `.log` file on a pastebin and give us the link?

**Comment by pcouderc12** [comment]
OK Elie, I do that.
But please note that for me, the error (the "gregorio" error) that I 
have declared is the error in the README.md file : "make  doc" doing 
nothing.

For "my" error, in the "make pdf" it is here 
http://www.tol.fr/download/GregorioRef-4_1_0.log.
Anyway, the link 
https://github.com/gregorio-project/gregorio/releases/download/v4.1.0/GregorioRef-4_1_0.pdf 
is enough for me.

Thank you.

**Comment by eroux** [comment]
Oh ok, in what directory did you run `make doc`? Your log doesn't show any error but doesn't properly end neither... could you paste a longer part of the console output?

**Comment by pcouderc12** [comment]
Unless you want to insist, I suggest to renounce to find the problem : you will find that I have some mistake in my configuration or my installation...
But as I am not (soon...) developer, and  I know where to find GregorioRef.pdf, it will loose our time for nothing important.

**Comment by eroux** [comment]
ok
