### ISSUE TITLE
text-only mode

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1039]
It would be useful for some Abbey if GregorioTeX had a text-only mode that just prints the text, with hyphens between each syllable and just a simple space between words. The idea is to typeset a document in this mode and give the result to someone who would proofread hyphenation.

I think this should be simple enough by overriding `\GreSyllable` and `\GreBarSyllable` with a simple `\GreTextOnlySyllable`.

**Comment by rpspringuel** [comment]
This is mostly already possible via existing settings.  If you generate a score with the following settings:

```
\gresetinitiallines{0}
\gresetclef{invisible}
\gresetlines{invisible}
\gresethyphen{force}
\grechangestaffsize{1}
\grechangedim{interwordspacetext}{0.5em}{fixed}
\grechangedim{interwordspacetext@bars}{0.5em}{fixed}
```

the results are pretty much as you describe.  The notes are still technically being printed, just very small to the point of being almost (but not quite) unnoticeable.  If this isn't sufficient, then I could add a flag which makes the notes truly invisible.  

A parallel flag to make the lyrics invisible would then complete the set, allowing the user to toggle the visibility of pretty much every element of the score.

**Comment by eroux** [comment]
Interesting, thanks for that!

It would be best if the notes could disappear completely indeed, but maybe just handling `\grechangestaffsize{0}` correctly should be enough.

End of lines should also not be handled in this mode, but it's not a big problem, we can close this even if they're not handled.
