### ISSUE TITLE
minimal grouped notes at syllable extrema

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1044]
A request from Solesmes: it would be best to leave the `x` first notes of a syllable together (meaning: keeping them on the same line), and the `y` last notes too. These values should be configurable on the TeX side. I think it should not be too difficult by adding two arguments to GreEndElement, indicating the position of the note from the beginning and from the end...

**Comment by eroux** [comment]
Maybe a total could be passed too, people might say "don't break the final x note, nor the first y notes, and break only if there are at least z notes". I think that would make the system handle more cases.

**Comment by henryso** [comment]
To be clear, you want this to be a count of notes, neither glyphs nor elements, correct?

**Comment by eroux** [comment]
That's the first idea yes... It would certainly be wise to count a pes as just one unit, but I'm not sure we need this level granularity...

**Comment by henryso** [comment]
You say it's "certainly" good to count a pes as one unit, but then say we don't need this level of granularity.  Should we count a pes a single unit or not?

**Comment by eroux** [comment]
Well... yes! Also, you'll certainly need default values. i think 2 for minimum at the beginning and end, and 5 for the total would be fine (it might change, but I think it's a reasonable start)

**Comment by eroux** [comment]
Sorry, thinking back about it, let's forget about pes counting for 1, it makes sense from a graphical point of view, but not from a musical reading point of view (not sure these words make any sense)... Also, looking at Solesmes books, I think 4 is a better default value for grouped notes at the beginning and end of a syllable. For the total, I think 10 makes sense.
