### ISSUE TITLE
flatted custos

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1049]
In (only) one of their pieces, Solesmes has a flat on a custos:

![sicut-novit](https://cloud.githubusercontent.com/assets/60868/13963184/b16e79ca-f064-11e5-866e-ce3357a0f2b4.png)

This kind of figures should be rare enough to handle by hand, but it would be nice to allow automation (optionally).

**Comment by henryso** [comment]
Why optional?  Is there any reason somebody (who wants custos in the first place) would not want this?

**Comment by eroux** [comment]
I'm not sure it's that beautiful... and I'm not sure how consistent the use of this by Solesmes is... I'll ask them

**Comment by eroux** [comment]
I got confirmation that it should be optional

**Comment by henryso** [comment]
I'm assuming that, if the flat before the note generating the custos is *not* on the same pitch as the note, the flat should not be presented on the custos.  For example something like `(ixhgi)` (or even just `(ixh)`) would generate an `h`-height custos without a flat, but something like `(ixisss)` would generate an `i`-height custos with a flat.  Please let me know if this is the wrong assumption.

**Comment by eroux** [comment]
That's correct yes

**Comment by henryso** [comment]
Should this default on or off?

**Comment by eroux** [comment]
Good question... Hmmm... I think it's reasonable to turn it on by default
