### ISSUE TITLE
Numbers introduced into score

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1052]
While working on the ability to hide lyrics/notes, I've come across something I don't understand.  To create a test for the new issue, I copied the PopulusSion test from tex-output and eliminated everything in the document but the `\gregorioscore` command.  
```
% !TEX TS-program = LuaLaTeX+se
% !TEX encoding = UTF-8

% This is a simple template for a LuaLaTeX document using gregorio scores.

\documentclass[11pt]{article} % use larger type; default would be 10pt

% usual packages loading:
\usepackage{fontspec}
\usepackage{graphicx} % support the \includegraphics command and options
\usepackage{geometry} % See geometry.pdf to learn the layout options. There are lots.
\geometry{a4paper} % or letterpaper (US) or a5paper or....
\usepackage[allowdeprecated=false]{gregoriotex} % for gregorio score inclusion
\usepackage{fullpage} % to reduce the margins
\setmainfont[
    Path = ../../../fonts/ ,
    Extension = .otf ,
    UprightFont = *-Regular ,
    UprightFeatures = { SmallCapsFont = *SC-Regular } ,
    BoldFont = *-Bold ,
    BoldFeatures = { SmallCapsFont = *SC-Bold } ,
    ItalicFont = *-Italic ,
    ItalicFeatures = { SmallCapsFont = *SC-Italic } ,
    BoldItalicFont = *-BoldItalic ,
    BoldItalicFeatures = { SmallCapsFont = *SC-BoldItalic } ,
    Ligatures = TeX
]{Alegreya}

% here we begin the document
\begin{document}

% and finally we include the score. The file must be in the same directory as this one.
\gregorioscore[a]{PopulusSion}

%\gresetlyrics{invisible}
%\gregorioscore[a]{PopulusSion}

%\gresetlyrics{visible}
%\gresetnotes{invisible}
%\gregorioscore[a]{PopulusSion}

\end{document}
```

That done, when I compile the document I get the following:

![temp](https://cloud.githubusercontent.com/assets/7671682/14062113/03c515dc-f36a-11e5-88bb-e262d627c7ca.png)

Note the numbers introduced into the text in `Dominus` (both first and second line, though the numbers are in different places), `veniet`, `ad`, and `cordis`.

I've double checked this against latest develop on both repositories (i.e. without any of the changes I'm making for the feature) and the problem is there too.

Does anyone have any idea what the heck is going on here?

**Comment by henryso** [comment]
I don't get this with the current develop.  Are you sure your tex files are clean?

**Comment by rpspringuel** [comment]
Well, I thought I was, but after cleaning up again to double check, the problem has disappeared, so they must not have been.
