### ISSUE TITLE
Centering text over the first syllable after a big initial

### ISSUE THREAD

**Issue by bbloomf** [gregorio-project/gregorio#1055]
In the documentation, [here](https://gregorio-project.github.io/graphy.html) (third paragraph from the bottom), it says 
> Gregorian chant scores usually start with a large initial letter. In this case the alignment point is in the middle of the first letter after the initial (even if it may be a consonant).

but I think this is only the case if the large initial happens to be a vowel.  Otherwise the normal centering rules should apply.  I think it only ends up affecting chants that begin with 2 or more consonants, but these are easy to find.  (See, e.g., [Credo](http://gregobase.selapa.net/chant.php?id=344) or [Christus factus est](http://gregobase.selapa.net/chant.php?id=873) on GregoBase, and look at the difference between Gregorio's output and the source images)

I should note that I'm not sure which version of Gregorio is running on GregoBase, but even if this behavior has changed since then, the documentation ought to be updated.

**Comment by eroux** [comment]
It's fixed on the Gregorio side, see [#42](https://github.com/gregorio-project/gregorio/issues/42), I've opened an issue on the website's repo (see [here](https://github.com/gregorio-project/gregorio-project.github.io/issues/32))
