### ISSUE TITLE
Windows 7 install fails with fonts

### ISSUE THREAD

**Issue by bmaire28** [gregorio-project/gregorio#1057]
I get an error message at the end of Gregorio's install :
"unable to execute file: texlua.exe"
"CreateProcess failed, code 2."
"Le ficheir spécifié est introuvable."
![installation1](https://cloud.githubusercontent.com/assets/15168081/14148909/e87cb722-f6a1-11e5-9a21-26687b34904f.JPG)

I'm using TeXlive 2015 (201update to 2013 updated to 2015)
I've verified that LuaTex is installed as a packaged and found on the disk :
![texluaexe](https://cloud.githubusercontent.com/assets/15168081/14148966/247cd0cc-f6a2-11e5-92e1-2c63d574af2e.JPG)

I've tried to installed fonts manually with the Python script and i get another error : 
c:\Program Files (x86)\gregorio\fonts>install.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\gregorio\fonts\install.py", line 23, in <module>
    from os import access, F_OK, W_OK, makedirs, system, symlink, chmod, popen
ImportError: cannot import name symlink
![installation2jpg](https://cloud.githubusercontent.com/assets/15168081/14148910/ec54e4f0-f6a1-11e5-9ed0-1730e4a85ede.JPG)

I've installed Python 2.7. I've tried with Python 3.5 and get others errors about not using () with print or about tabulation.

**Comment by bmaire28** [comment]
Trying with Cygwin (Tex is left uninstalled) :
MAIREB@MAIREB /cygdrive/c/Users/MAIREB/Downloads/gregorio-4.1.1
$ ls
CHANGELOG.md     CONTRIBUTORS.md  Makefile.am  README.md   VersionManager.py  build-aux  configure     contrib  examples  install          install.sh  src  windows
CONTRIBUTING.md  COPYING.md       Makefile.in  UPGRADE.md  aclocal.m4         build.sh   configure.ac  doc      fonts     install-gtex.sh  m4          tex

MAIREB@MAIREB /cygdrive/c/Users/MAIREB/Downloads/gregorio-4.1.1
$ ./install
Installing Gregorio
make: 'install' is up to date.

Installing GregorioTeX
./install-gtex.sh: line 96: kpsewhich: command not found
./install-gtex.sh: line 99: kpsewhich: command not found
Invalid TeX variable: 'TEXMFLOCAL'

Usage: ./install-gtex.sh var:{tex-variable}
       ./install-gtex.sh dir:{directory}
       ./install-gtex.sh system|user|tds
Failed to install GregorioTeX.  Did you forget to run as root?

I'm administrator on my PC.

**Comment by eroux** [comment]
Thanks for your detailed bugreport ! Python is not used to install fonts under Windows, texlua is. I think everything will run better if `texlua.exe` can be found. Maybe it's a problem with your `PATH` system variable? Do you know how to view it? It should probably contain the path to texlua, which is something like `C:\\TeXLive\bin` (but I'm not sure, I don't have a Windows to check that)

**Comment by henryso** [comment]
What version of gregorio are you installing?  Current versions of Gregorio (which you will need to use for TeX Live 2015) don't even have an install.py.

**Comment by henryso** [comment]
Never mind my earlier comment.  It looks like you are attempting to install 4.1.1.  So the only thing I have to add is that perhaps you need to clean up the files from an older Gregorio install (older installers were not very good at cleaning up after themselves).

**Comment by rpspringuel** [comment]
The installer for 4.1.1 is supposed to be smart enough to find and clean 
up old installations on Windows.

Please run system-setup.bat and post the results.  You should be able to 
find it in the contrib folder inside the Gregorio installation.

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
St. Anselm’s Abbey
Washington, DC
(R. Padraic Springuel)

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by bmaire28** [comment]
Thank you for all your answers.

The problem was the PATH env.

BUT the correct directory to set in PATH is bin\win32, not only \bin. (in my case c:\texlive\2011\bin\win32).
Thanks to system-setup.bat (which i've found in contrib directory from the install), i got error abour kpsewhich not found. Until the PATH was correctly set.

**Comment by bmaire28** [comment]
Thank you for all your answers.

The problem was the PATH env.

BUT the correct directory to set in PATH is bin\win32, not only \bin. (in my case c:\texlive\2011\bin\win32).
Thanks to system-setup.bat (which i've found in contrib directory from the install), i got error abour kpsewhich not found. Until the PATH was correctly set.

**Comment by bmaire28** [comment]
New problem : while compiling the test.tex file as found on the website, i got the error "gregoriotex.sty not found" :

This is LuaTeX, Version beta-0.80.0 (TeX Live 2015/W32TeX) (rev 5238) 
 \write18 enabled.
(./test.tex
LaTeX2e <2016/02/01>
Babel <3.9q> and hyphenation patterns for 1 language(s) loaded.
(c:/texlive/2011/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(c:/texlive/2011/texmf-dist/tex/latex/base/size12.clo))
(c:/texlive/2011/texmf-dist/tex/latex/fontspec/fontspec.sty
(c:/texlive/2011/texmf-dist/tex/latex/l3kernel/expl3.sty
(c:/texlive/2011/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(c:/texlive/2011/texmf-dist/tex/latex/l3kernel/l3pdfmode.def))
(c:/texlive/2011/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(c:/texlive/2011/texmf-dist/tex/luatex/luaotfload/luaotfload.sty(using cache: C:
/texlive/2011/texmf-var/luatex-cache/generic)
luaotfload | main : initialization completed in 0.117 seconds)
(c:/texlive/2011/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
(c:/texlive/2011/texmf-dist/tex/latex/base/fontenc.sty
(c:/texlive/2011/texmf-dist/tex/latex/euenc/eu2enc.def)
(c:/texlive/2011/texmf-dist/tex/latex/euenc/eu2lmr.fd)(load luc: C:/texlive/2011
/texmf-var/luatex-cache/generic/fonts/otf/lmroman10-regular.luc))(load luc: C:/t
exlive/2011/texmf-var/luatex-cache/generic/fonts/otf/lmroman12-regular.luc)
(c:/texlive/2011/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(c:/texlive/2011/texmf-dist/tex/latex/tipa/t3enc.def(load luc: C:/texlive/2011/t
exmf-var/luatex-cache/generic/fonts/otf/lmromanslant12-regular.luc)(load luc: C:
/texlive/2011/texmf-var/luatex-cache/generic/fonts/otf/lmroman12-italic.luc)(loa
d luc: C:/texlive/2011/texmf-var/luatex-cache/generic/fonts/otf/lmroman12-bold.l
uc) (c:/texlive/2011/texmf-dist/tex/latex/euenc/eu2lmss.fd)(load luc: C:/texlive
/2011/texmf-var/luatex-cache/generic/fonts/otf/lmsans12-regular.luc))
(c:/texlive/2011/texmf-dist/tex/latex/graphics/graphicx.sty
(c:/texlive/2011/texmf-dist/tex/latex/graphics/keyval.sty)
(c:/texlive/2011/texmf-dist/tex/latex/graphics/graphics.sty
(c:/texlive/2011/texmf-dist/tex/latex/graphics/trig.sty)
(c:/texlive/2011/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(c:/texlive/2011/texmf-dist/tex/latex/pdftex-def/pdftex.def
(c:/texlive/2011/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(c:/texlive/2011/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))))
(c:/texlive/2011/texmf-dist/tex/latex/fontspec/fontspec.cfg)))

! LaTeX Error: File `gregoriotex.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
Processus arrêté par l'utilisateur

**Comment by henryso** [comment]
It seems like things are not sensibly installed on your machine.  I would suggest following @rpspringuel's instructions above: run system-setup.bat and post the results.

**Comment by bmaire28** [comment]
Everything seems OK :

###	Gregorio Windows Setup Results 
####	Created: 31/03/2016 
----------------------------------------------------------------------------- 
 
 
###	Windows Version 

Microsoft Windows [version 6.1.7601]
 
 
----------------------------------------------------------------------------- 
 
 
###	LuaTeX Setup 
####	Version 
 
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015/W32TeX) (rev 5238)

Execute  'luatex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

Copyright 2015 Taco Hoekwater, the LuaTeX Team.

 
####	Location 
 
C:\texlive\2011\bin\win32\luatex.exe 
 
 
#### TEXMFDIST 
C:/texlive/2011/texmf-dist
 
#### 	TEXMFLOCAL 
 
C:/texlive/2011/texmf-local 
 
#### TEXINPUTS.lualatex 
.;{C:/Users/MAIREB/.texlive2015/texmf-config,C:/Users/MAIREB/.texlive2015/texmf-var,C:/Users/MAIREB/texmf,!!C:/texlive/2011/texmf-config,!!C:/texlive/2011/texmf-var,!!C:/texlive/2011/texmf-local,!!C:/texlive/2011/texmf-dist}/tex/{lualatex,latex,luatex,generic,}//
 
#### LUAINPUTS.lualatex 
.;{C:/Users/MAIREB/.texlive2015/texmf-config,C:/Users/MAIREB/.texlive2015/texmf-var,C:/Users/MAIREB/texmf,!!C:/texlive/2011/texmf-config,!!C:/texlive/2011/texmf-var,!!C:/texlive/2011/texmf-local,!!C:/texlive/2011/texmf-dist}/scripts/{kpsewhich,unsetengine,}/{lua,}//;{C:/Users/MAIREB/.texlive2015/texmf-config,C:/Users/MAIREB/.texlive2015/texmf-var,C:/Users/MAIREB/texmf,!!C:/texlive/2011/texmf-config,!!C:/texlive/2011/texmf-var,!!C:/texlive/2011/texmf-local,!!C:/texlive/2011/texmf-dist}/tex/{lualatex,latex,luatex,generic,}//
 
#### shell_escape 
p
 
#### Shell Escape Commands 
bibtex,bibtex8,extractbb,kpsewhich,makeindex,mpost,repstopdf,
 
#### openout_any 
p
 
#### openin_any 
a
 
 
----------------------------------------------------------------------------- 
 
 
###	Gregorio Setup 
####	Version 
 
Gregorio 4.1.1.
Copyright (C) 2006-2016 Gregorio project authors (see CONTRIBUTORS.md)
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 
#### 	Location 
 
C:\Program Files (x86)\gregorio\bin\gregorio.exe 
 
####	GregorioTeX Locations 
 
##### gregorio-vowels.dat 
##### gregoriosyms.sty 
##### gregoriotex-chars.tex 
##### gregoriotex-main.tex 
##### gregoriotex-ictus.tex 
##### gregoriotex-nabc.lua 
##### gregoriotex-nabc.tex 
##### gregoriotex-signs.lua 
##### gregoriotex-signs.tex 
##### gregoriotex-spaces.tex 
##### gregoriotex-syllable.tex 
##### gregoriotex-symbols.lua 
##### gregoriotex-symbols.tex 
##### gregoriotex.lua 
##### gregoriotex.sty 
##### gregoriotex.tex 
##### gsp-default.tex 
##### greciliae.ttf 
##### greciliae-op.ttf 
##### greextra.ttf 
##### gregorio.ttf 
##### gregorio-op.ttf 
##### gresym.ttf 
##### parmesan.ttf 
##### parmesan-op.ttf 
##### gregall.ttf 
##### gregsmodern.ttf 
 
####	kpsewhich --all -engine luatex -progname lualatex gregoriotex.sty 
 
####	kpsewhich --all -engine luatex gregoriotex.tex 
 
 
-----------------------------------------------------------------------------

**Comment by eroux** [comment]
Not quite! Did you have an error message when you tried to reinstall Gregorio?

**Comment by bmaire28** [comment]
no error message

**Comment by bmaire28** [comment]
I've just done a re-install :

Looking for old GregorioTeX files...
Looking for C:\texlive\2011\texmf-local\tex\generic\gregoriotex...
Looking for C:\texlive\2011\texmf-local\tex\latex\gregoriotex...
Looking for C:\texlive\2011\texmf-local\fonts\ofm\gregoriotex...
Looking for C:\texlive\2011\texmf-local\fonts\tfm\gregoriotex...
Looking for C:\texlive\2011\texmf-local\fonts\type1\gregoriotex...
Looking for C:\texlive\2011\texmf-local\fonts\ovp\gregoriotex...
Looking for C:\texlive\2011\texmf-local\fonts\ovf\gregoriotex...
Looking for C:\texlive\2011\texmf-local\fonts\map\gregoriotex...
Looking for C:\texlive\2011\texmf-local\tex\luatex\gregoriotex...
Looking for C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex...
Looking for C:\texlive\2011\texmf-local\fonts\source\gregoriotex...
Looking for C:\texlive\2011\texmf-local\doc\luatex\gregoriotex...
Looking for 2...
Removing old executable in bin...
removing C:\texlive\2011\texmf-dist\..\bin\win32\gregorio.exe


Copying files into texmf tree...
Distribution is TeXLive
GregorioTeX files...
C:\Program Files (x86)\gregorio\texmf\doc\luatex\gregoriotex\README.md -> C:\tex
live\2011\texmf-local\doc\luatex\gregoriotex\README.md
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\convertsfdtottf.p
y -> C:\texlive\2011\texmf-local\fonts\source\gregoriotex\convertsfdtottf.py
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\greciliae-base.sf
d -> C:\texlive\2011\texmf-local\fonts\source\gregoriotex\greciliae-base.sfd
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\greextra.sfd -> C
:\texlive\2011\texmf-local\fonts\source\gregoriotex\greextra.sfd
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\gregall.sfd -> C:
\texlive\2011\texmf-local\fonts\source\gregoriotex\gregall.sfd
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\gregorio-base.sfd
 -> C:\texlive\2011\texmf-local\fonts\source\gregoriotex\gregorio-base.sfd
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\gresgmodern.sfd -
> C:\texlive\2011\texmf-local\fonts\source\gregoriotex\gresgmodern.sfd
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\gresym2.sfd -> C:
\texlive\2011\texmf-local\fonts\source\gregoriotex\gresym2.sfd
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\parmesan-base.sfd
 -> C:\texlive\2011\texmf-local\fonts\source\gregoriotex\parmesan-base.sfd
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\simplify.py -> C:
\texlive\2011\texmf-local\fonts\source\gregoriotex\simplify.py
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\squarize.py -> C:
\texlive\2011\texmf-local\fonts\source\gregoriotex\squarize.py
C:\Program Files (x86)\gregorio\texmf\fonts\source\gregoriotex\stemsschemas.py -
> C:\texlive\2011\texmf-local\fonts\source\gregoriotex\stemsschemas.py
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\grecilia
e-op.ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\grecil
iae-op.ttf
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\grecilia
e.ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\greciliae
.ttf
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\greextra
.ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\greextra.t
tf
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\gregall.
ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\gregall.ttf

C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\gregorio
-op.ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\gregori
o-op.ttf
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\gregorio
.ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\gregorio.t
tf
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\gresgmod
ern.ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\gresgmo
dern.ttf
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\parmesan
-op.ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\parmesa
n-op.ttf
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\parmesan
.ttf -> C:\texlive\2011\texmf-local\fonts\truetype\public\gregoriotex\parmesan.t
tf
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregorio-vowels.dat
 -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregorio-vowels.dat
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriosyms.sty ->
 C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriosyms.sty
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-chars.t
ex -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-chars.tex
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-main.te
x -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-main.tex
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-nabc.lu
a -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-nabc.lua
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-nabc.te
x -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-nabc.tex
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-signs.l
ua -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-signs.lua
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-signs.t
ex -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-signs.tex
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-spaces.
tex -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-spaces.tex

C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-syllabl
e.tex -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-syllable
.tex
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-symbols
.lua -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-symbols.l
ua
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-symbols
.tex -> C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex-symbols.t
ex
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex.lua ->
C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex.lua
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex.sty ->
C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex.sty
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex.tex ->
C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gregoriotex.tex
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gsp-default.tex ->
C:\texlive\2011\texmf-local\tex\luatex\gregoriotex\gsp-default.tex
37 fichier(s) copié(s)


Running mktexlsr...
mktexlsr: Updating C:/texlive/2011/texmf-local/ls-R...
mktexlsr: Updated C:/texlive/2011/texmf-local/ls-R.
mktexlsr: Done.

Post-install script complete.
Press return to continue...

**Comment by bmaire28** [comment]
All is ok for now ? ! ?

What i have done :  execute the lines at the end of system-setup report (kpsewhich --all -engine luatex -progname lualatex gregoriotex.sty / kpsewhich --all -engine luatex gregoriotex.tex) and re-install.

**Comment by eroux** [comment]
You have a strange mix of TeXLive 2011 and 2015, Gregorio apparently gets installed in the 2011 folder, but maybe when you compile you're using the 2015 one... I don't really know...

**Comment by rpspringuel** [comment]
I still need the output of system-setup.bat if I'm to help. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by eroux** [comment]
Isn't it [here](https://github.com/gregorio-project/gregorio/issues/1057#issuecomment-203936687)?

**Comment by rpspringuel** [comment]
Sorry, crossed messages, I'll look at what you've posted in more detail later. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by bmaire28** [comment]
About the texlive isntall : it is a 2011 one upgraded to 2013 upgraded to 2015.
At the end, texlive2015 is in the 2011 directory. I have no 2013 nor 2015 directories.

**Comment by rpspringuel** [comment]
Well, the system-setup.log that you posted indicates that the GregorioTeX files were not found in your texmf tree (most of the files should have a location listed underneath their name in the list), but the output of the post install script indicates that they were copied there.  If I'm reading things correctly, that post install output comes from an attempt to reinstall after you ran system-setup.bat.  If that is the case, please rerun system-setup.bat and post the new result if it is different.

If the system-setup.log that you posted comes from after your most recent installation attempt, then try opening a command prompt with administrative privileges and running `texhash` to see if that fixes the problem.

**Comment by bmaire28** [comment]
here is the last one after all i've done :
###	Gregorio Windows Setup Results 
####	Created: 01/04/2016 
----------------------------------------------------------------------------- 
 
 
###	Windows Version 

Microsoft Windows [version 6.1.7601]
 
 
----------------------------------------------------------------------------- 
 
 
###	LuaTeX Setup 
####	Version 
 
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015/W32TeX) (rev 5238)

Execute  'luatex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

Copyright 2015 Taco Hoekwater, the LuaTeX Team.

 
####	Location 
 
C:\texlive\2011\bin\win32\luatex.exe 
 
 
#### TEXMFDIST 
C:/texlive/2011/texmf-dist
 
#### 	TEXMFLOCAL 
 
C:/texlive/2011/texmf-local 
 
#### TEXINPUTS.lualatex 
.;{C:/Users/MAIREB/.texlive2015/texmf-config,C:/Users/MAIREB/.texlive2015/texmf-var,C:/Users/MAIREB/texmf,!!C:/texlive/2011/texmf-config,!!C:/texlive/2011/texmf-var,!!C:/texlive/2011/texmf-local,!!C:/texlive/2011/texmf-dist}/tex/{lualatex,latex,luatex,generic,}//
 
#### LUAINPUTS.lualatex 
.;{C:/Users/MAIREB/.texlive2015/texmf-config,C:/Users/MAIREB/.texlive2015/texmf-var,C:/Users/MAIREB/texmf,!!C:/texlive/2011/texmf-config,!!C:/texlive/2011/texmf-var,!!C:/texlive/2011/texmf-local,!!C:/texlive/2011/texmf-dist}/scripts/{kpsewhich,unsetengine,}/{lua,}//;{C:/Users/MAIREB/.texlive2015/texmf-config,C:/Users/MAIREB/.texlive2015/texmf-var,C:/Users/MAIREB/texmf,!!C:/texlive/2011/texmf-config,!!C:/texlive/2011/texmf-var,!!C:/texlive/2011/texmf-local,!!C:/texlive/2011/texmf-dist}/tex/{lualatex,latex,luatex,generic,}//
 
#### shell_escape 
p
 
#### Shell Escape Commands 
bibtex,bibtex8,extractbb,kpsewhich,makeindex,mpost,repstopdf,
 
#### openout_any 
p
 
#### openin_any 
a
 
 
----------------------------------------------------------------------------- 
 
 
###	Gregorio Setup 
####	Version 
 
Gregorio 4.1.1.
Copyright (C) 2006-2016 Gregorio project authors (see CONTRIBUTORS.md)
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 
#### 	Location 
 
C:\Program Files (x86)\gregorio\bin\gregorio.exe 
 
####	GregorioTeX Locations 
 
##### gregorio-vowels.dat 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregorio-vowels.dat
##### gregoriosyms.sty 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriosyms.sty
##### gregoriotex-chars.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-chars.tex
##### gregoriotex-main.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-main.tex
##### gregoriotex-ictus.tex 
##### gregoriotex-nabc.lua 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-nabc.lua
##### gregoriotex-nabc.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-nabc.tex
##### gregoriotex-signs.lua 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-signs.lua
##### gregoriotex-signs.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-signs.tex
##### gregoriotex-spaces.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-spaces.tex
##### gregoriotex-syllable.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-syllable.tex
##### gregoriotex-symbols.lua 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-symbols.lua
##### gregoriotex-symbols.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex-symbols.tex
##### gregoriotex.lua 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex.lua
##### gregoriotex.sty 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex.sty
##### gregoriotex.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex.tex
##### gsp-default.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gsp-default.tex
##### greciliae.ttf 
c:/texlive/2011/texmf-local/fonts/truetype/public/gregoriotex/greciliae.ttf
##### greciliae-op.ttf 
c:/texlive/2011/texmf-local/fonts/truetype/public/gregoriotex/greciliae-op.ttf
##### greextra.ttf 
c:/texlive/2011/texmf-local/fonts/truetype/public/gregoriotex/greextra.ttf
##### gregorio.ttf 
c:/texlive/2011/texmf-local/fonts/truetype/public/gregoriotex/gregorio.ttf
##### gregorio-op.ttf 
c:/texlive/2011/texmf-local/fonts/truetype/public/gregoriotex/gregorio-op.ttf
##### gresym.ttf 
##### parmesan.ttf 
c:/texlive/2011/texmf-local/fonts/truetype/public/gregoriotex/parmesan.ttf
##### parmesan-op.ttf 
c:/texlive/2011/texmf-local/fonts/truetype/public/gregoriotex/parmesan-op.ttf
##### gregall.ttf 
c:/texlive/2011/texmf-local/fonts/truetype/public/gregoriotex/gregall.ttf
##### gregsmodern.ttf 
 
####	kpsewhich --all -engine luatex -progname lualatex gregoriotex.sty 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex.sty
 
####	kpsewhich --all -engine luatex gregoriotex.tex 
c:/texlive/2011/texmf-local/tex/luatex/gregoriotex/gregoriotex.tex
 
 
-----------------------------------------------------------------------------

**Comment by rpspringuel** [comment]
So this is working now?
