### ISSUE TITLE
not enough space allocated for text with multiple voices

### ISSUE THREAD

**Issue by asbloomf** [gregorio-project/gregorio#1070]
In something like `(c4)Jé({a}er)` the a seems to be ignored when considering space needed for the text.  But `(c4)Jé({er}a)` renders properly.

[example.zip](https://github.com/gregorio-project/gregorio/files/213456/example.zip)

**Comment by henryso** [comment]
Closing as wontfix, in deference to documentation in gregorio-project/gregorio-project.github.io#42.
