### ISSUE TITLE
renaming parmesan into granapadano

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1075]
Packaging GregorioTeX for ctan, I realize that keeping the name parmesan is not the best idea I ever had, as it can only cause problems with original parmesan from Lilypond...  So the `parmesan.*` files should be renamed `greparmesan.*`, and maybe a hack should be done so that documents calling the `parmesan` font continues to work. I'm just not sure there is any single document using `parmesan`, so that second part is not mandatory.

**Comment by henryso** [comment]
How about another cheesy name for the font?  Gruyère starts with "gr".  Is that a bad idea?

**Comment by eroux** [comment]
Haha, good idea! Gruyere sounds good, maybe Granapadano (a kind of parmesan actually) could be good too... I let you decide what you prefer

**Comment by henryso** [comment]
Grana Padano sounds good since it's similar to parmesan.  My only reservation (not a big one) is that the name is kind of long, but I'm in favor of granapadano as the font name.

**Comment by rpspringuel** [comment]
I like the name and don't thing the length is too bad.
