### ISSUE TITLE
oriscus queue length

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1079]
A request from Solesmes for their font: they want to have a different "queue" length for their oriscus depending on the previous or next note. By "queue" I mean the shape of the oriscus, nothing to do with the stem. Examples:

- the oriscus of `(goi)` would have a long "queue" on the left, and a long queue on the right, merging with the joining line
- the oriscus of `(goh)` would have a long "queue" on the left, and a short queue on the right, because a long queue would merge with the second note and would not be elegant

Until now, this is purely a font problem that can be solved relatively easily. The main problem is with `!` and `@`, as these should make the oriscus use a short queue in case of an ambitus of one. This means duplicating all glyphs starting or ending with an oriscus, and use the long or short form according to what's around. I cannot find another solution though. What do you think?

**Comment by henryso** [comment]
I don't fully understand what you (they?) mean by "long" vs. "short" here.  The things that come to mind don't match your examples.  I think I need an illustration.

**Comment by henryso** [comment]
@eroux Do you have any further explanation?

**Comment by eroux** [comment]
The problem doesn't really appear with greciliae, but I've made an example of what it could be. The current oriscus shape is

![oriscus-normal](https://cloud.githubusercontent.com/assets/60868/15137450/4da520d2-168a-11e6-89cf-ef06d3f41044.png)

and it's good for standalone oriscus glyphs, but when an oriscus is touching another note, for instance `(go!h)`, with Solesmes' font, the "queue" (or wave, or whatever) is too pronounced, so they've made another glyph for these occasions, something like that:

![oriscus-smooth](https://cloud.githubusercontent.com/assets/60868/15137492/96e1c3c2-168a-11e6-95d9-4458c7a97c4a.png)

(I've just drawn it from greciliae, it's just to give you the idea). With this glyph, the queue is less pronounced and `(go!h)` looks nicer. The problem is to have the correct queue length in correct places, sometimes it can be on the left and not on the right, sometimes both, etc. according to the notes around. The idea would be to use the smooth queue only when there is an ambitus of one, in all other cases (ambitus more than one, a space, etc.), the normal glyph should be used. Do you see what I mean? I'm not sure it's particularly easy to do...

**Comment by henryso** [comment]
If I'm understanding properly, it means six new base glyphs (two orientations, left/right/both styles for each).  We would redraw existing pre-fused glyphs according to these rules and (I suggest) use fusion for everything else.  Instead of `(go!h)`, it would be `(go@h)`  Am I missing anything?

**Comment by eroux** [comment]
This sounds correct! I didn't think about using `(go@h)` instead of `(go!h)`, that's a good idea, and it allows much simpler code! I'm not entirely sure we really need to redraw new glyphs... maybe the `squarize.py` script could automatically copy the base glyph if the others don't exist?

**Comment by henryso** [comment]
Well, that's actually what I meant by redrawing existing pre-fused glyphs.

**Comment by henryso** [comment]
Do you think any of the free fonts need or could benefit from this feature?  It will be a difficult to test and maintain this feature if none of the free fonts support it.  I'm not particularly artistic, so I don't feel qualified to judge the aesthetics.

**Comment by eroux** [comment]
Well, let's not use that in granapadano or gregorio, but in greciliae I think this could be good, the modification could look like this:

![oriscus-smallbar](https://cloud.githubusercontent.com/assets/60868/15171786/7d7cffa6-1751-11e6-90a8-f5d974c77d5f.png)

**Comment by eroux** [comment]
Just thought about that: it would be pretty easy to make it optional with a switch in `squarize.py` or a value in the `.json` file, I think that would be a good idea...

**Comment by henryso** [comment]
This adds 114 fusion building block glyphs to greciliae, leaving 745 in the BMP PUA.
