### ISSUE TITLE
Skip fonts install option in install-gtex.sh

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1080]
I normally keep my repository very clean by running `make maintainter-clean` after installation.  As a result, the font ttf files are not usually present.  However, this creates a problem when I'm testing changes which only affect the tex files, as `install-gtex.sh` tries to install the font files (which aren't present) and thus fails before running `texhash`.  It would be useful, therefore, if `install-gtex.sh` had an option which would allow one to skip installing the font files.

**Comment by henryso** [comment]
#1097 will allow you to do something like...

```
SKIP=fonts,docs,font-sources ./install-gtex.sh system
```

... to skip installation of fonts, documentation, and font sources.
