### ISSUE TITLE
Recent changes in *.sty locations

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1081]
The recent changes in the location of `gregoriosyms.sty` and `gregoriotex.sty` mean that a user upgrading the GregorioTeX files via the `install-gtex.sh` interface will end up with two copies of these files on their systems (one from 4.1.1 or earlier, the other from 4.2.0-beta1 or later).  This can obviously create problems with version conflicts if the wrong file is grabbed first (or if `texhash` hasn't been run properly.  At minimum this needs to be documented, but it might be better if `install-gtex.sh` was modified to remove the old versions of these two files.

**Comment by eroux** [comment]
Sure, I think `install-gtex.sh` can be modified
