### ISSUE TITLE
TeXLive 2016 Pretest Errors

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1084]
So, I'm starting the process of checking the TeXLive 2016 Pretest and lo-and-behold it doesn't work out of the box.

For starters I'm using the debugging document, which merely tests to make sure that our package can successfully be loaded.  When compiling I get the following error:

```
Module gregoriotex Error: 
(gregoriotex)             Uncoherent file versions!
(gregoriotex)             gregoriotex.tex is version 4.1.1
(gregoriotex)             while greciliae.ttf is version Version 4.1.1 
(gregoriotex)             please update file
(gregoriotex)             nil on input line 1747
```

This seems to indicate that have been some changes in how the font meta data is accessed.  In particular `gregoriofont.shared.rawdata.metadata.version` now appears to prepend a "Version" (hence "4.1.1" != "Version 4.1.1")  and `gregoriofont.shared.rawdata.metadata.origname` no longer works (hence the `nil` in the last line of the error).  Unfortunately I don't know enough about how these methods work to come up with a fix.

Well, I could fix the first through string methods, but I'm not sure if that's the appropriate solution.

**Comment by eroux** [comment]
Oh, many things changed in the fontloader I'm affraid... @phi-gamma are the changed described here intended?

**Comment by henryso** [comment]
@rpspringuel Perhaps compare the strings with and without `Version ` prepended to the gregoriotex.tex version.  This should work on both versions, then.

**Comment by jakubjelinek** [comment]
Or just strip an optional 'Version ' prefix from the strings before comparison.

**Comment by phi-gamma** [comment]
···<date: 2016-04-30, Saturday>···<from: Elie Roux>···

> Oh, many things changed in the fontloader I'm affraid...
> @phi-gamma are the changed described here intended?

The new loader outputs different version info:

    luaotfload-tool --list='*' --fields=fontname,version   | grep -i graeciliae

For most fonts this outputs longer version strings than Fontforge
did. They should work as reliable, though, which isn’t so say
much. In your case you can just test for the new version string.

Maybe it’d be better a better approach to get the path to the
font file and hash it?

Best,
Philipp

**Comment by henryso** [comment]
The github UI obliterates @phi-gamma's message, so here it is:
```
The new loader outputs different version info:

    luaotfload-tool --list='*' --fields=fontname,version   | grep -i graeciliae

For most fonts this outputs longer version strings than Fontforge
did. They should work as reliable, though, which isn’t so say
much. In your case you can just test for the new version string.

Maybe it’d be better a better approach to get the path to the
font file and hash it?

Best,
Philipp
```

**Comment by rpspringuel** [comment]
I'm not familiar enough with the hashing methods in Lua to go that route, but I can implement the string methods (either adding or removing "Version").

How about getting the filename?  What would be the appropriate method for doing that with the new font loader?

**Comment by rpspringuel** [comment]
Hmm... Looking at the output again, it seems that I could simply reuse `gregoriofont.shared.rawdata.metadata.fontname` which is used to produce the `greciliae.ttf` earlier in the message.  Was there some explicit point to using `gregoriofont.shared.rawdata.metadata.origname` instead of resuing `gregoriofont.shared.rawdata.metadata.fontname`? (@henryso, I think you were the one who coded the original font check and so might know the answer to that).

**Comment by henryso** [comment]
Actually, that was @eroux in b8eedd751638fc102109cd3014a22353317b0600

**Comment by eroux** [comment]
No idea, these things aren't really documented nor stable, so whatever works is fine!

**Comment by rpspringuel** [comment]
What if I make the error say this:

```
Module gregoriotex Error: 
(gregoriotex)             Uncoherent file versions!
(gregoriotex)             gregoriotex.tex is version 4.1.1
(gregoriotex)             while greciliae.ttf is version Version 4.1.1 
(gregoriotex)             please reinstall one so that the versions match.
```

**Comment by eroux** [comment]
ok

**Comment by rpspringuel** [comment]
Question: How do I suppress the line number which is being attached to the error message?  In LaTeX speak, this would be the difference between `\ClassError` and `\ClassErrorNoLine`.  Is there a similar alternative to `err` in the Lua code?

**Comment by eroux** [comment]
I don't think so

**Comment by rpspringuel** [comment]
Okay, I'll do without it.

In any event, I've been able to make changes that allow TeXLive 2016 to compile the debugging document and am now moving on to the test repository.

**Comment by rpspringuel** [comment]
Okay, next problem: `\pdfstartlink` and `\pdfendlink` (presumably amongst others, these are simply the first two I've come across) are not defined in the new LuaLaTeX kernel.  This is due to the massive reorganization of command names in the back end.  I should be able to get around this by loading `luatex-pdf.tex`, which redefines a whole bunch of these commands.  Is that an acceptable work around, or should I create our own version of this file which only defines those that we use?

**Comment by eroux** [comment]
I think using it for now (if it exists) is fine, in a near future the best is certainly to rely on the new names, with a fallout on the old ones... What do you think?

**Comment by rpspringuel** [comment]
Right now, for `\gre@localleftbox` (and likewise `\gre@localrightbox`) we do the following:

```
\ifdefined\localleftbox%
	\let\gre@localleftbox\localleftbox%
\else%
	\let\gre@localleftbox\luatexlocalleftbox%
\fi%
```

We could do something similar here:

```
\ifdefined\pdfextension%
	\def\gre@pdfstartlink{\pdfextension startlink }%
\else%
	\let\gre@pdfstartlink\pdfstartlink%
\fi%
```
This is basically what `luatex-pdf.tex` does, except instead of defining the internal alias (`\gre@pdfstartlink`) it defines the old command name (`\pdfstartlink`) using the new syntax.

**Comment by phi-gamma** [comment]
> I'm not familiar enough with the hashing methods in Lua

Luatex has the luamd5 library built into it. You can hash strings
and get a portable representation of the hash by calling
``md5.sumhexa()``, for example. It might have a noticable
performance impact, though to do that with each run.

Perhaps it’d make sense to keep a hash in the Luaotfload font
index?

> How about getting the filename?  What would be the appropriate
> method for doing that with the new font loader?

The lookups are hopefully independent of the new loader =)
If Luaotfload is loaded and you have the filename, you can call
``fonts.names.lookup_font_file()`` on it and it will yield the
path.

If you only know some name, it’s a bit more involved since you
need to create a lookup spec first and then feed it into
``fonts.names.lookup_font_name()``. There’s an example of how a
minimal spec is supposed to look like in ``luaotfload-tool``:

    https://github.com/lualatex/luaotfload/blob/master/src/luaotfload-tool.lua#L1149

Where ``query`` is a string containing the font name requested by
the user.

Those aren’t public APIs but they are fairly stable at this
point.

Best,
Philipp

PS: Sorry for the way Github renders my comments but I’d hate
    composing a text of more than two lines lengths in a web
    browser form.

**Comment by eroux** [comment]
@rpspringuel I think what you describe would be best, if you can do that instead of using `luatex-pdf`, that would be perfect

**Comment by rpspringuel** [comment]
Okay, got the local aliases.  New problem:

It appears that `gregoriocolor` is not defined, but only within a score.  Take the following document:

```
\documentclass{article}

\usepackage[debug]{gregoriotex}

\listfiles

\begin{document}
\color{gregoriocolor}
Debugging document

\gresetlinecolor{gregoriocolor}
\gabcsnippet{(c3) test(g)}
\end{document}
```
Comment out the snippet, and it will compile fine under TeXLive 2016.  Leave it in, and you'll get a complaint about `gregoriocolor` being undefined.  Given that it clearly is, because it works on the text which preceeds it, this has got to be a scoping issue (which is weird because the color is defined at the top level of the style file).  Somehow the color definition isn't making it down into the box where the lines are drawn.  Any ideas as to whether this is something we need to fix or a bug that needs to be passed on to the developers of the color package?

**Comment by eroux** [comment]
I remember seing something about xcolor and LuaTeX in a mailing list, but I don't know if the bugs have been fixed or not... Anyway, since this short example is not supposed to compile under TeXLive 2016 without your previous modifications, this makes it difficult for the developpers of xcolor to test. So I propose the following: merge all the fixes you can in `release-4.1`, build a new ctan zip and [upload it](http://ctan.org/upload) (you should be able to), then wait a few days so that the new code gets into TeXLive (I'll ask Karl to make the import quickly, explaining the situation), then report it to the devs of xcolor, who will be able to test by simply updating their TeXLive 2016 pretest version. What do you think?

**Comment by rpspringuel** [comment]
Okay, after some further testing, I've been able to reproduce the error with the following MWE:

```
\documentclass{article}

\usepackage{xcolor}

\definecolor{gregoriocolor}{RGB}{229,53,44}%
\newenvironment{test}{\color{greogiocolor}}{}

\listfiles

\begin{document}
{\color{gregoriocolor}
Debugging document}

\test Debugging document\endtest
something
\end{document}
```
That tells me its definitely a color issue.  I'll work on filing the appropriate bug report after lunch.

**Comment by eroux** [comment]
Ok, that's perfect!

**Comment by eroux** [comment]
BTW, if the bug is LuaTeX-specific, add the luatex list (luatex@tug.org) in copy of your bugreport.

**Comment by rpspringuel** [comment]
Or maybe not.  I don't know what I was doing before lunch, but I cannot reproduce the error now without using our package.  I'll work on porting in the other fixes then so that we can go the route @eroux suggested.

**Comment by rpspringuel** [comment]
Okay, now I know what I was doing before lunch that was the problem, I misspelled `gregoriocolor` in the definition of test.  Fix that and the document compiles fine, though the document which uses our package doesn't.  Such a simple stupid error.

**Comment by rpspringuel** [comment]
I have built the ctan package from my `texlive2016` branch and uploaded it.  I'll let you know if I hear anything back from them.

**Comment by rpspringuel** [comment]
The update has been processed and should be on the mirrors within 24 hours.  Once it's there I'll see about contacting the xcolor people to try and work out the problem.

In other news, I've seen just one other bug that's preventing our test repository from fully passing with TeXLive 2016, and I don't believe it's our fault: the `geometry` package doesn't seem to be working with the revised LuaLaTeX, with the result being that some of our tests are failing because they're being created on the wrong size paper (letter instead of a4).  On my test system (Ubuntu 14.04), where the default page size is letter, the following document comes out on letter paper (when it should be A4):

```
\documentclass{article}

\usepackage{geometry}
\geometry{a4paper}

\begin{document}
Test
\end{document}
```

I've already emailed the geometry and LuaTeX people on this.

**Comment by rpspringuel** [comment]
After some work, I've isolated the xcolor error using the following document:

```
\documentclass[11pt]{article}

\usepackage{xcolor}%

\def\GreScoreOpening{%
	\hbox to 0pt{%
		\vbox{%
			\begingroup\color[named]{gregoriocolor}
			\hrule height 0.4pt width \hsize\relax%
			\kern3mm\relax %
			\hrule height 0.4pt width \hsize\relax%
			\kern3mm\relax%
			\hrule height 0.4pt width \hsize\relax%
			\kern3mm\relax%
			\hrule height 0.4pt width \hsize\relax%
			\kern3mm\relax%
			\hrule height 0.4pt width \hsize\relax%
			\endgroup%
		}%
		\hss%
	}%
}%

\definecolor{gregoriocolor}{RGB}{229,53,44}%

\listfiles

\begin{document}

\GreScoreOpening

\end{document}
```

I emailed the xcolor author with the problem earlier today and just sent another email with the new MWE.  I'll let you know if anything comes of it.

**Comment by rpspringuel** [comment]
Now that I've got the isolated document, I was able to test it against pdfLaTeX and found that the error does not occur there, so it's specifically a xcolor + LuaLaTeX error.  To that end, I just send an email to luatex@tug.org letting them know about the issue too.

**Comment by rpspringuel** [comment]
A fix for the geometry problem is apparently in the offing, but no one has heard anything from the xcolor developer to know if that is going to be fixed.  I have an oral final in a couple of hours, but will see if I can't come up with a work around after that.

**Comment by eroux** [comment]
The workaround should be done by the LaTeX team, not us, I'm sure they'll come up with something... In the meantime you can just use the `luatex85` package in your tests, if everything goes well with this package, it should go well in TL2016

**Comment by rpspringuel** [comment]
The problem with using the `luatex85` package is that it will mask any problems our own code would have with the LuaTeX changes.  When I say "work around" I'm just talking in terms of our tests as a way to make sure I've caught all the potential TL2016 issues.  At this point, I've only got about 36 tests which are failing and all are triggering either the geometry or xcolor error.  If I can patch over those two problems in some fashion, then I'll be able to make the final checks to ensure TL2016 compatibility.

**Comment by rpspringuel** [comment]
I have a new PR for this: #1094
