### ISSUE TITLE
font format

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1086]
The fonts are currently generated as .ttf, but maybe opentype would be better? Especiall when it comes to hinting (for dispay on screen)... Disabling the PS hints at font generation in fontforge makes the file size not much larger (1167840 instead of 976492 for greciliae), but I'm not really sure what this option does... What do you think?

**Comment by henryso** [comment]
How is OpenType hinting better than TrueType?

**Comment by eroux** [comment]
I reported the issue after reading [this](http://blog.typekit.com/2010/11/12/microsoft-directwrite-is-coming/) (in a completely different context). If I understand correctly, with CFF fonts, the hinting is automatically done by the renderer, while with TT fonts, the hinting should be done by the font itself. As we don't have hinting in our fonts (and I don't think it will ever happen), CFF (and this otf) sounds like a better option... But I may be wrong, I'm not sure I understood everything...

**Comment by henryso** [comment]
I think that post is *very* specific to Microsoft DirectWrite.  Whether the renderer applies anti-aliasing or auto-hints fonts that are not hinted (regardless of whether they are OpenType/CFF or TrueType) depends entirely on the renderer.  I think the real question (to which I cannot find a clear answer) is whether more renderers do a better job with OpenType than with TrueType.

**Comment by eroux** [comment]
Indeed, no idea about that... I'll ask some contacts (who aren't usually answering fast... if at all)

**Comment by rpspringuel** [comment]
@eroux, is this still relevant?

**Comment by rpspringuel** [comment]
I'm closing this as unresolvable for now.
