### ISSUE TITLE
Escaped "&" in XML output

### ISSUE THREAD

**Issue by benyanke** [gregorio-project/gregorio#1089]
When the there is an & within the header of a score, it is not escaped properly when converting to XML, causing XML validation errors. Should replace & with "&amp;" if I understand the XML spec correctly.

[kyrie18.xml.txt](https://github.com/gregorio-project/gregorio/files/253575/kyrie18.xml.txt)
[kyrie18.gabc.txt](https://github.com/gregorio-project/gregorio/files/253576/kyrie18.gabc.txt)

**Comment by rpspringuel** [comment]
Support for conversion to XML was dropped in v4.0.

**Comment by eroux** [comment]
What was your use of XML? I didn't know it was actually used...

**Comment by benyanke** [comment]
Actually using the XML to hold data which will eventually be put in a Braille music book. Using gregorio to convert from the wide selection of GABC chants to XML, since we can process it more easily in XML.
