### ISSUE TITLE
Revision to Installation instructions/Installers to use shell_escape_commands

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1100]
Once TeXLive 2016 comes out, our command line tool will be in the `shell_escape_commands` list for new/updated TeXLive installations.  This means that those users will not need to use the `--shell-escape` option when running `lualatex`.  Since our current configuration instructions assume that said option needs to be applied, they would need to be split to account for the difference.  There would also need to be a split in our usage instructions.

In thinking about that split, it occurred to me that it might be a better solution if instead of instructing the user to use `--shell-escape` (which allows *all* external programs to run), we should provide instructions for adding `gregorio` to the list of `shell_escape_commands` (thus enabling our program, but not others).  The installation/configuration instructions would remain split, but the split would consist of an extra step for TL2015 and earlier users.  Additionally, the usage instructions to be uniform across TeXLive versions.

Further, I've looked into the possibility of automating that process, possibly allowing us to include the configuration in the installers.  This would make things even easier for novice users.  So far, I've come up with a script which appears to work on my Mac with TL2015:

```
TARGET=`kpsewhich --var-value=TEXMFLOCAL`"/web2c"
mkdir -p ${TARGET}
TARGET=${TARGET}"/texmf.cnf"
touch ${TARGET}
if grep -q "^shell_escape_commands =.*gregorio.*" ${TARGET}; then
    echo "gregorio is already in the shell_escape_commands"
    echo "doing nothing"
elif grep -q "^shell_escape_commands =" ${TARGET}; then
    sed -i.old '/^shell_escape_commands =/ s/$/gregorio,/' ${TARGET}
    mktexlsr
else
    cp ${TARGET} ${TARGET}.old
    echo "" >> ${TARGET}
    echo "shell_escape_commands = `kpsewhich --var-value=shell_escape_commands`gregorio," >> ${TARGET}
    echo "" >> ${TARGET}
    mktexlsr
fi
```

I haven't yet tested this against other TeXLive versions or platforms.

Does anyone have any thoughts on this?  Is this a good idea for me to continue chasing down?

**Comment by henryso** [comment]
I don't think it's a good idea to modify the shell_escape_commands in any automatic fashion.  That's a big security violation.

Also, I think the instructions should remain adding the `--shell-escape` until mid-2017 at the earliest, at which point there should be a note for TeXLive older than 2016 requiring it, which should remain for at least a few years.

**Comment by eroux** [comment]
I also think modifying `shell_escape_commands` automatically is not very nice, but I think we can make the instructions on the website say "only if you have a TeXLive < 2016" for the `shell-escape` part...

**Comment by henryso** [comment]
I'm fine with @eroux's suggestion, not that my opinion means much.

**Comment by rpspringuel** [comment]
I would argue that calling `lualatex --shell-escape` is a bigger security hole than adding gregorio to the list of `shell_escape_commands` as the former would allow a document to run anything, while the latter would only allow `gregorio` to run (in addition to whatever else is in the list).

Still, I can see how making the modification without telling the user would also be a problem.  What if the installers offered to do the change (with the default being not to make it)?  Or perhaps a separate tool (something like the configuration scripts in `contrib` for TeXworks and TeXShop)?

**Comment by eroux** [comment]
What you're exposing is one of the main reasons why I pushed gregorio reviewing and integration into TeXLive, so I'm quite aware of it. But it's been like that for a few years, and I'm affraid viruses targetting LuaTeX users running with the `--shell-escape` switch are "quite rare"... I think the best would be to document that on the website, though I'm affraid it's too technical for most users...

**Comment by rpspringuel** [comment]
> though I'm affraid it's too technical for most users...

That is why I thought some sort of automation of the process would be useful.  Seeing as both of you don't like the idea, however, I'll confine myself to changes to the instructions on the website.
