### ISSUE TITLE
better error handling on \n\n inside a syllable in gabc

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1111]
gregorio could replace (\n|\r)+ with \n inside syllables when outputing GregorioTeX, see [this thread](https://mail.gna.org/public/gregorio-users/2016-05/msg00009.html)

**Comment by henryso** [comment]
Should it not replace multiple whitespace (\t| |\n|\r)+ with a single blank space?

**Comment by rpspringuel** [comment]
With the exception of two line breaks in a row (which is treated as equivalent to `\par`), TeX already treats multiple white space characters as a single white space character.

**Comment by henryso** [comment]
Got it, thanks.

**Comment by pcouderc12** [comment]
Is it a problem to ignore any "special" character (under "space") in gabc ?

**Comment by henryso** [comment]
I don't think it's a good idea to be over-zealous with this change.  There's too much chance of breaking something outside gabc (present or future) that uses a control character for its operation.

**Comment by pcouderc12** [comment]
1-Most problems come from  (\t| |\n|\r) as you state it.
2- I cannot imagine a soon existing (or future) code using these characters (or ANY "special" character) in a meaningful state in gabc source. 
3- Problems with non printable characters are very difficult to detect. So I "vote" for replacing any special character....

My problem was created the following way : I wanted to create a new version of Pange Lingua. I did start from a classical version, and used https://bbloomf.github.io/jgabc/transcriber.html to get the accentuated text and change the music, and got the problem with this result. It was difficult to find it. Sed ego non sum Lumen...

**Comment by eroux** [comment]
What do you mean by "special character"? This is pretty unclear to me... What other special characters do you see?

**Comment by pcouderc12** [comment]
Good old special characters : U+0000 à U+001F
None of them would be present in gabc after %% (except \n \r...) and 
none of them makes sense. If they occurs it is a corruption of the file 
but may very difficult to detect.
But this is not an important issue.

**Comment by henryso** [comment]
@rpspringuel It seems like {newline}{blank}{newline} is also treated as \par, so I think the pattern for replacement should be (\n|\r)(\t| |\n|\r)*.

**Comment by jakubjelinek** [comment]
But can't somebody have in between <v> and </v> arbitrary TeX stuff, including \par, \n\n etc.?  Changing that in any way would be IMNSHO undesirable?

**Comment by eroux** [comment]
Maybe a good option would be to handle that on the TeX side, by just ignoring new lines... users who do not want this behavior could change it easily

**Comment by henryso** [comment]
The `<v></v>` stuff and `<alt></alt>` stuff can be handled separately from plain text and the text between style tags.  I think it's best to leave the verbose and above lines text alone and only eat repeated newlines for lyric text everywhere else.

**Comment by eroux** [comment]
Good idea yes

**Comment by rpspringuel** [comment]
> It seems like {newline}{blank}{newline} is also treated as \par, so I think the pattern for replacement should be (\n|\r)(\t| |\n|\r)*.

While I didn't think about it, given that TeX automatically ignores blanks spaces at the beginning of a line, that does make sense.
