### ISSUE TITLE
Finer control on notes-text spacing

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1125]
In some cases, a short `spacelinestext` should make `d` pitch considered as a low note adding space between notes and text.

See the following example

``` tex
\documentclass[11pt]{article} %%
\usepackage{fontspec} %%
\usepackage{gregoriotex} %%
\begin{document} %%

% espace au-dessus des lignes
\grechangedim{spaceabovelines}{0.429 cm plus 0.286 cm minus 0.0715 cm}{scalable}%
%the space between the lines and the bottom of the text
\grechangedim{spacelinestext}{0.32 cm}{scalable}%

\gabcsnippet{%
(c4)
Mys(e)té(gh)ri(h)um(hg) fí(h!iwjh)de(gh)i.(h) Vel:(::) Mys(e)té(gh)ri(h)um(h) fí(i)de(h)i.(h) (::Z)
<sp>R/</sp> Mor<alt>Omnes:</alt>(e)tem(g) tu(gh)am(h) an(h)nun(h)ti(h)á(h)mus,(g) Dó(h!iwj)mi(h)ne,(h) (;) et(e) tu(gh)am(h) re(h)sur(h)rec(h)ti(h)ó(h)nem(h) con(i)fi(h)té(gh)mur,(g) (,) do(hf)nec(gg) vé(e)ni(de)as.(e) (::) (g+)
}%
\end{document}
```

in which the `i` merges within the podatus. Of course this example is a bit extreme, but I think having a system similar to what's happening at the top of the staff with (`additionaltopspacealtthreshold`) would fix this issue...

**Comment by henryso** [comment]
There is a request to try to get this specifically into 5.0, so if everyone else is busy, maybe someone can give me pointers to "what's happening at the top of the staff", so I can try to look into this?

**Comment by eroux** [comment]
I think the important description is [this one](https://github.com/gregorio-project/gregorio/blob/24787f35245d7aa395c249eccb477305a5492930/tex/gsp-default.tex#L322). What I remember is that you can define a threshold above which notes will start to move the space above staff lines, if you set it high, no note will change the above staff line space, whatever its height; if you set it to 0, this means that `k` (or `j`, can't remember) will start making the space above staff lines bigger. There should be a similar mechanism for the space between the staff lines and the text. Note that it will possibly be more difficult because the different stem length have to be taken into account... Also, the amount of space it difference with the threshold will add on the spacing should be settable. For instance you should be able to say "all notes below c will add 2mm", something like that... do you see what I mean?

**Comment by henryso** [comment]
Should the space be based on the number of notes before the threshold (e.g., `a` adds 4 mm and `b` adds 2 mm) or is the space just added (e.g., `a` or `b` just adds 2 mm).

**Comment by eroux** [comment]
First option. Also, it would be great if the variables can be tuned per-line. there are a few cases in the italian Antiphonale where the custos is relatively far from the text (horizontally) but is the only very low note `(a)` of the line. In these cases users should be able to say "don't take the custos into account on the first line", by just making the threshold value 99 for this line... do you see what I mean? Also, sorry for the lack of involvement, I'm starting a new job tomorrow and I ended the current one on Friday, so there's quite a lot going on...

**Comment by henryso** [comment]
Note: while I am looking into this, things are slow going as I experiment with stuff.  If anyone has the time and inclination to take this on, please feel free.

**Comment by henryso** [comment]
What should the default be? "all notes below c will add 2mm"?

**Comment by eroux** [comment]
I think it should be all notes below c will add half of the space between staff lines...

**Comment by henryso** [comment]
Maybe it's because I'm misunderstanding what should be done, but given the other spaces, I think half the space between staff lines (which is almost 3 mm with a grefactor of 17) is rather excessive.

![image](https://cloud.githubusercontent.com/assets/421318/22023266/7372c84e-dc93-11e6-90f6-07d1044a014e.png)

In this screenshot, the lowest pitch on the top staff is `a`, so about 6 mm of space (i.e., the space between staff lines) is added.  The bottom staff (where no extra space is added) is there for comparison's sake.

Is this what is desired?

**Comment by henryso** [comment]
Here's how it looks with the feature disabled (by setting the threshold appropriately):

![image](https://cloud.githubusercontent.com/assets/421318/22023683/24bbab2e-dc95-11e6-92d6-16dd00899083.png)

**Comment by eroux** [comment]
Hmmm, it looks like you're modifying the wrong space here... the space that should be set is the space between the baseline of the text and the bottom staff line (the one on `d`).

In your pictures, the space between lines is 10px, half is 5px. The base value of the space according to the second line is 23px. So this means that on the first line, the space should be 23+3x5=38px, while in your image it's 57px... do you see what I mean?

**Comment by henryso** [comment]
Yes, looking at these pictures this way, it's more obvious that I'm doing something wrong.  I'll keep banging my head against it.

**Comment by eroux** [comment]
I think the problem is that the modification of the space looks applied twice: in your second post, when you disable the feature, it seems the space is modified anyway... ?

**Comment by henryso** [comment]
No, when disabled, that picture matches the old expectation from that test.

Looking at the code, I think I am double counting `\gre@pitch@a`.

**Comment by eroux** [comment]
Hmm, yes, but that feature should replace the current modification of the space, not add another modification on top of it!

**Comment by eroux** [comment]
it's just a more convenient way to tune this spacing (and it's necessary for correctly tuning it), it's not really something new...

**Comment by henryso** [comment]
Ok, that was totally unclear from the opening post.  I'll see if I can figure out how to do that.

**Comment by eroux** [comment]
Sorry, I didn't realize it could be interpreted another way! Basically I think the calculation already more or less does this (add half the space between staff lines for each note beneath d), the feature is just to add a way to tune the threshold and the value

**Comment by henryso** [comment]
Ok, then the current calculation is 15750 sp * the number of pitches below c, which I guess this shall be the default.

And this issue is actually requesting that "15750 sp" and "the number of pitches below c" be configurable, correct?

**Comment by eroux** [comment]
yes
