### ISSUE TITLE
Fresh builds from source

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1132]
If a user is trying to install from a repository clone and has never installed gregorio before (and as TL2015 or 2014), they are likely to run into problems when the build script attempts to build the documentation.  Users installing form the distribution tarball are fine, as the docs are pre-built for them.  At the very least, this should be documented for those building from the repository, but it might also be a good idea to have alternate build and install targets which bypass the docs and thus can be done as a first pass.  Thoughts?

**Comment by henryso** [comment]
Documentation should build properly from non-installed gregorio based on a fresh checkout.  Is it broken?

**Comment by rpspringuel** [comment]
Sorry.  Misdiagnosed the problem I was seeing.
