### ISSUE TITLE
interwordspacetext@nonotes

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1137]
It would be very useful to be able to set interwordspacetext and interwordspacenotes in the case where there is no associated note. These would be `interwordspacetext@nonotes` and `interwordspacenotes@nonotes`. Currently the value used is really unclear and bogus, for instance the output of 

```
\documentclass[11pt]{article}
\usepackage{fontspec}
\usepackage{gregoriotex}
\begin{document}
\gabcsnippet{(c3) a(gggggg) *() i(gf)}
\end{document}
```

is

![gregobug](https://cloud.githubusercontent.com/assets/60868/16363036/76261760-3bbe-11e6-9ba9-c6b296737b4a.png)

**Comment by henryso** [comment]
@eroux You might need to take this.  I don't quite understand how the bar spacing algorithm works and how this new dimension would fit into it.

**Comment by eroux** [comment]
sure

**Comment by eroux** [comment]
Let's merge #1147 into this one

**Comment by eroux** [comment]
This is actually a bug, I've updated the description with an example
