### ISSUE TITLE
spaceafterlineclef@close

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1138]
It would be useful to differenciate `spaceafterlineclef` when the notes are "close" to the key or not, for instance in `(c4) (a)` the note is far, and in `(c3) (h)` the note is closed. There are a few corner cases (the second note should be taken in the case of a pes), but it can be made in a very simple way.

**Comment by henryso** [comment]
Can you define how close is close?  For example `(c4)` physically spans `(i)` through `(k)`, so would `(h)` and `(l)` be considered close?  How about `(g)` or `(m)`?  I'm assuming in the case of the pes that "close" applies if *either* note is close, correct?

**Comment by eroux** [comment]
I think `h` and `g` would be considered close yes, but `f` not... You're right about the pes

**Comment by henryso** [comment]
The way I see to implement this, we need to redefine the localleftbox before every glyph.  Is there a better way?

**Comment by eroux** [comment]
Wow, it seems I spoke too fast when I said that it would be easy to implement... I think using the bolshift would be easier, but it's not trivial neither... we can delay that one for later... The real blocking issues for the Antiphonale project are #1141 and #1137, if the others are complex, we can delay them...

**Comment by eroux** [comment]
Thinking about it, this feature poses another big problem: the left-alignment of lines on notes will be broken... The real-life example of this feature was actually for the very first note of a score, after an initial. I think it would be fairly easy to handle this case only, and close this ticket (as breaking the left-alignment looks like a bad idea)... What do you think?

**Comment by henryso** [comment]
In that case, it seems like it would only be applicable for one-line initials, as applying it to the first line of no-initial and two-line-initial scores would break left alignment in the same way.

**Comment by eroux** [comment]
indeed!

**Comment by eroux** [comment]
I think this one is the most important of the remaining features for 4.2, I think I can make the TeX part, the C part would consist only in adding an argument to `\gresetinitialclef` which would be `0` or `1` if the clef and notes can be considered close or not... I think we can just use `0` where there are two clefs or a flat on the clef. @henryso do you think you could make the C part in a branch if you have time?

**Comment by henryso** [comment]
@eroux I will try to work on the C part of this tonight.

**Comment by henryso** [comment]
I created the fix-1138 branch with the changes you requested.  The gabc-gtex tests fail (of course), but no other tests change.  I didn't create a branch in the test repository as I'm sure you'll be doing that after this is completed.
