### ISSUE TITLE
big initial sometimes cutting lines

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1141]
May be related to #1139: using the same TeX file and the gabc file

```
name:Advenit ignis;
%%
(c4) Ad(f!/0)vé(fe)nit(d) *() i(ed~)gnis(c) di(df)ví(f_0fg)nus,(f_) (,) non(f_hz) com(g)bú(fe)rens(fg_) <v>\kern-4pt</v>sed(d) <v>\kern-4pt</v>il(f>)lú(de)mi(dc)nans,(c_z) nec(c) con(cd~)sú(ddo>)mens(c) sed(df) lu(f_0fg)cens,(f.) (;) et(fhgh) trí(g)bu(fe)it(fgf) e(d)is(d_) cha(d)rís(f)ma(fe)tum(de) do(ddo>)na,(c.) (;) al(c)le(d)lú(f_0fg)ia,(fe__) al(g)le(gh)lú(f.)ia.(f.) (::Z-) <eu>E(h) u(h) o(f) u(gh) a(g) e</eu>(f) (::)
```

one gets:

![buggreg](https://cloud.githubusercontent.com/assets/60868/16054877/5adddbe4-326f-11e6-81fb-dcd7133031be.png)

**Comment by rpspringuel** [comment]
Did you compile twice?  I've seen this sort of behavior before and have always found that another compilation gets rid of it.

**Comment by henryso** [comment]
This problem occurs even if you compile multiple times.

**Comment by henryso** [comment]
The more I look at this, the less it seems related to #1139.
