### ISSUE TITLE
reducing notes-bar spacings when notes far from the bar

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1144]
In this extract of a real-life example:

```
name:Redemptor noster;
%%
(c4) tres(f_g) pú(gh)e(gf)ros(d_f!/ddoc) (,) de(c) ca(d)mí(f)no(f) (::)
```

giving this output:

![bug1](https://cloud.githubusercontent.com/assets/60868/16078591/1f4123a2-3300-11e6-93b0-b0eb329b7b9c.png)

the notes around the bar could be close to each other because they are far from the bar.

This would introduce:
- `bar@virgula@standalone@notext@lownotes`
- `bar@minima@standalone@notext@lownotes`
- `bar@virgula@standalone@text@lownotes`
- `bar@minima@standalone@text@lownotes`

(no emergency for this one!)

**Comment by henryso** [comment]
While it's fresh in your mind, what is considered a low note?  Should it be configurable?  If so, what should be the default?

**Comment by eroux** [comment]
I think notes from `a` to `f` could be considered low... I don't think it needs special configuration no...

**Comment by jakubjelinek** [comment]
How would more complex neumes be treated though?  E.g. for pes it is low note if the upper note is low note, what about clivis, etc.?

**Comment by henryso** [comment]
@eroux I'm assuming you mean for a 4-line staff, and that this should change appropriately for 2-, 3-, or 5-line staves.

@jakubjelinek I think in the general case, you would need to go by the last note in the glyph before and the first note in the glyph after, unless the first glyph is a pes, in which case you go by the second note.

**Comment by eroux** [comment]
@henryso indeed, and you're right for notes determination

**Comment by jakubjelinek** [comment]
Yeah, though not just for pes, but also e.g. for liquescences - for `feh~` h, but for `fed~` e, not d.

**Comment by eroux** [comment]
That's true indeed...

**Comment by henryso** [comment]
@jakubjelinek Agreed, it's more complex than I thought.
