### ISSUE TITLE
interwordspacenotes@nonotes

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1147]
In cases such as `te(gg) *() fi(g)` the space (and rubber) used between the notes of the two syllables, I think it should be a new `interwordspacenotes@nonotes`

**Comment by henryso** [comment]
How is this different than #1137?

**Comment by eroux** [comment]
#1137 is for text (I rephrased it)

**Comment by eroux** [comment]
let's close it and consider it merged into #1137
