### ISSUE TITLE
Nabc vertical position should not depend on the pitch of the gabc notes

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#1153]
As has been reported on gregorio-users, when a score line contains l or higher notes, the <alt> baseline seems to be moved above (verified already in 4.1), which is not bad for <alt>, but undesirable for nabc, which has a way of positioning the neumes vertically.
Wonder if it is \gre@dimen@additionaltopspacealt and \gre@space@count@additionaltopspacealtthreshold that matters in this case.  If yes, wonder if we could not then duplicate/modify the \GreSetTextAboveLines and \def\gre@typesettextabovelines macros as well as add additionaltopspacenabc* variants of the above (use Nabc or nabc instead of Text and text), so that it could be configurable differently for nabc.  And by default use higher treshold.
Could this still be done for 4.2?

**Comment by henryso** [comment]
Copied from gregorio-project/gregorio-test#242, the following changes to the documentation are necessary:

- `additionaltopspacenabcthreshold` should be added as a new count to Command_Index_User.tex
- `\gre@typesettextabovelines` should be updated (to document the `#2` argument) in Command_Index_internal.tex
- `\GreSetNabcAboveLines` should be added to Command_Index_gregorio.tex
