### ISSUE TITLE
tuning `spacelinestext` on a per-line basis

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1156]
In some rare cases, `spacelinestext` (including the adjustments gregorio makes) are not optimal, and a tuning must be done by hand, but I don't think it is possible with the current state...  This would be needed in case where, for instance, a very low note meets a very high letter (with an accent).

Looking at [this thread](https://mail.gna.org/public/gregorio-users/2016-06/msg00033.html) I think the same should be done for the other vertical spaces such as `abovelinestextraise` or the different future nabc heights.

My feeling is that a macro could just store these user values in a lua table, emptied at each end of score, and these could be used in the lua second pass. From this very general point of view it seems easy so it could fit into 4.2, but if it's more complex, this could go into 5.0.

**Comment by henryso** [comment]
Can you describe the syntax?  Are you expecting texverbs here?

**Comment by eroux** [comment]
Oh, no, I was thinking about something like `\grelocalchangedim{dim}{value}{linenum}`, but maybe there are some better options...

**Comment by henryso** [comment]
I'll use the command `grechangenextscorelinedim{line}{dim}{value}{mod}` since I think that name is more obvious.

**Comment by eroux** [comment]
Apart from the comment on the doc, this looks wonderful, this will really help in some edge cases in which there was previously no solution at all!
