### ISSUE TITLE
pressus cistercianus

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1174]
I received a mail from a cistercian abbey who is in the process of reediting the Cistercian Graduale with Gregorio, they'll use the shape `(g@e)` for pressus (they will use no oriscus). I don't think there's any real problem, but I'm thinking maybe it could be pre-built into the font? No emergency at all, this ticket was also to share the good news!

**Comment by henryso** [comment]
How would you notate this in gabc, sans fusion, in order to recognize it as a unique family of glyphs?  This changes the C code and gabc syntax as well, and adds 20 glyphs (I think).

**Comment by henryso** [comment]
Looking at this further, won't `(@ge)` suffice?  That's already a single glyph in the font.

**Comment by eroux** [comment]
In fact `(g@e)` is fine, the point was just to make it use a pre-composed glyph, but it's not really crucial...

**Comment by eroux** [comment]
But `(@ge)` is fine too, so I think documenting it will be enough...

**Comment by henryso** [comment]
This is already documented.  The statement is:
```
Placing the @ character before a primitive that would get a stem will suppress the
stem. Given the above list of primitives, this means the ﬂexus and the porrectus.
```
Should I change the documentation?

**Comment by eroux** [comment]
This part is ok, but I'm affraid noone looks at this, especially this French Abbey with certainly 0 person speaking an average English... So I was thinking more about the cheat sheet, or somewhere on the website along with a list of glyphs.

**Comment by henryso** [comment]
Closing this in deference to gregorio-project/gregorio.github.io#41.
