### ISSUE TITLE
Unison following an oriscus should point downwards.

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#1177]
In a recent email on the mailing list, Sr. Maria Ruth OSB brings up a point that, if the note *following* an oriscus is at the same pitch, the oriscus should point downwards.  Currently it points upwards, but this shouldn't be hard to fix.

@eroux are you able to get confirmation from your contacts?  If confirmation can come soon, I should be able to fix this for 4.2.

**Comment by henryso** [comment]
References:

The recent post: https://mail.gna.org/public/gregorio-users/2016-07/msg00026.html (and its follow ups)

A two-year-old post mentioning this rule: https://mail.gna.org/public/gregorio-users/2014-08/msg00052.html

**Comment by eroux** [comment]
thanks, I've asked my contacts

**Comment by eroux** [comment]
The Italian Antiphonale Monasticum gave its go, and Solesmes did too, so let's implement it. According to Solesmes, it may be possible to refine that into setting the direction according to the note after the next one (if there is no such note, then descendent), but I think we can discuss it for 5.0 and just make descending for 4.2...
