### ISSUE TITLE
Oriscus leading to a unison should point in the direction of the following note

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#1179]
Following up on #1177, Solesmes suggests that, if the note after an oriscus is at the same pitch as the oriscus, then the oriscus should point in the direction of the note following the note after the oriscus.

If no note follows, the oriscus should point downwards.

**Comment by henryso** [comment]
Open question: does this refer to the note after the unison note or the first non-unison note after the oriscus.

**Comment by eroux** [comment]
Certainly the second case, but it would be a bit far-fetched... It's best to wait for confirmation before implementing that I think... (I'll ask when things will have settled down for 4.2)

**Comment by eroux** [comment]
I'm not entirely sure we should keep it open, what do you think about closing it as wontfix? We can reopen it later if someone asks for it...

**Comment by henryso** [comment]
Let's close this as wontfix and reopen if needed.

**Comment by eroux** [comment]
reopening as Solesmes now has an example where it would be useful:

![coriesu](https://cloud.githubusercontent.com/assets/60868/23096588/ee24e950-f61f-11e6-90be-65691ef07ef5.png)

**Comment by eroux** [comment]
(there's also a problem with the first glyph of this score, I've asked my contact at Solesmes to report it directly on the github issue tracker)

**Comment by henryso** [comment]
Have you received confirmation on your point from 7 July?

**Comment by eroux** [comment]
I don't really know... I guess we can implement the first non-unison note algorithm
