### ISSUE TITLE
remove translation system?

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#118]
There is a translation system for the messages (errors, warning and help) output by gregorio, but it's never been used in 7 years... maybe we should just remove it? I don't think it's really helpful, and it would simplify the build process. What do you think?

**Comment by eroux** [comment]
adressed by #120

**Comment by henryso** [comment]
I assume that the translations are out of date (if there at all), but how difficult would it be to put the translation system back in when Gregorio rules the world and we have an army of translators?

**Comment by eroux** [comment]
Gregorio uses the GNU gettext system in its very common form, it's very easy to set up... No translations were ever available, and I really don't think they will be necessary one day: with the new `\includescore`, people won't even know the `gregorio` command exists, and will thus never care about the very rare messages it issues sometimes...

**Comment by henryso** [comment]
As long as it's not difficult to put back in, then I agree. Scrap it.

**Comment by eroux** [comment]
Ok, let's wait a few hours for comments, and I'll merge #120

**Comment by rpspringuel** [comment]
If it wasn't being used in the first place, then I'm all for removing it.

**Comment by eroux** [comment]
It would be easier for me to fix the release system (debian, make distcheck, etc.) if I could merge it into release-3.0 too. What do you think?

**Comment by henryso** [comment]
Because of where that was branched, it would pull in some of my changes in develop.  I don't think we should destabilize this release by doing that.  I will try cherry-picking your change against release-3.0 and see if it works against my complex project.

**Comment by rpspringuel** [comment]
I agree with @henryso.  This is background enough that I think it could be included in the release (i.e. it doesn't really constitute a new feature), but it has to be cherry picked in.

**Comment by eroux** [comment]
cherry picking works fine, I did it in my fixdebian branch, so we'll discuss that in the corresponding pull request (tonight I believe)

**Comment by henryso** [comment]
I ran https://github.com/henryso/gregorio/tree/test-merge-remove-nls through my large project and the https://github.com/gregorio-project/gregorio-test test cases, and it seems so be fine.  I'm fine with cherry-picking this into release-3.0.

**Comment by eroux** [comment]
Done in #133

**Comment by eschwab** [comment]
NLS removed with #120
