### ISSUE TITLE
sha1.c fails to build with clang on OS X Lion

### ISSUE THREAD

**Issue by mojca** [gregorio-project/gregorio#1185]
See https://trac.macports.org/ticket/51779 (which also includes a patch).

Building of gregorio with clang fails on Lion (more precisely, with Xcode >= 4.3 and < 5) with the following error:
```
gregorio-src/src/sha1.c:171:13: warning: implicit declaration of function 'alignof' is invalid in C99 [-Wimplicit-function-declaration]
        if (UNALIGNED_P(buffer)) {
            ^
gregorio-src/src/sha1.c:170:43: note: expanded from macro 'UNALIGNED_P'
#define UNALIGNED_P(p) ((uintptr_t) (p) % alignof (uint32_t) != 0)
                                          ^
gregorio-src/src/sha1.c:171:13: error: unexpected type name 'uint32_t': expected expression
        if (UNALIGNED_P(buffer)) {
            ^
gregorio-src/src/sha1.c:170:52: note: expanded from macro 'UNALIGNED_P'
#define UNALIGNED_P(p) ((uintptr_t) (p) % alignof (uint32_t) != 0)
                                                   ^
1 warning and 1 error generated.
```

**Comment by jakubjelinek** [comment]
Then it should better test __alignof_is_defined macro.  Though, for __cplusplus >= 201103L, alignof will not be a macro and __alignof_is_defined will not be defined either, yet alignof will be a keyword and will work.  So if future C++ compatibility is desired, it should be:
```
#ifdef HAVE_STDALIGN_H
#include <stdalign.h>
#ifdef __clang__
#pragma clang diagnostic ignored "-Wc11-extensions"
#endif
#endif
#if !defined (__alignof_is_defined) && __cplusplus < 201103L
#define alignof(x) sizeof(x)
#endif
```

**Comment by henryso** [comment]
Maybe it would be better to have autotools check for alignof?

**Comment by jakubjelinek** [comment]
That would work too, sure.  __alignof_is_defined is a macro mandated by C11 though, so it isn't relying on some implementation detail.  And, if llvm used to ship some non-conforming C11 stdalign.h, it surely didn't define that macro in there if it didn't define also alignof macro.

**Comment by jakubjelinek** [comment]
You could also define alignof to `__alignof__` for `__GNUC__ >= 3`.

**Comment by henryso** [comment]
Another option might be to use offsetof, but I have to check compatibility with C89, our target language level.

**Comment by mojca** [comment]
May I please ask for a minimal example to test the functionality, so that I can test different compilers?

The clang compiler as shipped by OS X/Xcode kind-of supports C++11, but one has to switch to libc++ (which is not the default). So some "crippled C++11-alike functionality" is there which often confuses "ifdefs" in software (it sees that some feature A (not in C89) is available, but then fails to compile because of another missing feature B).

**Comment by jakubjelinek** [comment]
If you mean:
```
#include <stddef.h>
struct Swhatever { char c; uint32_t i; };
```
and replacing `alignof (uint32_t)` with `offsetof (struct Swhatever, i)`, then it will often work, unless packed pragma is in effect or the default, but it is not necessarily the same on all architectures.
E.g. on i?86-linux, not for uint32_t, but for double or long long, offsetof will return 4, so will alignof, but __alignof__ will return 8, sizeof too.  offsetof is portable even in C89 (you just can't use it on C++ non-PODs), not aware of any compiler not supporting that.  In any case, this is used just as an optimization, it is unlikely some ABI has uint32_t alignment requirements larger than its size, so sizeof should be a conservative enough default.

**Comment by henryso** [comment]
In that case, perhaps it's best for autotools to probe alignof as an operator, then __alignof__ as an operator, then alignof as a macro in stdalign.h, and finally a fallback to sizeof.

@mojca Once we settle on a solution, I'll try to pull together something for you.

**Comment by henryso** [comment]
After more searching, it seems I can do something like AC_CHECK_ALIGNOF(uint32_t) in autotools to define ALIGNOF_uint32_t.  @jakubjelinek: are you aware of any reason that shouldn't work?

**Comment by jakubjelinek** [comment]
Would that work?  For the uint32_t type you need some headers, so you'd probably need to tweak the second argument of AC_CHECK_ALIGNOF, and it will use offsetof (only) anyway.
So it would be easier to use offsetof directly in the source instead.

**Comment by henryso** [comment]
I tried it out, and `AC_CHECK_ALIGNOF` generates code in configure which uses `ac_includes_default`, which includes `stdint.h`.  On my system, using gcc ...
```
gcc (Gentoo 4.8.5 p1.3, pie-0.6.2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
... or clang ...
```
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
```
... yielding ...
```
checking alignment of uint32_t... 4
```
... in both cases.

**Comment by jakubjelinek** [comment]
Does it also include inttypes.h if stdint.h is not available though?  uint32_t might be defined in stdint.h, or inttypes.h ...

**Comment by henryso** [comment]
Yes, it does:
```
ac_includes_default="\
#include <stdio.h>
#ifdef HAVE_SYS_TYPES_H
# include <sys/types.h>
#endif
#ifdef HAVE_SYS_STAT_H
# include <sys/stat.h>
#endif
#ifdef STDC_HEADERS
# include <stdlib.h>
# include <stddef.h>
#else
# ifdef HAVE_STDLIB_H
#  include <stdlib.h>
# endif
#endif
#ifdef HAVE_STRING_H
# if !defined STDC_HEADERS && defined HAVE_MEMORY_H
#  include <memory.h>
# endif
# include <string.h>
#endif
#ifdef HAVE_STRINGS_H
# include <strings.h>
#endif
#ifdef HAVE_INTTYPES_H
# include <inttypes.h>
#endif
#ifdef HAVE_STDINT_H
# include <stdint.h>
#endif
#ifdef HAVE_UNISTD_H
# include <unistd.h>
#endif"
```

**Comment by henryso** [comment]
@mojca See https://gist.github.com/henryso/77ee1a31b4e88d16c72ad4e68c50a217 for the minimal sample you wanted.

**Comment by henryso** [comment]
@eroux and/or @rpspringuel Should this change be 4.2 or 5.0?

**Comment by eroux** [comment]
Well, I don't know... maybe 4.2 is safer (in the sense that it will prevent people from having problems with the final version)?

**Comment by rpspringuel** [comment]
If we can get confirmation that the fix works for the OP (and it doesn't break on any of our systems) then I say this can go into 4.2 as a bug-fix.

**Comment by henryso** [comment]
I created a pull request with the changes.  Please try it when you have some time.

**Comment by mojca** [comment]
Wonderful, I like the simplification a lot. In particular the fact that it doesn't do any weird acrobatics with compiler detection (and if anything goes wrong, you can always blame autotools).

As expected all the compilers I have (a tested quite a few) return `pass (4)`. Thank you. I'll try to invest some time into creating a patch for `texlive-bin` for MacPorts and try to test there directly (I need to create a patch for the relevant configure files).
