### ISSUE TITLE
first note alignment with c and f clefs

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1189]
In the following example:

```tex
\documentclass[12pt, a5paper]{book}
\usepackage{libertine}
\usepackage[autocompile]{gregoriotex}
\grechangestaffsize{16}
\pagestyle{empty}
\begin{document}
\gabcsnippet{(f3) Res(f) est(e) ad(f)mi(h)rá(gf)bi(e)lis(f) vir(i)go(h) ve(g)ne(f)rá(hg)bi(f)lis(e) (z0c4) pa(c)rit(e) sed(d) in(h)tác(gfg)ta.(f.) (d+::f3) Si(f)ne(e) vi(f)ri(h) có(gf)i(e)tu,(f) ple(i)na(h) San(h)cto(f) Spí(hg)ri(f)tu,(e) gé(c)ni(e)trix(f) est(h) fac(gfg)ta.(f.) (::)}
\end{document}
```

giving

![buggregorio](https://cloud.githubusercontent.com/assets/60868/17017522/f186ccfa-4f33-11e6-868d-393700a52a07.png)

the first note of the lines is at the same distance of the clefs, but when there is a mix of c and f clefs, the consequence is that they are not aligned. I see a few ways to fix it:

- one is manual: the user calls `\gregoriobolalignonfclefs` and the next score has all beginning of lines aligned as if they were f clefs
- one is automatic (but optional): calling a function `\GreScoreContainsFClef` at the beginning of each score containing an f clef
- one is even more automatic with two pass: the first detects if an actual f clef appears in the score, then the second adjusts things

I think the second one is the best... what do you think? (it should be optional though)

**Comment by eroux** [comment]
Thinking more about it, there should also be a user-level command like `\grealignboloncleftype{x}` where `x` is

- `auto` for the current case
- `c` to force alignment on c clef only
- `f` to force alignment on f clef
- maybe also `cc`, `cf`, `ff`, etc.? not sure about that...

the idea is that this function could be called in the middle of a score in the case where you want a different behavior in the middle of a score if there's a page change (with an f clef on the first page but only c clefs on the second page). The function would be called in a verbatim

**Comment by eroux** [comment]
In fact the most generic (and precise) way to do that would be to add a `\GreSetLargestClef` at the beginning of the score, with the same arguments as `\GreSetInitialClef` but corresponding to the largest clef... That would be the only required change in C, the rest would be in TeX. @henryso do you think we could share this one, you for the C side, I'll do the TeX side?

**Comment by henryso** [comment]
Sure.  I'll try to work on it this weekend.

**Comment by henryso** [comment]
Does the `#7` argument make sense for `\GreSetLargestClef`?  If so, can you describe the desired semantics?

**Comment by eroux** [comment]
Well, I think it has the same meaning as `#4`...? I'm not really sure I'm following...

**Comment by henryso** [comment]
`#7` is 0 if the clef and first note are far enough to use a shorter space or 1 otherwise.

**Comment by eroux** [comment]
Well, the idea here is to have exactly the same arguments as would be typeset in another context, so the arguments should be exactly the same as the arguments with which `\GreSetLineClef` was called on the largest clef... do you see what I mean?

**Comment by henryso** [comment]
I see what you mean, but '`#7` is specific to the first note of the score.  If `\GreSetLargestClef` will be typeset in place of `\GreSetInitialClef`, then I should make `#7` depend on the first note of the score there also.  If it is to be typeset elsewhere, then `#7` probably doesn't make sense at all.

**Comment by henryso** [comment]
Put another way, `\GreSetLinesClef` only takes six arguments.  The seventh argument is used in `\GreSetInitialClef` here:
```
      \ifnum#7=1\relax %
        \gre@typeclef{#1}{#2}{0}{1}{#3}{#4}{#5}{#6}%
      \else %
        \gre@typeclef{#1}{#2}{0}{2}{#3}{#4}{#5}{#6}%
      \fi %
```

**Comment by eroux** [comment]
oh sorry, I misread, well you can make it `0`

**Comment by henryso** [comment]
OK.

**Comment by henryso** [comment]
Since this is a new macro, I'll just omit the seventh argument.  You can always synthesize it as necessary in TeX.
