### ISSUE TITLE
Flat hole placement incorrect

### ISSUE THREAD

**Issue by rarty** [gregorio-project/gregorio#1192]
The FlatHole glyph is printed all the way down at the bottom of the score, using `Gregorio 4.2.0-rc2-develop-a74fc5a-1`.

![texshop_image](https://cloud.githubusercontent.com/assets/6454162/17119313/b9d7115c-528a-11e6-989c-6188371a5e6d.png)

```
\documentclass[12pt]{article} 
\usepackage{libertine}
\usepackage[allowdeprecated=false]{gregoriotex}
\begin{document}
\gabcsnippet{(c4) Dó(f)mi(gh)ne(h_) (,) ad(h) ad(h)iu(h)ván(h)dum(h) me(ixg!hwi) fe(h)stí(hg)na.(gh..) (z0::f3) lllll{l}(dxb!cwd) (::)}
\end{document}
```

**Comment by rpspringuel** [comment]
I can reproduce this on the develop branch, but not on release-4.2.  It thus is most likely related to the new hollow glyph system.
