### ISSUE TITLE
glitch in \gre@setinitial

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1202]
Report from @OldClaudio:

The start of `\gre@setinitial` (in `gregorioriotex-main.sty` file), that is responsible of actually inserting the commentary over the first staff is as such:

```
\def\gre@setinitial#1{%
    % see comments on this function to see what it does
    \gre@debugmsg{commentary}{Time to calculate the true raise.}%
    \gre@calculate@commentarytrueraise%
    % we start by printing the commentary
    % when doing this we place it inside a box as which is linewidth wide with an \hfill before to get it to align to the right of the page
    % we then place that box inside one of 0 width so that our cursor doesn't move when we place the commentary
    \ifvoid\gre@box@commentary\else%
        \gre@debugmsg{commentary}{I am printing a commentary box}%
        \raise\gre@dimen@commentarytrueraise\hbox to 0pt{\hbox to \gre@dimen@linewidth{\hfill\box\gre@box@commentary}}%
    \fi%
```

The line before the last one (`\raise...`) appears to me to be wrong, to the point that the log file reports a bad hbox exceeding the linewidth by another linewidth.

In facts `\raise` raises the external hbox by `\gre@dimen@commentarytrueraise`. Such box is defined to be 0pt wide; its contents is another hbox which is declared to be `\gre@dimen@linewidth` wide. But the external hbox does not contain any glue to shrink to 0pt. I think the statement should be modified by adding the `\hss`  special glue that has a zero natural width and a first order infinite stretch and shrink components; I suggest:

```
  \raise\gre@dimen@commentarytrueraise\hbox to 0pt{\hbox to \gre@dimen@linewidth{\hfill\box\gre@box@commentary}\hss}%
```

Remember that `\hss` is an (almost primitive) glue value used also by plain TeX; therefore there is no problem with the users who use luatex instead of lualatex to typeset their documents while using gregoriotex

**Comment by rpspringuel** [comment]
You are correct that an `\hss` should be introduced, but I would check to see if it should be before or after the inner `\hbox`.  I suspect that one of those positions will mess up the flush right alignment of the commentary.

**Comment by eroux** [comment]
Ok, can I assign the issue to you?

**Comment by OldClaudio** [comment]
Exactly to the right of thr inner box; when I wrote to Élie to notify 
him le little bug, I had already tested the solution I was proposing.
Notice that \hbox to 0pt{#1\hss} is the definition of the \rlap (right 
overlap) box of zero width with its contents protruding to the right; if 
its argument is a box of specified width, this whole box will protrude 
to the right without any secondary effect on the alignment of its 
contents, or the alignment of the whole commentary.

All the best
Claudio
