### ISSUE TITLE
problems when final syllable has no notes

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1205]
The following example:

```
\documentclass[a5paper, 12pt]{book}
\usepackage[autocompile]{gregoriotex}
\begin{document}
\gresetinitiallines{0}
\gabcsnippet{(c4) Ma(i)rí(kko>)a!(j.) R(::) Salve Mater.()}
\end{document}
```

produces the strange result:

![buggregorio](https://cloud.githubusercontent.com/assets/60868/17659341/2302c638-62d2-11e6-9c85-10ee840e5f48.png)

I think this is because of the way `\GreLastOfScore` is handled...

**Comment by eroux** [comment]
(originally from [this thread](https://www.mail-archive.com/gregorio-users@gna.org/msg03711.html))

**Comment by eroux** [comment]
The problem disappears if `\GreLastOfScore` is not called before the bar, so I think it should probably not be output by gregorio in this case, but I'm not sure what the consequences would be on other edge cases... @henryso what do you think?

**Comment by henryso** [comment]
I'm not sure I'm the best person to opine on that, but I can try to make the change and see what tests it breaks.  I take it this is for 5.0?

**Comment by eroux** [comment]
Well, I would prefer 4.2, but if you think this is too much, then 5.0 is fine

**Comment by henryso** [comment]
No I can do it in 4.2, but the milestone is not set, so I wasn't sure.

**Comment by henryso** [comment]
From reading the description, I think this *might* conflict with #1116.

**Comment by henryso** [comment]
If the check is only for syllables that follow, this breaks `(g) (Z)`, which would cause a dummy custos to be emitted at the end of the last line.  As a result, I will check that there are no elements after the `\GreLastOfScore` element before suppressing it.
