### ISSUE TITLE
Release 4.1.5?

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1209]
Should we create a 4.1.5 release?  Several of the fixes that are pending or going into 4.2 would be compatible with 4.1 and thus could be pushed to CTAN.

If we were to create a 4.1.5 I would include the following:

* #1201 
* The fixes for #1199 (94c4288 and ca8b226 and a local commit on my machine)
* 54bc8b8
* 30bd15d
* f96b2c2
* Documentation mods from fc54014

**Comment by henryso** [comment]
I tend to favor this, but I think we should have a long-lived "ctan" branch for it, so that when 4.2 becomes master, we still have a "live" branch for what's on CTAN.

**Comment by eroux** [comment]
Ok for me too, I don't really have an opinion on the branches, do as you prefer

**Comment by rpspringuel** [comment]
I created a PR against master with the changes I proposed above.  I also named the branch `ctan` as suggested.  For now said branch is just in my fork, but if we go through with this I'll push it into the main repository.

**Comment by rpspringuel** [comment]
I'm coming across something weird in terms of backwards compatibility with TL2015.  I'm still trying to isolate the problem and will let you know when I've figured out the cause.

**Comment by rpspringuel** [comment]
Okay, the backwards compatibility issues were localized to my machine and not symptomatic of the release itself.
