### ISSUE TITLE
remove compiled files from repository?

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#121]
Having compiled filles (doc/UserManual.pdf, fonts/*.ttf) in the repository seems like a anti-pattern to me, and make it a bit bloated (very long to clone).

The reason why I added fonts in the repository was because:
 * the build process used to be extremely convoluted (needed `perl`, some obscure tools for `ofm`, etc.)
 * due to the extremely slow release cycle, most people were using the svn version, and couldn't build the fonts

But the situation is different now:
 * the build process only requires `python-fontforge`
 * the new release cycle will drastically lessen the need for using the git version

So I propose to remove the compiled files from the repository, but to build and include them in the source code release (`make dist`).

What do you think?

**Comment by henryso** [comment]
I agree this is an anti-pattern.  People using the current `cd fonts; make install` process were likely building fonts anyway.  UserManual.pdf seems easily buildable as well.  I'm fine with removing them both.  Of course, the various build scripts will need to be modified to make sure fonts are built.

**Comment by eschwab** [comment]
Fine with me. The current state of the UserManual is not 100% user friendly, so no harm in dropping the pdf.

**Comment by rpspringuel** [comment]
Are we making the assumption then that if you're installing from the repository then you're rebuilding everything?  I don't think that's necessarily a bad assumption, but we might want to make it clear in the installation guide (i.e. the website) that that's what you're doing.

**Comment by eroux** [comment]
Yes, I think we can make that assumption and document it.

**Comment by eroux** [comment]
what branch should I target for this? develop?

**Comment by henryso** [comment]
If we do this in release-3.0, then the install instructions (on the website) should have separate `make` and `sudo make install` commands for the fonts directory.  If for develop, those instructions will have to change anyway (but to something else entirely).

**Comment by eroux** [comment]
Not really, the distributed tarball will have the generated files (the one made with `make dist`), so make in the fonts directory won't be necessary

**Comment by henryso** [comment]
Ok, so then the instructions will changed to be based on a tarball rather than git.  So no autoreconf.  Fine.

**Comment by eschwab** [comment]
If it cleans up the install process, I'm in favor of doing it in release-3.0. Makes more sense to change the release/install process with a major version release. I know there really should not be new features introduced into release-3.0 but since we just adopted our new git workflow I'm fine with it.

**Comment by rpspringuel** [comment]
I agree with @eschwab.  While it's "technically" too late for new features for 3.0, I say that a major release is a perfect time to change the installation instructions and we should make an exception.

Indeed, we might want to incorporate @henryso's updated installation scripts too.

**Comment by eroux** [comment]
Agreed for the new installation scripts

**Comment by rpspringuel** [comment]
Should `.pdf` and `.ttf` be added to `.gitignore`?  That way when we rebuild these files on our personal systems they don't get added back to the repository.

**Comment by eroux** [comment]
Indeed, I'll do that (unless someone else does)

**Comment by henryso** [comment]
If you'd like me to cherry pick the changes for the installation scripts into release-3.0, let me know, but I won't be able to get to it for about nine hours (01:00 UTC).

**Comment by eroux** [comment]
I've done that in the fixdebian branch, so no need. Thanks!
