### ISSUE TITLE
minimal width of initial

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1213]
A request from Solesmes: it would be useful to be able to set a minimal width for an initial, so that there is no big difference between an I and an M as intials, and make a more coherent output.

**Comment by rpspringuel** [comment]
Setting `manualinitialwidth` should do this.  Has this been tried and found to be not working (in which case this is a bug report, not an enhancement request)?

**Comment by eroux** [comment]
I'm not really sure it's exactly the same, `manualinitialwidth` sets the width, here it would set the minimal width, meaning that initials can grow larger, but not smaller than the minimal value

**Comment by rpspringuel** [comment]
Ah, that is a bit different and not what `manualinitialwidth` does.

A work around would be to use the illumination feature to fill the initial box manually and include a horizontal strut which would set the width of the box.  However, the enhancement itself would not be hard to implement.  How do you see it interacting with `manualinitialwidth`?

**Comment by eroux** [comment]
the interaction is quite the problem indeed... maybe we could avoir the problem by taking `manual` when set whatever the value of `minimal`?
