### ISSUE TITLE
missing episemi bridges

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1216]
The following MWE:

```tex
\documentclass[12pt, a5paper]{book}
\usepackage{libertine}
\usepackage[autocompile]{gregoriotex}
\begin{document}
\gabcsnippet{(c4) no(ghF_E_D_g_e_!/f_g)bis(f.) (;) men.(f_e_!/0hv_hs!hs) (::)}
\end{document}
```

gives the result

![buggregorio1](https://cloud.githubusercontent.com/assets/60868/18266905/14b89ec0-741d-11e6-8450-3c617e9a187f.png)

in which two vertical episemi bridges are missing

**Comment by henryso** [comment]
The first break is because the bridge breaks across elements (i.e., the bridge currently only crosses glyphs).  Should the punctum-inclinatum-to-something-else transition continue break the element (and thus the bridge be modified to cross elements) or should the transition be modified to only break the glyph?

The second break is because the code is not bridging across for the half space, so that fix is clear.

**Comment by eroux** [comment]
Well, to be honest I'm not entirely sure what's the best behavior here... There should be a way to make a bridge, but I'm not sure if gregorio should make one by default and then the user should break it if necessary, or if in these cases the current behavior is ok and there should be a `_7` to force a bridge... maybe the first solution is the best one?

**Comment by henryso** [comment]
The simpler solution is to extend the bridge across elements by default(but not across syllables) and let the user break the episema if necessary (i.e., with `!`). However, it is possible, though more complex (both in the code and in the gabc syntax), to break the bridge through elements by default with a user override to force the bridge.

**Comment by henryso** [comment]
After debugging further,  I was wrong about the cause of the second issue.  After the element thing is fixed, it will affect the first issue as well.

Per https://github.com/gregorio-project/gregorio/pull/401#issuecomment-101712617, bridging across a space will only occur if the ambitus is less than 3.  Should I change that?

**Comment by henryso** [comment]
After debugging even further, I think this ambitus fix is pretty clean, so I'll create a pull request.  If you agree with the change, please review and merge.

**Comment by eroux** [comment]
merged, thanks a lot!
