### ISSUE TITLE
remove OpusTeX and GregorioXML support?

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#122]
I don't think these two are used by anyone, I think we should drop them in order to reduce the code base and make it less frightening... What do you think?

**Comment by henryso** [comment]
I think we should ask the list to avoid surprises.

**Comment by eroux** [comment]
Agreed

**Comment by eroux** [comment]
Apparently noone on the list is using it... Should we remove it it 3.0 or wait for next minor or major release? At least we could make them as deprecated in the changelog?

**Comment by eschwab** [comment]
Marking as deprecated and removing later would give more time to avoid surpises.

**Comment by henryso** [comment]
Let's deprecate them in this release, no promises that is works for you.  That way, we don't need a major release to finally get rid of them.

**Comment by eroux** [comment]
Ok, let's do that

**Comment by rpspringuel** [comment]
A bit late, but I agree with depreciation before removing as obsolete.

**Comment by eschwab** [comment]
Deprecated by #133 

Still to be removed in the future.
