### ISSUE TITLE
glyph determination improvement when invalid oriscus

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1220]
The following MWE:

```tex
\documentclass[12pt, a5paper]{book}
\usepackage{libertine}
\usepackage[autocompile]{gregoriotex}
\begin{document}
\gabcsnippet{(c4) A(g)men.(hogh.) (::) A(g)men.(hog!/h.) (::)}
\end{document}
```

gives

![bug](https://cloud.githubusercontent.com/assets/60868/18344922/948fa632-75b9-11e6-8c3f-21edb887f930.png)

while the first should be equal to the second according to the people working on the Italian Antiphonale project. I kind of agree: when a user typesets an o, it probably shouldn't be ignored. But this complexifies the glyph determination process I'm affraid... @henryso what do you think? It's not really top priority, as it's easy to work around.

**Comment by henryso** [comment]
I think this will add only minor complexity.
