### ISSUE TITLE
Install uninstall-gtex.sh into texmf tree?

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#1223]
Now that I added the code to generate an uninstall manifest (see #1217), should this script be installed into (and therefore also delete itself from) the texmf tree into which it installed GregorioTeX?

This would make the TDS installation different from the command-line installation, but it would seem to be a good place to install the manifest for easier uninstall of GregorioTeX.

If we do this, I presume it would be under `scripts/gregoriotex`?

**Comment by henryso** [comment]
Any thoughts on this?

**Comment by rpspringuel** [comment]
I'm not sure what you mean by the installations being different, but I agree that it makes sense to put the uninstall script somewhere on the user's system so that they can find it if they need it. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
@rpspringuel What I mean by "different" is that the TDS zip file will not have this uninstall script in it, so it you install by unzipping the TDS zip into an appropriate place, you will not have the uninstall script.  You will only get the uninstall script if you install directly using `install-gtex.sh`.

**Comment by rpspringuel** [comment]
Is there some reason why we can't include the uninstall script in the TDS file?

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
It wouldn't make any sense.  The paths to the installation are unknown.

**Comment by rpspringuel** [comment]
Absolute paths, yes.  But if the script is inside a TDS structure, then it should know the relative path to other files in the same structure. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
If that's how you want it, then the only way I can see that working is to have two *different* scripts.  So it'll still be different, but I guess that's OK?

**Comment by rpspringuel** [comment]
Why would we need two different scripts?  Is there some condition under which the script in the texmf tree (with relative paths) isn't enough and a script outside the texmf tree with absolute paths would be desirable?

I'm not sold on any particular solution at this point, I'm just trying to understand what our options are.

**Comment by henryso** [comment]
The script currently changes to the texmf root (that was passed to `install-gtex.sh`) and deletes files using relative paths.  The script in the TDS zip will need logic to compute the texmf directory from the directory of the script itself rather than using the path passed to `install-gtex.sh`.

Thinking about it as I type this, I suppose the script can simply always put in this computation logic; then it wouldn't be different.  I'll consider this and try to make the changes later this week.
