### ISSUE TITLE
Is it possible to run Gregorio before installing it?

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#123]
When I was adding the code to protect against clobbering the input file, I ran into a problem running Gregorio from its compiled location.  I had to build and install it to some user directory in order to test it out.  Is it possible, during development, to run it before installing it?

**Comment by eroux** [comment]
It's certainly possible if you pass the `--all-static` option to `./configure`... can you give it a try?

**Comment by henryso** [comment]
Thank you!  Assuming you meant `--enable-all-static`, that works wonderfully.
