### ISSUE TITLE
executable name in release description and UPGRADE.md

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1233]
release description and UPGRADE.md state that the executable file name is `gregorio-4.2.0` while it's `gregorio-4_2_0`. (reported by Akira Kakuto)

**Comment by henryso** [comment]
Would it be permissible to re-release 4.2.0 with just the documentation correction?  If so, I think we should do that.

**Comment by eroux** [comment]
yes definitely

**Comment by henryso** [comment]
@rpspringuel This is ready for 4.2.0 to be re-released.
