### ISSUE TITLE
Scribus interaction does not allow for Brackets or Slurs

### ISSUE THREAD

**Issue by domoknight** [gregorio-project/gregorio#1236]
Using the GABC syntax for adding brackets or slurs does not appear to work when using gregorio with Scribus.  In testing this, I tried the following sample short scores:

%%
(c3) Test(g[ob:1;6mm] thing(h)

_No glyph seen in Scribus output_

%%
(c3) Test(g[oslur:1{]) thing(h[oslur:1}])

_No slur line seen in Scribus output_

**Comment by henryso** [comment]
This is because the scribus scripts do not process multiple passes, which is now required.  This will require a rewrite of those scripts.  @eroux Which milestone should I target?

**Comment by eroux** [comment]
good question...  I think 5.0 is reasonable

**Comment by henryso** [comment]
@domoknight Your first example is missing the close parenthesis in the "Test" syllable.

**Comment by domoknight** [comment]
@henryso, Oops, typo! The parentheses are closed in my Scribus window.  That's what I get for typing too fast here.

**Comment by henryso** [comment]
@domoknight Please try the 900_gregorio.xml in my develop branch (pull request is #1237) and let me know if that helps.  You will need latexmk installed (which most likely you already have).

**Comment by domoknight** [comment]
I get error messages when I try to use the new 900_gregorio.xml:

`calling latexmk -g -pdflatex='lualatex --interaction=nonstopmode --shell-escape' -pdf scribus_temp_render_l14836`
`Latexmk: -shell-escape' bad option`
`Latexmk: Bad options specified`

Am I needing to modify something in TexWorks?

**Comment by henryso** [comment]
@domoknight which operating system are you using?

**Comment by domoknight** [comment]
Windows x64 (7,8 and 10)

**Comment by henryso** [comment]
@domoknight Please try this next version and let me know if it helps.

**Comment by domoknight** [comment]
@henryso,

First, let me just say thank you for jumping on this issue.

b212cd5 does work partially.  It produces scores with no brace syntax, but still fails on scores with brace syntax:

%%
(c4)TEst(g) thing(h)

_score is produced_

%%
(c4)TEst(g[ob:1;6mm]) thing(h)

_fails with attached error log_

[bracefail.txt](https://github.com/gregorio-project/gregorio/files/506703/bracefail.txt)


b212cd5  also appears to break \gresetheadercapture{commentary}{grecommentary}{string}, but there are manual ways around that.

**Comment by henryso** [comment]
@domoknight:

According to `bracefail.txt`, there is some problem with the metapost handling.  Are you able to use braces outside Scribus?  I'm trying to see if this is a problem specifically with Scribus or with something else in Windows.  It works fine on my computer, under Linux.

Regarding `\gresetheadercapture`, since your examples above don't use this feature, please describe how you are configuring that in Scribus and what is "broken".

**Comment by domoknight** [comment]
@henryso

I have not tried to use braces outside of drafting scores in Scribus outside of using one of the online tools (like http://gregorio.gabrielmass.com/cgi/process.pl).  With respect to the `gresetheadercapture`, I've figured out my issue:

I used to be able to type this:
`\gresetheadercapture{commentary}{grecommentary[3]}{string}`

But according to the error log, gregoriotex doesn't understand "3" as a valid measurement, so I have to define it like so:
`\gresetheadercapture{commentary}{grecommentary[3mm]}{string}`

**Comment by domoknight** [comment]
@henryso 

I updated my metapost package (post 2016 install of TeX Live) and braces/slurs are appearing for me now in Scribus using both your updated 900 XML and the current 900 XML from the stable release.

**Comment by henryso** [comment]
Ok, thanks!  I shall merge the pull request then.
