### ISSUE TITLE
show/hide nabc

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1257]
It seems it would be practical to have a high level command to show/hide nabc, something like 

```tex
\setvoicevisibility{1}{visible} % gabc
\setvoicevisibility{2}{hidden} % nabc
```

It would be useful for the Italian Antiphonale project. I think this should be quite easy...

**Comment by henryso** [comment]
I see the value in this enhancement, but I don't like that syntax.  Let's think about the syntax a bit more.

**Comment by eroux** [comment]
Sure, that was just what first came to my mind, feel free to change it!

**Comment by rpspringuel** [comment]
We already have the `\gresetnotes` command for controlling the 
visibility of the gabc notes.  The new command, therefore, should 
probably only control the visibility of the nabc elements.  Perhaps 
something like:

`\gresetnabc[<voice number>]{visible/invisible}`

Omitting the voice number argument would result in all nabc being set to 
visible/invisible.  Including it would set only that nabc voice.

This syntax isn't that much different from what @eroux proposed, so 
further adjustments may be in order.
-- 
✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
St. Anselm’s Abbey
Washington, DC
(R. Padraic Springuel)

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by eroux** [comment]
@henryso any update on what you think the API should look like?

**Comment by henryso** [comment]
I agree with @rpspringuel's suggestion, but I have done nothing towards an implementation.
