### ISSUE TITLE
Problem with header field

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1269]
The `transcription-date` header field seems to be throwing errors now.  The following file throws a `error:syntax error` using the most recent develop.  Comment out the `transcription-date` line and the error disappears.

```
name: When Christ was born;
gabc-copyright:  (C) R. Padraic Springuel, This work is licensed under a Creative Commons Attribution 4.0 International License.;
office-part: Hymn;
occasion: Epiphany;
meter: 8.8.8.8;
arranger: Nicolas;
transcriber: Br. Samuel Springuel, OSB;
transcription-date: 20131231; 
mode: 2;

%%

(f3) When(f) Christ(f) was(f) born,(e) God(f) sent(h) a(g) star,(f_) (,)
A(h) sign(i) of(i) hope(i) whence(h) light(i) should(i) spring,(j.) (;)
And(j) Is(j)rael's(i) glo(j)ry(h) shine(i) for(h) all,(f_) (,)
For(f) pa(e)gan(f) and(h) for(i) pil(f)grim-(e)king.(f.) (::)
```

**Comment by henryso** [comment]
Using develop, I don't get an error when compiling that file to tex, nor when typesetting it with my boilerplate "main" .tex file.  Is it possible your "main" .tex file is taking that field and doing something with it?

**Comment by rpspringuel** [comment]
Did you uncomment the `transcription-date` line?  It only throws the syntax error when that line is uncommented.  Indeed, I'll edit my starting post to reflect that.

I'm using `Gregorio 4.2.0-develop-7029d95e-4061` (which is latest develop) and the error is a rather uninformative `error:syntax error`.

**Comment by henryso** [comment]
Yes, I did uncomment that line.  However, I hand typed (rather than copied) your sample.  However, in copying your example, I have realized what the error is.  There is a space after the semicolon on that line.  I'll see what I can do about ignoring that space.

**Comment by henryso** [comment]
Because we support headers with embedded semicolons, such as:
```
book: Graduale Romanum, 1908, p. 249; Graduale Triplex, 1979, p. 253; Sg. 376 p. 296;
```
... I'm having trouble coming up with an appropriate expression to ignore the space, but I'll keep trying.

**Comment by rpspringuel** [comment]
Wouldn't the regex for the end of the line be be something like: `;\s*$`

**Comment by rpspringuel** [comment]
Or perhaps we should modify the spec to say that if the header contains a semicolon, then it should be ended with a double one?

**Comment by henryso** [comment]
The problem is that I need to figure out a regular expression (actually a flex expression) that matches the stuff before the end-of-header sequence of characters.

**Comment by rpspringuel** [comment]
Well, I think the following regex will match any valid header line: `^[^:]+: .*;[ \t]*(%.*)?$`

I don't know much about flex expressions (just what a quick google search can tell me) but,
I think you could use the trailing context possibility to turn the above into something like this: `^[^:]+: .*/;[ \t]*(%.*)?$`

In this case, the returned match will just be the header name and content.  Everything after `/` (from the end of content `;` to the end of the line (including the `;`)) would not be returned as part of the match, but is used to determine if the match has been made.  That is, if I understand what I've read correctly.

**Comment by henryso** [comment]
The parser matches with *pieces* of the header, not the entire header (which would then need to be parsed ... again ... for its parts).  In any case, I think I've come up with a solution.
