### ISSUE TITLE
no custo after bar

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1271]
In most cases, there should be no custos before the first `<sp>V/</sp>` sign (I'm still waiting for some input on this from Solesmes), but as there is no easy way to catch this in gregorio (some will use `<v>\myVBar</v>` for instance), there should be a way to prevent a custos if the line breaks after a bar. Currently it's only possible by adding a forced end of line with no custo (`z-`), it would be practical if there was a way to express that without forcing the end of line, so that the gabc file remains correct at all widths. Maybe something like `(::0)`? What do you think?

**Comment by henryso** [comment]
I think this feature has merit, but I'm not liking using `0` for it due to how `0` is used dissimilarly elsewhere.  I haven't come up with a better option yet, but let's think about syntax a bit more.

**Comment by eroux** [comment]
Sure, `0` is definitely not a very good option...

**Comment by henryso** [comment]
I thought about it a bit more and consulted the code.  I have two suggestions:

- If this is not particularly common, then we can use something like `[nocustos]` (i.e., `::[nocustos]`)
- If this is somewhet common, how about `$`? (i.e., `::$`)

**Comment by eroux** [comment]
Well, i like both ideas, I let you choose!

**Comment by eroux** [comment]
It seems the process cannot be automated even if we manage to spot the `V/` as not all scores will follow this pattern, even in the same book... so the new notation for bar without custos should be enough

**Comment by henryso** [comment]
I choose `[nocustos]`.
