### ISSUE TITLE
Musica Ficta

### ISSUE THREAD

**Issue by signumaltum** [gregorio-project/gregorio#1278]
It would be useful for producing scholarly editions of chant that flat signs, natural signs, and sharps display above the staff as "musica ficta."  This is common in editions of medieval and renaissance music to denote places where the original manuscript source did not indicate a flatted pitch (or less often in chant, a natural sign or sharp), that nevertheless was intended to be sung as a flat, usually to avoid a tritone.  Using the polyphony feature, I have had success with simple neumes.  For more complicated neumes, the polyphony feature does not work as well: E.g., (Ky(dss)ri({gv}kxFEfv)e(hiHFED/eV/@ed)

<img width="302" alt="screen shot 2017-01-09 at 11 18 54 pm" src="https://cloud.githubusercontent.com/assets/24361471/21821585/15a07384-d742-11e6-92ca-0b23f1f7ab4f.png">

Notice the undesired space between the virga with ficta mark and the descending puncta.  In some cases, the ficta sign needs to be placed over one of a cluster of descending puncta, for example, where it is virtually impossible to properly align the ficta sign with the appropriate note using the polyphony feature:

<img width="180" alt="screen shot 2017-01-10 at 3 07 53 pm" src="https://cloud.githubusercontent.com/assets/24361471/21822799/b495aece-d746-11e6-98d2-703dfbb63d70.png">

In chant, the effected pitch is usually diatonic "b" (as below c-clef), which could potentially appear above the fourth line of the chant staff depending on clef placement.  It is not necessary that the ficta sign appear on the "k" line so much as it should hover above the staff directly in line with the effected neume, like the "rare" sign does.  In some editions of treble clef music, the ficta sign appears in a smaller font than the flat on the clef, although this may or may not be desirable for chant.  I've included an example for the purpose of comparison:

<img width="413" alt="screen shot 2017-01-10 at 1 58 33 pm" src="https://cloud.githubusercontent.com/assets/24361471/21821603/2cf3f394-d742-11e6-89ca-9dd6a6068369.png">

**Comment by henryso** [comment]
I can implement this as additional rare signs (`r6`, `r7`, `r8`) or we can come up with some other syntax, such as
- `[musicaficta:x]`, `[musicaficta:y]`, `[musicaficta:#]`
- or more explicitly `[musicaficta:flat]`, `[musicaficta:natural]`, `[musicaficta:sharp]`
- or `X`, `Y`, (some "majuscule" substitute of `#` )

I think probably additional rare signs is the most obvious solution, but the others may perhaps be clearer.  I'm open to other suggestions.

**Comment by eroux** [comment]
hmmm good question... I cannot find any preference for a solution, so I let you choose!

**Comment by henryso** [comment]
Ok, since there are no objections, I will use additional rare signs: `r6`, `r7`, and `r8`.
