### ISSUE TITLE
ability to select multiple lines in the grechangenextscorelinedim

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1280]
It would be practical to be able to select multiple lines in the same `\grechangenextscorelinedim` command, as in

```tex
\grechangenextscorelinedim{2,4,6,8}{spacelinestext}{0,6 cm}{scalable}
```

that's just for comfort so no emergency...

**Comment by henryso** [comment]
I decided to take this on since I had just worked with this function and it was fresh in my mind.
