### ISSUE TITLE
\grechangenextscorelinecount problem

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1286]
In reviewing the tests in order to prep a beta release I'm getting the following test failure for tex-output/per-line-counts:

![diff-page-0](https://cloud.githubusercontent.com/assets/7671682/22405583/13a0315c-e613-11e6-8100-e6b8e4bf73c8.png)

As you can see the additional space between lines 2 and 3 of the second score is not being inserted on my system.  Has anyone else seen this behavior?

**Comment by henryso** [comment]
I see this as well, after I upgraded TL 2016 yesterday.

**Comment by rpspringuel** [comment]
Since this breaks functionality, I think we need to track down the change which caused this before releasing 5.0.  If it's something that we can fix on our end, then the fix should be in 5.0.  If not, then we should report the problem to the appropriate package maintainer and include whatever status notices are appropriate in the 5.0 documentation.

**Comment by henryso** [comment]
I agree with that plan, but it shouldn't stop the beta.

**Comment by eroux** [comment]
I agree with Henry here, there are many changes in 5.0 and very few have been tested in big projects so if we want a solid release for TeXLive 2017, we should release a beta as soon as possible

**Comment by henryso** [comment]
I think the problem is that latexmk is not running all the necessary passes.  At the end of the cmdout log, it shows:

```
Latexmk: Log file says output to 'per-line-counts.pdf'
Latexmk: ===For rule 'pdflatex', actual output 'per-line-counts.pdf'
       ======appears not to match expected output 'per-line-counts.tex.out/per-line-counts.pdf'
=== TeX engine is 'LuaTeX'
Latexmk: All targets (per-line-counts.tex.out/per-line-counts.pdf) are up-to-date
```

... after the first run, and there are no runs after.

**Comment by henryso** [comment]
This appears to be a problem with latexmk when the output is not in the current directory.  I have switched to a different method of rerunning lualatex, and this issue no longer occurs.  Thus, this is not a defect in the code for 5.0.0-beta1.
