### ISSUE TITLE
Support for third party fonts with no hollow version

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1293]
Related to #844 : I'm currently adapting the Solesmes font for Gregorio 5, it's quite straightforward but I'm not planning to create a hollow font. The compilation fails when it looks for `mechtildis-hollow`, which doesn't exist... I can't find the way to do that simply nor any indication in the doc... How can I do that? I don't think we need a high level function for that, third party fonts are quite rare...

**Comment by henryso** [comment]
I think the only way would be to add a flag that would be consulted when hollow and hole fonts are desired.

**Comment by eroux** [comment]
hmmm ok, I'll do that... what about the flat and natural glyphs, is there a simple way to redefine the hole glyph?

**Comment by eroux** [comment]
sorry, there is no problem about them, I'll have a PR in a few minutes
