### ISSUE TITLE
more episema bridges

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1304]
Solesmes is trying to reproduce the following:

![venite-1](https://cloud.githubusercontent.com/assets/60868/23094639/28961406-f5fd-11e6-8396-1f6f53eebe05.png)

![christus-1](https://cloud.githubusercontent.com/assets/60868/23094640/2c77ac60-f5fd-11e6-85ab-9014dd946f43.png)

with

```tex
\documentclass{article} %%
\usepackage[autocompile]{gregoriotex} %%
\begin{document} %%
\gabcsnippet{(c4) ve(c_e!fw_g)ní(g)te,(g_h)}

\gabcsnippet{(c4) Chris(d_e!fw_!g_h)tus(g)}

\gabcsnippet{(c4) Chris(d_e!fw_0!g_h)tus(g)}
\end{document}
```

but it gives

![gregobug](https://cloud.githubusercontent.com/assets/60868/23094655/6790ee88-f5fd-11e6-9cc1-d488c56faf46.png)

it sounds reasonable enough to be included in next beta, wdyt?

**Comment by henryso** [comment]
I don't know if I'll have enough time before we need to release to make it into TeX Live 2017.

**Comment by henryso** [comment]
This is why we added the manual episema group feature:
```
(c4) Chris(d_e[uh{]!fw_0!g_h[uh}])tus(g)
```
Is that not sufficient?

**Comment by eroux** [comment]
Yes it is, thanks!
