### ISSUE TITLE
missing nabc glyph

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1305]
See [this thread](https://mail.gna.org/public/gregorio-users/2017-02/msg00030.html):

> Reges Tharsis GT 58 Line 4 (e)um Eins121,51 :
> In the neum table : to!ciG is the best choice:
> (cfrEP1) in annex
> Is it possible to have the folowing (cfr EP2)
> The image  also present in the neum table
> Probably is not used.

ep1:

![ep1](https://cloud.githubusercontent.com/assets/60868/23094745/d9c0c4be-f5fe-11e6-8df1-24191c82d437.jpg)

ep2:

![ep2](https://cloud.githubusercontent.com/assets/60868/23094747/ddda7e14-f5fe-11e6-94f4-15dc2eec6b24.jpg)

**Comment by jakubjelinek** [comment]
I'll have a look next week.

**Comment by jakubjelinek** [comment]
I'll rename the first one to to!ciGhh (so when typing the height of the climacus will need to be at height of torculus plus 2) and to!ciG will be the new glyph.
