### ISSUE TITLE
initio debilis with virga

### ISSUE THREAD

**Issue by fradec** [gregorio-project/gregorio#1310]
In some rare cases initio debilis should be linked with a following virga, like this example:
![iubilemus](https://cloud.githubusercontent.com/assets/24571790/23134612/bb745960-f795-11e6-9279-0489604abe5c.png)

It seems that none of the following tests make it possible.

```tex
% !TEX TS-program = LuaLaTex+se
\documentclass{article} %%
\usepackage[autocompile]{gregoriotex} %%
\begin{document} %%
\gabcsnippet{(c4) Iu(f)bi(f)lé(-fgv)mus(f)}
\gabcsnippet{(c4) Iu(f)bi(f)lé(@-fgv)mus(f)}
\gabcsnippet{(c4) Iu(f)bi(f)lé(-f@gv)mus(f)}
\end{document}
```

**Comment by eroux** [comment]
@fradec I've updated your comment so that it's more readable, look at the source (by editing it for instance) to see how I did it

**Comment by henryso** [comment]
This will require either drawing new glyphs or making the virga a possible ending to a fusion or both.  @eroux How much time to we have before the TeX Live 2017 deadline?

**Comment by eroux** [comment]
Well, I admit I cannot remember exactly how things work, but we should have a new version on March 4th (can be beta1 or beta2 if we release it before), and we can aim say end of March for the definitive version...

**Comment by henryso** [comment]
Looking structurally at the font (though it's not semiologically-correct naming), these new glyphs would be "pes quadratum initio debilis", with various size queues.  The executable will parse `-fqg` as this figure, though the glyph is currently not being drawn.  Drawing the extra glyphs is relatively easy, but I can go further and try to get the C code to transform `-fgv` into this glyph.  Should I do that, or is `-fqg` sufficient?

**Comment by eroux** [comment]
Well, to me it looks like `-fqg` is sufficient... @fradec what do you think?

**Comment by fradec** [comment]
It's ok for me, it does not matter to have a different syntax for this kind of neumes, and the name proposed by @henryso is semiologically-correct I think, it can be also named "pes cassus initio debilis", it's the same. Thank's!
