### ISSUE TITLE
missing nabc glyph

### ISSUE THREAD

**Issue by marekklein** [gregorio-project/gregorio#1314]
I have found another glyph not yet available in gregall font
![gregall](https://cloud.githubusercontent.com/assets/18429222/23167612/61c3ce5e-f845-11e6-91ed-917a8e9534de.jpg)
Not shure how to name it.
Source: http://www.e-codices.unifr.ch/en/csg/0391/025
(Resp. Tradiderunt - end of the second line - adversum me FORtes)

**Comment by jakubjelinek** [comment]
I'll add it as to>2 , I believe it is liquescent torculus.
