### ISSUE TITLE
Problem of elision

### ISSUE THREAD

**Issue by fradec** [gregorio-project/gregorio#1320]
the following code
```tex
% !TEX TS-program = LuaLaTex+se
\documentclass{article} %%
\usepackage[autocompile]{gregoriotex} %%
\begin{document} %%
\gabcsnippet{(c4) sal(d)vúm(d)qu<e>e</e> ab(d) hos(dh)tis(h) ím(h)pe(g)tu(hvGFgwh/GFED.) (;)}
\end{document}
```
gives this
![screenshot](https://cloud.githubusercontent.com/assets/24571790/23365672/298027a4-fd04-11e6-93d8-17f6b38433d8.png)
but should give this
![screenshot2](https://cloud.githubusercontent.com/assets/24571790/23365693/3f5bf3e6-fd04-11e6-8eff-e4f5ef93aed9.png)
I known I can obtain this with `qu<e>e</e> {a}b(d)` but it would be good that the elision of a vowel preceded of 'qu' that can be correctly recognized.

**Comment by rpspringuel** [comment]
I believe the intended usage of the elision tags is to encapsulate the whole elided syllable, not just the vowel in it.  `<e>que</e> ab` does get the neume position right, but italicizes (i.e. applies the elision format to) `que` not just `e`.  Is it common for people to want just the vowel in the elided syllable formatted?

**Comment by eroux** [comment]
The initial elision feature request actually comes from @fradec, so I think he knows how it should be used

**Comment by fradec** [comment]
The elisions concern only the vowels since the consonant must be pronounced, vocalized with the vowel of the following word, so it's not good to insert the entire syllable in the tags. See for example this hymn from Liber Hymnarius p.38
![screenshot3](https://cloud.githubusercontent.com/assets/24571790/23367556/eef64a26-fd0a-11e6-9c26-1b24eae93ef6.png)

**Comment by henryso** [comment]
Question: in general, putting aside elision into account, for Latin, if you have "que", should this be equivalent to `q{ue}` or `qu{e}`?

**Comment by rpspringuel** [comment]
From [here](http://ewtn.com/expert/answers/ecclesiastical_latin.htm):

> U preceded by Q or NG and followed by another vowel as in words like qui and sanguis, keeps its normal sound and is uttered as one syllable with the vowel which follows : qui, quae, quod, quam, sanguis. But notice that cui forms two syllables, and is pronounced as koo-ee. In certain hymns, on account of the metre, this word can be treated as one syllable.

From [another place](http://www.canticanova.com/latin_pron.htm):

> after Q, pronounce QU like KW, then pronounce the 2nd vowel

It thus seems to me like either interpretation is valid from a pronunciation stand point.

**Comment by eroux** [comment]
It should be equivalent to `qu{e}`

**Comment by rpspringuel** [comment]
Looking in the Graduale Simplex (2007 edition from Liberia Editrice Vaticana) I find:
![temp](https://cloud.githubusercontent.com/assets/7671682/23370159/cd02fb90-fce1-11e6-8c11-cf787880f9b8.png)
and
![temp copy](https://cloud.githubusercontent.com/assets/7671682/23370233/14fa8e04-fce2-11e6-8a83-0d6f7ba79407.png)
and
![untitled](https://cloud.githubusercontent.com/assets/7671682/23370339/5655954c-fce2-11e6-8990-9d8c9fb224a1.png)
all of which seem to lean towards considering the `u` part of the vowel.

In the Hebdomadae Sanctae ( I find the following examples:

![temp](https://cloud.githubusercontent.com/assets/7671682/23370556/090f485e-fce3-11e6-964c-baf2c3a81e55.png)
and
![untitled](https://cloud.githubusercontent.com/assets/7671682/23370534/f612fb7e-fce2-11e6-97a9-d4ae96b54fc7.png)
and
![untitled](https://cloud.githubusercontent.com/assets/7671682/23370610/40c315c8-fce3-11e6-8b2f-827e967acd0d.png)
all of which seem to be going the other way (`u` is part of the `qu`).

**Comment by eroux** [comment]
Well, in my exchanges with abbeys, I never encountered anyone who would consider semi-consonants (like `u` in `qui` or `i` in `cuius`) as part of the vowel when it comes to centering notes... that's a very strange idea, to me it looks like the *Graduale Simplex* is not particularly well crafted (which is no big surprise)

**Comment by rpspringuel** [comment]
That's a possibility.  I'm no expert and simply used those two reference because I happen to have files for them on my computer.

**Comment by eroux** [comment]
In terms of typography, the best books are the Solesmes books before 1975 (*Antiphonale Monasticum*, *Graduale Romanum*, etc.), they consistently use `qu{e}`

**Comment by henryso** [comment]
If we agree that "qu" should be considered a consonant, which would solve the original problem, then I will change the default vowel rules to consider it so.

**Comment by henryso** [comment]
Actually, looking at code, I think it's actually a bug rather than a rule change.
