### ISSUE TITLE
Font mapping messages

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1326]
Is it possible to assign the font mapping messages to a specific debug flag so that they don't appear in all log files?  There are a lot of them and wading through them is a chore when taking a detailed look at a log file.

**Comment by henryso** [comment]
I'll see what I can do.

**Comment by henryso** [comment]
I haven't come up with a good solution yet. The biggest issue is that the value of `\gre@debug` is not available at the time `gregoriotex.init` is called.  I'm considering queueing messages or deferring initialization of some things until `\AtBeginDocument` is reached.

**Comment by henryso** [comment]
I think #1327 will work.  Font mapping is logged using `debug=mapfont`, glyph changes against `debug=glyphchange`, and offset cases against `debug=offsetcase`.
