### ISSUE TITLE
`\grecreatedim` in documents

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1336]
Right now `\grecreatedim` is in the user space in order to allow users to load their own custom spacing files.  However, this means that a user could also use it inappropriately to "change" a dimension, the function properly belonging to `\grechangedim` (I noticed this in the example for #1319).  Should we set things up so that `\grecreatedim` is less accessible to the user?  Perhaps restricting it to only appearing in a spacing configuration file?  Heck, it would even be possible to restrict it even further to just gsp-default.tex, but then this file would become less useful as a template for users creating their own spacing configuration.

**Comment by henryso** [comment]
I don't think it's necessary, but I also don't feel particularly strongly about that.

**Comment by rpspringuel** [comment]
See #1467
