### ISSUE TITLE
Feature request: Option to omit clef

### ISSUE THREAD

**Issue by igneus** [gregorio-project/gregorio#1346]
It seems that gregorio doesn't support clef-less scores yet. When clef position is left unspecified, a c-clef on a default position is rendered. Search in issues open and closed suggests that this topic hasn't been discussed yet.

Option to omit clef would be useful (not only) for transcriptions from manuscripts which don't employ clefs.

**Comment by rpspringuel** [comment]
This is already supported.  Issue the command `\gresetclef{invisible}` before including the score and the clefs (whether defined in the score or not) will not be printed.  `\gresetclef{visible}` changes the behavior back to printing clefs.
