### ISSUE TITLE
Dotted Barline

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1360]
A user has requested the ability to make the dotted bar line as shown in this picture:

![20170504_165813-1024](https://cloud.githubusercontent.com/assets/7671682/25707247/f49131ba-30b0-11e7-9468-d9dac3e4bd4f.jpeg)

I've seen them elsewhere in a slightly different style (bigger and fewer dots), but can't remember where off the top of my head.  If I find it, I'll post an image.

To make this work we need the following:

- [ ] gabc syntax for the element
- [ ] lexer modifications to recognize the new syntax
- [ ] new glyph in the fonts
- [ ] modification to `\gre@writebar` for the new bar and `\GreDottedBar` alias

On the syntax issue, `:` would be the most obvious choice, but is already used for divisio maior.  We could swap in `|` for that, but such a change to the gabc syntax is probably way too invasive for those who have been using Gregorio for a while.  On the other hand I think that using `|` for the dotted bar and `:` for the divisio maior would be counter-intuitive and thus is probably not a good idea for newbies.  I'm not sure if there is any other intuitive character that could be added.

We could make it a post-fix solution, say `:0`, but that raises the question as to whether we need dotted versions for all the current bar types and not just the divisio maior.

**Comment by henryso** [comment]
If we needed dotted versions for any bar type, then I suggest appending `?` to differentiate it a little for the Dominican bars.  If we only need a dotted version for divisio maior, then how about just `?`?

As to the the style of the dotted bar, if a single score cannot have more than one style, then I think it's good enough to just put it in the font and let people select the style by selecting a different font (or using a substitution if we want to provide multiple within the font itself).

**Comment by henryso** [comment]
Any response on this?

**Comment by rpspringuel** [comment]
> If we needed dotted versions for any bar type, then I suggest appending `?` to differentiate it a little for the Dominican bars. If we only need a dotted version for divisio maior, then how about just `?`?

That works for me.  If I'm reading the above correctly, then the dotted bar is part of the "optional" syntax.  A `?` suggests optional quite well.

> As to the the style of the dotted bar, if a single score cannot have more than one style, then I think it's good enough to just put it in the font and let people select the style by selecting a different font (or using a substitution if we want to provide multiple within the font itself).

I don't think more than one style is necessary for each score, so handling the various styles with a different font or a variant glyph seems appropriate.

As for the other context I came across this in, it was the Psalm tone that my community uses for the Magnificat of the O Antiphons.  The dotted bar is used to indicate the start of the section which is skipped in the first verse (so again, related to "optional" notes):

[Scan.pdf](https://github.com/gregorio-project/gregorio/files/1485724/Scan.pdf)

**Comment by henryso** [comment]
Do you think we need more than just a dotted division maior?  In other words, is `?` a bar modifier or a bar character?

**Comment by rpspringuel** [comment]
I've never seen anything but the dotted divisio maior.

How hard would it be to change this once implemented?  Say we started with `?` being a bar character and then later people started asking for other dotted bars.  Would it be possible to make the switch at that point?

**Comment by henryso** [comment]
It's possible to switch.  We could start with `?` to mean a dotted divisio maior, and if more is needed, `?` can become a shortcut for `:?` after we make `?` a modifier.  This might break scores where people do things like `:?` (prior to making `?` a modifier) to mean a divisio maior followed by a dotted divisio maior.  Alternately, we could just implement `:?` to mean a dotted divisio maior without implementing any other dotted bars.

**Comment by rpspringuel** [comment]
> Alternately, we could just implement `:?` to mean a dotted divisio maior without implementing any other dotted bars.

That sounds reasonable.
