### ISSUE TITLE
Loading microtype before gregoriotex breaks metapost-based features.

### ISSUE THREAD

**Issue by lpburrows** [gregorio-project/gregorio#1364]
I keep getting an error when trying to set braces in Gregorio 5.0.2 on TexShop 3.77 on Mac. The error reads: 

"Undefined control sequence.
l.5 \mplibtoPDF
             {
l.468 \GreSyllable
                {\GreSetThisSyllable{}{}{}{}{}}{}{\GreUnstyled}{1}{\GreSetNe…”

My gabc file has (jr[ocba:1{] ih[ocba:0}]), but it does it at any place braces are coded. Any ideas?

**Comment by henryso** [comment]
Run the `system-setup.command` and provide the output.

**Comment by lpburrows** [comment]
Sorry about that.

[system-setup.txt](https://github.com/gregorio-project/gregorio/files/1079168/system-setup.txt)

**Comment by henryso** [comment]
When you installed TeX Live, did you perform a full installation?  It seems like some metapost-related commands are unavailable.

**Comment by lpburrows** [comment]
I did a full installation, yes. And I just uninstalled MacTeX 2017 and did a fresh installation, and still have the same issue.

**Comment by henryso** [comment]
Ok, I'm puzzled as to why it's not working.  Perhaps our resident Mac expert can help you.  @rpspringuel?

**Comment by lpburrows** [comment]
A minimal example and then trial and error commenting out packages revealed that microtype was the culprit.

**Comment by henryso** [comment]
@lpburrows Do you mind sharing the MWE?  I tried a trivial example with microtype and that error didn't happen.

**Comment by lpburrows** [comment]
`% !TEX program = LuaLaTeX+se
% !TEX encoding = UTF-8 Unicode
\documentclass[a5paper,9pt,english-us]{book}
\usepackage{microtype}
\usepackage[autocompile]{gregoriotex}

\begin{document}

\gabcsnippet{(c4) (f) (gh) (h) (h) (h) (ixir1) (hr) (h) (gr1) (hr) (h.) (:) 
%(h) (h) <b>/</b>(h) (g) (f) (gr) (gf) (d.) (::)} %functional
(h) (h) <b>/</b>(h) (g) (f) (gr[ocba:1{]) (gf[ocba:0}]) (d.) (::)} %nonfunctional

\end{document}`

**Comment by henryso** [comment]
Ok.  Load microtype *after* gregorio.

**Comment by rpspringuel** [comment]
If it's just a package loading order question, then I think that we can just document the required order.  There are plenty of other packages that care about their loading order with respect to other packages.

**Comment by henryso** [comment]
How best to document this?

**Comment by rpspringuel** [comment]
IIRC we had a blurb in the package loading section about a package conflict before.  That conflict got solved, so the blurb was removed, but I think it's a suitable model for how to document this sort of thing.  You might try searching through the history of the documentation folder to find what I'm referring to (as my memory isn't up to remembering any more specifics than this).

**Comment by henryso** [comment]
I can't find the revision with the blurb.  Do you know which package had a conflict so I can search for something rather than paging through hundreds of commits?

**Comment by rpspringuel** [comment]
`fontspec`:  see be4c9f37
