### ISSUE TITLE
Ledger lines across divisio minima/quarter bar line

### ISSUE THREAD

**Issue by rarty** [gregorio-project/gregorio#1370]
![texshop_image](https://user-images.githubusercontent.com/6454162/28174391-fe6a006c-67b6-11e7-9054-c0062bdf2f1d.png)
(Graduale Romanum—Gloria ad lib. I)

This is surely a rare case overall, but at least this common chant is consistently printed this way.

Ledger lines can be arbitrarily extended across barlines, but there isn't a way to raise the quarter bar to the ledger height.

**Comment by rpspringuel** [comment]
What's the closest you can get currently?  Is it with the ledger line extending across the bar line, but the bar line too low (i.e. in it's normal position)?  Or can you not get the ledger line to extend across the bar line?

Also, what's the desired behavior here?  Do you want the bar line to move up automatically if there is a ledger line which spans across it, or do you want a new bar line (i.e. gabc code) that is like the current quarter bar, but typeset higher?

Finally, whatever the desired behavior, should the virgula and dominican bar (when placed high) be similarly effected?

**Comment by rarty** [comment]
![texshop_image](https://user-images.githubusercontent.com/6454162/28235919-5d554168-68de-11e7-98bf-adeb5909f858.png)

I've never encountered another instance in print, but I think it might look odd to extend ledger lines across other types of bars, but maybe a virgula. So it could be a new bar with explicit gabc notation—`,1` ?—to print a raised divisio minima (or virgula).

**Comment by henryso** [comment]
`,1` would conflict with a Dominican bar, so I would suggest `,0` and `` `0`` for high divisio minima and virgula, respectively.  If there are no objections, shall I start on this?

**Comment by eroux** [comment]
ok for me!
