### ISSUE TITLE
Vertical Episema bellow note instead of above

### ISSUE THREAD

**Issue by Nokel81** [gregorio-project/gregorio#1381]
With the following code: `(de//f'd)` it produces what is shown in the image, but that is rather hard to see and I would have liked it to be above the `f`, especially because of the two lines already bellow the note.
![capture](https://user-images.githubusercontent.com/8225332/31047429-970fc7d4-a5d8-11e7-9ac9-60667f6186c5.PNG)

**Comment by henryso** [comment]
Please use `(de//f'1d)` instead.
