### ISSUE TITLE
Text not aligning properly under bar lines

### ISSUE THREAD

**Issue by Alexander-Eager** [gregorio-project/gregorio#1384]
When you put an asterisk under a bar line after a long melisma, it tends to skew to the left:

<img width="540" alt="kyrie-ix-output" src="https://user-images.githubusercontent.com/6404373/32999028-81bb16a6-cd54-11e7-84cc-6f8f5c8f6614.png">

If you look at how this chant appears in the Graduale 1908, the asterisk is placed directly under the bar line:

<img width="521" alt="kyrie-ix-final" src="https://user-images.githubusercontent.com/6404373/32999029-81d34758-cd54-11e7-86ac-342f3cbbdb34.png">

This test example was made with gregorio 5.0.1 on macOS 10.12.  Here is the gabc code:

```
name: Kyrie;
office-part: Kyrie;
mode: 1;
%%

(c4) Ký(h)ri(jk)e(kv.jkh.ixgh@ivHG'Fghh) *(,) (hj@kv.jkh.ixgh@ivHG'Fghh) **(,) (hvGFgvFED.fvDC'd) e(cd)lé(fg)i(f)son.(ed..) (::)
```

*Edit*: actually, it is not limited to asterisks.  It also occurs with text:

```
name: Kyrie;
office-part: Kyrie;
mode: 1;
%%

(c4) Ký(h)ri(jk)e(kv.jkh.ixgh@ivHG'Fghh) d(,) (hj@kv.jkh.ixgh@ivHG'Fghh) **(,) (hvGFgvFED.fvDC'd) e(cd)lé(fg)i(f)son.(ed..) (::)
```

<img width="597" alt="with-text" src="https://user-images.githubusercontent.com/6404373/32999464-369752ea-cd57-11e7-9707-18b03694c7c0.png">

**Comment by rpspringuel** [comment]
Feature, not a bug.  The bar spacing algorithm attempts to place barlines exactly between the surrounding notes and the text associated with it exactly between the surrounding text.  However, it also respects the limits set by `maxbaroffsetleft` and `maxbaroffsetright` (max distance the center of the text can be to the left or right of the associated bar, respectively).  If you want the text to always be exactly under the bar then set those two distances to zero.

**Comment by Alexander-Eager** [comment]
My mistake, thank you.

**Comment by chrylis** [comment]
This is very surprising behavior; it is mentioned in the documentation?

**Comment by rpspringuel** [comment]
Indirectly.  The distances are documented in GregorioRef as is `\gresetbarspacing` (which can be used to switch back to the older behavior).  Our documentation is in need of some considerable upgrades, especially the web version.
