### ISSUE TITLE
Fixing or removing archlinux/

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#139]
The archlinux/ directory is something I never showed any interest it, as I don't have archlinux. But in the cleaning process we're in right now, it would be best to know how to deal with it. Do one of you have Archlinux? [archlinux/gregorio/PKGBUILD](archlinux/gregorio/PKGBUILD) seems quite outdated, and I have to way to test possible fixes...

**Comment by rpspringuel** [comment]
Don't even know what archlinux is.

**Comment by eroux** [comment]
A linux distribution, like Debian or Ubuntu, but with a different package manager.

**Comment by rpspringuel** [comment]
Ah.  Then I'm definitely out when it comes to testing possibilities or interest in developing here.  I'm going to have enough on my hands figuring out the Mac distribution channel(s).

**Comment by henryso** [comment]
@eschwab uses Arch.

**Comment by eschwab** [comment]
Arch user reporting in. Yes, that PKGBUILD  and tarball are killable. We may not even need the archlinux/ dir at all. I've been meaning ask gregorio-users if anyone else uses arch. In the meantime though, feel free to `rm -r archlinux/` I can add it later if it becomes relevant again (if it ever was).

**Comment by eroux** [comment]
Ok, I think I'll remove it then... it is quite outdated, and it's still in the history of git!

**Comment by eschwab** [comment]
`archlinux/` removed by #133
