### ISSUE TITLE
Misplaced episema

### ISSUE THREAD

**Issue by ahinkley** [gregorio-project/gregorio#1394]
[an_ecce_puer_meus-main.pdf](https://github.com/gregorio-project/gregorio/files/1532826/an_ecce_puer_meus-main.pdf)
For some reason the horizontal episema appears over the wrong note in
e(h_g)le(ixi')ctus,(h)

It should appear over the h, but appears over the g instead.

The gabc code is:
name:Ecce puer meus;
mode:1;
annotation:1;
office-part:Antiphonae;
book:Liber Antiphonarius, 1960, pp 280;
%%
(c4) EC(d)ce(dc) pu(f)er(g) me(f_h)us(h.) *(,) e(h_g)lÃ©(ixi')ctus,(h) quem(g') e(g)lÃ©(f_h)gi:(g.) (;) pÃ³(g)su(g)i(g) su(e')per(g) e(h_g)um(f_g) (,) spÃ­(e_c)ri(e_g)tum(fe~) me(d.)um.(d.) (::)

**Comment by rpspringuel** [comment]
Already fixed in develop.  See #1379.

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by ahinkley** [comment]
My mistake -- the default search was set to open issues. I should have cleared the search box. :)
