### ISSUE TITLE
Improve VersionManager.py

### ISSUE THREAD

**Issue by eschwab** [gregorio-project/gregorio#140]
With #132 the VersionManager.py script was born. It needs to be brought to maturity:

1.   `-b` or `--bugfix`: increment the z version number (of x.y.z) and propagate that change.
2.   `-e` or `--enhancement`: increment the y version number, resetting z to 0 in the process and propagate the change.
3.    `-m` or `--major`: increment the x version number, resetting y and z to 0 in the process and propagate the change
4.    `--manual=###`: change the version number to ### and propagate the change (especially useful for marking a beta release, a develop release, or other release with an unusual number)
5.   `-h` or `--help`: print the list of options
6.   `-c` or `--get-current`: return the current version number.
7.   Add do not modify warning to `.gregorio-version`.

Calling `VersionManager.py` with no arguments should be equivalent to `VersionManager.py --help`.

Thanks to @rpspringuel for the TODO list.

**Comment by rpspringuel** [comment]
Given that `.gregorio-version` is a hidden file, adding a "Do Not Modify" warning may not be entirely necessary.

On the other hand it may be better to be safe rather than sorry.

**Comment by eschwab** [comment]
Would rather be safe, since I don't plan on putting any checks in the `.py`.

**Comment by eroux** [comment]
The file has changed quite a lot in `fixdebian` branch, please wait or it to be merged before modifying it (as conflicts won't be easy to solve)

**Comment by eschwab** [comment]
To streamline the release process is it worth adding:

1. `--commit`: Makes a commit for the version change.
2. `-t`, `--tag`: Same action as `--commit` but also adds a git tag.

**Comment by eroux** [comment]
why not yes. Maybe a warning or a confirmation message should be good too... something like "before commiting, don't forget to blablabla, as indicated on the wiki".

**Comment by eroux** [comment]
I think if we want to make it have high level commands like `-gt` and `-gc`, it would be necessary to have a `--dry-run` option, to see what is going to happen... The workflow is kind of made for humans, so committing, tagging, etc. are human decisions, so I want to completely control what is going to happen, and see if the script will do exactly what I want (otherwise I'm not sure I would use it).

**Comment by eschwab** [comment]
i was planning on making all human actions (commit, tag) interactive. Confirm, edit commit/tag message, etc. What I will do is finish adding the `-b, -m, -e` flags and logic, then post a PR for review and feedback to make sure I'm on the right track.

**Comment by eroux** [comment]
Ok good!

**Comment by eschwab** [comment]
Good enough for now with #158
