### ISSUE TITLE
Copyright dates need to be updated

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1406]
New year.  Copyright dates need to be updated to reflect that.  There are lots of these scattered through the files and it's difficult to keep track of them all, so it might be useful to make VersionManager capable of handling this to make life easier in the future.

**Comment by eschwab** [comment]
This could be added into VersionManager. I would propose to have the script check the copyright on each run by having the current year included with the version in `.gregorio-version` Then it will automatically update the copyright year in all the files the first time a release is made in a new year. Unless it is better to manually invoke the updating of the year (which one would have to remember to do).

**Comment by rpspringuel** [comment]
I don't have a problem with having the VersionManager update the year automatically with each run, but there are a whole lot more files which contain copyright notices than they're are which contain version statements.  It would be wasteful of resources to check every file for both version statements and copyright notices.  The list of files containing copyright notices should be separated from the current list of those with version statements so that each file is only checked for what it actually contains.

**Comment by eschwab** [comment]
Agreed on separate file lists.

To clarify: VersionManager would only check `.gregorio-version` for the year. If the year noted in that file was old, then VersionManager would update all the necessary files with the new year.

**Comment by rpspringuel** [comment]
That makes even more sense than what I was thinking of.

**Comment by eschwab** [comment]
Should this be based on CTAN or develop?

**Comment by rpspringuel** [comment]
This is a ctan compatible update because it doesn't involve a change to the gregorio executable.
