### ISSUE TITLE
UPGRADE.md

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1407]
There were no special instructions for upgrading this time around, so we never added a 5.1 section to UPGRADE.md.  Should we do so in the future to be clear when there are no special instructions?  The folks at CTAN noticed the lack so it the additional clarity might pay off.  I would think that if there are several versions in a row without special instructions that their sections could be consolidated somehow.

**Comment by henryso** [comment]
I think we should, but if two no-instruction versions follow each other, they should be collaped (e.g., "No changes are needed for updates from any version between xxxx and yyyy" or somesuch).
