### ISSUE TITLE
Oriscus pointing in wrong direction on Mac

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1412]
Now that the Linux binaries have been updated, I'm running the test repository against the TeXLive 2018 Pretest and am getting 3 failures.  2 of these (`gabc-output/glyphs/pitches` and `tex-output/eol-euouae`) appear to be the usual failures due to minor shifts in elements that are imperceptible to the human eye.

One, however, appears to be significant: `gabc-output/glyphs/broken-shapes`.  In this test the first oriscus has changed direction (from pointing up at the end to down).  @henryso, you wrote the oriscus direction logic, can you take a look at this test and determine which direction the oriscus is meant to point in and whether the current test expectation is correct?

**Comment by henryso** [comment]
It should be pointing downwards.  The expectation is incorrect (probably old, as this was the former behavior).  The oriscus should point in the direction of the first non-unison note that follows unless an explicit direction is specified.

**Comment by henryso** [comment]
Note: If I run against TL 2017, the oriscus is pointing downwards, but I think the dpi I'm using (150) is too low to detect the error.

**Comment by rpspringuel** [comment]
I'll adjust the test expectation then and push up the change.

**Comment by rpspringuel** [comment]
Okay, this is a bit more complicated than I thought.  On my primary Mac using TL2017 the oriscus is pointing up.  I'm going to have to look into this to see what is going on, but do not have the time to do so today.

**Comment by rpspringuel** [comment]
Question @henryso: where is the logic that determines oriscus direction?  Is that in the executable or the TeX?

**Comment by henryso** [comment]
It's in the executable.  The key would be to look at the gtex output and see if it is asking for OriscusAscendens or OriscusDescendens.  If it's asking for the wrong one, the executable is at fault; if the right one, it's probably the font.

**Comment by rpspringuel** [comment]
Okay, I've confirmed that the gtex is right.  So I toggled off the passed test cleaning (which I have on by default) and am looking directly at the output of the tests and seeing that it is correct too now (so I was probably looking at the wrong files before).  However, I cannot get the test to fail the way it did on the Ubuntu VM where I was testing TL2018, even at a ridiculously high resolution (1500 dpi).  That would imply a problem with the imagemagick compare operation on the Mac, right?

**Comment by rpspringuel** [comment]
On Ubuntu 16.04 `compare --version` is 

```
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-07-31 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
```
So it's slightly older.

At 300 dpi on the Ubuntu machine using files created on that machine the `compare` returns `0.998343`, which is clearly on the failing side of the test, but only just.  Using the files created on the Mac, the `compare` returns `0.998631` which is identical to what the Mac `compare` returns using the same images.  That tells me that the `compare` algorithms are not at fault.

So, I constructed the difference image on each platform (actually, the Ubuntu one was constructed for me because the test was failing), and looked at what actually changed between the two.

On the Mac:
![image](https://user-images.githubusercontent.com/7671682/38382772-cee493ea-38d8-11e8-810c-bd50dfd92e96.png)

On Ubuntu:
![image](https://user-images.githubusercontent.com/7671682/38383095-92b534d2-38d9-11e8-8606-f39ed7d7380d.png)

As you can see, on the Ubuntu machine there is a slight horizontal shift to the oriscus in addition to the change in shape which is probably what tips the difference over the line into being detectable.

So my conclusion is that this comes down to the sensitivity of the test.  I'm going to do a bit more research on that front, but that would be a test repository issue, not a bug in Gregorio itself.
