### ISSUE TITLE
Clef change & manual line break

### ISSUE THREAD

**Issue by termiciasty** [gregorio-project/gregorio#1414]
When the clef change happens at the end of the line – automatically calculated – everything seems to be OK:

`<v>{\Chr}</v> Di(h)xit(j) er(j)go(j) e(j)is(j) Pi(g)lá(h)tus<v>\,:</v>(f) (z0::c3)
<v>{\Syn}</v> Ac(i)cí(k)pi(j)te(i) e(k)um(k) vos,(k) (;)`

![gabc-clef-change1r](https://user-images.githubusercontent.com/25668757/37827540-2bc42404-2e98-11e8-9cd0-0bb5c758673e.png)

But if I were to move the neume for "S. Quam" to the next line, like this: 
`et(g) di(h)xit<v>\,:</v>(f) (z0::zc3) <v>{\Syn}</v> Quam(i)`
I get this:

![gabc-clef-change2r](https://user-images.githubusercontent.com/25668757/37827849-6197ae56-2e99-11e8-8599-410c2c348639.png)

And this for this:
`et(g) di(h)xit<v>\,:</v>(f) (::z) (c3) <v>{\Syn}</v> Quam(i)`
I get this:

![gabc-clef-change3r](https://user-images.githubusercontent.com/25668757/37827936-b2140258-2e99-11e8-880f-3ae608dd03ba.png)

Is there a right way to mix up line break and clef change that I haven't thought of?

**Comment by rpspringuel** [comment]
`z0` is specifically for a mid-line custos and thus shouldn't be combined with an explicit line break.  Something like `(z::c3)` is probably what you're looking for.

**Comment by termiciasty** [comment]
I don't think that's the way to go:

`et(g) di(h)xit<v>\,:</v>(f) (z::c3) <v>{\Syn}</v> Quam(i) ac(k)cu(k)sa(k)ti(k)ó(k)nem(j)`
![gabc-clef-change4r](https://user-images.githubusercontent.com/25668757/37891229-cdf8819c-30d3-11e8-862a-92a5d82dbbd7.png)

No divisio & wrong clef.

**Comment by termiciasty** [comment]
Oh good. I was worried it can't be done.

Both versions:
`et(g) di(h)xit<v>\,:</v>(f) (z0::c3z+) <v>{\Syn}</v> Quam(i) ac(k)cu(k)sa(k)ti(k)ó(k)nem(j)`
and
`et(g) di(h)xit<v>\,:</v>(f) (z0::c3) (z) <v>{\Syn}</v> Quam(i) ac(k)cu(k)sa(k)ti(k)ó(k)nem(j)`

do work:
![gabc-clef-change5r](https://user-images.githubusercontent.com/25668757/38013621-192b8770-3266-11e8-91cc-bb0ad8fddc19.png)

Now it's alright with the bars and custos, and clef. But can I do something to stretch the system, so that the divisio is closer to the right end of staff (and the custos)?
