### ISSUE TITLE
`latin` is not considered a valid alias for `Latin`

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1423]
In the gabc files, if one puts `latin` as the language header, then gregorio raises an error about being unable to find the language and falling back onto the default `Latin`.  Other languages don't have this problem because we establish aliases for them in the `gregorio-vowels.dat`.  The `Latin` rules, however, are hard-coded into the source so I think the alias needs to be established there as well.

**Comment by eroux** [comment]
I'm not sure making the change now is relevant, but if I were to do this part again, I would use [BCP47](https://en.wikipedia.org/wiki/IETF_language_tag) lang tags instead of names...

**Comment by rpspringuel** [comment]
Do you mean somehow embedding the tag in document meta data, or using the tag as the contents of the language header?

If the latter, it's easy enough to define aliases for the those tags.  One could even go so far as to modify the documentation to indicate a preference for those tags.  So long as the names currently defined continued to exist as aliases, there would be no backwards compatibility issues.

**Comment by rpspringuel** [comment]
Question for those more knowledgeable in C than I:

Right now the [code](https://github.com/gregorio-project/gregorio/blob/master/src/characters.c#L105-L121) which sets checks for the `Latin` language is as follows

```
void gregorio_set_centering_language(char *const language)
{
    if (!read_vowel_rules(language)) {
        if (strcmp(language, "Latin") != 0) {
            gregorio_messagef("gregorio_set_centering_language",
                    VERBOSITY_WARNING, 0, _("unable to read vowel files for "
                        "%s; defaulting to Latin rules"), language);
        }

        gregorio_vowel_tables_init();
        gregorio_vowel_table_add(DEFAULT_VOWELS);
        gregorio_prefix_table_add("i");
        gregorio_prefix_table_add("I");
        gregorio_prefix_table_add("u");
        gregorio_prefix_table_add("U");
    }
}
```

If I read this correctly, then the line which hard codes for `Latin` as the language name is line [108](https://github.com/gregorio-project/gregorio/blob/master/src/characters.c#L108).  To fix this issue, I think changing `strcmp` to `strcasecmp` would do it, but that is only supported on POSIX compliant systems (i.e. not Windows).  Is this is a compile time thing or a runtime thing?  If it's compile time, then I think that we can make that change because we compile our Windows executables on a Linux cross compiler (which should be POSIX compliant).

Further, to allow for the BCP47 lang tags, I think adding `|| (strcasecmp(language, "la") != 0)` to the condition would check the box for Latin (assuming `strcasecmp` being defined is a compile time issue), while adding the appropriate aliases in `gregorio-vowels.dat` would work for everything else.

Have I read these things right?

**Comment by henryso** [comment]
On Tuesday, 19 June 2018 at 02:33:16 pm -0700, Br. Samuel Springuel wrote:
> Question for those more knowledgeable in C than I:
> 
> Right now the [code](https://github.com/gregorio-project/gregorio/blob/master/src/characters.c#L105-L121) which sets checks for the `Latin` language is as follows
> 
> ```
> void gregorio_set_centering_language(char *const language)
> {
>     if (!read_vowel_rules(language)) {
>         if (strcmp(language, "Latin") != 0) {
>             gregorio_messagef("gregorio_set_centering_language",
>                     VERBOSITY_WARNING, 0, _("unable to read vowel files for "
>                         "%s; defaulting to Latin rules"), language);
>         }
> 
>         gregorio_vowel_tables_init();
>         gregorio_vowel_table_add(DEFAULT_VOWELS);
>         gregorio_prefix_table_add("i");
>         gregorio_prefix_table_add("I");
>         gregorio_prefix_table_add("u");
>         gregorio_prefix_table_add("U");
>     }
> }
> ```
> 
> If I read this correctly, then the line which hard codes for `Latin` as the language name is line [108](https://github.com/gregorio-project/gregorio/blob/master/src/characters.c#L108).  To fix this issue, I think changing `strcmp` to `strcasecmp` would do it, but that is only supported on POSIX compliant systems (i.e. not Windows).  Is this is a compile time thing or a runtime thing?  If it's compile time, then I think that we can make that change because we compile our Windows executables on a Linux cross compiler (which should be POSIX compliant).

There is no standard for a case-insensitive compare.  This is something
that is possible with detection at compile time, but remember that TeX
Live compiles gregorio using an old version of Visual Studio, and that
causes all sorts of problems.

> 
> Further, to allow for the BCP47 lang tags, I think adding `|| (strcasecmp(language, "la") != 0)` to the condition would check the box for Latin (assuming `strcasecmp` being defined is a compile time issue), while adding the appropriate aliases in `gregorio-vowels.dat` would work for everything else.
> 
> Have I read these things right?

Is all of this extra business really necessary just to hide a warning,
which is hidden by default in the first place?

Henry

**Comment by rpspringuel** [comment]
It's a consistency thing.  Both `english` and `English` are considered valid, but only `Latin` is.  Sure, its only a warning and it falls back on the right language, but if there's an easy fix, then it's low hanging fruit.

**Comment by henryso** [comment]
On Wednesday, 20 June 2018 at 05:56:15 am -0700, Br. Samuel Springuel wrote:
> It's a consistency thing.  Both `english` and `English` are considered valid, but only `Latin` is.  Sure, its only a warning and it falls back on the right language, but if there's an easy fix, then it's low hanging fruit.

The easy (and portable) fix, then, is to compare with "latin" as well.

**Comment by rpspringuel** [comment]
Right.  Working that up.
