### ISSUE TITLE
eighth bar

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1424]
Someone (working on a project of Cistercian graduale) asked about the possibility to have an eight bar, basically a smaller division minima. It seems quite reasonable to me and doesn't seem like a very big change (?). She'll send me a drawing of what it should look like, I'll post it as a comment here, but I think it's helpful to start tracking the issue here

**Comment by eroux** [comment]
Here's a picture of the desired result:

![al--ego_sum_pastor--cist_08-06-18-2](https://user-images.githubusercontent.com/60868/41593106-409f646c-73bf-11e8-84e5-81b89825acd2.jpg)

the asked characteristics are:
- same width as the quarter bar, half its height
- the top of the eighth bar is the same as the top of a note in the `l` position
- same general properties as the other bars

**Comment by henryso** [comment]
Any suggestions for the gabc?  Perhaps caret (`^`)?  I don't think a modifier on `,` or `` ` `` is a good idea at this point because we already have `,0` / `` `0 `` for a divisio minima/virgula on the ledger line.

**Comment by henryso** [comment]
Another option would be double quote (`"`).

**Comment by eroux** [comment]
I think caret is the option if prefer (double quotes may be confusing to softwares). Or maybe it could be a variation of the quarter bar? like `,2`? Caret is more user friendly...

**Comment by henryso** [comment]
`,2` already generates a Dominican bar, so it'll have to be caret.

**Comment by henryso** [comment]
First cut:

![image](https://user-images.githubusercontent.com/421318/43983100-dea60c76-9cc6-11e8-97d7-e874ee66e0d1.png)

**Comment by eroux** [comment]
the design has been approved by the abbey who requested it, closing, thanks!
