### ISSUE TITLE
Clivis with epiphonus at the end

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#143]
In Antiphonale Romanum II, p. 183, Antiphona Liberavit Dominus, I found on the pau syllable of pauperem something I haven't managed to typeset properly with gregorio.
The original neume is:
http://www.e-codices.unifr.ch/en/csg/0390/179/x-large
combined quilisma with clivis and epiphonus at the end (with tractulus below it).
I've tried:
(g!hw!ihi~) and also simpler (ihi~), but that gives:
![test1](https://cloud.githubusercontent.com/assets/9370665/6808963/817a382a-d257-11e4-930c-b6e5a7ed60d4.png)
Is there or could there be a way to typeset it (perhaps with different gabc syntax) as something like:
![test2](https://cloud.githubusercontent.com/assets/9370665/6808972/8830021c-d257-11e4-88eb-580c0f8a462d.png)
which is used in the AROMII 2009 book?

**Comment by eroux** [comment]
Can you please attach a scan of the neume? I don't have AROMII

**Comment by jakubjelinek** [comment]
Sure, here it is:
![test3](https://cloud.githubusercontent.com/assets/9370665/6809515/22092726-d25b-11e4-91b3-a6b5f88006ed.png)

**Comment by henryso** [comment]
Is the current output for `(ihi~)` wrong?  Is it an outdated form?  Is it a house style?  Can the same score have both forms simultaneously?

**Comment by eroux** [comment]
I can't remember the details, but I think the current form of `ihi~` appears (rarely) in Solesmes' books. But there could be a glyph for `hihi~` (and `hwihi~`) that corresponds to the desired shape here... That would be a solution, I don't think it would have side-effects... What do you think?

**Comment by jakubjelinek** [comment]
I haven't seen the ihi~ in this form, but haven't looked for it carefully yet.
For ijij~, there are examples that match the current output, e.g.
http://gregobase.selapa.net/chant.php?id=1263
http://gregobase.selapa.net/chant.php?id=3912
http://gregobase.selapa.net/chant.php?id=533
hwihi~ doesn't appear anywhere in gregobase (at least from 2 months ago).
So perhaps this is just about hwihi~ and nothing else?

**Comment by eroux** [comment]
I think it's more a special feature of Nocturnale Romanum (that might not be special on purpose)... In the future maybe Solesmes will have `hwihi~` with an output similar to Gregorio, who knows... So I think it would be relevant to add a way to switch between current form of porrectus deminutus, and an alternate form... Maybe this could fit in the alternate glyph system ongoing in `develop`? What do you think @henryso ?

**Comment by jakubjelinek** [comment]
This was actually in Antiphonale Romanum II, so recent (2009) Solesmes book with lots of neographies: http://www.solesmes.com/GB/editions/livres.php?cmY9MTMx

**Comment by eroux** [comment]
Sorry, my mistake! Well, then I think `hwihi~` can be a special case, no need for alternate form mechanism...

**Comment by jakubjelinek** [comment]
Actually no, have a proof that this is an alternative issue.
http://gregobase.selapa.net/chant.php?id=2576
has GAUdens and exSULtant (hgh~) typeset the way gregorio does.
That is Liber Usualis, Solesmes 1961.  The same antiphona in Antiphonale Monasticum 1934 is just with normal (hgh) in both places (p. 758/759).
And in Anitphonale Romanum II, 2009, the same antiphona (p. 780) uses the (hgh~) glyph as in
https://cloud.githubusercontent.com/assets/9370665/6808972/8830021c-d257-11e4-88eb-580c0f8a462d.png in both places.

**Comment by eroux** [comment]
Thanks a lot for you research! @henryso, I think it's the right time to deal with this kind of alternate right? I can do the font drawing part if you want

**Comment by henryso** [comment]
Yes, that is what I was trying to discern with my pointed question. This does indeed sound like a variant of the same neume. It sounds like the AROMII should be the default, with the current neume (which appears to be outdated) the alternative.

**Comment by henryso** [comment]
@eroux Let me give font drawing a shot. It'll help me learn how the bigger figures work.  But I'm not going to be able to do it as fast as you can.

**Comment by eroux** [comment]
Sure, that's a good thing to learn, new shape requests appear from time to time

**Comment by henryso** [comment]
Unless someone disagrees, `(hwihi)` will be a "quilisma torculus resupinus" and `(hwihi~)` will be a "quilisma torculus resupinus deminutus".

**Comment by eroux** [comment]
ok

**Comment by henryso** [comment]
Question: why is the "porrectus deminutus" section of `squarize.py` commented out?  I'm going to uncomment it for this fix, but the reason it was commented out in the first place might force me to do something differently.

**Comment by eroux** [comment]
It might be because I changed to the shape we have now, I certainly just commented the calls... So I think you can just uncomment and give if a different name

**Comment by henryso** [comment]
I'd like to base my changes off of newbars since the Lua code is improved over develop.  Is that agreeable?

**Comment by eroux** [comment]
A possibility is to merge newbars as it is, and I'll make another request actually implementing the bar macros... Sorry to be so slow, big bug in my job required extra work...

**Comment by henryso** [comment]
I'll base my changes off of newbars, and whichever merges first will be merged into the other before the final merge.  It shouldn't be too much of an issue.
