### ISSUE TITLE
Start new line in gabc file

### ISSUE THREAD

**Issue by Nokel81** [gregorio-project/gregorio#1436]
It would be very useful to be able to start a new line of numes while still in the same gabc file. This would be very useful for V/R music.

I propose that the `%%` be used to delineate the sections and that the text have no large starting letter. 

I know that it is possible to just use multiple files but that can become extremely unwieldy. 

If this is a good addition I should like to take a shot at it for my first addition.

**Comment by rpspringuel** [comment]
You're looking for `z` and `Z`.  The first justifies the line being ended before starting the new line while the second simply starts the new line with no justification of the line being ended.  Both are entered as a note (inside the parentheses) and can appear either within an existing syllable or in a syllable by themselves.
