### ISSUE TITLE
Bug in docs - inclinatum debilis

### ISSUE THREAD

**Issue by SirPL** [gregorio-project/gregorio#1437]
According to the current documentation punctum inclinatum and punctum inclinatum debilis is encoded the same way:
![image](https://user-images.githubusercontent.com/11311649/48665709-a00c3400-eab3-11e8-8840-adbdadb00db8.png)

Possibly someone forgot to escape a tilde.

**Comment by rpspringuel** [comment]
You’re right.  The error is in line 491 of Gabc.tex.  I’ll look into posting a fix later (probably tomorrow). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
