### ISSUE TITLE
Missing staff lines after first line

### ISSUE THREAD

**Issue by BeyondTheHorizon** [gregorio-project/gregorio#1438]
I'm running MiKTeX with Gregorio 5.1.1 on Windows 10. I compiled the example score and all the staff lines after the first line disappear. This is the log file when running `lualatex --shell-escape main-lualatex.tex`:

lualatex: warning: running with administrator privileges
This is LuaTeX, Version 1.09.0 (MiKTeX 2.9.6880 64-bit)
 system commands enabled.
(./main-lualatex.tex
LaTeX2e <2018-04-01> patch level 5

luaotfload | main : initialization completed in 0.422 seconds
("C:/Program Files/MiKTeX 2.9/tex/latex/base/article.cls"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
("C:/Program Files/MiKTeX 2.9/tex/latex/base/size11.clo"))
("C:/Program Files/MiKTeX 2.9/tex/latex/fontspec/fontspec.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/l3packages/xparse/xparse.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/l3kernel/expl3.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/l3kernel/expl3-code.tex")
("C:/Program Files/MiKTeX 2.9/tex/latex/l3kernel/l3pdfmode.def")))
("C:/Program Files/MiKTeX 2.9/tex/latex/fontspec/fontspec-luatex.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/base/fontenc.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/base/tuenc.def"))
("C:/Program Files/MiKTeX 2.9/tex/latex/fontspec/fontspec.cfg")))
("C:/Program Files/MiKTeX 2.9/tex/latex/graphics/graphicx.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/graphics/keyval.sty")
("C:/Program Files/MiKTeX 2.9/tex/latex/graphics/graphics.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/graphics/trig.sty")
("C:/Program Files/MiKTeX 2.9/tex/latex/graphics-cfg/graphics.cfg")
("C:/Program Files/MiKTeX 2.9/tex/latex/graphics-def/luatex.def")))
("C:/Program Files/MiKTeX 2.9/tex/latex/geometry/geometry.sty"
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/ifpdf.sty")
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/ifvtex.sty")
("C:/Program Files/MiKTeX 2.9/tex/generic/ifxetex/ifxetex.sty")
("C:/Program Files/MiKTeX 2.9/tex/latex/geometry/geometry.cfg"))
("C:/Program Files (x86)/gregorio/texmf/tex/lualatex/gregoriotex/gregoriotex.st
y" ("C:/Program Files/MiKTeX 2.9/tex/latex/xcolor/xcolor.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/graphics-cfg/color.cfg"))
("C:/Program Files/MiKTeX 2.9/tex/latex/oberdiek/kvoptions.sty"
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/ltxcmds.sty")
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/kvsetkeys.sty"
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/infwarerr.sty")
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/etexcmds.sty"
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/ifluatex.sty"))))
("C:/Program Files/MiKTeX 2.9/tex/luatex/luatexbase/luatexbase.sty"
("C:/Program Files/MiKTeX 2.9/tex/luatex/ctablestack/ctablestack.sty"))
("C:/Program Files/MiKTeX 2.9/tex/luatex/luamplib/luamplib.sty")
("C:/Program Files/MiKTeX 2.9/tex/latex/xstring/xstring.sty"
("C:/Program Files/MiKTeX 2.9/tex/generic/xstring/xstring.tex"))
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex-main
.tex"
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex-comm
on.tex")
(main-lualatex.gaux)
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex-spac
es.tex")
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex-char
s.tex")
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex-sign
s.tex")
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex-syll
able.tex")
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex-symb
ols.tex")
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gsp-default.tex"
)
("C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex-nabc
.tex"))) ("C:/Program Files/MiKTeX 2.9/tex/latex/preprint/fullpage.sty")
("C:/Program Files/MiKTeX 2.9/tex/latex/libertine/libertine.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/xkeyval/xkeyval.sty"
("C:/Program Files/MiKTeX 2.9/tex/generic/xkeyval/xkeyval.tex"
("C:/Program Files/MiKTeX 2.9/tex/generic/xkeyval/xkvutils.tex")))
("C:/Program Files/MiKTeX 2.9/tex/latex/base/textcomp.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/base/ts1enc.def"))
("C:/Program Files/MiKTeX 2.9/tex/latex/libertine/LinLibertine_R.tex")
("C:/Program Files/MiKTeX 2.9/tex/latex/libertine/LinBiolinum_R.tex")
("C:/Program Files/MiKTeX 2.9/tex/latex/libertine/LinBiolinum_K.tex")
("C:/Program Files/MiKTeX 2.9/tex/latex/libertine/LinLibertine_I.tex")
("C:/Program Files/MiKTeX 2.9/tex/latex/libertine/LKey.tex"))
(./main-lualatex.aux) ("C:/Program Files/MiKTeX 2.9/tex/latex/base/ts1cmr.fd")
("C:/Program Files/MiKTeX 2.9/tex/context/base/supp-pdf.mkii"
[Loading MPS to PDF converter (version 2006.09.02).]
) ("C:/Program Files/MiKTeX 2.9/tex/latex/oberdiek/epstopdf-base.sty"
("C:/Program Files/MiKTeX 2.9/tex/latex/oberdiek/grfext.sty"
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/kvdefinekeys.sty"))
("C:/Program Files/MiKTeX 2.9/tex/generic/oberdiek/pdftexcmds.sty"))
*geometry* driver: auto-detecting
*geometry* detected driver: luatex
(./PopulusSion-5_1_1.gtex) (./FactusEst-5_1_1.gtex) [1{C:/Users/Robert/AppData/
Local/MiKTeX/2.9/pdftex/config/pdftex.map}] (./main-lualatex.aux))
 2068 words of node memory still in use:
   36 hlist, 8 vlist, 29 rule, 1 local_par, 30 glue, 34 kern, 7 penalty, 13 gly
ph, 202 attribute, 72 glue_spec, 38 attribute_list, 1 write, 1 user_defined nod
es
   avail lists: 2:16672,3:1635,4:208,5:2543,6:199,7:2553,9:2777,10:19,11:3
<C:/Program Files (x86)/gregorio/texmf/fonts/truetype/public/gregoriotex/gregal
l.ttf><C:/Program Files (x86)/gregorio/texmf/fonts/truetype/public/gregoriotex/
greextra.ttf><C:/Program Files (x86)/gregorio/texmf/fonts/truetype/public/grego
riotex/greciliae.ttf><C:/Program Files/MiKTeX 2.9/fonts/opentype/public/liberti
ne/LinLibertine_RB.otf><C:/Program Files/MiKTeX 2.9/fonts/opentype/public/liber
tine/LinLibertine_RI.otf><C:/Program Files/MiKTeX 2.9/fonts/opentype/public/lib
ertine/LinLibertine_R.otf>
Output written on main-lualatex.pdf (1 page, 40804 bytes).
Transcript written on main-lualatex.log.

And here's the .pdf file for evidence.
[main-lualatex.pdf](https://github.com/gregorio-project/gregorio/files/2593062/main-lualatex.pdf)

**Comment by rpspringuel** [comment]
Is this after the first or second run of lualaTeX?  I seem to recall a bug where that might happen after the first run, but would fix itself on the second. 

✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️
Br. Samuel, OSB 
(R. Padraic Springuel)
St. Anselm’s Abbey 
4501 South Dakota Ave, NE
Washington, DC, 20017
202-269-2300
(c) 202-853-7036

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by BeyondTheHorizon** [comment]
Hi, thanks for replying. Unfortunately, I have run it multiple times.

**Comment by rpspringuel** [comment]
Please download and run contrib/system-setup.bat and post the results.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BeyondTheHorizon** [comment]
It says "Cannot open C:\Program", and then goes onto a new line saying "Cannot open Files", and then another new line saying "Cannot open (x86)" and so on. I take it there's a problem with spaces in the path?

**Comment by rpspringuel** [comment]
Please open the bat file in a text editor and post the first 5 lines. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rpspringuel** [comment]
That looks right.  Please post the entire output of a filed run of the script.

**Comment by BeyondTheHorizon** [comment]
Creating system-setup.log...
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\lualatex\gregoriotex\gregoriosyms.sty
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\lualatex\gregoriotex\gregoriosyms.sty
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-chars.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-chars.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-main.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-main.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-nabc.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-nabc.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-signs.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-signs.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-spaces.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-spaces.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-syllable.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-syllable.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-common.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-common.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-symbols.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-symbols.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-nabc.lua
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-nabc.lua
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-signs.lua
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-signs.lua
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-symbols.lua
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex-symbols.lua
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex.lua
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex.lua
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\lualatex\gregoriotex\gregoriotex.sty
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\lualatex\gregoriotex\gregoriotex.sty
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files
FINDSTR: Cannot open (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex.tex
FINDSTR: Cannot open C:\Program
FINDSTR: Cannot open Files\MiKTeX
FINDSTR: Cannot open 2.9\tex\luatex\gregoriotex\gregoriotex.tex


system-setup.log created and saved in a temporary location.
Upon exiting this script, the log will be opened in Notepad for you.
Please save the file to a convenient location and email it to
gregorio-users@googlegroups.com as part of your bug report.

You can also create an issue at
http://github.org/gregorio-project/gregorio/issues
and copy-paste the content of this file into the description.

Press any key to continue . . .

**Comment by rpspringuel** [comment]
Okay, based on that I at least know where to look for the problem with the script.  I’ll put this on the task list for Friday. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rpspringuel** [comment]
You can also simply install the tools as a stand alone: https://www.lcdf.org/type/

**Comment by BeyondTheHorizon** [comment]
Okay, so after a bit of hassle I was able to install lcdf-typetools on MiKTeX so that the log file from system-setup.bat doesn't complain that otfinfo wasn't found. I also refreshed the file name database and font map files.

Unfortunately, it didn't resolve the staff lines problem, so either I did something wrong or MiKTeX requires another manual package as well. I might as well send you the log file for the main .tex file, if that helps.

[main-lualatex.log](https://github.com/gregorio-project/gregorio/files/2636840/main-lualatex.log)

**Comment by rpspringuel** [comment]
The lcdf-typetools were never going to fix the compilation problem.  They would only serve to make the log file generated by system-setup.bat more complete (by allowing the extraction of font versions).

I would still like to see the system-setup.log file, though, as it'll help me recreate your setup on my VM so that I can hopefully duplicate your issue.

**Comment by mfbps** [comment]
This is my system-setup.log:

````
###	Gregorio Windows Setup Results 
####	Created: 20/12/2018 
----------------------------------------------------------------------------- 
 
 
###	Windows Version 

Microsoft Windows [Version 10.0.17134.472]
 
 
----------------------------------------------------------------------------- 
 
 
###	LuaTeX Setup 
####	Version 
 
This is LuaTeX, Version 1.09.0 (MiKTeX 2.9.6880 64-bit)

Execute  'luatex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

LuaTeX is Copyright 2018 Taco Hoekwater and the LuaTeX Team.

 
####	Location 
 
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\luatex.exe 
 
 
#### TEXMFDIST 
C:/Program Files/MiKTeX 2.9
 
#### 	TEXMFLOCAL 
 
C:/Users/migsi/AppData/Roaming/MiKTeX/2.9 
 
#### TEXINPUTS.lualatex 

 
#### LUAINPUTS.lualatex 

 
#### shell_escape 
p
 
#### Shell Escape Commands 
miktex-bibtex,miktex-bibtex8,miktex-epstopdf,miktex-gregorio,miktex-kpsewhich,miktex-makeindex,bibtex,bibtex8,epstopdf,extractbb,findtexmf,gregorio,kpsewhich,makeindex,texosquery-jre8
 
#### openout_any 

 
#### openin_any 

 
 
----------------------------------------------------------------------------- 
 
 
###	Gregorio Setup 
####	Locations and Versions 
"C:\Program Files\MiKTeX 2.9\miktex\bin\x64\gregorio.exe" 
Gregorio 5.1.1 (MiKTeX 2.9.6880 64-bit). 
Copyright (C) 2006-2018 Gregorio Project authors (see CONTRIBUTORS.md) 
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> 
This is free software: you are free to change and redistribute it. 
There is NO WARRANTY, to the extent permitted by law. 
 
"C:\Program Files (x86)\gregorio\bin\gregorio-5_1_1.exe" 
Gregorio 5.1.1. 
Copyright (C) 2006-2018 Gregorio Project authors (see CONTRIBUTORS.md) 
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> 
This is free software: you are free to change and redistribute it. 
There is NO WARRANTY, to the extent permitted by law. 
 
####	GregorioTeX Locations 
 
##### gregoriosyms.sty 
C:\Program Files (x86)\gregorio\texmf\tex\lualatex\gregoriotex\gregoriosyms.sty 
5.1.1 
##### gregoriotex-chars.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-chars.tex 
5.1.1 
##### gregoriotex-main.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-main.tex 
5.1.1 
##### gregoriotex-nabc.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-nabc.tex 
5.1.1 
##### gregoriotex-signs.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-signs.tex 
5.1.1 
##### gregoriotex-spaces.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-spaces.tex 
5.1.1 
##### gregoriotex-syllable.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-syllable.tex 
5.1.1 
##### gregoriotex-common.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-common.tex 
5.1.1 
##### gregoriotex-symbols.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-symbols.tex 
5.1.1 
##### gregoriotex-nabc.lua 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-nabc.lua 
5.1.1 
##### gregoriotex-signs.lua 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-signs.lua 
5.1.1 
##### gregoriotex-symbols.lua 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex-symbols.lua 
5.1.1 
##### gregoriotex.lua 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex.lua 
5.1.1 
##### gregoriotex.sty 
C:\Program Files (x86)\gregorio\texmf\tex\lualatex\gregoriotex\gregoriotex.sty 
5.1.1  
##### gregoriotex.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregoriotex.tex 
5.1.1  
##### greciliae.ttf 
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\greciliae.ttf 
'otfinfo' is not recognized as an internal or external command,
operable program or batch file.
##### greciliae-hollow.ttf 
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\greciliae-hollow.ttf 
'otfinfo' is not recognized as an internal or external command,
operable program or batch file.
##### greciliae-hole.ttf 
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\greciliae-hole.ttf 
'otfinfo' is not recognized as an internal or external command,
operable program or batch file.
##### greciliae-op.ttf 
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\greciliae-op.ttf 
'otfinfo' is not recognized as an internal or external command,
operable program or batch file.
##### greciliae-op-hollow.ttf 
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\greciliae-op-hollow.ttf 
'otfinfo' is not recognized as an internal or external command,
operable program or batch file.
##### greciliae-op-hole.ttf 
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\greciliae-op-hole.ttf 
'otfinfo' is not recognized as an internal or external command,
operable program or batch file.
##### greextra.ttf 
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\greextra.ttf 
'otfinfo' is not recognized as an internal or external command,
operable program or batch file.
##### gregorio.ttf 
##### gregorio-hollow.ttf 
##### gregorio-hole.ttf 
##### gregorio-op.ttf 
##### gregorio-op-hollow.ttf 
##### gregorio-op-hole.ttf 
##### granapadano.ttf 
##### granapadano-hollow.ttf 
##### granapadano-hole.ttf 
##### granapadano-op.ttf 
##### granapadano-op-hollow.ttf 
##### granapadano-op-hole.ttf 
##### gregall.ttf 
C:\Program Files (x86)\gregorio\texmf\fonts\truetype\public\gregoriotex\gregall.ttf 
'otfinfo' is not recognized as an internal or external command,
operable program or batch file.
##### gregorio-vowels.dat 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gregorio-vowels.dat 
##### gsp-default.tex 
C:\Program Files (x86)\gregorio\texmf\tex\luatex\gregoriotex\gsp-default.tex 
##### gregoriotex-ictus.tex 
##### gresym.ttf 
##### parmesan.ttf 
##### parmesan-op.ttf 
====================================================================== 
starting package maintenance... 
installation directory: C:\Users\migsi\AppData\Roaming\MiKTeX\2.9 
package repository: http:\\mirrors.up.pt\pub\CTAN\systems\win32\miktex\tm\packages\ 
visiting repository http:\\mirrors.up.pt\pub\CTAN\systems\win32\miktex\tm\packages\... 
repository type: remote package repository 
loading package repository manifest... 
downloading http:\\mirrors.up.pt\pub\CTAN\systems\win32\miktex\tm\packages\miktex-zzdb1-2.9.tar.lzma... 
0.18 MB, 0.47 Mbit\s 
package repository digest: 3c5073e73fe09b0cfc8e2b3f296cee88 
going to download 10645819 bytes 
going to install 54 file(s) (1 package(s)) 
downloading http:\\mirrors.up.pt\pub\CTAN\systems\win32\miktex\tm\packages\gregoriotex.tar.lzma... 
10.65 MB, 2.66 Mbit\s 
extracting files from gregoriotex.tar.lzma... 
====================================================================== 
C:\Users\migsi\AppData\Roaming\MiKTeX\2.9\fonts\truetype\public\gregoriotex\parmesan-op.ttf 
##### gregsmodern.ttf 
 
####	kpsewhich --all -engine luatex -progname lualatex gregoriotex.sty 
C:/Users/migsi/AppData/Roaming/MiKTeX/2.9/tex/lualatex/gregoriotex/gregoriotex.sty
C:/Program Files (x86)/gregorio/texmf/tex/lualatex/gregoriotex/gregoriotex.sty
C:/Users/migsi/AppData/Roaming/MiKTeX/2.9/tex/lualatex/gregoriotex/gregoriotex.sty
C:/Program Files (x86)/gregorio/texmf/tex/lualatex/gregoriotex/gregoriotex.sty
 
####	kpsewhich --all -engine luatex gregoriotex.tex 
C:/Users/migsi/AppData/Roaming/MiKTeX/2.9/tex/luatex/gregoriotex/gregoriotex.tex
C:/Program Files (x86)/gregorio/texmf/tex/luatex/gregoriotex/gregoriotex.tex
 
 
----------------------------------------------------------------------------- 
```

**Comment by mfbps** [comment]
For me it works with Tex Live but not with MikTex.

**Comment by BeyondTheHorizon** [comment]
Hi again, I was wondering if the "words of node memory still in use" have anything to do with the (still ongoing) problem?

**Comment by rpspringuel** [comment]
This problem has shown up in the TeX Live 2019 pretest.  It appears that MiKTeX users saw it earlier because LuaTeX was updated for them.  You'll note that the above system-setup.log notes `This is LuaTeX, Version 1.09.0 (MiKTeX 2.9.6880 64-bit)`.  TeX Live 2018 had `This is LuaTeX, Version 1.07.0 (TeX Live 2018)` while TeX Live 2019 is headed for Version 1.10.  I've yet to identify anything beyond the LuaTeX version as the cause, but I'm working on it.

**Comment by BeyondTheHorizon** [comment]
I've been following #1446, and seeing that the fix is now in the pretest for TeXLive I decided to update MiKTeX and see if the bug had been fixed there too. I can happily confirm that it has indeed been fixed for MiKTeX now, so unless anybody else still has this problem this issue can now be closed.

**Comment by eroux** [comment]
great, thanks for the test!
