### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1441]
Could we make a new release? There are a few features that have been done in the past months that would be helpful to some users and monasteries

**Comment by rpspringuel** [comment]
I have to admit that I've been sitting on a the code review for 
protecting filenames.  I'll put that on the schedule for this weekend. 
Once that's merged I don't really have any objection to a release.  The 
kpse file search feature still has plenty of bugs to be worked out and 
while I'd love to get them worked out before the TeXLive 2019 freeze, 
I'm not sure I'll have the time.  I'm in my last semester of seminary 
and just a bit busier than usual as a result.
-- 
✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
St. Anselm’s Abbey
4501 South Dakota Ave, NE
Washington, DC, 20017
202-269-2300
(c) 202-853-7036

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by eroux** [comment]
@rpspringuel any news on the release? I think it would be really good to have a release with what has currently been done and keep the kpse file search features for the next one... would that be ok? There are a few monasteries pressuring for the new release

**Comment by rpspringuel** [comment]
Sorry, I’d forgotten about this.  I’ll look at getting something going tomorrow afternoon. 

✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️
Br. Samuel, OSB
(R. Padraic Springuel)
St. Anselm’s Abbey 
4501 South Dakota Ave, NE
Washington, DC, 20017
202-269-2300
(c) 202-853-7036

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by eroux** [comment]
Great, thanks!

**Comment by rpspringuel** [comment]
I just did my first check for a release (build the distribution package at the head of develop), and I got the following bison error:

```
bison -y -v -d -p "gabc_score_determination_" -o gabc/gabc-score-determination-y.c gabc/gabc-score-determination.y
gabc/gabc-score-determination.y:692.1-11: invalid directive: `%precedence'
gabc/gabc-score-determination.y:692.13-18: warning: symbol HYPHEN redeclared
gabc/gabc-score-determination.y:693.1-11: invalid directive: `%precedence'
gabc/gabc-score-determination.y:692.20-41: warning: symbol PROTRUDING_PUNCTUATION redeclared
gabc/gabc-score-determination.y:693.13-29: warning: symbol TRANSLATION_BEGIN redeclared
gabc/gabc-score-determination.y:694.1-11: invalid directive: `%precedence'
gabc/gabc-score-determination.y:693.31-52: warning: symbol TRANSLATION_CENTER_END redeclared
gabc/gabc-score-determination.y:695.1-11: invalid directive: `%precedence'
gabc/gabc-score-determination.y:694.13-27: warning: symbol TRANSLATION_END redeclared
gabc/gabc-score-determination.y:695.13-27: warning: symbol OPENING_BRACKET redeclared
make[3]: *** [gabc/gabc-score-determination-y.c] Error 1
```

I've triggered an update of my build system to make sure everything is in order, but if that doesn't fix things, I don't understand what this error is telling me.

**Comment by eroux** [comment]
What is your version of bison?

**Comment by rpspringuel** [comment]
bison (GNU Bison) 2.3
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by eroux** [comment]
According to http://ftp.gnu.org/gnu/bison/ it's actually from 2006... is there a way for you to update it? Or else I can probably generate the file you need

**Comment by rpspringuel** [comment]
Hmm...   Some more checking reveals that as the system installed bison, not the upgraded version I usually have from my package manager (which should be at 3.3.2).  Seems I lost the bison package at some point and just never realized it until now.  I'll fix that and see what changes.

**Comment by rpspringuel** [comment]
Updating bison did it.  I also discovered that flex was in a similar position.  I must have done some overly aggressive clean-up the last time I did updated the OS (which requires a full rebuild of my package manager).

Now, however, I'm seeing some errors in the font building:
```
Internal Error (overlap) in FlexusOneDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusTwoDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusThreeDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusFourDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusFiveDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusLongqueueOneDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusLongqueueTwoDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusLongqueueThreeDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusLongqueueFourDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusLongqueueFiveDeminutus: The end of the monotonic does not match that of the containing spline.
Internal Error (overlap) in FlexusOpenqueueOneDeminutus: The end of the monotonic does not match that of the containing spline.
```
This is just the first block.  There are lots more like this, and the build keeps going past them.

```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 17:18 UTC 23-Jan-2019-D.
 Based on source from git with hash: 
fontforge 17:18 UTC 23-Jan-2019
libfontforge 20190123
```
It's too late for me to look into this more tonight.

**Comment by eroux** [comment]
Does it give bad results in the end? If not maybe these can be ignored

**Comment by rpspringuel** [comment]
I don't know if the result is bad yet.  I've run into some problems with attempting to build the docs against TeX Live 2018.

I'm getting:
```
! error:  (type 0): cannot find file ''
!  ==> Fatal error occurred, no output PDF file produced!=== TeX engine is 'LuaTeX'
```
Which seems familiar, but I can't remember where from or how to deal with it.

**Comment by rpspringuel** [comment]
I remembered what caused that error: it's a corrupted font cache.  `luaotfload-tool --cache=erase` fixed it.  I've got the dist successfully built and now have moved on to my second test: running the test suite.  Assuming that works, I'll move into the process of actually creating the release.

**Comment by eroux** [comment]
great, thanks a lot!

**Comment by rpspringuel** [comment]
I got 8 test failures.  All complaints about "Failed to create image."  Seems I'm not getting a proper install and the failing tests involve the new glyphs.  I'll have to look into that, but won't have time until Friday at the earliest.

**Comment by rpspringuel** [comment]
Got past that failure.  I had a loose `uninstall-gtex.sh` file on my system which was blocking installation.  Once I got rid of it, everything installed fine.  I'm now running the tests to see if the font build errors are problematic or not.

Oh, and I noticed during the build that we have `MAINTAINERCLEANFILES` defined twice in `fonts/Makefile.am`.  Is there a reason for this, or is it safe to consolidate them (and stop `make` from complaining about the double definition)?

**Comment by eroux** [comment]
great, thanks! no idea about the Makefile

**Comment by rpspringuel** [comment]
Test suite passes.  Whatever those font errors are about, they don't appear to be blocking the creation of a release.

I'll post the beta for review shortly.

**Comment by eroux** [comment]
thanks a lot!
