### ISSUE TITLE
5.2.1 Installation Documentation for Windows

### ISSUE THREAD

**Issue by domoknight** [gregorio-project/gregorio#1456]
This is purely a documentation issue.

For a "minimal" installation on Windows (using TeXLive), other packages that need to be installed are:

- extsizes
- filecontents
- metapost
- xkeyval

Also, it may be worth mentioning the Windows system PATH variable may need to be updated manually for gregorio to find the TeX bins.

**Comment by rpspringuel** [comment]
metapost and xkeyval I can see, but are you sure about extsizes and filecontents?

**Comment by domoknight** [comment]
I just did a clean install (on TeX Live 2018) and gregorio inside of Scribus would fail saying that it couldn't find extsizes.sty and filecontents.sty.

**Comment by domoknight** [comment]
When "filecontents" is not installed, Scribus dies with this message:


> ! LaTeX Error: File `filecontents.sty' not found.
> 
> Type X to quit or <RETURN> to proceed,
> or enter new name. (Default extension: sty)
> 
> Enter file name: 
> ! Emergency stop.

**Comment by rpspringuel** [comment]
Ah!  That's a Scribus specific issue.  That plugin makes use of those packages to make itself work more smoothly (and with additional options) within the limits of a Scribus frame.  They aren't actually needed outside of Scribus.  I'll edit the Scribus related documentation.
