### ISSUE TITLE
gsp-default.tex does not include a version check

### ISSUE THREAD

**Issue by BillyV2018** [gregorio-project/gregorio#1460]
Gregoriotex 5.2 in TexLive 2019, checked latest updates of May 3 at 10 AM.

GreSet variables work okay, except the \grechangestaffsize. According to documentation defaults to 17. I want to reduce it to 15. That provokes an error 'undefined control sequence'.
Adding 'pt' is not a solution. Leaving it to default is the workaround for the moment.
The relevant paragraphs from the error log:

! Undefined control sequence.
\gre@changedimenfactor ...ifgre@scale@bar@minimis 
                                                  \gre@changeonedimenfactor ...
l.22 \grechangestaffsize{15}
                           % 17 is de standaard maat
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Missing number, treated as zero.
<to be read again> 
\gre@space@skip@bar@minimis 
l.22 \grechangestaffsize{15}
                           % 17 is de standaard maat
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)

! Illegal unit of measure (pt inserted).
<to be read again> 
\gre@space@skip@bar@minimis 
l.22 \grechangestaffsize{15}
                           % 17 is de standaard maat
Dimensions can be in units of em, ex, in, pt, pc,
cm, mm, dd, cc, nd, nc, bp, or sp; but yours is a new one!
I'll assume that you meant to say pt, for printer's points.
To recover gracefully from this error, it's best to
delete the erroneous units; e.g., type `2' to delete
two letters. (See Chapter 27 of The TeXbook.)

! Missing ) inserted for expression.
<to be read again> 
\gre@space@skip@bar@minimis 
l.22 \grechangestaffsize{15}
                           % 17 is de standaard maat
I was expecting to see `+', `-', `*', `/', or `)'. Didn't.

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.22 \grechangestaffsize{15}
                           % 17 is de standaard maat
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

! Illegal unit of measure (pt inserted).
<to be read again> 
\gre@space@skip@bar@minimis 
l.22 \grechangestaffsize{15}
                           % 17 is de standaard maat
Dimensions can be in units of em, ex, in, pt, pc,
cm, mm, dd, cc, nd, nc, bp, or sp; but yours is a new one!
I'll assume that you meant to say pt, for printer's points.
To recover gracefully from this error, it's best to
delete the erroneous units; e.g., type `2' to delete
two letters. (See Chapter 27 of The TeXbook.)

! Missing \endcsname inserted.
<to be read again> 
\relax 
l.22 \grechangestaffsize{15}
                           % 17 is de standaard maat
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

Runaway text?
0\relax 0\relax 0\relax 0\relax 0\relax 0\relax 0\relax 0\relax 0\relax \ETC.
! TeX capacity exceeded, sorry [token memory size=63191721].
\gre@space@skip@bar@minimis ->0
                               \relax \gre@space@skip@bar@minimis 
l.22 \grechangestaffsize{15}
                           % 17 is de standaard maat
If you really absolutely need more capacity,
you can ask a wizard to enlarge me.

**Comment by eroux** [comment]
Thanks for your report, can you please give a [minimal working example](https://tex.meta.stackexchange.com/a/3225/33382) reproducing this problem?

**Comment by BillyV2018** [comment]
\documentclass[14pt,a4paper,twoside]{extarticle}
\usepackage[inner=25.00mm, outer=25.00mm, top=25.00mm, bottom=25.00mm]{geometry}
\usepackage[T1]{fontenc} 
\usepackage[autocompile]{gregoriotex}

% Gregoriotex definities
\grechangestaffsize{15} % 17 is de standaard maat

\begin{document}

\gregorioscore{gabc/asperges-me} % Where the gabc file is taken from GregoBase

\end{document}

**Comment by BillyV2018** [comment]
The absolute bottom-line MWE is:

\documentclass{article}
\usepackage[autocompile]{gregoriotex}
\grechangestaffsize{15}

\begin{document}
\gregorioscore{gabc/asperges-me}
\end{document}

**Comment by eschwab** [comment]
Using the current `develop` branch I cannot reproduce the error. Does the same error occur when using a different size other than 15?

**Comment by BillyV2018** [comment]
With any size it occurs, also for example 17, the default value.

**Comment by eschwab** [comment]
Could you post the output of `gregorio -V` ? Or perhaps it is `gregorio-5_2_1 -V`

**Comment by rpspringuel** [comment]
If running off TeX Live it would be `gregorio -V`.  More useful, however, would be the output of the system-setup script (.command for Linux and Mac, .bat for Windows). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BillyV2018** [comment]
Seen the comment of Fr Elijah, I uninstalled the collection-music first and re-installed it.
No effect.
The output of gregorio -V is:
Gregorio 5.2.0 (kpathsea version 6.3.1).
Copyright (C) 2006-2019 Gregorio Project authors (see CONTRIBUTORS.md)
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by BillyV2018** [comment]
@rpspringuel 
The output of the install-tl-windows.bat (run as administrator) with -no-gui and logfile=

Loading C:/texlive/2019/tlpkg/texlive.tlpdb
Installing TeX Live 2019 from: C:/texlive/2019 (not verified)
Platform: win32 => 'Windows'
Distribution: live (uncompressed)
Directory for temporary files: C:\Users\wjgav\AppData\Local\Temp\dPDOKQ8tbo
Installer revision: 50796
Database revision: 
Settings:
  TEXDIR: "C:/texlive/2019"
  TEXMFCONFIG: "~/.texlive2019/texmf-config"
  TEXMFHOME: "~/texmf"
  TEXMFLOCAL: "C:/texlive/texmf-local"
  TEXMFSYSCONFIG: "C:/texlive/2019/texmf-config"
  TEXMFSYSVAR: "C:/texlive/2019/texmf-var"
  TEXMFVAR: "~/.texlive2019/texmf-var"
  binary_win32: "1"
  collection-basic: "1"
  collection-bibtexextra: ""
  collection-binextra: ""
  collection-context: ""
  collection-fontsextra: ""
  collection-fontsrecommended: ""
  collection-fontutils: ""
  collection-formatsextra: ""
  collection-games: ""
  collection-humanities: ""
  collection-langarabic: ""
  collection-langchinese: ""
  collection-langcjk: ""
  collection-langcyrillic: ""
  collection-langczechslovak: ""
  collection-langenglish: ""
  collection-langeuropean: ""
  collection-langfrench: ""
  collection-langgerman: ""
  collection-langgreek: ""
  collection-langitalian: ""
  collection-langjapanese: ""
  collection-langkorean: ""
  collection-langother: ""
  collection-langpolish: ""
  collection-langportuguese: ""
  collection-langspanish: ""
  collection-latex: ""
  collection-latexextra: ""
  collection-latexrecommended: ""
  collection-luatex: ""
  collection-mathscience: ""
  collection-metapost: ""
  collection-music: ""
  collection-pictures: ""
  collection-plaingeneric: ""
  collection-pstricks: ""
  collection-publishers: ""
  collection-wintools: "1"
  collection-xetex: ""
  doc_splitting_supported: "1"
  inst_platform: "win32"
  instopt_adjustpath: "1"
  instopt_adjustrepo: "1"
  instopt_letter: ""
  instopt_portable: ""
  instopt_write18_restricted: "1"
  n_collections_available: "40"
  n_collections_selected: "2"
  n_systems_available: "1"
  n_systems_selected: "1"
  page: ""
  selected_scheme: "scheme-minimal"
  src_splitting_supported: "1"
  this_platform: "win32"
  tlpdbopt_autobackup: "1"
  tlpdbopt_backupdir: "tlpkg/backups"
  tlpdbopt_create_formats: "1"
  tlpdbopt_desktop_integration: "1"
  tlpdbopt_file_assocs: "1"
  tlpdbopt_generate_updmap: ""
  tlpdbopt_install_docfiles: "1"
  tlpdbopt_install_srcfiles: "1"
  tlpdbopt_location: "ftp://ftp.dante.de/tex-archive/systems/texlive/tlnet"
  tlpdbopt_post_code: "1"
  tlpdbopt_sys_bin: "/usr/local/bin"
  tlpdbopt_sys_info: "/usr/local/share/info"
  tlpdbopt_sys_man: "/usr/local/share/man"
  tlpdbopt_w32_multi_user: "1"
  total_size: "200"
Installing to: C:/texlive/2019
Making read-only
processed file: .
Successfully processed 1 files; Failed processing 0 files
processed file: .
Successfully processed 1 files; Failed processing 0 files

Making read-only
processed file: .
Successfully processed 1 files; Failed processing 0 files
processed file: .
Successfully processed 1 files; Failed processing 0 files

Making read-only
processed file: .
Successfully processed 1 files; Failed processing 0 files
processed file: .
Successfully processed 1 files; Failed processing 0 files

Making read-only
processed file: .
Successfully processed 1 files; Failed processing 0 files
processed file: .
Successfully processed 1 files; Failed processing 0 files

Installing [01/63, time/total: ??:??/??:??]: amsfonts [9021k]
Installing [02/63, time/total: 00:14/05:18]: bibtex [741k]
Installing [03/63, time/total: 00:15/05:14]: bibtex.win32 [101k]
Installing [04/63, time/total: 00:15/05:11]: cm [1369k]
Installing [05/63, time/total: 00:17/05:10]: collection-basic [1k]
Installing [06/63, time/total: 00:17/05:10]: collection-wintools [1k]
Installing [07/63, time/total: 00:17/05:10]: colorprofiles [265k]
Installing [08/63, time/total: 00:17/05:03]: dehyph [229k]
Installing [09/63, time/total: 00:18/05:14]: dviout.win32 [4805k]
postaction install fileassoc for dviout.win32: .dvi, TL.DVIOUT.view.2019
Installing [10/63, time/total: 00:21/04:20]: dvipdfmx [4129k]
Installing [11/63, time/total: 00:22/03:38]: dvipdfmx.win32 [905k]
Installing [12/63, time/total: 00:22/03:29]: dvips [1513k]
Installing [13/63, time/total: 00:23/03:24]: dvips.win32 [205k]
Installing [14/63, time/total: 00:23/03:22]: enctex [681k]
Installing [15/63, time/total: 00:24/03:25]: etex [561k]
Installing [16/63, time/total: 00:24/03:20]: etex-pkg [25k]
Installing [17/63, time/total: 00:24/03:20]: glyphlist [97k]
Installing [18/63, time/total: 00:24/03:19]: graphics-def [89k]
Installing [19/63, time/total: 00:24/03:18]: gsftopk [49k]
Installing [20/63, time/total: 00:24/03:18]: gsftopk.win32 [25k]
Installing [21/63, time/total: 00:25/03:26]: hyph-utf8 [1105k]
Installing [22/63, time/total: 00:26/03:25]: hyphen-base [97k]
Installing [23/63, time/total: 00:26/03:24]: ifluatex [169k]
Installing [24/63, time/total: 00:26/03:23]: ifxetex [185k]
Installing [25/63, time/total: 00:26/03:22]: knuth-lib [189k]
Installing [26/63, time/total: 00:26/03:20]: knuth-local [209k]
Installing [27/63, time/total: 00:27/03:26]: kpathsea [2489k]
Installing [28/63, time/total: 00:28/03:16]: kpathsea.win32 [1449k]
Installing [29/63, time/total: 00:28/03:07]: lua-alt-getopt [33k]
Installing [30/63, time/total: 00:29/03:13]: luatex [2513k]
Installing [31/63, time/total: 00:29/02:58]: luatex.win32 [12457k]
Installing [32/63, time/total: 00:30/02:14]: makeindex [561k]
Installing [33/63, time/total: 00:30/02:12]: makeindex.win32 [85k]
Installing [34/63, time/total: 00:30/02:12]: metafont [289k]
Installing [35/63, time/total: 00:30/02:11]: metafont.win32 [553k]
Installing [36/63, time/total: 00:31/02:14]: mflogo [301k]
Installing [37/63, time/total: 00:31/02:13]: mfware [185k]
Installing [38/63, time/total: 00:31/02:13]: mfware.win32 [181k]
Installing [39/63, time/total: 00:31/02:12]: pdftex [3045k]
Installing [40/63, time/total: 00:32/02:08]: pdftex.win32 [1829k]
Installing [41/63, time/total: 00:32/02:04]: plain [1345k]
Installing [42/63, time/total: 00:33/02:05]: tetex [1497k]
Installing [43/63, time/total: 00:34/02:05]: tetex.win32 [25k]
Installing [44/63, time/total: 00:34/02:05]: tex [109k]
Installing [45/63, time/total: 00:34/02:05]: tex-ini-files [37k]
Installing [46/63, time/total: 00:35/02:08]: tex.win32 [301k]
Installing [47/63, time/total: 00:35/02:08]: texlive-common [525k]
Installing [48/63, time/total: 00:35/02:06]: texlive-docindex [2261k]
Installing [49/63, time/total: 00:35/02:02]: texlive-en [5417k]
Installing [50/63, time/total: 00:37/01:58]: texlive-msg-translations [1521k]
Installing [51/63, time/total: 00:38/01:58]: texlive-scripts [429k]
Installing [52/63, time/total: 00:38/01:57]: texlive-scripts.win32 [41k]
Installing [53/63, time/total: 00:38/01:57]: texlive.infra [1497k]
Installing [54/63, time/total: 00:39/01:58]: texlive.infra.win32 [9649k]
Installing [55/63, time/total: 00:39/01:43]: tlgs.win32 [24873k]
Installing [56/63, time/total: 00:50/01:40]: tlperl.win32 [45117k]

Script stopped with error when overwriting texlive\2019\tlpkg\tlperl\bin\libgcc_s_dw2-1.dll

**Comment by BillyV2018** [comment]
Install from repository at ftp://ftp.dante.de/tex-archive/systems/texlive/tlnet

**Comment by BillyV2018** [comment]
Sorry, that ruined my entire installation. I will have to install from scratch I'm afraid.
I will call anew when ready.

**Comment by rpspringuel** [comment]
Sorry, I should have been clearer.  system-setup.bat is our diagnostic tool, not the installer from TeX Live. You can get it from the contrib folder here in the repository. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rpspringuel** [comment]
I just installed TeX Live 2019 on my Mac and cannot confirm this error.  We will definately need the full diagnostic information from [system-setup.bat](https://raw.githubusercontent.com/gregorio-project/gregorio/master/contrib/system-setup.bat) (this is a direct link to the raw file, you should be able to right-click "Save as...").

**Comment by BillyV2018** [comment]
@rpspringuel I finished the fresh install
Then I ran the system-setup.bat
The log:

[system-setup.log](https://github.com/gregorio-project/gregorio/files/3144515/system-setup.log)

**Comment by rpspringuel** [comment]
Please run `tlmgr --update self` and the `tlmgr --update all` and try again. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BillyV2018** [comment]
Here are the outputs of both tlmgr runs:

tlmgr update --self
tlmgr.pl: package repository http://ftp.snt.utwente.nl/pub/software/tex/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl: saving backups to C:/texlive/2019/tlpkg/backups
tlmgr.pl: no self-updates for tlmgr available.

And
tlmgr update --all
tlmgr.pl: package repository http://ftp.snt.utwente.nl/pub/software/tex/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl: saving backups to C:/texlive/2019/tlpkg/backups
tlmgr.pl: no updates available

The log of the MWE as attachment, same error
[mwe-gregoriotex.log](https://github.com/gregorio-project/gregorio/files/3144788/mwe-gregoriotex.log)

**Comment by BillyV2018** [comment]
@rpspringuel Should I use a different repository, or is utwente.nl (the nearest) okay?

**Comment by rpspringuel** [comment]
No, the repository shouldn't be the issue.  Looking closer at the log I notice that it's loading a local copy of gsp-default.tex (from the working directory), not the repository copy.  Are you making use of some custom spacings?  If so, when was that custom gsp-default.tex file created?

**Comment by BillyV2018** [comment]
@rpspringuel You solved the problem! This copy of the gsp-default.tex caused the problem.
No idea how it got there, but the fact remains: problem solved! The MWE compiled as expected.
Thank you, and God bless.

**Comment by rpspringuel** [comment]
I’m glad the problem is solved.  I’m re opening this to discuss with the other developers if there is something we should do to help prevent this in the future.  Right now gap-default.tex doesn’t have a version check in it.  Should we perhaps add that, as the problem with the old gap-default.tex was that it failed to define all the distances that the newer version needed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BillyV2018** [comment]
I am sorry I didn't save the local gsp-default.tex to show the contents of it.

**Comment by rpspringuel** [comment]
No need.  If that becomes a needed piece of information, I can figure it out from the log you posted. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
