### ISSUE TITLE
Searching for Latin in gregoriotex-vowels.dat

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1470]
If the language is `Latin`, `latin`, `lat`, or `la` then is there really a need to search the gregoriotex-vowels.dat files for vowel definition rules?  The only reason I can think of is to allow a user to define alternate vowel definitions for Latin.  Is that really reasonable?

If it is not, then we should modify `characters.c` lines [63-87](https://github.com/gregorio-project/gregorio/blob/master/src/characters.c#L63) so as to skip over this block when the language is Latin.

On the other hand, if it is reasonable that a user might want to define an alternate set of vowel determination rules for Latin, then we should probably add an informational message (or modify the existing ones) so that when the user sees "Could not find Latin..." they don't worry about it.

**Comment by henryso** [comment]
I think it is reasonable so that the user can override the built-in rules for ones they prefer, so I recommend the change of informational message.
