### ISSUE TITLE
Detect changes

### ISSUE THREAD

**Issue by Nokel81** [gregorio-project/gregorio#1471]
I don't know if this is possible but would it be possible to not have to recompile every .gabc file for every render if most of the document hasn't changed?

**Comment by rpspringuel** [comment]
Already a feature.  Use the autocompile option (which should be the default). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nokel81** [comment]
Is there a way to turn it on? Because if I change nothing and hit recompile in TeXworks it has to do the whole thing again which takes a very long time.

**Comment by eschwab** [comment]
A TeX document must be compiled in whole. It is not possible to only recompile the changed portions.
