### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by veromary** [gregorio-project/gregorio#1472]
line 80 of `tex/gregoriotex-symbols.tex`
looks like it should be `ABar.alt`
`````
\gredefsizedsymbol{greABarAlt}{greextra}{RBar.alt}
\gredefsizedsymbol{greRBarAlt}{greextra}{RBar.alt}
\gredefsizedsymbol{greVBarAlt}{greextra}{VBar.alt}

**Comment by rpspringuel** [comment]
I really should test things before acting on them:

This is not a typo.  There is no Abar.alt glyph.
