### ISSUE TITLE
Versicle and Response formatting

### ISSUE THREAD

**Issue by corei8** [gregorio-project/gregorio#1482]
I am trying to make a versicle-response line of chant, but am running into an issue. The `<sp>V/</sp>` is appearing as a default initial letter, but I want it to be the same height as the rest of the text. I tried `initial-style: 0;` but that did not work. Is there some way to do this that I am missing or is there a real issue somewhere?

```
% !TEX root = test.tex
% !TEX TS-program = LuaLaTeX+se
initial-style: 0;
name: Adjutórium nostrum;
%%

(c3) <c><sp>V/</sp>.</c> Ad(h)ju(h)tó(h)ri(h)um(h) no(h)strum(h) in(h) nó(h)mi(h)ne(h) Dó(h)mi(f)ni.(f) (::) <c><sp>R/</sp>.</c> Qui(h) fe(h)cit(h) cœ(h)lum(h) et(h) ter(h)ram.(f) (::)
```

**Comment by rpspringuel** [comment]
The `initial-style` header is obsolete and hasn't worked in several versions.  The way to determine the size of the initial (or the lack thereof) is in the TeX file with `\gresetinitiallines{<number>}` where `<number>` is the number of lines the initial takes up (currently either 0, 1, or 2).
