### ISSUE TITLE
Vbar and Rbar don't work with new lists

### ISSUE THREAD

**Issue by Nokel81** [gregorio-project/gregorio#1486]
The following small file fails to compile.

```tex
\documentclass{book}
\usepackage{enumitem}
\usepackage{etoolbox}
\usepackage[autocompile]{gregoriotex}

\newlist{alternate}{enumerate}{1}
\renewcommand\labelalternatei{\bfseries\protect\ifnumodd{\value{alternatei}}{\Vbar.}{\Rbar.}}

\begin{document}

Some text some text some text some text some text some text some text some text some text some text some text some text some text.
\begin{alternate}[wide=0pt]
  \item First
  \item Second
  \item Third
  \item Fourth
  \item Fifth
  \item Sixth
\end{alternate}

\end{document} 
```

With the following error: `! Use of \\alternate doesn't match its definition.`.

However, if you change the `\renewcommand...` to `...{V.}{R.}}` then it does compile.

**Comment by rpspringuel** [comment]
I think `\Vbar` et al. are fragile commands.  Try adding `\protect` in front of them in the original definition of your list. 

✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️✝️
Fr. Samuel, OSB
(R. Padraic Springuel)
St. Anselm’s Abbey 
4501 South Dakota Ave, NE
Washington, DC, 20017
202-269-2300
(c) 202-853-7036

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by Nokel81** [comment]
That has worked. Thank you.
