### ISSUE TITLE
Double punctum mora vertical alignment is off

### ISSUE THREAD

**Issue by fiat96** [gregorio-project/gregorio#1489]
While creating a Tenebrae booklet for our schola with gregorio 5.2.0 in TexLive2019, I noticed for the first time that the double punctum mora after a clivis does not align in the same spot as in the Solesmes books.  The potential for this type of problem was mentioned in #386, but it was decided to wait to do anything until problems "came up."  So, here it is!

An example: **runt(ji..)** compiles as this, with the higher dot in the (j) position:
![image](https://user-images.githubusercontent.com/62146958/76632780-b85a5a80-6511-11ea-8398-06cb05d23406.png)

Whereas in the L.U. it looks like this, with the higher dot in the (k) position:
![image](https://user-images.githubusercontent.com/62146958/76632939-f5bee800-6511-11ea-8ab0-a8608177a6b4.png)

The case is the opposite for a clivis where the _second_ note is on a line: **a:(ed..)** complies thusly, with the lower mora in (d) position:
![image](https://user-images.githubusercontent.com/62146958/76634344-23a52c00-6514-11ea-9a42-904aaa8105a4.png)

Whereas in the _Liber_ (ed..) and (ec..) have moras in the exact same positions:
![image](https://user-images.githubusercontent.com/62146958/76634267-12f4b600-6514-11ea-87e9-3a355ee1377a.png) ![image](https://user-images.githubusercontent.com/62146958/76635173-091f8280-6515-11ea-81a0-8c889b4cce87.png)

For the record, this is also the case with the double-mora podatus:
![image](https://user-images.githubusercontent.com/62146958/76635304-42f08900-6515-11ea-943e-c77ead987c86.png) ![image](https://user-images.githubusercontent.com/62146958/76635507-95ca4080-6515-11ea-9549-4b491c01eb10.png)

I think the line-note mora is being consistently and intentionally placed in the center of the nearest space.  Is this something that could be changed in the code, or at least made possible for manual correction?  Thanks much.

**Comment by eroux** [comment]
Hi! All this can be changed yes. There are different view on how these dots should be aligned vertically, and not all books (even authoritative ones) are very consistent or careful about that aspect... Gregorio's settings have been improved many times by people working on very precise editions and are generally seen as higher standard than many editions, but there's room for improvement and personal taste of course. There's a copious section of the user manual dedicated to the infinite settings related to that.

**Comment by fiat96** [comment]
I guess \GreAugmentumDuplex was what I was looking for...  Sorry I neglected to search the manual before posting.
