### ISSUE TITLE
color signs in GABC automatic

### ISSUE THREAD

**Issue by loic-rotsac** [gregorio-project/gregorio#1496]
Helo,
I start with Gregorio.
I would like to color "*", "Ps.", "V/"... in .GABC file automatiquely in the .tex file as https://bbloomf.github.io/jgabc/propers.html#sunday=Pent10.

Can you help me ?

**Comment by rpspringuel** [comment]
There are several ways to accomplish this:

1) The `<c></c>` tags can be placed in the gabc around the element which you want to be colored: `<c>Ps.</c>`
2) Single symbols (like the star and the versicle sign) can be redefined to be automatically colored:
```
\let\VbarOld\Vbar
\def\Vbar{{\color{gregoriocolor}\VbarOld}}%
```
3) New colored symbols can be defined:
```
\gresetspecial{c*}{{\color{gregoriocolor}\gresixstar}}
```
Will then allow `<sp>c*</sp>` to produce the colored star.

Also, you're better off getting usage help from the mailing list: gregorio-users@googlegroups.com
