### ISSUE TITLE
Footnotes do not display or increment correctly

### ISSUE THREAD

**Issue by adunning** [gregorio-project/gregorio#1500]
The `\footnote` command produces a footnote reference in the correct position, but numbers are not generated in sequence, and the footnote itself does not display.

The footnote text displays with a combination of `\footnotemark` and `\footnotetext`, but this still does not increment the sequence correctly.

<img width="542" alt="Screenshot 2020-12-11 at 15 18 46" src="https://user-images.githubusercontent.com/1084407/101920816-2c6e7f80-3bc4-11eb-9c03-8c418ea728b5.png">

<img width="242" alt="Screenshot 2020-12-11 at 15 20 19" src="https://user-images.githubusercontent.com/1084407/101920997-63dd2c00-3bc4-11eb-9f1e-59d56709b0a5.png">

```tex
\documentclass{article}

\usepackage{gregoriotex}

\begin{document}

\gabcsnippet{(c4) Mi(g)se<v>\footnote{test footnote 1}</v>(g)re(hv)re.<v>\footnote{test footnote 2}</v>(gf) (::)}

\gabcsnippet{(c4) Mi(g)se<v>\footnotemark</v>(g)re(hv)re.(gf) (::)}

\footnotetext{test footnote 3}

\end{document}
```

**Comment by adunning** [comment]
I also tried using the `footnotehyper` package and `savenotes` environment, which doesn't work but might help diagnose the problem, which I suspect is related to #1494:

<img width="582" alt="Screenshot 2020-12-11 at 15 36 47" src="https://user-images.githubusercontent.com/1084407/101922955-aef83e80-3bc6-11eb-97e6-950421bf8b76.png">

```tex
\documentclass{article}

\usepackage{gregoriotex}
\usepackage{footnotehyper}

\begin{document}
  
\begin{savenotes}

\gabcsnippet{(c4) Mi(g)se<v>\footnote{test footnote 1}</v>(g)re(hv)re.<v>\footnote{test footnote 2}</v>(gf) (::)}

\end{savenotes}

\end{document}
```

**Comment by adunning** [comment]
For anyone in the future who might similarly be trying to add commentary to a Gregorio score, endnotes at least are possible with the `enotez` package:

```tex
\documentclass{article}
\usepackage{gregoriotex}
\usepackage{enotez}

\begin{document}
\gabcsnippet{(c4) Test.<v>\endnote{test1}</v>(f) Test.<v>\endnote{test2}</v>(f)}

\printendnotes
\end{document}
```

**Comment by rpspringuel** [comment]
This is probably due to the fact that text in the lyrics is put in boxes and processed multiple times in order to get the spacing correct.  My advice would be to fake the footnote marks in the score and manually add the footnote text after it.  I do not know of anyway to fix this.

**Comment by adunning** [comment]
Thank you at least for offering an assessment. Should this be closed as unfixable?

**Comment by rpspringuel** [comment]
Good point.
