### ISSUE TITLE
Redundant distance?

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1507]
While running doc_check.sh on another issue I noticed that we have both `unisonpunctuminclinatumshift` and `punctuminclinatumunisonshift` defined in gsp-default.tex.  Both are set to the same value by default.  Each is only used once in `\gre@get@spaceskip`: one for case 23, the other for case 26, neither of which is documented explaining that function (the cases only go up to 22).

This raises the question: do we need both of these or is one redundant and should be changed to the other?

(Also, we should fix the documentation here to document all the cases above 22 when fixing this.)

**Comment by henryso** [comment]
23 is used when you have two "puncta inclinata" on a unison. 26 is used when you use the non-leaning "punctum inclinatum" after a non-"punctum inclinatum".  They could be merged, but I don't feel qualified to decide that.

**Comment by rpspringuel** [comment]
So case 26 isn’t really unison related?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by henryso** [comment]
I think that's a fair assessment.  The non-leaning punctum inclinatum is set to be used at the unison, but in the end this space case is used regardless of the previous note's pitch.

**Comment by rpspringuel** [comment]
Then I would suggest that the distance associated with said case be renamed and the documentation updated.

**Comment by rpspringuel** [comment]
@henryso Can you indicate what the other two cases are for (24 & 25)?

**Comment by henryso** [comment]
24 is used before a right-leaning puncta inclinata when the pitch is ascending (up to 4 pitches away).  25 is used before a left-leaning puncta inclinata when the pitch is descending (up to 4 pitches away).
