### ISSUE TITLE
completetest.gabc is incomplete

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#153]
I happened to notice that completetest.gabc doesn't test (O).  Does anyone know of any other figures completest.gabc doesn't test?

**Comment by eroux** [comment]
the new ones are also untested I imagine:

 * `egi`
 * `egi~`
 * `ige`
 * `ige~`
 * `ige~`
 * `dfec~`
 * `dwfec~`
 * `hof~`
 * `iv>`
 * `egOi`
 * `eOg`
 * `gwhg`
 * `gwhg~`
 * `gwhg<`
 * `gwhg>`
 * `_0`

But there might be some other lacks...

Also, `completetest` is quite a poor name, maybe separating it in `testglyphs` `testsymbols`, etc. would be better and give more relevant names... What do you think?

**Comment by eroux** [comment]
Also, translation and translation centering is not tested, nor color, nor most styles... the TeXworks/TeXShop header is not relevant here neither... A 2006 file, time is running...

**Comment by henryso** [comment]
I think splitting it up is a good idea.  I will update this issue when I have something worth reviewing.

**Comment by rpspringuel** [comment]
I'm probably the one who added the TeXShop headers. They would have been helpful when I was compiling the file to test something or other. 

I would also suggest breaking the file up, but would go even further.  If each category of glyphs is given its own file, it will be easier for the tests to report on exactly what is wrong.

**Comment by eroux** [comment]
That's right, it will allow more convenient error messages

**Comment by henryso** [comment]
Yes, I read your comment to mean breaking it down into pretty granular pieces.  Of course, that's a juggle, but it's also an opportunity for us to collaborate.

**Comment by henryso** [comment]
Should I test every pitch?  That would be a massive set of tests, but I can do it.  What makes sense?

**Comment by eroux** [comment]
No, I don't think it's useful...

**Comment by henryso** [comment]
How spotty should the spot check be, then?  Pick one pitch and test all ambitus variants?

**Comment by eroux** [comment]
I'm not even sure it's worth it... Just picking a few different ambitus and that should be enough... For me the main purpose of the test is gabc parsing, and it's done in a way that `gi` and `gh` will always give the same result, no need to check the two.

**Comment by henryso** [comment]
I've broken completetest.gabc into multiple tests in the gregorio-test project and have added the missing glyphs and style tests listed in this issue.  However, how do I do translation centering?

**Comment by eroux** [comment]
It's not really documented, only the changelog has [these](https://www.mail-archive.com/gregorio-users@gna.org/msg01760.html) two [links](https://www.mail-archive.com/gregorio-users@gna.org/msg01783.html)

**Comment by henryso** [comment]
I've added the remaining missing tests to the gregorio-test project.  Closing this issue.
