### ISSUE TITLE
Duplicate oriscus-orientation in doc

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#1530]
There are duplicate entries for `oriscus-orientation` in the doc

https://github.com/gregorio-project/gregorio/blob/e3ca9f3c5b7122f1e605573968500561b9cf142b/doc/Gabc.tex#L94

https://github.com/gregorio-project/gregorio/blob/e3ca9f3c5b7122f1e605573968500561b9cf142b/doc/Gabc.tex#L132-L134

**Comment by rpspringuel** [comment]
Fixed in 8922cb7.
