### ISSUE TITLE
Space between Lines

### ISSUE THREAD

**Issue by gamaanderson** [gregorio-project/gregorio#1533]
I'm not getting to manage the space between lines for very small staff size. The following

    \documentclass[12pt]{article} % use larger type; default would be 10pt
    
    % usual packages loading:
    \usepackage{fontspec}
    \usepackage{graphicx} % support the \includegraphics command and options
    \usepackage{geometry} % See geometry.pdf to learn the layout options. There are lots.
    \geometry{a4paper} % or letterpaper (US) or a5paper or....
    \usepackage{gregoriotex} % for gregorio score inclusion
    \usepackage{fullpage} % to reduce the margins
    \usepackage{libertine} % Decent (free) font for Gregorian, but should be changed if you have high standards
    
    \begin{document}
    
    % The title:
    \begin{center}\begin{huge}\textsc{Populus Sion}\end{huge}\end{center}

    \grechangestaffsize{5}
    
    
    \grechangedim{spacelinestext}{3ex}{fixed}
    \grechangedim{spacebeneathtext}{0.01ex}{fixed}
    
    \grechangedim{spaceabovelines}{0.01ex}{fixed}
    \grechangedim{abovelinestextraise}{0pt}{fixed}
    \grechangedim{abovelinestextheight}{0pt}{fixed}
    
    % Here we set the initial font. Change 43 if you want a bigger initial.
    \grechangestyle{initial}{\fontsize{12}{12}\selectfont}%
    
    % We set red lines here, comment it if you want black ones.
    \gresetlinecolor{gregoriocolor}
    
    % and finally we include the scores. The file must be in the same directory as this one.
    \gregorioscore[a]{PopulusSion}
    
    \bigskip
    \begin{center}\begin{huge}\textsc{Factus Est}\end{huge}\end{center}
    
    \gregorioscore[a]{FactusEst}
    
    
    \vspace*{10cm}
    
    \end{document}
 produces
 
 
![image](https://user-images.githubusercontent.com/7915525/111008442-656beb00-8391-11eb-8fed-7462b3b79f44.png)

The space below the text is too big

**Comment by eschwab** [comment]
Changing the `baselineskip` produces the ~desirable~ expected result for me.

`\grechangedim{baselineskip}{0pt}{fixed}`

**Comment by gamaanderson** [comment]
Thank you, thas does the trick. I spent a lot of time in this and could not figure out what dimension to change.
