### ISSUE TITLE
Custos causing unnecessary line height adjustment

### ISSUE THREAD

**Issue by fiat96** [gregorio-project/gregorio#1535]
When the custos at the end of a line is the only item below the staff, it is causing the text to shift downwards (even after a second pass).  There's no reason for the text to be so low and it looks odd.  Perhaps the custos could be excluded from the lowest-object calculation? 

MWE:
```
\documentclass[latin]{book}
\usepackage{gregoriotex}

\begin{document}
	
\gabcsnippet{(c4) SE(f)púl(h)crum(g) Chris(h)ti(f) vi(g)vén(fe~)tis,(d.) (;) et(d) gló(g)ri(f)am(g) vi(h)di(g) re(f)sur(g)gén(fe~)tis:(d.) (::z) An(a)gé(c)li(d)cos(f) te(g)stes,(e_d) (,) su(c)dá(f)ri(e)um,(d) et(e) ve(c)stes.(d.) (::)}
	
\end{document}
```
![image](https://user-images.githubusercontent.com/62146958/111325875-1b596280-863a-11eb-8dff-68d0ff76d6ac.png)

**Comment by henryso** [comment]
I would argue that this looks right to me.

**Comment by fiat96** [comment]
I was expecting something along the lines of this:

![image](https://user-images.githubusercontent.com/62146958/111360609-f1fcfe80-865a-11eb-9368-2db1b5a76853.png)
with the words at a normal distance from the notes on the first line.

I'll have a look and see if there are any cases in the books.

**Comment by rpspringuel** [comment]
The problem with trying to do that it creates the possibility of the words colliding with the custos.  What you're asking for would require detecting just how close to the end of the line the words get and adding space if they would collide with the custos.  This is far from a simple requirement.

**Comment by fiat96** [comment]
I did find a few examples in the _Liber_, for illustration.  Such a low custos seems to be tolerated only at a major division, so only a few examples seem to exist...

![image](https://user-images.githubusercontent.com/62146958/111476306-0b09bc00-86fc-11eb-9f28-3a05adc7b016.png)
![image](https://user-images.githubusercontent.com/62146958/111476586-4c9a6700-86fc-11eb-94d2-13d6c1ce1d5b.png)

![image](https://user-images.githubusercontent.com/62146958/111477273-f11ca900-86fc-11eb-86b5-bd1a794fdb33.png)
![image](https://user-images.githubusercontent.com/62146958/111477225-e6621400-86fc-11eb-97c0-5819a7d25419.png)

I understand how potential collision with the custos makes this complicated, but to me the large gap between the staff and the words is glaring.  It is a rare case, for sure, so I realize it might not be worthwhile to change.  One can always force a less ideal line break, I suppose.
