### ISSUE TITLE
hyphen before <i> causes "repeated style" error

### ISSUE THREAD

**Issue by gabrielmass** [gregorio-project/gregorio#1538]
In gregorio 5.2.1, placing a hyphen immediately before an "&lt;i&gt;" leads to gregorio aborting with an error message.

Sample GABC file:
name: March 30 sample;
%%
(c3)For(h)-&lt;i&gt;ev&lt;/i&gt;(h)er(h)

Result of processing:
$ gregorio a189517.gabc
997: in function `gregorio_rebuild_characters': assertion:encountered
repeated style
$ echo $?
1

**Comment by henryso** [comment]
This seems to only happen if the hyphen is the first thing in the syllable test.

**Comment by henryso** [comment]
OK, I know why this is happening, but the fix will be a little tricky.  It's definitely a bug due to the handling of the hyphen which causes it to have higher precedence (in computer science terms) than other characters.

**Comment by henryso** [comment]
I have a fix ready for this, but due to the effect of #1504 on tests, I'll wait until that one is reviewed and merged before proposing this one.

**Comment by henryso** [comment]
@gabrielmass This should be fixed in the development branch.  Please comment here if it doesn't work for you.
