### ISSUE TITLE
Code Quality Control

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#154]
So, the [documentation](CONTRIBUTING.md) already establishes that `.c` and `.h` files should be run through `indent` before being committed to ensure code quality.

I'd like to propose doing something similar for `.py` and `.lua` files.

To that end, I've been looking at beautifiers for Python and Lua.  (Note: [pylint](http://freecode.com/projects/pylint/) which the documentation already recommends for Python is a code checker, not a beautifier.  The difference is that while pylint can flag style errors, it doesn't actually fix them.  A beautifier would (or at least try to).)

For Python I think [autopep8](https://pypi.python.org/pypi/autopep8) is probably the way to go.  Like indent it can make use of a local configuration file which can live in the repository so that we all know we're running it with the same settings.  Also, it should be easy for anyone to get through their package manager.

For Lua I've had considerably more trouble finding something and the best I've been able to come up with is [this Lua beautifier written in PERL](http://notebook.kulchenko.com/programming/lua-beautifier-in-55-lines-of-perl).  I don't like that it's not written in a language we already use on the project, but I haven't been able to find anything that is written in either Lua or Python except [the Lua beautifer it improved on](http://web.archive.org/web/20120830041232/http://www.userpixel.com/486).

Part of the reason I want to do this is because by using filters and/or pre-commit hooks I should be able to automate the process of running code through these beautifiers.  I'm still working out which is better, but the idea is that once properly setup, it will become much harder to submit bad code (stylistically speaking).

What do the rest of you think?

**Comment by henryso** [comment]
I think, in theory, this is a good idea.  But I know I've had GNU indent, for example, do bad things to my files, so unless we can 100% trust the beautifier, I don't like the idea of doing it as an automated pre-commit hook.

**Comment by eroux** [comment]
I agree with Henry, I don't really like hooks to change my code (tab <-> space would be acceptable, but not more). But, here a re a few thoughts for a middle-way:

 * hooks could warn the user if linters output errors (currently the only linter we have is for python, which is not the most used language, but at least it's a start)
 * hooks could run some beautifiers but not overriding the file, just checking if the beautified output is different from the original file; and if it is different warn the user, with a message like "your code does not seem to respect the guidelines, please use this command"
 * the hook script could have an "autobeautify" option (that would be hardcoded in the script, but changeable) that would do things automatically, at the developer's risk

This would be ideal for me: as a developer I'm controlling the code I push, but I'm also helped in respecting the guidelines.

What do you think?

**Comment by rpspringuel** [comment]
After some more research, it turns out that both pre-commit hooks and filters are client-side operations, which means that each developer would have to set them up for themselves.  I can provide instructions for how to set things up, but we can't enforce anything this way.  It would probably be useful to have a matched set of checker and beautifiers, so that each developer can choose which they want to use in their own workflow knowing that both look for the same things.

If we want to enforce standards, then we'll need a server-side pre-receive or update hook that runs the checkers when some tries to push to the repository.  If the checker fails the code, then the push would be rejected and it would be up to the developer to fix the problem (which may require editing their history) and the try the push again.

**Comment by eroux** [comment]
The server-side hook seems really too much to me... What is usually done is to give an example script that most developers use, I think this could be a good thing. What do you think?

Also, @rpspringuel @eschwab @henryso are you all on `gregorio-devel` mailing list? I wanted to ask about a release date... After all these beautiful tests @henryso made, I think we're ready, the only thing I have no control on is Mac packaging... @rpspringuel do you plan to have something for 3.0 or will it be too early?

**Comment by eschwab** [comment]
I am on `gregorio-devel`.

**Comment by henryso** [comment]
I am also on gregorio-devel.

**Comment by henryso** [comment]
Anything else to do for this one?

**Comment by eroux** [comment]
for me it's ok

**Comment by rpspringuel** [comment]
I think we're missing standards for shell scripts.

**Comment by eroux** [comment]
I don't think standards for shell scripts are important enough to keep this issue open, what do you think?

**Comment by eroux** [comment]
Closing, reopen if something new is required
