### ISSUE TITLE
Setting lyric font in GregorioTeX

### ISSUE THREAD

**Issue by chrylis** [gregorio-project/gregorio#1546]
I am trying to embed some Gregorio snippets in a LaTeX booklet whose text typeface is Garamond, while I want to use Baskerville for the lyrics. Is there a way [besides `\setmainfont`](https://gregorio-project.github.io/tutorial/tutorial-gabc-file-03.html) to change the typeface used by Gregorio?

**Comment by rpspringuel** [comment]
No.  The lyrics are typeset as text and will inherit the text properties currently in effect from the main text body.  If you want to change the lyrics font for all scores, I would suggest creating a wrapper macro that changes the font before including the score, and then changes it back at the end.
