### ISSUE TITLE
gabc <c> tag not working with { } for setting syllable in chant text.

### ISSUE THREAD

**Issue by leduc006** [gregorio-project/gregorio#1551]
Hi,

Thanks again for a magnificent piece of software!

This is not the most earth-shattering problem, but the following example struck me as unexpected behavior.  The last syllable in the second example is not colored red.  

% !TEX TS-program = lualatex
\documentclass{article}

\usepackage[autocompile]{gregoriotex}

\begin{document}

\gabcsnippet{(c4) <c> Nar(c)ra(egf)bo(f.) </c> (::)  }

\gabcsnippet{(c4) <c> Nar(c)ra(egf){bo}(f.) </c> (::) }

\end{document}

**Comment by leduc006** [comment]
Sorry - forgot to say I run TeX Live 2021 with Gregorio TeX 6.0 on an ancient Mac running High Sierra 10.13.6.

**Comment by rpspringuel** [comment]
There are no `<c>` tags on the provided examples. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leduc006** [comment]
weird.  I cut and paste from my .tex file, and they disappeared.  Maybe got swallowed as html by the web page email form when I entered?

Anyway, they should be between (c4) and Nar and then a closing one after (f.) in each example.

Trying to attach the .tex file as a .txt file because the attachment mechanism here does not seem to support dragging and dropping .tex files.

[mwe.txt](https://github.com/gregorio-project/gregorio/files/6864821/mwe.txt)

**Comment by henryso** [comment]
I ran your mwe using TexLive 2021 with the TexLive-packaged gregorio on my Linux-based computer, and I get red words.  Can you provide any other information, like how you run lualatex (from some editor?) or perhaps your log file?

**Comment by leduc006** [comment]
Hi

I run TeXLive 2021 with the prepackaged gregorio; I just downloaded the file from the attachment I preloaded above and ran it and I still get one black syllable at the end of the second example.

Further details:  I'm running Mac OSX 10.13.6, so could not install TeX Live from the prepackaged binaries as my system is too old.  Instead I used the "unix install" script, which seems to work otherwise.  I execute the lualatex command from within the TeXShop editor Version 4.66, which I believe is the most recent.  In the configuration screen, the editor has a tab that says "Latex" but the % !TEX TS-program = lualatex line should (and appears to) cause the run to employ LuaLaTex.  Changing that edit tab to "LuaLaTaX" and clicking the Typeset button a couple of times does not change the result for me.

Log file attached.

[mwe.log](https://github.com/gregorio-project/gregorio/files/6896139/mwe.log)

**Comment by leduc006** [comment]
Oh - and the output pdf.
[mwe.pdf](https://github.com/gregorio-project/gregorio/files/6896144/mwe.pdf)

**Comment by henryso** [comment]
OK, I think I better understand the problem now.

**Comment by henryso** [comment]
It's not just the `<c>` tag, but apparently all styles.

**Comment by henryso** [comment]
I think this one is a problem in the gregorio_rebuild_characters function.

**Comment by henryso** [comment]
Is there anything preventing the close of this issue?

**Comment by rpspringuel** [comment]
I don't think so.
