### ISSUE TITLE
Command from gregoriotex-common not available

### ISSUE THREAD

**Issue by MaestroGlanz** [gregorio-project/gregorio#1553]
I want to use `\gresetgregpath{{./CREDO/}}` but I get an undefined-control-sequence-error. 

MnWE:

`\documentclass[10pt,a4paper]{article}`
`\usepackage[autocompile]{gregoriotex}`
`\gresetgregpath{{./CREDO/}}`
`\begin{document}`
`\end{document}`

According to the manual page 9 (GregorioRef.pdf), this should work. If I did it wrong, the manual isn't clear here.

**Comment by MaestroGlanz** [comment]
Might it be possible, that this is a new feature, which wasn't there before 2021? I use texlive-music on Ubuntu.

**Comment by rpspringuel** [comment]
It is a relatively recent feature and Ubuntu packages can be rather out of date at times. Try installing a more recent version. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
