### ISSUE TITLE
Fusion Enhancements

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1558]
Graduale Novum, in the offertory Recordare on p. 340 of the first volume, namely the first four notes, a torculus resupinus terminating with a virga:

![Recordare neume example](https://user-images.githubusercontent.com/7671682/150415718-6dc18562-8307-495b-a9f3-4452fd662e61.jpg)

Sandhofe's 2002 Nocturnale Romanum, page [126] in the Common for Virgins and non Virgins, Responsory 6 for Virgins, Offerentur Regi, sort of a porrectus with a fifth note stacked on top of the fourth (which should be a quilisma), at the end of the syllable Re in Regi: 

![chant_snippet](https://user-images.githubusercontent.com/7671682/150415940-e1be302b-b429-4475-9a84-728738770753.jpeg)

As best I can tell, the current rules for fusion prohibit both of these combinations (the latter is explicitly spelled out in the documentation, but the there's no mention of a virga as a primitive element in the fusion rules).  @henryso Can we modify the fusion rules to make these possible?

Reference mailing list thread: https://groups.google.com/g/gregorio-users/c/2NpiJsjEQnU/m/Ho_JZCxIAgAJ?utm_medium=email&utm_source=footer&pli=1

**Comment by henryso** [comment]
It's possible. It would require virga endings as well as a "quilisma pes" endings to be drawn and added to the glyph set along with the changes in the fusion code.

**Comment by rpspringuel** [comment]
Don't those glyphs already exist outside of fusion?

**Comment by henryso** [comment]
Not the ones with little nubs to connect to the lines of the previous glyph.

**Comment by henryso** [comment]
The quilisma-pes will end up being 5 glyphs given the ambitus.

**Comment by rpspringuel** [comment]
Where are we in terms of available glyph space?

**Comment by rpspringuel** [comment]
Also, has anyone looked at using glyph variants to define the connecting nubs rather than creating two separate glyphs (one connecting, one not)?

**Comment by henryso** [comment]
We're close, but maybe it can fit.  It depends on how many we need for the quilisma-pes.  I haven't looked into glyph variants.  There are nine for every shape within fusion and varying numbers for starting glyphs and ending glyphs.  Quilisma-pes is actually a new can of worms because it'll be the first two-note ending glyph.

**Comment by henryso** [comment]
I think we have enough characters.  We go to 0xf694, and I think we have until 0xf8ff.  I have shake off the cobwebs to do this one, so please don't expect anything quickly.

**Comment by henryso** [comment]
@rpspringuel  Are there any examples of figures ending in quilisma-pes that are separate from the previous figure by more than one pitch?

**Comment by rpspringuel** [comment]
That’s a question to put to the original reporter on the mailing list. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by henryso** [comment]
Per the list, there is no further example.  I can't even imagine how a stem would connect with a quilisma, so I'll implement the fusion into a quilisma-pes only at an ambitus of one.  This won't require any glyphs that we don't already have.

**Comment by henryso** [comment]
Playing with this for a bit, I'm starting to think it would be better to have a different syntax for the torculus-like figure before the quilisma that ends in a stroke rather than a note.  However, there are knock on effects to the fusion algorithm that I'm working through.  I'm not 100% sure on the right approach yet.

**Comment by henryso** [comment]
My proposal is to use `&[...]` to signal the use of an alternate interpretation of a figure. In this case it could be `&[stroke]` or something with a better name if there are other ideas.  @rpspringuel do you have any opinions on this?

**Comment by henryso** [comment]
I decided to use `[shape:stroke]` instead.  I didn't feel there was a need to use yet another sigil.
