### ISSUE TITLE
\grechangestaffsize not scaling all elements

### ISSUE THREAD

**Issue by fiat96** [gregorio-project/gregorio#1563]
I just updated to TexLive 2022 last night (I think; the folder suspiciously says 2021) and now am coming across an issue I never had before.  `\grechangestaffsize` is still increasing the size of the staff and chant, but not the text, or any of the distances.

MWE:
```
\documentclass{article}
\usepackage{gregoriotex}
	
\begin{document}
\gabcsnippet{(c4) Test(cde)}

\grechangestaffsize{80}
\gabcsnippet{(c4) Test(cde)}
\end{document}
```
Output:
![image](https://user-images.githubusercontent.com/62146958/161567680-df3a8298-7ed2-4168-937e-3f5c81182df9.png)

**Comment by rpspringuel** [comment]
`\grechangestaffsize` has never changed the text size. As for distances, which ones are you expecting to change that haven’t?  That enlarged staff looks exactly how I would expect it to. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fiat96** [comment]
I was referring to the distances between the notes and the text, but I suppose that isn't meant to change either.

This must be all my mistake.  It really befuddles me, though - I was always under the impression that the text scaled with the staff, but I guess not.  My apologies for the non-issue.
