### ISSUE TITLE
Centering above-lines text

### ISSUE THREAD

**Issue by fiat96** [gregorio-project/gregorio#1565]
I'm trying to add some chords above the staff for one of our organists who dislikes reading off of modern notation transcriptions.  

It would be great if I could get the chords centered over their note, rather than left-aligned.  But as far as I can tell, there is currently no way to do so.  I checked the documentation, and also tried to add centering code to \grechangestyle or to the gabc file itself.  Nothing's working.

Here's a MWE, without the centering:
```
\documentclass[]{article}
\usepackage{gregoriotex}
\grechangestyle{abovelinestext}{\color{red}\itshape}
\begin{document}
	\gabcsnippet{(c4) 
	Ro([alt:c]f)rá(gh)te([alt:Eb6]h.) cae(k')li(j) 
	dé(ix[alt:Ab]ji)su(h)per,([alt:F]hg..) (;) 
	et(h) nu(ixi')bes(h) plu([alt:g]gf)ant(e) 
	ju([alt:B♭]fe)stum.([alt:c]d.) <i><b>ij.</b></i>(::)}
\end{document}
```
![image](https://user-images.githubusercontent.com/62146958/179270634-12d1048f-cbbb-4597-a638-d171d797bca4.png)

Thank you!

**Comment by rpspringuel** [comment]
There's no way to do what you're asking using the supported tools.  The above line text system doesn't support playing around with its position and will always be left-aligned to it's note.

You might be able to trick something into working by turning your score into a gabc file, manually running it through the command line tool, and then further editing the gtex file manually, but that's the kind of solution that's so fragile I don't recommend it unless it's absolutely necessary.

**Comment by bmaire28** [comment]
Hi,

I've just re-installed TexLive and GregorioTex after several years 
without a PC capable of doing anything.

I've tried to recompile some old files and got error on \grestar mainly.

How can I modify my files so they are compatible with GregorioTex 6.0.0 ?


Rdgs,
Boris
