### ISSUE TITLE
\grestar?

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#1568]
Hi,

I've just re-installed TexLive and GregorioTex after several years 
without a PC capable of doing anything.

I've tried to recompile some old files and got error on \grestar mainly.

How can I modify my files so they are compatible with GregorioTex 6.0.0 ?

Rdgs,
Boris

_Originally posted by @bmaire28 in https://github.com/gregorio-project/gregorio/issues/1565#issuecomment-1303752276_

**Comment by rpspringuel** [comment]
`\grestar` has been renamed to `\GreStar`.

There was a big standardization of macro names for v4.0.0 (back in 2015).  If your files are that old and contain lots of custom stuff, you'll probably need to review them all to bring them up to snuff.  You might be well served to pick one and work it out from scratch to get a sense of the changes and then you'll be in better shape to fix the rest.

**Comment by bmaire28** [comment]
Hi Brother Samuel,

thanks for your quick answer.
In fact, this is what I've done.

I'm still blocked some :
\commentary{\textit{\color{rougeliturgique}Ps 111, 1-2}}
\gresetfirstlineaboveinitial{\small Grad. }{\small Grad. }
\gresetsecondannotation{\small V }

I've found out how to use the "mode" info from gabc file, but I've used 
the "date" field to get the source info.
How can I get the piece usage and mode above initial and the source not 
using the date field ?

I got errors also with those lines :
\setspaceafterinitial{2.2mm plus 0em minus 0em}
\setspacebeforeinitial{2.2mm plus 0em minus 0em}
\font\gregoriansymbolfont=gresym at 10pt

Any idea ?

Rdgs,
Boris


Le 04/11/2022 à 19:33, Br. Samuel Springuel a écrit :

**Comment by rpspringuel** [comment]
> `\commentary{\textit{\color{rougeliturgique}Ps 111, 1-2}}`

All GregorioTeX commands now have a prefix (either `gre`, `Gre`, or `gre@`, depending on who is meant to use them) in order to prevent name clashes with other packages.  As a result this should now read:

`\grecommentary{\textit{\color{rougeliturgique}Ps 111, 1-2}}`

This is assuming that you have `rougeliturgique` defined.  We define the color `gregoriocolor`, which is meant to be the liturgical red.  As far as I know, we've never defined `rougeliturgique`.

***

> ```
> \gresetfirstlineaboveinitial{\small Grad. }{\small Grad. }
> \gresetsecondannotation{\small V }
> ```

Annotation commands have been simplified to allow for as many lines as you want.  This should now read:

```
\greannotation{\small Grad. }
\greannotation{\small V }
```

***

> ```
> \setspaceafterinitial{2.2mm plus 0em minus 0em}
> \setspacebeforeinitial{2.2mm plus 0em minus 0em}
> ```

The interface for adjusting distances has been unified so that all adjustments are made with `\grechangedim`.  These lines should now read:

```
\grechangedim{spaceafterinitial}{2.2mm plus 0em minus 0em}{scalable}
\grechangedim{spacebeforeinitial}{2.2mm plus 0em minus 0em}{scalable}
```

***

> `\font\gregoriansymbolfont=gresym at 10pt`

Don't know why you need to load one of our fonts like this, as our packages give you access to the glyphs them in already.  However, if you insist on needing to load one of our fonts manually, you need the right font name.  The one I think you're looking for is greextra.

**Comment by bmaire28** [comment]
Hi,

Many thanks for your answers.

About rougeliturgisue I confirm I declare at first, before the begin document.

About last point, I think it Is to set the font size in partition.

I will try all you gave me.

Regards,
Boris

**Comment by bmaire28** [comment]
Hi,

I'm testing the new values:

|\grechangedim{spaceafterinitial}{2.2mm plus 0em minus 0em}{scalable} 
\grechangedim{spacebeforeinitial}{2.2mm plus 0em minus 0em}{scalable}|

==> doesn't work

Variable names have changed

|spaceafterinitial ==> ||afterinitial|shift
|spacebeforeinitial|  ==>|beforeinitial|shift

found on https://gregorio-project.github.io/gregoriotex/details.html

But I still get an error: "afterinitialshift cannot be a rubber lenght" 
(and same for the other).

Rgds,
Boris


Le 05/11/2022 à 17:55, Br. Samuel Springuel a écrit :

**Comment by bmaire28** [comment]
Hi,

no problem about the names :), web site is there for that.

I'll try without the rubber part and let you know.

Rgds,
Boris

Le 07/11/2022 à 15:04, Br. Samuel Springuel a écrit :
>

**Comment by bmaire28** [comment]
Hi Brother Samuel,

removing from the "plus" works !!

Thanks for all. Issue is solved.

Rdgs,
Boris Maire

Le 07/11/2022 à 15:04, Br. Samuel Springuel a écrit :
>
