### ISSUE TITLE
Extra hyphen appearing at end of each typeset pdf

### ISSUE THREAD

**Issue by mectojic** [gregorio-project/gregorio#1580]
I'm getting additional "-" hyphens showing up at the end of my pdf typeset, when they aren't present in the gabc file. What could be causing this?

![Screen Shot 2023-09-13 at 10 51 45 am](https://github.com/gregorio-project/gregorio/assets/144861704/e3a81ea5-71d7-485e-a768-931a2dd8cd72)

![Screen Shot 2023-09-13 at 10 50 27 am](https://github.com/gregorio-project/gregorio/assets/144861704/b965b100-8152-4b84-abf0-1315975cf82b)

**Comment by leduc006** [comment]
You don’t actually have to put your own hyphens in. Gregorio will automatically hyphenate syllables of the same word - except see note below.Compare what you have toyour(h) sal(g)va(higgh)tion.(h.)By smushing everything together on salvation, Gregorio knows this is one word and will hyphenate syllables “as needed”. Conversely, your is separated by the next word by a space and so won’t be hyphenated to the syllable sal. That is, just like text at a line break in a typical text word processor. “As needed” means to avoid notes being printed on top of one another, essentially.  But that means that sometimes syllables don’t have to be spread apart, for example of there is one note on each of two medium sized syllables, and so aren’t always hyphenated.If you prefer every syllable to be hyphenated no matter what, there was a Tex option provided by Gregorio that you could set at the top of your Tex or latex header to force that and avoid entering all your own hyphens.  In my experience that takes more space to write a piece; depending on what you’re used to that may be more or less “readable” to you.The Tex option should be easily found in the hyphenation section of the Gregorio documentation.  If you can’t find it, I’m happy to dig it up.In your case, the extra hyphen probably has something to do with the line break or maybe the lack of a space between the notes for “tion” and the (::) for the bar.  In the latter case, the bar may be treated as an extra syllable on salvation getting hyphenated.Best wishes,RobNo dia 12 de set. de 2023, às 8:51 PM, mectojic ***@***.***> escreveu:﻿
I'm getting additional "-" hyphens showing up at the end of my pdf typeset, when they aren't present in the gabc file. What could be causing this?

**Comment by mectojic** [comment]
Thanks for your advice. However, the problem still persists even after some formatting adjustment. I think it's some sort of bug?
![Screen Shot 2023-09-13 at 12 35 56 pm](https://github.com/gregorio-project/gregorio/assets/144861704/2706fd53-a560-41d5-8a97-0831b965fa26)

**Comment by leduc006** [comment]
Did you try a space between the (h.) and the (::) ?No dia 12 de set. de 2023, às 10:36 PM, mectojic ***@***.***> escreveu:﻿
Thanks for your advice. However, the problem still persists even after some formatting adjustment. I think it's some sort of bug?

**Comment by mectojic** [comment]
That seems to have worked. Thank you. I'll report back if a problem arises again.
