### ISSUE TITLE
reduce over-engineering

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#163]
Currently Gregorio is built in the following way (if `--enable-all-static` is not present)

 * a small cli tool, loading a library (gregorio.so), the library could be used by other tools
 * some plugins (xml, gabc, gtex, otex, dump), dynamically loaded by the library, which makes it possible for someone to build his own plugin and make gregorio use it

That was very interesting when I introduced the feature, and this is what made a second student project on gregorio possible at my school. So it was a good exercise and I learned many thing. Problem is, this is seriously over-engineered and make the code and the directory structure way too complex. Also, it makes it very difficult to compile with something else than autotools...

I propose to remove this system, and thus simplify the code... What do you think?

I also think it would be good to put all C files in `src/`, as it would be more in line with the code structure. It would also make a `CMakeList.txt` file possible in this directory, enabling the compilation under Windows (CMake has a windows version). We could also reorganise the repository and have a `cli` directory and a `GregorioTeX` directory... What do you think?

I think it belongs the develop branch, not the release-3.0 one.

**Comment by henryso** [comment]
I don't have any objections to anything here, and especially don't see the need for the dynamic loading, but a switch to cmake does change the build instructions again, which might bother some people.

**Comment by eroux** [comment]
Sorry, I meant to just make a CMakeList.txt for people who want to use it (like people absolutely wanting to build with windows native tools), but it wouldn't be used by default, autotools would still be there.

**Comment by henryso** [comment]
Do we really want to maintain two sets of build files?

**Comment by eroux** [comment]
the CMakeFile.txt will be only for the C files, and it's just one unique file, it will be very easy to maintain, much easier than building everything (TeX, fonts, distribution tarball, etc.), it will be basically just the list of C files

**Comment by eschwab** [comment]
I like this idea because I am still very unsure exactly how the current system works. Simplifying this and making the repository clear as to what is C and what is TeX would also help. Yes, this is not for release-3.0.

**Comment by rpspringuel** [comment]
Given that we're eliminating support for GregorioXML and OpusTeX, the functionality of the command line tool is going to be considerably streamlined. I think it makes sense for the source code to reflect that. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by eroux** [comment]
fixed in `develop`
