### ISSUE TITLE
Build error on Mac

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#167]
I was trying to build the latest release-3.0 and I got a strange error:

`plugin_loader.c:20:10: fatal error: 'ltdl.h' file not found`

Thinking it might have been accidentally introduced by a recent change, I backed up to older versions which I know installed fine, but I get the same error.  I even backed up to 2.4.2, which I know I've installed before, and got the same error.

The only thing I can think of that's changed that might cause this is the build scripts.  I updated my personal install script to use the new build scripts with all default settings, so I figured that the defaults must be different for a Mac as for Linux.

So, instead of using build.sh, I tried using the old instructions on the [website](http://home.gna.org/gregorio/installation-mac).  That worked (though I had to be a sudo make, rather than just make).

Clearly this indicates to me that the default settings for build.sh don't work on a mac.  Can one of you who understands these shell scripts better work out what the correct options are?

**Comment by eschwab** [comment]
`build.sh` seems to be missing adding the options:

    CFLAGS='-I/opt/local/include' CPPFLAGS='-I/opt/local/include' LDFLAGS='-L/opt/local/lib'

to the `MACCROSS` section.

**Comment by henryso** [comment]
@rpspringuel Since I can't test such a change, would you mind trying the following patch?

```
diff --git a/build.sh b/build.sh
--- a/build.sh
+++ b/build.sh
@@ -100,8 +100,8 @@
     * ) echo "ERROR: architecture $ARCH is not supported"; exit 1;;
   esac
   ARCHFLAGS="$ARCHFLAGS --enable-static-ltdl"
-  CFLAGS="-arch $ARCH -g -O2 $CFLAGS"
-  LDFLAGS="-arch $ARCH $LDFLAGS" 
+  CFLAGS="-arch $ARCH -g -O2 -I/opt/local/include $CFLAGS"
+  LDFLAGS="-arch $ARCH -L/opt/local/lib $LDFLAGS" 
 fi  
 fi
 
```

(There's a blank line after the second fi)

If it works, please check that in.  Also, let us know if you need to use sudo to run build.sh; it'll have to go in the build instructions.

**Comment by henryso** [comment]
Also, I think you'll have to specify --arch=x86_64 to get it to pick up these settings.

If that doesn't work, try
```
./build.sh CFLAGS='-I/opt/local/include' CPPFLAGS='-I/opt/local/include' LDFLAGS='-L/opt/local/lib'
```

`build.sh` should pass any unknown arguments to configure.

**Comment by eroux** [comment]
Hopefully this will disappear with the plugin system removal... In the mean time, can you try passing `--enable-static-ltdl` and `--disable-shared` to configure (as stated in the `macosx/README.MacPackage`)?

**Comment by rpspringuel** [comment]
After applying the patch `build.sh --arch=x86_64` fails as a normal user, but succeeds when run as root.  The issue appears to be the permissions on `gregorio-utils.o` (I suppose there could be others, but that one kills the build so I wouldn't see anything beyond that).  Is there a reason that file's is owned by the system?  All the other `.o` files are owned by my user account.

**Comment by henryso** [comment]
The `.o` file shouldn't exist until you do a build.  Did you mean the `.c` file?  If the `.c` file has weird ownership, then maybe it's some setting in git that can be tweaked.  If you delete the `gregorio-utils.c` and "force get" it from github, is the ownership still wrong?

**Comment by henryso** [comment]
If you did mean the `.o` file, maybe it got the wrong permissions on an older build.  Try running `make clean` as root (to delete all the .o files) and then try the make as a normal user again.

**Comment by rpspringuel** [comment]
I did mean the `.o` file, and as suggested deleting it and rebuilding solved the problem.  I can now build without invoking root.
