### ISSUE TITLE
Fonts makefile not building fonts with simple make.

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#168]
Using the latest commit on release-3.0, the command `make` in the fonts directory yields `make: Nothing to be done for 'all'.`  However, none of the ttf files are present in the directory.  Using `make gresym` etc. does build the fonts individually.  `make fonts` works to make everything.  Should there be an `all` entry that aliases to `fonts` so that an unadorned `make` will work as expected?

**Comment by henryso** [comment]
I don't think so.  If we do that, fonts will make when making at the root since the fonts Makefile is now generated by automake.  Since we don't want fonts to make from the distribution tarball, the default rule has to be left out of the fonts Makefile.

**Comment by rpspringuel** [comment]
How about a fake `all` target that informs the user of that, much like we have the fake `install` target which tells them that's now how the fonts are installed now?

**Comment by henryso** [comment]
Let me see if I can figure out how to do that.

**Comment by henryso** [comment]
Created pull request #169 to address this.
