### ISSUE TITLE
Adding torculus liquescent deminutus shape

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#17]
A user (gregorian chant specialist, monk in Italy) asked me to add a new shape, which he calls torculus liquescens auctus, that would replace pes subbipunctis liquescent deminutum (`ghGF~`). It would be like a torculus with a deminutus at the end (below last note), and would be represented by `dfec~` in gabc.

**Comment by eroux** [comment]
It should also be possible to have a quilisma on first note, see http://gna.org/bugs/?23132

**Comment by jakubjelinek** [comment]
Yeah, i!jwkji~ should IMHO look like:

![liquescence3](https://cloud.githubusercontent.com/assets/9370665/5614699/f13c93fc-94f3-11e4-9b6d-f02d9740c7f9.png)

**Comment by eroux** [comment]
done
