### ISSUE TITLE
\includescore with option semantics have changed 2.4.2

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#170]
In 2.4.2, the `[f]` option for `\includescore` returned that macro it its original semantics.  In 3.0.0, the equivalent option is `[n]` and `[f]` actually forces the new autocompile semantics.  Should this be explicitly pointed out in `UPGRADE.md` and/or `CHANGELOG.md`?

~~Note: the earlier fix for scribus added `[f]` and should now use `[n]` instead.  I will create a pull request to fix that.~~

(edited: the Scribus scripts have already been corrected)

**Comment by eroux** [comment]
It would be better to put it into CHANGELOG and UPGRADE indeed

**Comment by rpspringuel** [comment]
Sorry, when I renamed the options I didn't realize that `f` had made it into 2.4.2.  I thought I was just changing something that was still "development".

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by eschwab** [comment]
@rpspringuel no worries, making `\includescore` backwards compatible eliminated the need to add/change anything to the scribus script. It could stay as it was in `2.4.1`.

**Comment by henryso** [comment]
The fix for `[f]` in gregorio-scribus.lua that I described and then struck out earlier was applied to the develop branch but not to release-3.0.  I'm going to revert that commit in develop.  Pull request for that upcoming.

**Comment by henryso** [comment]
It's my fault for even mentioning scribus here.  This issue is that CHANGELOG.md and UPGRADE.md should be updated to describe the change in the parameter.

**Comment by eschwab** [comment]
Addressed in #173
