### ISSUE TITLE
Merge release-3.0 into develop.

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#172]
I think it's time to merge `release-3.0` to `develop`.  Once the versions are all in line, future merges should be easy.  If I attempt this,  I get unresolved conflicts in

```
build.sh
configure.ac
install-gtex.sh
tex/gregoriotex-spaces.tex
tex/gregoriotex-symbols.tex
tex/gregoriotex.lua
tex/gregoriotex.tex
tex/optimize-gabc.sty
```

As for `build.sh`, `configure.ac`, and `install-gtex.sh`, I know I should just take the version in `release-3.0`.

As for the TeX files, do the `release-3.0` versions all supersede the versions in `develop`?

**Comment by eroux** [comment]
I'd also like to see `release-3.0` merged in to `develop`, @rpspringuel you're the one who modified the tex files on both sides, what do you think?

**Comment by eschwab** [comment]
`gregoriotex.lua`, `gregoriotex.tex`, `-spaces.tex` should come from `release-3.0`

**Comment by henryso** [comment]
Thanks! I've checked the other two, and the only substantive differences are a bug-fix and indentation, so I'm confident in taking the release-3.0 version as well.  I will do this merge now.
