### ISSUE TITLE
Option for python in fonts' makefile?

### ISSUE THREAD

**Issue by eschwab** [gregorio-project/gregorio#174]
Fontforge has been updated for me and it switched the python bindings. I no longer have fontforge bindings for python2 but now have them for python3. It is possible to add a flag/option to `fonts/makefile.am` to set `PYTHON`?

**Comment by henryso** [comment]
You mean instead of running `make PYTHON=/path/to/python3 fonts` ?

**Comment by eschwab** [comment]
No, that is exactly what I was looking for. I was using `make fonts PYTHON=python`, for some reason I forgot that the target needed to be last.
