### ISSUE TITLE
Version Number idea

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#182]
So, this idea was sparked by the discussion going on in #181.  I thought I posted a remark on it there, but I don't see it so either it got lost or I'm mistaken.  In any event, I've had some further thoughts on the idea, so here it is fleshed out.

It would be nice if when you build on a branch which is not master, there was some indication of exactly where you were in the version number.  This way, it's easy to tell exactly when you most recently built and installed gregorio (by invoking the version number from the command line).

To that end the following would need to add the following code somewhere in the build process:

1. Before starting to build, inquire what branch we are on (`git rev-parse --abbrev-ref HEAD`).
2. If we are not on master, then get the description of where we are (`git describe`) and the current version number (`VersionManager.py --getcurrent`).  If we are on master, skip to step 4.
3. Change the version number to the description of where we are (note, the description takes the form `most_recent_tag-#_commits_since_tag-short_SHA_of_last_commit`, we might want to swap `#_commits_since_tag` for `branch_name` and possibly do some other jiggering to comply with semantic versioning.).
4.  Build gregorio.
5. If necessary (i.e. if we changed it), revert the version number to what it was before we built.

I'd personally prefer the code that does this in the Makefile, because that will make it harder to avoid.  If it's in build.sh, then some one who doesn't use that script might have these changes applied.

This would make the build process dependent on python, but only for those not building a stable release (i.e. something on master).  I don't think that's a huge issue, because these are our people on the cutting edge who are either developing or testing stuff for us.  I think having the extra information about where they are when they observe something outweighs the added dependency.

Thoughts?

**Comment by henryso** [comment]
I'll have to admit that this would break my set-up, but that's because I'm using a non-standard git client to handle all my version control needs.  If we do this, I'll figure out a way to make it work for me.

**Comment by eroux** [comment]
There is already a more or less similar version number for debian nighly builds, see `./VersionManager.py -dg`, there are a few differences though:

 * it adds the date, so that versions are incrementing (this is important for debian, it needs to detect that the new version is more recent than the old one
 * it doesn't print the branch, but this might be a good idea to add it... maybe instead of "git"?

Also, though I think the idea is excellent, I'm quite against making this too automatic: I like being able to build what I want, and I certainly don't expect `make` to change the files I want to build, it seems counter-intuitive. I understand what you say about automation, but if there is too much, the result will be an extremely confusing building process where everything is difficult to test because each time you build, all your files modify. So I'd be more keen on a solution with `VersionManager.py`, something like `VersionManager.py --set-git` or something, that would be invoked (and then reverted) by `build.sh`. What do you think?

Out of curiosity, what is your git client @henryso ?

**Comment by henryso** [comment]
@eroux I use the hg-git bridge since I am considerably more facile with the mercurial command set.

**Comment by eroux** [comment]
ok I see

**Comment by rpspringuel** [comment]
Ideally, I'd like to require the version number on non-master branches to indicate the location generally.  Since it's impossible to know what the short SHA of a commit is before the commit is made, it isn't possible to use `git describe` for this as one makes the commit (in the form of a hook).  That's why I suggested using `make` to do the work rather than `build.sh`.

If we switch to branch and date (in which case `git describe` is essentially useless, and we might consider adding the time stamp too) then this could be implemented as a pre-commit hook, thus requiring no change in `Makefile.am` (or `build.sh`).

**Comment by eroux** [comment]
I admit I'm a bit lost... can you give a more detailed description of the solution you're talking about in your last paragraph?

**Comment by rpspringuel** [comment]
Add a pre-commit hook which does the following:

1. Inquire which branch we are on.  If it is master, proceed with commit.  Otherwise continue with the hook.
2. Using `VersionManager.py` append the branch name and the date/time stamp to the version number (or change them if they are already there).
3. Proceed with the commit.

This way any commit off the master branch would be identified in the version number.  As a pre-commit hook, each developer would have to set this up themselves (though that's as easy as adding a script file which does it to the right place.

**Comment by eroux** [comment]
Hmm, I have to admit I don't think it's convenient: this would mean (among other things) that every commit would contain changes in a dozen of files... so if I change one line in the README.md, the diff will contain much more, which is completely anti-pattern.

Another solution that might be possible if you really want to automate it, would be:
 * in `post-commit` hook, change the version to the new git version, save the old version in `.tmp.gregorio-version`
 * in `pre-commit` hook, change the version back to the original version saved in `.tmp.gregorio-version`

Going back to your first proposal, something we could do is to have this in Makefile.am:  if python and git are present (as commands) and if on a git repository and if not in master and if not in a tag, then call `VersionManager.py` at the beginning of the build process, then revert it at the end of the build process. But this means that `make clean` should revert it (in case of a failing build process). I admit I find it overkill and not very intuitive, but that would be possible....

@henryso what do you think? Would that kind of things be useful to you?

**Comment by henryso** [comment]
I don't think you should value my opinion too much, since my setup is decidedly non-standard.  However, the downside to this is that, unless the source branch has not changed, branches will never be automatically merge-able.

**Comment by eroux** [comment]
that's right, let's forget about changing the version number in files each commit...

**Comment by rpspringuel** [comment]
So we're back to adding the functionality to `Makefile` (or `build.sh`): having the version number be changed, when possible, pre-build and then reverting it post-build. 

To be honest, the more I think about it, the less I am opposed to making it optional (and thus part of `build.sh`).  While it would be more convenient to be able to tell exactly where a build was on the tree, I think those making builds on the development branches are capable of performing a couple of extra steps when necessary.

**Comment by eroux** [comment]
I think so too... So what should we take as a version for this? Something like b`git rev-parse --abbrev-ref HEAD`-`date +%Y%m%d_%H%m`-g`git rev-parse --short head` ?

**Comment by rpspringuel** [comment]
Can you clarify with some examples?  I'm not following your suggestion(s).

**Comment by eroux** [comment]
`gregorio-bdevelop-2015-04-01_0742-g25c6c5`

**Comment by henryso** [comment]
Does #215 do what you want here?

**Comment by henryso** [comment]
I don't really think we need to have the date in the version.  The SHA-1 ref of the commit should be enough to uniquely identify where you are in the version graph.  Having the abbrev-ref is probably helpful (though not absolutely necessary) but what benefit does the date provide?

**Comment by eroux** [comment]
The date makes the version increment. I have to use it in the debian packages for instance, but I can keep it for debian only...

**Comment by henryso** [comment]
That's good enough a reason for me.  Better to be consistent.

**Comment by rpspringuel** [comment]
Ugh, I've been so busy I'm only just getting to this.

I like what's been implemented, and have only a few suggestions:

1. Instead of replacing the version number, could the additional information be added onto the existing version number?  This makes it easy to identify what the underlying stable version is.
2. The `b` prefix before the branch name is a bit confusing, and I don't think it's really necessary.  If we're going to keep it, can we at least introduce a separator character (such as `:` or `_`) between it and the actual branch name.

**Comment by henryso** [comment]
Any decision here?  I like the idea of prefixing with the version number, but I have no strong opinions.

**Comment by henryso** [comment]
Which of the following would you like?

- b{branch}-{date}_{time}-{commit} (current) -> bdevelop-20150426_1757-1bdd46e
- {branch}-{commit}-{date}{time} -> develop-1bdd46e-201504261757
- {commit}-{date}{time} -> 1bdd46e-201504261757
- {version}-{commit}-{branch}-{date}{time} -> 4.0.0-rc1-1bdd46e-develop-201504261757
- {version}-{branch}-{commit}-{date}{time} -> 4.0.0-rc1-develop-1bdd46e-201504261757
- {version}-{commit}-{date}{time} -> 4.0.0-rc1-1bdd46e-201504261757

**Comment by rpspringuel** [comment]
My preference is for {version}-{branch}-{commit}-{date}{time}

**Comment by eroux** [comment]
Maybe {version}-{branch}-{revision} would be shorter? (`4.0.0-rc1-develop-1690` for current develop) That's just an idea, I really don't have strong opinion about this.

**Comment by henryso** [comment]
I prefer commit to count, so I will go with @rpspringuel's choice if no one has any further objection.

**Comment by eroux** [comment]
ok

**Comment by rpspringuel** [comment]
I wouldn't mind substituting {count} for {date}{time}, but agree that {commit} should definitely be there.

**Comment by rpspringuel** [comment]
Oh, and it should be noted that the output of `git describe --tags` is {most recent tag}-{count}-{commit}.  Assuming that the tags are all version numbers (as they currently are) then one would just need to insert the branch name if we made the switch from {date}{time} to {count}.

**Comment by henryso** [comment]
I think that {version} should still be based on the package version as managed by `VersionManager.py`.

So am I hearing {version}-{branch}-{commit}-{count} ?

**Comment by rpspringuel** [comment]
Sounds good.

**Comment by henryso** [comment]
Please review #335 at your convenience.
