### ISSUE TITLE
C function prefixes

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#191]
When gregorio was built as a library and could be linked against other software, it more or less made sense to prefix all functions with `gregorio_`, but it has no sens anymore, and makes the code harder to read, I think these prefix should be removed. What do you think?

**Comment by henryso** [comment]
Due to the lack of name-spacing in C, and with the view of possibly embedding gregorio into a GUI in the far future, I think it's a good idea to keep the prefix.

**Comment by eroux** [comment]
ok, let's keep them then
