### ISSUE TITLE
\setgrefactor -- Backwards incompatible

### ISSUE THREAD

**Issue by eschwab** [gregorio-project/gregorio#205]
In `release-3.0` `\setgrefactor` must occur after `\begin{document}`. Previous versions did not have this requirement and `\setgrefactor` could appear in the preamble. Can everything be initialized earlier so `\setgrefactor` can be used in the preamble? If not this change should appear in `Upgrade.md` and possibly `Changelog.md` as well.

It would be great if the old behaviour could return. Then those who have their own config or documentclass can continue using them without needing to add `\setgrefactor` later in the document.

**Comment by henryso** [comment]
Quoting @rpspringuel (gregorio-users):

> This is because I moved the loading of the default space configuration to
> \AtBeginDocument to ensure that all the macros were defined properly before we
> tried to use them.  It's not necessary that it be that late. Using the begin
> document hook was just convenient.  I could move loading of the default space
> configuration to the end of the loading of the GregorioTeX package if that
> would be preferable.

**Comment by rpspringuel** [comment]
See #207.
