### ISSUE TITLE
Problem with (ih/jki'hhf.)

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#214]
Compile this mwe with `lualatex --shell-escape mwe.tex`

###### mwe.tex
```
\documentclass[11pt]{article}
\usepackage{luatextra}
\usepackage{graphicx}
\usepackage{gregoriotex}
\usepackage[utf8]{luainputenc}
\autocompilegabc
\begin{document}
\includescore{mwe}
\end{document}
```

###### mwe.gabc
```
initial-style: 0;
%%
(c4) him(ih/jki'hhf.) (,)
```

###### output
![out](https://cloud.githubusercontent.com/assets/421318/6944949/6d180994-d864-11e4-8f2e-112900eb3a7e.png)

Note that the generated TeX file appears to be correct:
```

% File generated by gregorio 3.0.0-beta
\gregoriotexapiversion{3.0.0-beta}%
\begingregorioscore%
\grenoinitial %
\grebeginnotes %
\gresetinitialclef{c}{4}{a}%
\gresyllable{h}{i}{m}{1}{\gresetnextsyllable{}{}{}}{}{11}{}{%
\greglyph{\char 5282}{i}{j}{8}{}{}%
\greendofelement{0}{0}%
\greglyph{\char 27845}{j}{h}{0}{}{%
\grevepisemus{h}{0}%
}%
\greendofglyph{0}%
\greglyph{\char 6307}{h}{g}{1}{}{%
\grepunctummora{f}{0}{0}{0}%
}%
}%
%
\grebarsyllable{}{}{}{1}{\gresetnextsyllable{}{}{}}{}{0}{%
\grelastofscore %
}{%
\gredivisiominima{}%
}%
%
\endgregorioscore %
\endinput %
```

There are three glyphs, but for some reason `\char 27845` is not showing (although the ictus is showing and overlapping the prior glyph).

**Comment by eroux** [comment]
wow, `luatextra` is seriously outdated (I know what I'm talking about) and `luainputenc` is totally unneccessary with `utf8` and should be avoided... I believe replacing it with `\usepackage{luaotfload}` should work under TeXLive 2012? It would be much cleaner...

**Comment by henryso** [comment]
OK, I'll switch those out.  In any case, this turns out to be one of the incompatibilities going to release-3.0.  This sequence used to parse into what I expected.  Now I need to do (ih/jki'/hhf.) to get the same effect.
