### ISSUE TITLE
Left-aligning scores on notes (not text)

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#221]
Gregorio currently aligns score text so that all first syllables are on the same vertical line. But Gregorian scores are usually not aligned this way: the best rendering to the eye is when the first notes are on the same vertical line.

This fine tuning would allow Gregorio to be fully on the level of Gregorian books such as Solesmes books.

Currently, the only way to have scores aligned on notes is to force end of lines, but this is not a satisfactory solution.

**Comment by henryso** [comment]
I integrated everything together into https://github.com/henryso/gregorio/tree/integration and tried running the gregorio-test suite.  There are some TeX failures (pes.gabc, other.gabc, ...).  If you want me to attach logs, let me know, but it's pretty copious output.

**Comment by eroux** [comment]
Thanx! What does "integration" refer to? To let you know I was planning one more modification in spacings and then pull requesting and testing further (will happen hopefully this week-end, if not next week)

**Comment by henryso** [comment]
Integration is where I combine branches together for whatever reason (to test something, to preview a merge, etc.)  I never intend to create a pull request out of my integration branch.

**Comment by eroux** [comment]
also, here is not the right place for this, but did I break my installation somehow or does the example give too short lines (notes go much further than lines themselves)

**Comment by henryso** [comment]
There are some spacing anomalies between syllables in my tests against integration, but I don't get what you describe (if I understand it) after https://github.com/gregorio-project/gregorio/commit/9e76b3360f0be4dd92d6920c2be8fc42ed313a11 is applied.

**Comment by eroux** [comment]
Oh, sorry, I meant even on the release-3.0 branch, but I'll try to clean things up, it's probably my fault

**Comment by henryso** [comment]
Is it possible or even desirable to make this optional?

**Comment by eroux** [comment]
In the first implementation I had in mind, this would have had a performance impact, but the current implementation shouldn't have this problem, so we can make it non-optional

**Comment by henryso** [comment]
What I meant is, do you think everyone would want this, or would some people like it the way it is currently (and therefore want to disable the new feature)?

**Comment by eroux** [comment]
I think 99.9% of Gregorio users don't notice this detail (which kind of surprises me)... But I don't think anyone would not like the behaviour exposed in this pull request
