### ISSUE TITLE
gregoriotex-chars.tex is not included in the distribution archive

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#232]

**Comment by rpspringuel** [comment]
Easy fix.  See #234

**Comment by avbop** [comment]
A diff of the files in tex/luatex/gregoriotex for the rc distribution tarball against v2.4.2 (via my recent PKGBUILD) gives:

2c2,3
< gregoriotex-ictus.lua
---
> gregoriotex-chars.tex
> gregoriotex-chars-translate.lua

**Comment by rpspringuel** [comment]
`gregoriotex-chars-translate.lua` script doesn't really need to be in the distribution.  That script recreates `gregroiotex-chars.tex`, shifting the character code points by some number (currently 160).  It's related to the effort to first get the font characters to not use control characters (already done) and eventually to migrate them to the private use area of UTF (not yet done).

**Comment by henryso** [comment]
I think we should add

- `gregoriotex-chars.tex`
- `gregoriotex-chars.tex.in`
- `gregoriotex-chars-translate.lua`
- `optimize_gabc.lua`
- `optimize-gabc.sty`
- `optimize_gabc_style.lua`

Since this is a source code distribution (similarly to how we include the `.py` and `.sfd` files in `fonts/`)

**Comment by henryso** [comment]
Ok, scratch my previous comment then.  However, do we need `optimize-gabc.sty` ?

**Comment by eroux** [comment]
the `optimize-gabc` stuff is outdated and removed in develop, it doesn't need to be in the tarball. Since gregoriotex-chars is generated, maybe its generation should be in the makefile too?

**Comment by henryso** [comment]
Based on @rpspringuel's comment, I don't think `gregoriotex-chars.tex` is generated.  The lua script and the `.tex.in` file are part of an as-yet incomplete effort to fix the code points of the characters in the fonts.  I merged #234 and will close this.

**Comment by eroux** [comment]
I tend to disagree: there is `gregoriotex-chars.tex.in` which is the base on which `gregoriotex-chars-translate.lua` generates `gregoriotex-chars.tex`. It's not really perfect, as the configuration should be global and the script should also modify `gregoriotex.h`, but we could have

    gregoriotex-chars.tex: gregoriotex-chars.tex.in gregoriotex-chars-translate.lua
      gregoriotex-chars-translate.lua

this would make one less file in the repository... What do you think about the global idea?

**Comment by eroux** [comment]
The other solution would be to finish the translation to unicode private area and remove the file generation...

**Comment by henryso** [comment]
I tend to favor finishing the translation and removing the file generation.

**Comment by eroux** [comment]
Ok. there is just a little study on the current number of glyphs and their organization, to be sure that it fits in the private area, but it shouldn't be long. This would mean that we would have to release Gregorio 4.0.0 though.

**Comment by henryso** [comment]
Two things.  I'd have to be convinced this change would be a major bump. The users would have to recompile their gabc, but that's it, unless they were using the glyphs directly.

Second, I know the glyphs were moved from the control character area because they were causing problems with integration.  Since this font is not really a lettering font, unless there's a practical reason to do it, maybe it's fine the way it is.

**Comment by eroux** [comment]
Sadly, there is no abstraction for glyph numbers, gregorio writes them directly in the `.gtex` file, so users will have to recompile them. If you take a look at mail archives, there is a full month of bug reports after I did a change... But anyway, maybe it would be the occasion to do this abstraction layer. ie: write \gre@clivis{5} instead of the clivis with ambitus of 5. I didn't do it because it will take the compilation a bit heavier, but I don't believe it would be significant.

About keeping the font like that, why not, it would be cleaner to make it compliant with the standards though...

**Comment by henryso** [comment]
I've created #239 to track this rather than continuing the discussion under this closed issue.
