### ISSUE TITLE
Update install.sh to handle multiple directory names in TEXMFLOCAL

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#235]
In Arch Linux, `TEXMFLOCAL` is apparently set to `/usr/local/share/texmf:/usr/share/texmf`.  If this is a standard thing (the colon makes me suspicious...), then install.sh should be made to handle it.

**Comment by eroux** [comment]
`TEXMF*` variables are on the same model as PATH so they should be parsed the same way... it's possible that the separator is also changed to `;` under Windows (like in `PATH`), but I'm not 100% sure..

**Comment by henryso** [comment]
So here's the trick question.  Do I use the first path on `TEXMFLOCAL`?  The last?

**Comment by eroux** [comment]
(sorry, I answered by editing the comment, before seeing your question)

**Comment by avbop** [comment]
You could try parsing `kpsewhich somefile.sty` for something that should come with any given TeX install (and/or something that's required by gregorio but not packaged with it). That should at least give a texmf directory that TeX is already looking in.

**Comment by henryso** [comment]
I don't think it's a good idea to just put stuff into `TEXMFDIST`, for example.  I think the solution of taking the first element of `TEXMFLOCAL` (or whatever variable is specified) is best.
