### ISSUE TITLE
Hard-coded characters against \gregoriofont in gregoriotex-syllable.tex

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#243]
While I was trying to figure out my glyph problem I noticed the following in [gregoriotex-syllable](https://github.com/gregorio-project/gregorio/blob/release-3.0/tex/gregoriotex-syllable.tex) at line 225:
```
    \ifnum#1<40\relax%
      \advance\gre@count@temp@three by -20\relax %
      \grefindsimplenotesaligncenter{\gre@count@temp@three}{1}%
      \gre@dimen@temp@five=\wd\GreTempwidth %
      \divide\gre@dimen@temp@five by 2\relax %
      \setbox\GreTempwidth=\hbox{\gregoriofont \char 6}%
    \else%\ifnum#1<40
      \advance\gre@count@temp@three by -40\relax %
      \grefindsimplenotesaligncenter{\gre@count@temp@three}{1}%
      \gre@dimen@temp@five=\wd\GreTempwidth %
      \divide\gre@dimen@temp@five by 2\relax %
      \setbox\GreTempwidth=\hbox{\gregoriofont \char 7}%
    \fi %
```
It looks like it wants character 6 and 7, but there's currently nothing there (even after the control character bump).  Maybe this is related to the spacing issues @jperon is experiencing?

**Comment by eroux** [comment]
It's definitely a bug indeed! But it's related to the flats and naturals, so I'm affraid this is not the cause of the other one... you can replace them by `\greflatchar` and `\grenaturalchar`

**Comment by henryso** [comment]
Without fully understanding the purpose of this code, let me ask, should there be some sort of sharp handling here as well?

**Comment by eroux** [comment]
certainly... I admit I can't remember how all of this works...
