### ISSUE TITLE
Undefined control sequence when the first syllable is italic or bold

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#247]
I know it's [quite a silly idea](https://mega.nz/#!j8ZlWJSS!71u6WywKKGGD68ZZx8DlcJAxD2M4iXKGhaJgWvlOqMg), but I discovered that by preparing a mwe for another bug : when the first syllable is between `<i></i>` or `<b></b>`, the compilation fails with an "undefined control sequence". Though I don't think it's necessary to support italic or bold initials, perhaps a more explicit message would facilitate the work to those who would have such an idea ?

**Comment by henryso** [comment]
There is a fix in the `develop` branch which fixes this silently, but that's for the next version of Gregorio.  The initial will not be styled, but the rest of the syllable will be.  I'll look into having Gregorio produce a warning in this case.  The code is a little convoluted, so I'm not 100% sure I can do that without breaking something.

**Comment by henryso** [comment]
The version in `develop` will emit a warning in this case, but only if warnings are enabled (which they are not, by default).
