### ISSUE TITLE
Suggestion about default initial style

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#249]
This issue follows the discussion initiated in #238.
For now, the default initial style is quite small. Detecting whether the package `fontspec` is loaded and, in that case, setting a bigger initial size would avoid difficulties, especially to beginners.

**Comment by eroux** [comment]
I have to admit I don't understand everything:

 * what exactly would fontspec do differently?
 * in the example, there is `\def\greinitialformat#1{{\fontsize{43}{43}\selectfont #1}}`, which seems quite easy to tweak to get something bigger... but do you mean something like that should be set as the default?

**Comment by jperon** [comment]
I wrote this by reference to @rpspringuel's reply : it seems that, pending on the font handling, all fonts are not necessarily infinitely scalable, and that would explain why the initial is defined as \huge by default, which gives a smaller initial than usual. With fontspec, the scale is definitely possible ; this is the reason why I'd suggest adjusting the size by default in that case, as most users would expect bigger initials.
But perhaps I miss something, and it would be sufficient to define `{\fontsize{43}{43}\selectfont #1}` as a default.

**Comment by jperon** [comment]
Thinking about once more, I think it shouldn't be necessarily 43, but something relative to the font size of the score.

**Comment by eroux** [comment]
Fonts are infinitely scalable, but perhaps this could be like 5 times the font size by default yes...

**Comment by rpspringuel** [comment]
Fixed by #313
