### ISSUE TITLE
GREGORIO_VERSION in gregoriotex.h

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#265]
We might want to move this to a separate header file (included from gregoriotex.h) to ease merge issues when the version number is bumped by VersionManager.py.

Thoughts?

**Comment by eroux** [comment]
Well, now that the gabc/gregoriotex/gregorio versions are the same, `VERSION` from `config.h` should fit?

**Comment by henryso** [comment]
Great.  I'll make the change in `develop` once the dust from rc2 settles a bit more.

**Comment by henryso** [comment]
If I change it to use `VERSION`, then it won't work properly for non-tagged (off-master) builds.
