### ISSUE TITLE
Fonts metadata

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#270]
There seems to be some metadata missing from the generated fonts, here are a few ideas of improvements (not really urgent)

 * version in the `.sfd` files are old, they should be updated by `VersionManager.py`
 * no version is present in the TTF, `squaryze.py` should write it
 * there is no Unique ID nor XUID
 * I'm not sure about the OS/2 character set (nor what it does)

**Comment by eroux** [comment]
When the version will be accessible in the font, GregorioTeX should check if the versions match between the TeX and font.

**Comment by henryso** [comment]
What remains to be done here?

**Comment by eroux** [comment]
I think it's ok now
