### ISSUE TITLE
TeX file versions

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#271]
I never realized that replacing the hardcoded versions in the different `gregoriotex-*.tex` by

    \gredeclarefileversion{gregoriotex-spaces.tex}%
     {\directlua{tex.write(gregoriotex.get_gregorioversion())}}%

changed the behaviour and made the process almost pointless: this means that an outdated `gregoriotex-*.tex` won't be detected anymore, as it will just use the version of the not-outdated `gregoriotex.lua`... So I think we should switch back to the old hardcoded versions and add the different files to `VersionManager.py`... What do you think?

This could be for 3.1 or 3.0, I don't know...

**Comment by henryso** [comment]
For what it's worth, I agree.  If the changes are not risky, then 3.0.  Otherwise, 3.1.

**Comment by eschwab** [comment]
I could do this later today for 3.0. Seems best to get this done right away to prevent issues with bad installs.

**Comment by rpspringuel** [comment]
Agreed, the check is essentially useless as is and this should be fixed for 3.0.
