### ISSUE TITLE
gregoriostylefont character references in gregoriotex-chars.tex are wrong

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#272]
While reverting the change to fix #266, I noticed that `gregoriotex-chars-translate.lua` indiscriminately updated the values for this font which is not offset into PUA-A.  However, undoing this to the version prior to that change does not appear to be selecting the right characters out of `greextra.ttf`.  If I subtract 161 (the old offset), the characters *still* seem to be off.  Does anyone know what the correct values are for the `\gregoriostylefont`?

**Comment by eroux** [comment]
Good point... I admit it has been a few years since I haven't opened this font though, sorry...

**Comment by henryso** [comment]
If I had to guess, the offset is 66.  I will use that for now unless someone knows better.
