### ISSUE TITLE
Hard coded character code points in gtex files

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#279]
Right now gregorio hard codes the character code point for most (but not all) glyphs into the gtex file when it creates it.  This means that there has to be coordination between the `.ttf` files, GregorioTeX, and the command line tool for those code points.

Would it be possible to reduce the amount of needed coordination by having the commandline tool use the character names defined in `gregroriotex-chars.tex` instead of hard coding the code points?

If not, can some sort of check be established that would verify that all three are working from the same character code points?

Heck, even if the coordination can be reduced, it might be nice if some sort of check can be built into `gregoriotex-chars.tex` that makes sure the code points defined there match the font.

**Comment by henryso** [comment]
I have already modified the code to use \gregoriocharoffset to eliminate coordination of the offset with the tex files.  The next level is something Élie has mentioned to use macros and have the TeX code to do the computation of the code point based on ambitus.  I'm not sure this is necessary, but it is worth discussing.

**Comment by eroux** [comment]
I've been wondering about this for a few years, the main reason why I didn't do this is because I have the weird belief that it will slow down computation a little bit... But this might not be justified at all, and there should be some tests about that... I think it's misplaced optimization, a few integer additions are certainly neglectible compared to the font handling... But I don't have a very long document to test compilation time, and I know some do books of around 1000 pages with Gregorio, I wouldn't want to make their computation ubearably slow... In order to bring some rationality, maybe there could be an extremely long document in gregorio-test, with a special test target about computation time? Of course it couldn't be automatic, but it would allow to test if some changes introduce slowness. What do you think?

**Comment by henryso** [comment]
Do you know of a large non-copyright-protected document?  Should I just grab a bunch of scores from gregobase?

**Comment by rpspringuel** [comment]
@henryso, the use of `\gregoriocharoffset` certainly makes changing the offset easier, but the code points are still coded into `gregoriotex-chars.tex`.  There just in two pieces: the offset and the relative position within the character block.  This then has to be coordinated with the `.ttf` files and with the numbers which are written to `.gtex` files (though I think that these latter numbers are also calculated from the offset and relative position, making coordination easier).  Further, the files don't currently talk to each other to check that they are coordinated.

What about the possibility of creating a single dictionary file that contains the code points?  Could `squarize.py` be convinced to export a file which contains the names of each glyph and its code point?  With the right format, it should then be possible for GregorioTeX to use this file to look up the code points for glyphs by name.  Could the command line tool do something similar?

On the issue of speed testing, perhaps querying the user list for just such a project (and permission to use it for testing purposes) would help.

**Comment by henryso** [comment]
If I had a choice, I would reference all glyphs by name, using names generated according to formula by `squarize.py` in the fonts.  I have no idea what the performance impact would be, as I suppose this would mean breaking into Lua for every glyph.

However, in the absence of that, there's no reason `squarize.py` couldn't read `gregoriotex-chars.tex` and use it to define the shape offset when generating the fonts.  The C code would then use well-defined macros with ambitus arguments and the macro would do the calculation.

**Comment by eroux** [comment]
The document could be 1000 pages of PopulusSion.gabc, with just one line of text between them (you can make a loop in TeX for that, see [this thread](http://tex.stackexchange.com/questions/16189/repeat-command-n-times)

**Comment by rpspringuel** [comment]
A document which just repeated the same score many times would only check the performance of GregorioTeX.  The command line tool would only be called the first time through the loop.  Subsequent passes would find an up to date score already compiled and would use that.

Of course that's only an issue if we're worried about testing the command line tool.  Further, it might be more efficient to test the command line tool performance with a bash script which loops a call of the tool.  That would avoid needing a large number of scores for that test too.

**Comment by eroux** [comment]
My proposal was indeed only intended for GregorioTeX performance testing, but it's a good idea to be able to test the command line tool too...

**Comment by henryso** [comment]
There are some visually identical duplicates in the font (i.e., 161+1 and 161+3, 161+2 and 161+4, multiple punctum glyphs).  What purpose does this duplication serve?

**Comment by eroux** [comment]
161+1 is used in the case of a clef at the beginning of the line and 161+3 is used for a clef change in the middle of a line. Some fonts (I think parmesan does) make the clef changes inside a line slightly smaller... What other duplicates do you see?

**Comment by henryso** [comment]
Actually, I think that's it.  I was mistaken about the punctum.  One of them was actually the small punctum (deminutus?).

**Comment by eroux** [comment]
I think there is one in the final font to be able to compute some widths from TeX (if that answers the question?)

**Comment by henryso** [comment]
What is 161+16, and how do you get 161+90 vs 161+88?

**Comment by henryso** [comment]
I figured out 161+90 and 161+88.  I still can't figure out 161+16; gregoriotex-write.c calls it 'circumflexus'.

**Comment by henryso** [comment]
What remains is to remove the hard-coded code points for the greextra font and to possibly add a change log entry.  None of these changes should require the user to do anything except possibly running `luaotfload-tool --cache=erase` if they run into problems, so should there be a change log entry?

**Comment by henryso** [comment]
Continuing the discussion in #292, I made an attempt to feed off of the LuaTeX font tables rather than opening the font myself.  You can see this in https://github.com/henryso/gregorio/commit/8c0cc4a6d775dfafb6b62d2964e03ae01697961e.  However, this seems to be about a second slower on the big test because (my hypothesis) it loads the greextra font fully into TeX unnecessarily, so I'm reluctant to do it this way.

Is there any way to look into the cached font tables without actually bringing the font fully into TeX ?

**Comment by eroux** [comment]
Indeed, when you define two fonts with greciliae, one for mapping and another for typesetting... Maybe you could hook into `\setgregoriofont` so that you map fonts when they load?

**Comment by henryso** [comment]
That was the previous try, which requires using `\gdef` for the things in `gregoriotex-chars.tex` and thus ended up slower also.

**Comment by eroux** [comment]
then, indeed, the fontloader option might be the best

**Comment by henryso** [comment]
... unless I can get into the cache without loading the font, but I haven't been able to find a way to do that.

**Comment by henryso** [comment]
None of these changes should require the user to do anything except possibly running luaotfload-tool --cache=erase if they run into problems, so should there be a change log entry?

**Comment by eroux** [comment]
I don't think so... Too bad, because it's really a very positive and strong change!

**Comment by henryso** [comment]
I concur.  I think the only thing that remains is removing the hard-coding of gresym characters in `\tex\gregoriotex-symbols.tex`, but that is better handled as part of #295.  Closing this issue.
