### ISSUE TITLE
five-note neume does not display

### ISSUE THREAD

**Issue by chonak** [gregorio-project/gregorio#284]
If there are five notes in a row, with no specification of neume type, the first four notes do not appear in the output, and only the last note is displayed.  If I add a separator ("!" or "/") to the input, the neume is formed correctly. 

Here is a minimal example:
%%
(c4)A(g!hgfg) (::)
a(ghgfg) (::)

When I process this, the first series of notes appears in full; but the second group of notes doesn't: only the last note of the series appears.  

![snapshot18](https://cloud.githubusercontent.com/assets/11400036/7189494/640a3120-e44d-11e4-8ad4-34775bcda875.png)

I found this behavior in v.3.0.0-rc1 (on Linux, with TeXLive2013).  Another user confirms it with v.3.0.0-rc2 on Mac.

**Comment by henryso** [comment]
If you need a short-term work around, use ghg/fg.

**Comment by henryso** [comment]
Team, should I target `develop` or `release-3.0` ?  This bug was introduced with the so-called "torculus liquescens" (ghgf~)

**Comment by henryso** [comment]
I decided to just target both.  If we decide not to include in `release-3.0`, close #285.

**Comment by eschwab** [comment]
If it passes all the tests, then it would be good for `release-3.0`.

**Comment by henryso** [comment]
Yes, it passes all the tests I expect it to pass.  There are some tests which are known different in `develop` because of bug fixes and new features.  I don't expect `release-3.0` to pass them.

**Comment by eroux** [comment]
I'd be in favor of both `develop` and `release-3.0` too, thanx for the fix!
