### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#291]
In trying to build `develop` and `release-3.0` from a freshly cloned repository on a Mac I get the following error:

`bison: gabc-score-determination-y.c: cannot open: Permission denied`

Checking the file, it's permissions don't seem to be any different from the other files.  Does anyone have any idea as to why this error might be cropping up?  I can obviously get around it by running the build with root permissions, but I thought we had fixed things so that wasn't necessary.

**Comment by henryso** [comment]
Check the permission/ownership of the gabc directory itself.  Anything odd there?

**Comment by rpspringuel** [comment]
Nope.  It has the same permissions as the other folders in `plugins` (on `release-3.0`) or `src` (on `develop`).  Namely `rwxr-xr-x`.  Owner is `RPS` (i.e. me) for all.

**Comment by henryso** [comment]
What's strange to me here is that bison is supposed to be writing that file, so something is preventing it from being overwritten. I know very little about Mac security, but under Unix, the next thing I would check is the ACLs.

**Comment by henryso** [comment]
If you delete `gabc-score-determination-y.c` and `gabc-score-determination-y.h`, can you build as non-root?  If you can, immediately try touching `gabc-score-determination.y` and building again.  If it works, then some permission somehow got onto that file and it should be fine from now.  If it doesn't, then bison is doing something weird on Mac, and I'm not sure how to troubleshoot that.

**Comment by rpspringuel** [comment]
I'm in the process of setting up a clean development environment using a virtual computer in order to test some things here.  Right now my best guess as to what is happening is that using `sudo` within the repository is changing permissions in a non-obvious way.  I'm hoping that a comparison between a completely clean environment and my main system will reveal just what's going on.

**Comment by rpspringuel** [comment]
Building in my clean test environment works without a hitch as an ordinary user.  Clearly this boils down to a permissions issue.

After some further testing, I found that deleting the `build-aux` folder and starting the build process from scratch (i.e. from `autoreconf -fi`) worked.

Take home message: once you start using `sudo` to do the build process on a Mac the files that are created from that point on will be own by root and thus will have to be removed or their ownership changed before you can build as non-root again.  Unfortunately, `make maintainer-clean` won't always work for this because it can't remove files that are root owned unless it is run as root.  This failure, however, is relatively silent: an error appears in the output, but it doesn't halt the process.  The end result is that the `Makefiles` are removed, but one still might have some detruis lying around that is root owned and which will interfere with subsequent builds.

Is there anyway to modify the clean targets so that they will halt upon encountering a "Permission Denied" error, rather than blithely continuing on?

**Comment by henryso** [comment]
I know how to do this in a plain Makefile (remove the leading `-`), but I don't know how to make autotools generate the line without the leading `-`.

**Comment by henryso** [comment]
@eroux Do you know how to control this aspect of autotools/automake?

**Comment by eroux** [comment]
I don't think it's possible... this would mean that autotools should know the return code of all commands, and check: for this command and this return code, then exit, for this other one then continue, etc. Autotools are big, but not that big I believe...

**Comment by henryso** [comment]
In that case, I think we have to close this as wontfix.
