### ISSUE TITLE
improvements in gresym

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#295]
I believe gresym shouldn't have pre-composed `A/` `V/` and `R/`, especially since it makes the copyright more complex (the letter glyphs come from another font). Also, there should be a bar in other styles (more round), I have nice examples, but I need to ask for permission before using them...

**Comment by rpspringuel** [comment]
I would apply the same logic to the gothic variations as well.

**Comment by eroux** [comment]
Good idea yes, though the gothic characters were drawn by me (from some scans I made in an old book) and do not pose copyright problems... so I think they could stay, but the round bar should also be available separately.

**Comment by henryso** [comment]
Since work on `gresym.ttf` is possibly forthcoming, I will defer to whomever implements this to add the mapping code for the glyphs in the font.

**Comment by henryso** [comment]
We might also want to consider merging this font into `greextra.ttf`.  There's not much in that font, and it's one less font to open and map at runtime.

**Comment by eroux** [comment]
That's a good idea yes!

**Comment by henryso** [comment]
If we take out the pre-composed characters, how will `\Abar`, '\Rbar`, and `\Vbar` be defined?

**Comment by eroux** [comment]
I think they can be a reasonable default like `V\kern -0.5em{\gresym\barforV}` (or so), with a redefinition in the example so that users can see how to change it... Wdyt?

**Comment by henryso** [comment]
Personally, that's what I do to integrate better with the text font I like to use, but I've found that it needs to be tweaked slightly for each different font (which isn't a surprise), so people will likely not get satisfactory results from the default.  I don't think that's a blocker, but I just wanted to be sure what to do before embarking on this change.

**Comment by eroux** [comment]
Indeed, this will require some tweaking when changing font, but I'm sure people will be happy to have something in the font they choose... Though it will certainly require a strong warning in the example file.

**Comment by henryso** [comment]
Just a reminder from #279 to remove the hard-coding of code points from `tex/gregoriotex-symbols.tex`.  Anyone have any strong feelings about the names for any of the glyphs in this font?  If not, I'm sure I can come up with something.

**Comment by henryso** [comment]
I know I closed pull request #306 because it was becoming unwieldy, but change log entries for it are still needed.  The change log should note that `\Vbarsmall`, `\greletterbar`, and `\greletteraltbar` are now supplanted by the new glyph system and bar macros.
