### ISSUE TITLE
Missing pre-1985 oriscus shape.

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#302]
See http://www.mail-archive.com/gregorio-users%40gna.org/msg01991.html for the earlier discussion.

![old-oriscus](https://cloud.githubusercontent.com/assets/421318/7273122/89f849b0-e8be-11e4-9204-340d6f36c8c3.png)

(Image excerpted from http://download.gna.org/gregorio/pdf/Antiphonaire_Milan_%281935%29.pdf#page=8)

**Comment by henryso** [comment]
Perhaps this is another candidate for #301.

**Comment by henryso** [comment]
Does any one have high resolution scans of this oriscus figure?

**Comment by henryso** [comment]
No response for a long time; should we just close this?

**Comment by eroux** [comment]
Ok
