### ISSUE TITLE
Font loading error on develop

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#303]
I just build and installed from develop (which proceeded without a hitch) and got the following error when I tried to typeset a document:

`Font \local@greciliae=greciliae not loadable: metric data not found or bad.`

I tried flushing the font cache, but got the same error afterwards.  Any ideas as to what might be wrong and what I should try?

**Comment by henryso** [comment]
I put these lines
```
\font\local@greciliae = {greciliae}\relax %
\font\local@greextra = {greextra}\relax %
```
into gregoriotex.tex (which should work according to the LuaTeX manual).

Please try changing them to
```
\font\local@greciliae = "name:greciliae" at 17 sp\relax %
\font\local@greextra = "name:greextra" at 17 sp\relax %
```
and let me know if that works any better.

**Comment by eroux** [comment]
The LuaTeX manual only documents the core engine, but (especially in LuaTeX) there is a whole layer above the engine (called the format) which sets the user commands, and in LuaTeX, the font user commands are handled by luaotfload, so the best place to look for documentation about fonts in LuaTeX is the [luaotfload doc](http://mirrors.ircam.fr/pub/CTAN/macros/luatex/generic/luaotfload/luaotfload.pdf), that documents the `name:` prefix.

**Comment by rpspringuel** [comment]
That works.  See the pull request.

**Comment by henryso** [comment]
What's interesting is that the former syntax works on my system.  Perhaps it's a difference in LuaTeX.  I suppose this version (which is what we do elsewhere) should work everywhere Gregorio currently works, so it's better.
