### ISSUE TITLE
Proposal: Windows batch file or powershell script to grab system information for support requests

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#325]
With users at various levels of facility with Windows (one recent user was using a camera to take screen shots of output), it might be a good idea to have the installer install a batch file which calls things like

- `kpsewhich --var-value TEXMF`
- `kpsewhich gregoriotex.sty`
- `where lualatex.exe`
- `gregorio -V`

and so on, putting the results in a file that the user can then attach to an email.

**Comment by henryso** [comment]
While we're at it, maybe for Linux and MacOS as well?

**Comment by eschwab** [comment]
Could this be added directly to the binary? Then if they get gregorio installed, which seems to be the easy part, something like `gregorio --print-env` would run those commands and produce a nice summary file.

**Comment by henryso** [comment]
It's possible, but if it's a batch file (for example) the user can just double-click on it to have it do its work.  The point is to try to make it easier for people who (for example) don't know how to open a command prompt.

**Comment by eroux** [comment]
Agreed, with Windows as priority, but why not Unixes in a second time...

**Comment by rpspringuel** [comment]
I agree that this would definitely be useful.  I'll have to brush up on my batch file scripting again or finally break down and learn PowerShell to make it happen, though.  Given my schedule, the time for that probably isn't available this week or next.

**Comment by rpspringuel** [comment]
Would this be something that goes on 3.0.0 or develop?

**Comment by eroux** [comment]
3.0.0 seems like a good idea to me

**Comment by henryso** [comment]
My opinion would be to develop it in a branch against release-3.0, but without any sort of promise that it would make it into 3.0 unless it's complete.

**Comment by rpspringuel** [comment]
Had to jot down some ideas to prevent myself from forgetting them.  See b645e324a817b11a83b8563f54bb6681c9d316de to comment.

**Comment by rpspringuel** [comment]
#398 Gets this started with a batch file for windows.
