### ISSUE TITLE
make squarize.py more generic (handling possibly more fonts)

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#328]
This request is with gregoria4o in mind. squarize.py should be able to handle more fonts (with the same format) than the three in the Gregorio repository. To do so, an important step is to get rid of the hardcoded widths in `get_lengths`. I think they come from the old convoluted system where python was generating a fontforge script, but it would be fairly easy to get rid of them now, by having get_lengths read the lengths in the base font directly.

Also, it would be best if the table returned by `get_lengths` was having the width of all the glyphs in the base font.

Finally, Gregoria has different widths for base4, base2, base5, base3, etc. so squarize.py shouldn't consider them all to have the same width.

**Comment by eroux** [comment]
@eschwab I was thinking maybe you could do that? That's just an idea, if you have no time or if you see other priorities, no problem

**Comment by eschwab** [comment]
I can, but I am overbooked until the school year ends in late May. I am interesting in doing it, since I need to learn more on fonts.

**Comment by eroux** [comment]
I'm afraid late May will be a bit too late, as I'll be blocked by this tomorrow (which I didn't really expect), so I'll do it, but don't worry, there is still a lot to do on fonts!
