### ISSUE TITLE
"Hungarian Gregorian"

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#35]
This came up on the Lilypond mailing list and reminded me of something on [our old task list] (https://gna.org/task/?7766).

A user over there wanted to create something that is sort of a [hybrid between gregorian notation and modern notation] (https://drive.google.com/file/d/0BzQDuwMSrodQU19yRTVLM0F3ZHM/view?pli=1).  It uses a five line staff, modern clefs, and round note heads, but links those note heads together like square notation notes.  If we ever get to the point where we're working on adding a 5-line staff, then we might also want to look at creating a font which would allow this sort of thing to work.

Anyway, it's not something that I'm in any position to work on, nor do I think it's in any way critical (as this isn't, technically, gregorian notation) but I thought I'd post the idea here to create a record of it.

**Comment by eroux** [comment]
Well, let's be realistic, we don't have enough info for that... lets reopen it when if we get some.
