### ISSUE TITLE
Windows Installer not Compatible with MiKTeX

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#355]
Right now the Windows Installer works fine with TeXLive as tested on both Windows XP and Windows 7 (a test on Windows 8 is forthcoming).  However, the post install script does not play well with MiKTeX on Windows 7 (tests on Windows XP and Windows 8 should be forthcoming here).

First inspection indicates that the directory that MiKTeX sets as `TEXMFLOCAL` doesn't exist by default and that `mktexlsr` doesn't accept a directory argument.

**Comment by eroux** [comment]
Does `mktexlsr` fail if it's provided an argument? (this would seem quite odd)

**Comment by rpspringuel** [comment]
That does appear to be what the output of the post-install script is indicating.  I haven't had a chance to explicitly test that behavior from the command line.  It's very counter intuitive, as the behavior for TeXLive is very different.

A quick search that I conducted yesterday seemed to indicate that `mktexlsr` is not really in MiKTeX.  Rather, that handle is an alias for something which is more MiKTeX specific (`inittexmf`) which is provided for compatibility purposes with TeXLive.  However, if it doesn't take arguments in the same way that TeXLive's `mktexlsr` does, then it's not really providing that compatibility.  TeXLive's `mktexlsr` can be called without a directory argument, but that will rebuild all the indexes, not just the one for `TEXMFLOCAL` and thus could be costly (in terms of time).

While I haven't done any playing yet, I'm thinking that it may be necessary to have the post-install script detect whether TeXLive or MiKTeX is installed and the take actions which are appropriate to whichever one it finds (not sure yet how one could tell which was installed).  That would be highly annoying, but probably doable.  My other brainstorming ideas are to have a separate MiKTeX installer (which would be the same except for its post-install script, and so not a very efficient solution on our end) or to simply not support MiKTeX with the installer at all (a last resort option, in my mind)

**Comment by henryso** [comment]
I wonder if the Windows installer could be made a lot simpler.  Note: I say this with the naivete of someone who has never used the Gregorio Windows installer and who doesn't know how to create Windows installers in general.

What I'm thinking is that perhaps the installer should just give a "best effort" to find the right directories to use and present the discovered directories to the user with a big warning that changing them might prevent the system from working properly.  If the installer cannot find good directories to use, then it should ask the user to choose the right directories.  Then a pre-flight check can see if the directories are writable/create-able and fail the install up front.

As I tend to say... is this possible?  Is this a bad idea?

**Comment by rpspringuel** [comment]
In some ways, that's what the installer is already doing.  The actual installation procedure is as follows:

1. Install all of the files packaged in the installer into some location (default is `C:\Program Files\gregorio`, or `C:\Program Files (x86)\gregorio` on 64-bit systems, but user can change this as part of the installation process).
2. Use `kpsewhich` to query for the path of `TEXMFLOCAL` and the location of the TeX binaries.
3. Check for old installations of Gregorio and remove them if found (to prevent conflicts).  The list of places to look is based on where previous installers might have put things that won't be overwritten by the new installation.
4. Copy `gregorio.exe` to the location of the TeX binaries.  Since this path should already be in `PATH` (the TeX distro installation is supposed to do this), this means we don't have to manipulate that variable ourselves.
5. Copy GregorioTeX into the path found for `TEXMFLOCAL`.
6. Reindex `TEXMFLOCAL` in order to register GregorioTeX.

This process means that we have two copies of `gregorio.exe` and GregorioTeX on the system in the end, one inside the TeX distribution (which the one actually being used) and one in that initial storage folder (along with `contrib`, `exemples`, etc.).

Right now, steps 2 to 6 are done without user input.  Step 2 could, in theory, be expanded/changed to allow for user input like you describe.  This would not solve the MiKTeX problem entirely, though, as step 6 still would have problems without some sort of change.

**Comment by eroux** [comment]
Maybe there could be an option in the intaller to select the installation for TeXLive or MikTeX? I'm not sure that would be very easy with InnoSetup, but that should be doable... What do you think?

**Comment by rpspringuel** [comment]
That's an idea.  At the very least the last pane could have separate check-boxes for TeXLive and MiKTeX.  That's not ideal, since one should, in theory, have just one or the other (i.e. use radio buttons rather than check-boxes).  Still, it would probably be better than having separate installers.  I'll have to research InnoSetup some more when I get the chance.

I will still need to figure out how to make a post-install script that works for MiKTeX though.

**Comment by eroux** [comment]
I think Br. Gabriel-Marie said he had some experience with InnoSetup... @BGMcoder could you help us on this?

**Comment by BGMcoder** [comment]
Inno Setup WILL allow the user to make choices.  It should be easy enough in the setup to follow one procedure or another depending on what the user chooses.  You could have two checkboxes - one each for MikTex and TexLive, and run the installer scripts for the ones the user checks.  Radio-Buttons would work if you only want to install Gregorio to work with one, but if the user has both, then the checkboxes would allow the user to prepare Gregorio for use with both.  That sounds reasonable to me and that's what I'd do.

**Comment by rpspringuel** [comment]
Grrr...  MiKTeX does not provide unzip capabilities, so I can't extract `gregoriotex.tds.zip` from the post install script as is.  This leaves a couple of options:

1. Ship the installer with the GregorioTeX files unzipped.  This will make the installer larger, naturally, and thus it may be best to split the installers into a TeXLive (with compressed files) and MiKTeX (with uncompressed files)
2. Try to invoke the native unzip capabilities of Windows.  This is a bit of a bear and would require a VBS script to be added to the package to enable the functionality.  (Assuming [this](http://jagaroth.livejournal.com/69147.html) still works.)
3. Require 7-zip, free byte zip, infozip, or similar unzip tool and then use it to unzip the file for MiKTeX.
4. Try to find a self-contained unzip tool with an appropriate license, package it into our installer and then use that.  The unzip tool from TeXLive is probably a good candidate for this, but [there might be other options](http://stahlworks.com/dev/?tool=zipunzip).

Opinions?

**Comment by henryso** [comment]
Can't InnoSetup compress the files and just unpack them before invoking the installation script?  A Google search sends me to http://www.jrsoftware.org/ishelp/index.php?topic=setup_compression.

**Comment by BGMcoder** [comment]
Hi, all.  I can try tomorrow to test again with MikTex.
Henry is right - you can use Inno scripting to do unpack the files.
If you are building Inno Setups, you might take a look at Inno Script Studio - it's an IDE for Inno that provides more than the regular Inno editor: https://www.kymoto.org/

**Comment by eroux** [comment]
I think first option is the most viable, as InnoSetup compresses in lzma. zip compressing was just convenient as it makes installation only one line, it shouldn't change the size of the final installer file.

**Comment by rpspringuel** [comment]
Okay, I'll modify the file inventory to list all the files explicitly and see what happens.

**Comment by rpspringuel** [comment]
Switched to a full inventory list and the size of the installer is smaller, if anything (1.3 MB instead of 1.5 MB according to the file system on my Mac).  Still need to get the MiKTeX post-install script working, but I should have something ready for review by the weekend.

**Comment by rpspringuel** [comment]
Something to look at: #427
