### ISSUE TITLE
Fail to build debian package (master branch)

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#356]
Here is the output I get when I do `cd debian ; ./build-deb.sh` :

    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking for gcc option to accept ISO C99... -std=gnu99
    checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
    checking how to run the C preprocessor... gcc -std=gnu99 -E
    checking for flex... flex
    checking lex output file root... lex.yy
    checking lex library... -lfl
    checking whether yytext is a pointer... yes
    checking for bison... bison -y
    checking for windres... no
    checking whether C compiler accepts -fstack-protector-strong... yes
    checking whether C compiler accepts -fPIE... yes
    checking whether C compiler accepts -Wformat... yes
    checking whether C compiler accepts -Werror=format-security... yes
    checking whether the linker accepts -Wl,-z,relro... yes
    checking whether the linker accepts -Wl,-z,now... yes
    checking whether the linker accepts -fPIE... yes
    checking whether the linker accepts -pie... yes
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdint.h... (cached) yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating src/Makefile
    config.status: creating examples/Makefile
    config.status: creating contrib/Makefile
    config.status: creating doc/Makefile
    config.status: creating tex/Makefile
    config.status: creating fonts/Makefile
    config.status: creating src/config_.h
    config.status: src/config_.h is unchanged
    config.status: executing depfiles commands
    make  dist-bzip2 am__post_remove_distdir='@:'
    make[1]: Entering directory '/root/greg/gregorio-dev'
    if test -d "gregorio-4.0.0-rc1"; then find "gregorio-4.0.0-rc1" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "gregorio-4.0.0-rc1" || { sleep 5 && rm -rf "gregorio-4.0.0-rc1"; }; else :; fi
    test -d "gregorio-4.0.0-rc1" || mkdir "gregorio-4.0.0-rc1"
     (cd src && make  top_distdir=../gregorio-4.0.0-rc1 distdir=../gregorio-4.0.0-rc1/src \
	 am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
    make[2]: Entering directory '/root/greg/gregorio-dev/src'
    make[2]: Leaving directory '/root/greg/gregorio-dev/src'
     (cd examples && make  top_distdir=../gregorio-4.0.0-rc1 distdir=../gregorio-4.0.0-rc1/examples \
	 am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
    make[2]: Entering directory '/root/greg/gregorio-dev/examples'
    make[2]: Leaving directory '/root/greg/gregorio-dev/examples'
     (cd tex && make  top_distdir=../gregorio-4.0.0-rc1 distdir=../gregorio-4.0.0-rc1/tex \
	 am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
    make[2]: Entering directory '/root/greg/gregorio-dev/tex'
    make[2]: Leaving directory '/root/greg/gregorio-dev/tex'
     (cd contrib && make  top_distdir=../gregorio-4.0.0-rc1 distdir=../gregorio-4.0.0-rc1/contrib \
	 am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
    make[2]: Entering directory '/root/greg/gregorio-dev/contrib'
    make[2]: Leaving directory '/root/greg/gregorio-dev/contrib'
     (cd doc && make  top_distdir=../gregorio-4.0.0-rc1 distdir=../gregorio-4.0.0-rc1/doc \
	 am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
    make[2]: Entering directory '/root/greg/gregorio-dev/doc'
    make[2]: Leaving directory '/root/greg/gregorio-dev/doc'
     (cd fonts && make  top_distdir=../gregorio-4.0.0-rc1 distdir=../gregorio-4.0.0-rc1/fonts \
	 am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
    make[2]: Entering directory '/root/greg/gregorio-dev/fonts'
    make[2]: Leaving directory '/root/greg/gregorio-dev/fonts'
    test -n "" \
    || find "gregorio-4.0.0-rc1" -type d ! -perm -755 \
	    -exec chmod u+rwx,go+rx {} \; -o \
      ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
      ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
      ! -type d ! -perm -444 -exec /bin/bash /root/greg/gregorio-dev/build-aux/install-sh -c -m a+r {} {} \; \
    || chmod -R a+r "gregorio-4.0.0-rc1"
    tardir=gregorio-4.0.0-rc1 && ${TAR-tar} chof - "$tardir" | BZIP2=${BZIP2--9} bzip2 -c >gregorio-4.0.0-rc1.tar.bz2
    make[1]: Leaving directory '/root/greg/gregorio-dev'
    if test -d "gregorio-4.0.0-rc1"; then find "gregorio-4.0.0-rc1" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "gregorio-4.0.0-rc1" || { sleep 5 && rm -rf "gregorio-4.0.0-rc1"; }; else :; fi
    mv: impossible d'évaluer « gregorio-4.0.0-rc1.tar.gz »: Aucun fichier ou dossier de ce type
    tar (child): gregorio-4.0.0-rc1.tar.gz : open impossible: Aucun fichier ou dossier de ce type
    tar (child): Error is not recoverable: exiting now
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now
    mv: impossible d'évaluer « gregorio-4.0.0-rc1.tar.gz »: Aucun fichier ou dossier de ce type
    ./build-deb.sh: ligne 50 : cd: gregorio-4.0.0-rc1: Aucun fichier ou dossier de ce type
    ./build-deb.sh: ligne 51: ./configure: Aucun fichier ou dossier de ce type
    cp: impossible d'évaluer « ../../../debian/source »: Aucun fichier ou dossier de ce type
    rm: impossible de supprimer « debian/README.md »: Aucun fichier ou dossier de ce type
    rm: impossible de supprimer « debian/build-deb.sh »: Aucun fichier ou dossier de ce type
    dpkg-buildpackage: paquet source gregorio
    dpkg-buildpackage: version source 4.0.0~rc1-1
    dpkg-buildpackage: distribution source UNRELEASED
    dpkg-buildpackage: source changé par Gregorio Builder <gregorio-devel@gna.org>
    dpkg-buildpackage: architecture hôte amd64
    dpkg-buildpackage: avertissement: debian/rules n'est pas exécutable ; corrigé.
     dpkg-source --before-build build
    dpkg-source: erreur: impossible de lire build/debian/control: Aucun fichier ou dossier de ce type
    dpkg-buildpackage: erreur: dpkg-source --before-build build a produit une erreur de sortie de type 2

**Comment by eroux** [comment]
This is due to gregorio-xxx.tar.gz having become gregorio-xxx.tar.bz2 in develop, I'll fix it tomorrow if noone else does so.

**Comment by jperon** [comment]
I've just tested that, and it works like a charm.

**Comment by eroux** [comment]
Thank you very much! Apparently your github account is not fully configured, if you take a look at your commit, it doesn't recognize your mail address... can you fix this? Also, we usually use Github Pull Request system to work on the code, please use it in the future.
