### ISSUE TITLE
Remove unused glyphs?

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#357]
In creating the font tables, it seems to me that `AuctumDuplex`, `Circumflexus`, and the `FlexusNobar` glyphs are unused.  Should they be removed?

There's also a special punctum used for measurement.  Why don't we just use a normal `Punctum` for measurement?

**Comment by eroux** [comment]
If AuctumDuplex is never used it would be good to remove it indeed. The Circumflexus is not used, but originally it was a request from Le Barroux Abbey that wanted it mapped on `^` in gabc, to use as a replacement for ictus. Maybe we could reintegrate it as an alternative for `VEpisemus`? About FlexusNobar, many things are changing in the generation script and these might be used during the generation... Let's wait a few days before deciding.

**Comment by henryso** [comment]
AuctumDuplex is never used as far as I can tell, so I can remove that.

Circumflexus can be made a replacement for ictus.  Hopefully the positioning logic will make sense of it; otherwise we will need to fix it.

Regarding FlexusNobar, I understand that it may be used during generation, and actually I wasn't thinking of removing the primitives from the `.sfd` file, only that we should probably not generate them into the `.ttf` files (though in retrospect, I didn't make it particularly clear).  Do you agree with that?

**Comment by henryso** [comment]
Update: Apparently `FlexusNobar` one- and two-ambitus glyphs are used for measurement, so I will leave them for now.

**Comment by eroux** [comment]
Yes, let's keep it. Also, I cannot remember where I've seen this, but you were asking about `PunctumForMeasurement`, but it cannot be removed, as it has the length of `phigh`, used as the upper note of podatus, and the final noeXte of porrectus, but not present alone in the final font, and TeX needs if for measurment. In some fonts (Gregoria, but not only), it has a different width from basic punctum.

**Comment by henryso** [comment]
Changes are in #360 and ready for review.
