### ISSUE TITLE
Excluding glyphs from the documentation

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#376]
As we go forward, it looks like we will be adding more glyphs which are not accessible via gabc, such as the glyphs used for measurement.  I think these should be excluded from the documentation.  Do you agree?

**Comment by eroux** [comment]
indeed

**Comment by eroux** [comment]
This could be closed isn't it?

**Comment by henryso** [comment]
I'm left it open to do one more check after your latest changes.  I just haven't gotten around to it yet.

**Comment by henryso** [comment]
I'm thinking of excluding horizontal episemae.  There are a lot of them in the font, and I don't think they are particularly interesting in the glyph table.  What does everyone thing about this?

**Comment by eroux** [comment]
Agreed

**Comment by eschwab** [comment]
Fine by me.

**Comment by eroux** [comment]
Note: doc building is currently broken due to this issue (missing Hepisemus)

**Comment by henryso** [comment]
Yes. I will fix shortly.
