### ISSUE TITLE
Centralized Version Number

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#38]
Right now the version number is hard coded into several different files, making it difficult to update.  I think it would be nice if we could have a single text file which contains the current version number (and nothing else) and then have the various files which need the version number load it from there.  Is this possible?  A quick google search tells me that [Makefiles can import information from a file into a variable] (http://stackoverflow.com/questions/6767413/create-a-variable-in-a-makefile-by-reading-contents-of-another-file) (at least in theory, I haven't tested it) and InnoSetup (which creates the Windows installer) can do [something similar] (http://stackoverflow.com/questions/14530504/innosetup-how-to-declare-a-variable-by-reading-from-a-file).  I know from experience that python scripts can do so, and I assume that lua and C can as well.

Alternatively (or perhaps additionally if there are files which can't read the version number in themselves), a script could be written which would systematically replace the version number in all files where it appears.

**Comment by rpspringuel** [comment]
Oh, and it would also be nice if commits to the main project repository would trigger a webhook which would automatically increment the version number.

**Comment by eschwab** [comment]
Could pull the version number from the commit hash. Would not be a nice +1 increment though.

**Comment by rpspringuel** [comment]
The issue I see with a simple count is that it doesn't have any reset possibilities.

If we are at version number 2.4.1, then ideally the hook should increment the last, and only the last number, changing the version number to 2.4.2.  A subsequent commit should increment to 2.4.3, etc.  However, at some point we're going to want to manually increment one (or both) of the first two numbers and reset the third: e.g. 2.5.0.  A simple count would continue to increment the third number resulting in something like 2.5.4.  This, I think, would be unduly confusing.

You are right, though, that only commits to the master branch should matter (as your suggestion implies).

**Comment by eschwab** [comment]
Fixed by #48 and #51. Please close.
