### ISSUE TITLE
force vertical episemus placement top or below

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#385]
It would be useful to have `'0` and `'1` forcing placement of vertical episemus on top or below the corresponding note (reported on [the ancient bugtracker](https://gna.org/bugs/?22699)).

**Comment by henryso** [comment]
Now that we have the variant system in place, and with the circumflexus as an alternate glyph for the vertical episemus, should we have/use an inverted vertical episemus when it appears above?  An inverted vertical episemus using the default glyph would look the same, but possibly the alternate may need two forms?  A silly idea?

**Comment by henryso** [comment]
Any thoughts on this?

**Comment by eroux** [comment]
Oh sorry... I'm not sure the circumflexus would look nice reverted, what do you think? But maybe the normal vertical episemus could have two forms yes, not sure it would be noticeable without magnifying glass, but it would look nicer...

**Comment by rpspringuel** [comment]
If the circumflexus is supposed to flip when it appears above vs. below, then I'd say go for it.  It placement doesn't cause the circumflexus to flip, then I'd wait until someone requests that feature.

**Comment by henryso** [comment]
Ok, I will just implement this using the same glyph upper and lower until there is need to do otherwise.

**Comment by eroux** [comment]
For this kind of hesitations, I admit I never know what to do: for instance if we decide to change this in the future version, this means that the gtex output will slightly change, and that we thus have to go for a new major version... So sometimes I doubt modifcation of the gtex output is a right criteria... what do you think?

**Comment by henryso** [comment]
I originally thought major version is one for which there are backwards incompatible changes to the gabc syntax or to user commands in TeX.  However, we interpreted this to mean that if the gabc files need to be recompiled, then it would be a major version.  I can see the sense in both, and frankly, it doesn't matter too much to me either way, so I don't see a problem bumping up the major version if gabc files need to be recompiled or, on the on the opposite side, with requiring a recompile at the minor version number level.

**Comment by rpspringuel** [comment]
While I understood major version number as @eroux did, I think @henryso has a point.  With autocompiling, changes to the gtex don't necessarily need to be a major version change because they don't affect the user.  Perhaps, though, we should wait a while to let autocompiling take hold in the user base before doing that.

**Comment by eschwab** [comment]
A thought: If the new feature requires recompiling the gabc to use it, but no change if the user does not want the new feature, then no major version change.

If the new feature requires recompiling regardless if the user wants to use it or not, then major version change.

**Comment by henryso** [comment]
@eroux If we follow @eschwab's guideline, then adding the inverted vertical episema (if ever) would not be a major release.

**Comment by henryso** [comment]
Does this mean that you can have a vertical episema both above and below the same note at the same time?  It'll be somewhat more complicated if that's allowed, so I'll hold off on this until a decision is made.

**Comment by eroux** [comment]
@henryso I don't think having both is necessary, no...
