### ISSUE TITLE
punctum mora placement for notes on lines

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#386]
On the ancient bugtracker, there is [an issue with punctum mora placements](https://gna.org/bugs/?21917). I'm thinking about several solutions:

- just fix the punctum mora after the torculus
- allow `.0` and `.1` to force the placement up or down
- add an option in TeX for this (but it might be complex due to many cases)

**Comment by henryso** [comment]
Any further thoughts on the solution?

**Comment by eroux** [comment]
I think combining 1. and 2. would be good... what do you think?

**Comment by eroux** [comment]
Note that there is also https://gna.org/bugs/?21737 on the old tracker...

**Comment by henryso** [comment]
I'll see if I can figure it out from this.

**Comment by henryso** [comment]
How does `.0` and `.1` interact with `..`?  The first `.` is the most recent note and the second `.` is the prior note?  So for `hf.0.1`, the `.0` would apply to `f` and the `.1` would apply to `h`, or the other way around?

**Comment by eroux** [comment]
Good question... I admit I wouldn't have done it with two punctum, but if it's not too complex then, I think your second solution (*the other way around*) is a bit more clear...

**Comment by henryso** [comment]
It does make things simpler to ignore the suffix(es) with `..`, and the question of which dot is which becomes moot, so I will only handle the suffix with a single `.`.

**Comment by eroux** [comment]
That's fine for me, it's supposed to be something simple to accommodate some rare styles or particular cases, not a complete convoluted feature, so let's ignore placements for `..`. If some use cases of different placements of `..` for some neumes/styles pop up, we'll treat them later.
