### ISSUE TITLE
Automatic Decision on inclusion of hyphen not correct

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#388]
Reported by a user to developers mailing list:

>But, preparing in advance the scores for Pentecost, I noticed some glitches with the spacing among syllables, where the "-" signal should have been inserted automatically. I had to do this by hand.
   I hope not to bother with and example of the problem in Scribus...
>
>   I just managed to prepare a MWE in pure gabc. If you play with the value of \setgrefactor{} the problem can manifest in other words. With 16 it's in La va, 3rd line, with 15 it´s in Ri ga, and worse than before.

  
>   Second problem:
>   In the gloria, look for the Qui sedes, the torculus (Qui) shape is incomplete in the vertical line. In this sample the first problem appears again, at Al tis si-mus.

Looking at his examples, it appears that the problem occurs on syllables under narrow neumes.  What I think might be happening, though I'm only guessing, is that when the line gets justified, a space which was too small for the hyphen is getting opened up and now should require a hyphen.  Not sure how one might go about fixing that.

**Comment by eroux** [comment]
Not sure it's really doable... You can advise to make minimalspacewithouthyphen (or whatever the name) shorter, but I don't think there's a costless definitive solution to that... 4.0 should be better on this point though.

**Comment by rpspringuel** [comment]
That was my advice.

**Comment by jakubjelinek** [comment]
I've run into this too (with develop https://github.com/gregorio-project/gregorio/commit/28b6cc3 ), e.g. what used to look like
![1](https://cloud.githubusercontent.com/assets/9370665/7549374/38f05540-f632-11e4-95df-0e34d87c99df.png)
4 months ago now looks like:
![2](https://cloud.githubusercontent.com/assets/9370665/7549377/4812b14e-f632-11e4-8d4e-f945f58c1af5.png)
and it happens pretty much everywhere on short syllables with shorter notes above them.

**Comment by eroux** [comment]
Can you please try with a more recent develop? Things changed quite heavily since the commit you're talking about

**Comment by jakubjelinek** [comment]
Current develop has the problem fixed indeed (had to port the nabc patch again, the code is changing very rapidly).  Thanks.
