### ISSUE TITLE
Thick version of horizontal episemus?

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#393]
Looking at Gregoria, there is a huge difference in how the horizontal and vertical episemus look. It's easy to switch to Greciliae's vertical episemus in TeX thanx to the new macros made by Henry, but horizontal episemus is a different thing... In Gregoria it is much thiner. What I'm thinking about would be to make a thin version of horizontal episemus in Greciliae, and a thick version of horizontal episemus in Gregoria4o, plus some macros to switch from one thickness to another. Like this gregoria4o would still be Gregoria, but it would be easy to make things look closer to the usual Gregorio output (which is a better better, but it's just my opinion). It doesn't seem to be much work. What do you think?

**Comment by henryso** [comment]
Sounds like a good idea to me.

**Comment by rpspringuel** [comment]
As long as they are clearly documented, more options are always better for me.

**Comment by eroux** [comment]
(I'm just waiting for answers from Elena Albertoni before going on)

**Comment by henryso** [comment]
If Elena Albertoni is not responding, should we table (or cancel) this issue?

**Comment by eroux** [comment]
Let's postpone it (removing the milestone)

**Comment by eroux** [comment]
Closing due to lack of answer by Elena Albertoni, I'll reopen when it becomes relevant again.
