### ISSUE TITLE
<eu> block and finalis

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#396]
#371 gives `<eu>E(i) u(i) o(i) u(h) a(h) e</eu>(fe..) (::)` as the good syntax for `<eu>` blocks ; but in some rare cases, this gives bad output where the final bar is on a new line ; the bug isn't present when not closing the `<eu>` block at the end of the piece.
![euouae](https://cloud.githubusercontent.com/assets/4775231/7553558/f1d372a0-f6fe-11e4-85e7-666e4f5754a5.png)

*mwe.tex* : 

    \documentclass[a3paper,42pt,DIV=17]{scrartcl}
    
    \usepackage[autocompile]{gregoriotex}
    \usepackage{libertine}
    \pagestyle{empty}
    \setgrefactor{40}
    
    \begin{document}
        \includescore{test}
    \end{document}

*test.gabc* : 

    name:Cantémus Dómino;
    initial-style:1;
    %%
    (c3) CAN(df~)té(fef)mus(d) Dó(fh)mi(f)no :(ff) *(;)
    glo(h)ri(g)ó(hih)se(fe) e(hhh)nim(h.) (,) ma(hf)gní(hji)fi(h_g)cá(hji)tus(h_g) est.(hhh!/fgf___.) (:)
    
    For(f)ti(ef)tú(d!e'f)do(f) me(fefd)a,(d.) (,) et(d) laus(efe) me(f!g'h)a(hie'!f) Dó(fe)mi(h)nus,(hif___.) (;)
    et(f) fa(hh)ctus(h) est(hi) mi(igh)hi(gf..) (,) in(d) sa(ef)lú(fhF'EfvED'e)tem.(ed..) (::)
    
    <i><c>T.P.</c></i>
    Al(df~)le(fef)lú(hf!/hhh)ia,(hiHF.) (,) al(ef)le(gxfhe___!fw!gvFE)lú(de!fvED'e)ia.(ed..) (::)
    
    <i><c>Ps.</c></i> Can(d)tá(f)te(h) Dó(h)mi(h)no(h) cán(h)ti(h)cum(i) no(i)vum :(h.) *(:)
    qui(f)a(h) mi(h)ra(h)bí(i)li(g)a(g) fe(h)cit.(f.) (::)
    
    Gló(d)ri(f)a(h) Pa(h)tri.(h) (::) <eu> E(h) u(h) o(i) u(g) a(h) e.</eu>(fefvEDe.) (::)

**Comment by eroux** [comment]
What's the output with 

    <eu> E(h) u(h) o(i) u(g) a(h) e.(fefvEDe.) </eu>(::)

?

**Comment by eroux** [comment]
This is a bug anyway, as a bar is never supposed to appear at the beginning of a line, I shall inspect that

**Comment by jperon** [comment]
There's no problem with `<eu> E(h) u(h) o(i) u(g) a(h) e.(fefvEDe.)
</eu>(::)`.

2015-05-10 11:28 GMT+02:00 Elie Roux <notifications@github.com>:

**Comment by henryso** [comment]
The fix for this is pull request #527.  Please review.
