### ISSUE TITLE
short horizontal episemus

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#40]
In order for many horizontal episemus to render correctly, it would be useful to introduce a new feature (that will actually be used in some new books): horizontal episemus with 2/3 width. For instance, `gd_` would use this (not automatically).

These horizontal episemus would be left-aligned, right-aligned or centered, according to the wish of the user. They could be noted by 

 * `_1` for left-aligned
 * `_2` for right-aligned
 * `_3` for centered

and they would have a width corresponding to 2/3 of the width they have now, which is proportional to the note they are above (or under).

These short episemus can also be under the notes, in which case they are noted `_01`, `_02` and `_03`.

The episemus are combined like other episemus in certain cases: left-aligned short episemus, it combines with the episemus on the left, and right-aligned short episemus combine with episemus on the right.

**Comment by olivierberten** [comment]
In some exotic cases, some fine-tuning would be useful:
* episemae on repeated notes: http://gregobase.selapa.net/chant.php?id=2282
* episemae not extending to the last note of a porrectus: http://gregobase.selapa.net/chant.php?id=1329

This proposal would fix the first issue but I don't know how to fix the latter one...

**Comment by eroux** [comment]
@olivierberten I admit I don't understand at all :) Can you give the line number (in the printed score on gregobase) and the gabc code of the problems?

**Comment by olivierberten** [comment]
For the first example, it is on the 3rd line of LU and 4th of gregobase, on the word "calceamenta". The original scores has 2 distinct episemae, while gregorio puts only a big one.

The second one is on the 6th line of the 2nd page of GR, and 8th line of gregobase, on the word "Ita". The episemus stops before the last note of the porrectus, which is afaik impossible to achieve with gabc...

**Comment by eroux** [comment]
Oh, thanx! Did you update the scores since I reduced horizontal episemus size (a few weeks ago)? It might have dealt with the first prolem... About the second, it's interesting, but quite unrelated to this issue (though it might be solved at the same time. I've opened a [separate issue](https://github.com/gregorio-project/gregorio/issues/70) for it.

**Comment by henryso** [comment]
How would this work for larger neumes like porrectus or torculus resupius flexus?

**Comment by eroux** [comment]
I guess so... the feature is really not about them, but I guess just mimicking the others will be ok

**Comment by eroux** [comment]
Well, doing some testing, I'm affraid this feature will be a bit more complex than expected, as the point of the feature is to be able to do something like `g_1ig` where the first episemus would be on the top of the first note. In the current state, `g_ig` puts the episemus at the bottom of the first note, because it would look odd on the top, but it's not the case with a left-aligned small episemus... So the width is not the only difference... I don't really know how to handle that, should we add something to force an episemus on the top of the note? That might be the best option for users, as all users are not happy of the algorithm deciding if an episemus should go at the bottom or on the top of a note... What do you think?

**Comment by eroux** [comment]
Maybe something like:

- hepisemus_prefix = `_` for automatic placement, `_0` for bottom, `_1` for up
- hepisemus_suffix = nothing for normal, `1` for small aligned left, `2` for small centered, `3` for small aligned right, `4` to prevent bridge

?

**Comment by jperon** [comment]
I'd fully welcome such a feature !

2015-05-08 10:37 GMT+02:00 Elie Roux <notifications@github.com>:

**Comment by eroux** [comment]
And maybe using h_episemus_type a bit better, like 2 bits for placement (bottom, up, auto), 3 bits for the new types (small left,, etc.) and 5 bits for the current types would be enough... But that's up to you

**Comment by henryso** [comment]
`4` prevent bridge would be left aligned?  center aligned?  I admit I don't fully understand the implications of preventing the bridge yet.

**Comment by henryso** [comment]
Never mind ... I misunderstood about `4`, but then the question is, do we need left/center-aligned small preventing bridge, or does left/center small imply preventing the bridge?

**Comment by eroux** [comment]
left/center prevent bridges and also should not be taken into consideration when computing the highest or lowest note. For instance `g_11h_1g` should produce episemus with different height, but `g_13h1g` shoud put them at the same height... do you see what I mean?

**Comment by henryso** [comment]
Ok, I understand.  Thanks.

**Comment by eroux** [comment]
Hmm... the case I just described will look stupid due to the episemus being in the same line interval, but  `g_11i_1g` vs `g_13i_1g` is more interesting, as it is for this kind of case that the feature has been asked. (the previous case is still valid, but this one is more interesting)

**Comment by henryso** [comment]
Is there any need for automatic placement and small episema or are you required to use manual placement when using a small episemus?

**Comment by eroux** [comment]
Good point... I don't have strong opinion on this, but it I think the best solution is not to use automatic placement, maybe with a default (top), as automatic placement would be different and would require to rewrite the (certainly quite bloated) positioning algorithm... What do you think?

**Comment by henryso** [comment]
I don't have a strong opinion either.  My question was more technical.  According to the (newer) rules above, `_1` could either mean a normal sized episemus placed above or a small left-aligned episemus placed automatically.

**Comment by eroux** [comment]
Oh right, let's start suffixes with 2 if that's ok to you

**Comment by henryso** [comment]
Clever!

**Comment by eroux** [comment]
What do you think about doing #385 (and maybe #386) at the same time? It will certainly be on the same code...

**Comment by henryso** [comment]
I'll give it a shot.

**Comment by eroux** [comment]
Thanx a lot! These are also features that have been requested for quite a long time...

**Comment by henryso** [comment]
How does this sound?

- No suffix to `_` indicates a horizontal episemus, full size, bridges enabled, with automatic vertical placement.
- `0` force vertical placement below the note
- `1` force vertical placement above the note
- `2` disable bridges
- `3` use a small episemus, aligned left
- `4` use a small episemus, aligned center
- `5` use a small episemus, aligned right

These may be specified in any order.  However `0` and `1` are mutually exclusive and `3`, `4`, and `5` are mutually exclusive.  If more than one mutually exclusive suffix is added, the last one takes precedence.  `2` only really has effect against no suffix and `5`.  Thus to have a right aligned small episemus with bridged disabled and force-placed above the node, use `_521`.

**Comment by eroux** [comment]
Ok!

**Comment by henryso** [comment]
Can a bridge cross syllables?

**Comment by eroux** [comment]
Well, theoretically yes, but I think that would be pretty hard to implement, as we don't know the space between syllables, while the space between neumes is much easier to compute... So I think we can  stick to bridges inside syllables for now...

**Comment by henryso** [comment]
if an episema is *not* bridged to the following episema, should they still be at the same height or can they be at different heights depending on the notes they decorate?  Or should I allow both, depending on whether or not `2` is specified?

**Comment by eroux** [comment]
Hmm, I'd say they can be different height... but I admit I don't see any real use case... I let you choose

**Comment by eroux** [comment]
In #395, @jperon raises an interesting case not handled by Gregorio: in the case of `ghg_`, there are two changes that need to be done:

- the last episemus should be above, not below when automatically detected (this should be straightforward
- the last episemus should consider that it's above `h`, not `g` if it's a normal episemus, but not if if's right-aligned or centered small episemus

Does it sound reasonable? (should I open a new issue for it?)

**Comment by henryso** [comment]
I'm waist-deep in the positioning code and am keeping all these things in mind (or at least trying to).  Having both below could push the horizontal episema three levels below `a` vertically.  Do you think the TeX will handle this easily?

**Comment by eroux** [comment]
I don't think it's a big deal... it should just be checked by the function that defines the lowest level, adding a new level, but it should be simple

**Comment by eroux** [comment]
Anyway, thanks a lot for taking care of that, this is really not simple (much more complex than I originally thought!), but it will improve many scores and make the life of many users better!

**Comment by henryso** [comment]
The current gregorio lets you do weird stuff like g_0_h_g_0_, which produces something that looks like
```
------
  ##
##  ##
--  --
```
The new implementation will not allow a single note to have two episemae.  I don't think this is too much of a restriction, but let me know.  It'll be quite a bit of rework to implement this.

**Comment by henryso** [comment]
Another interesting case: `(h_/gh_)`.  The old code would produce
```
------
##  ##
      ;
    ##
```

The rewrite will note join the `h`'s because it's not a continuous episema, and will instead produce
```
--  --
##  ##
      ;
    ##

However, `(gh_/h_)` will produce
------
##  ##
  ;
##
```

... because of the continuity.

This one will be a weird one to detect, so I'm going to leave it out until someone comes looking for it.

**Comment by jakubjelinek** [comment]
Two horizontal episemae actually happens in the liturgical books quite often, longer bar above with say only one of the notes stressed under.  If needed, I can look up examples.

**Comment by eroux** [comment]
Indeed, `(g_0_h_g_0_)` and `(h_/gh_)` needs to continue to work... Sorry :( I'll help you on that.

**Comment by jakubjelinek** [comment]
TRi(d)bus(c) mi(d!ewf)rá(f_0gF'___ED/eed)cu(cd)lis(d.)
is a real-world example from Antiphonale Monasticum 1933, p. 296.  The upper horizontal episemus is above the pes and first subpuncta, small episemus below the pes and ictus below first subpuncta.

**Comment by eroux** [comment]
@jakubjelinek thanks a lot for your research!

**Comment by olivierberten** [comment]
FYI, they changed it in the Liber Usualis: http://gregobase.selapa.net/chant.php?id=2199

**Comment by eroux** [comment]
Well, these would still be representable with the current state... But I'm quite sure I've seen something with a torculus... I'll continue looking.

**Comment by henryso** [comment]
Given what was mentioned in #401, is it satisfactory to require `(g_0_1h_g_0_1)` or must I somehow make `(g_0_h_g_0_)` work?  Stuff like `(f_0gF'___ED/eed)` (from @jakubjelinek, above) would need to change to `(f_0_1gF'__ED/eed)` as well.  If I need to make this work, then please help me define rules to disambiguate the bare `_`.  Does it mean to add whichever second episema is not already set?

**Comment by eroux** [comment]
I think a way to make it work the same as previous is: when encountering a bare `_`, if there is already an automatic or forced top episemus on last note, add an automatic on the note before, or if the note before already has one, on the note before it, etc. Would that work?

**Comment by eroux** [comment]
Coming back to this (not sure it's the right place). I've asked for some real-life use cases of short episemus and everything works fine! So well done, thanks!

The tests are:

`(ivH_4GF) (gf_15f_d_!ewf_) (gf_15E_D_ewf_ED) (h_g_3!hwi) (hih_15)`

Doing these tests, it would seem more practical if the small episemi were always on top of the notes, and not automatically determined (as if implying `1`)... Do you think it would be a good idea? I would tend to think it would, but I'm not really sure...

**Comment by henryso** [comment]
I can't say if default to above for small episemae is more correct/better or not, but I would be happy to make this change once we agree upon the approach.
