### ISSUE TITLE
make distcheck fails in develop

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#412]
Upon running `make distcheck`, it fails with the following error:
```
ERROR: files left in build directory after distclean:
./doc/GregorioRef-3_0_0.pdf
./doc/GregorioNabcRef-3_0_0.pdf
Makefile:629: recipe for target 'distcleancheck' failed
make[1]: *** [distcleancheck] Error 1
make[1]: Leaving directory '/home/inxi/develop/gregorio/gregorio-3.0.0/_build'
Makefile:557: recipe for target 'distcheck' failed
```

However, these files should be rightly(?) left behind since they are only cleaned with `maintainer-clean`.  I think I'm at the limits of my autotools understanding to fix this issue.

**Comment by henryso** [comment]
Ok, this is happening because GregorioRef and GregorioNabcRef depend on gtex files.  I thought I fixed this before, but it somehow got unfixed, so I'm going to refix it.

**Comment by rpspringuel** [comment]
It may be that when I merged master into develop I accidentally unfixed it.  I don't remember messing with the Makefiles in doing that, but I accidentally messed up some other things, so maybe I did something here without realizing it.

**Comment by henryso** [comment]
No I think it was unfixed in merging the nabc reference.
