### ISSUE TITLE
Episema beneath scandicus

### ISSUE THREAD

**Issue by rarty** [gregorio-project/gregorio#419]
I've been testing the developer build against some outstanding issues I've noted in my scores. The new episema code is working quite well!

Here is a case of the correct episema not appearing as expected, but perhaps this case wasn't foreseen, as I don't see it in any of the tests (I don't think the scandicus is completetest.gabc).

The expected result, (from [Scriptum est enim percutiam](http://gregobase.selapa.net/chant.php?id=2162) as in the Liber Usualis):
![screen shot 2015-05-15 at 1 01 09 pm](https://cloud.githubusercontent.com/assets/6454162/7658759/841a4ace-fb02-11e4-8df5-5af35e3ac34e.png)

The episema only partially appears:

    au(j_0k_0l)tem(k.)

![screen shot 2015-05-15 at 12 58 57 pm](https://cloud.githubusercontent.com/assets/6454162/7658742/50ae1116-fb02-11e4-9cf6-1b4dd76e72e2.png)

The correct episema appears, but with a strange duplication on the second note:

    au(j_0!k_0l)tem(k.)

![screen shot 2015-05-15 at 12 43 06 pm](https://cloud.githubusercontent.com/assets/6454162/7658743/56c23ec4-fb02-11e4-9140-c1bb36fda2ee.png)

**Comment by henryso** [comment]
@rarty Please type `gregorio -V` into a command prompt or shell and paste the result here.

**Comment by rarty** [comment]
This is from `3.0.0-develop-9a387b6-1`.

**Comment by henryso** [comment]
I can fix `(j_0k_0l)`.  It's actually an incorrect position number chosen for the second note in the scandicus.  However, I need help with the second.  The GregorioTex produced is:
```
\gresyllable{}{au}{}{0}{\gresetnextsyllable{t}{e}{m}}{}{0}{}{%
\greglyph{\grecpPunctum}{j}{k}{0}{}{%
\grehepisemusbridge{i}{}{}%
\grehepisemus{i}{0}{0}{1}{f}{i}%
}%
\greendofglyph{1}%
\greglyph{\grecpPesOneNothing}{k}{k}{0}%
{%
\greadditionalline{18}{0}{2}%
}{%
\grehepisemus{i}{0}{0}{1}{f}{i}%
}%
}%
```
From my limited understanding, the `\grehepisemusbridge` is at the right height.  However, it is drawn a bit higher than it should be.  Is gregorio passing the correct thing?  What should I make it pass instead?

**Comment by henryso** [comment]
Typing that actually gave me a clue.  Maybe I can actually figure this out...

**Comment by henryso** [comment]
This is ready for review and merge.
