### ISSUE TITLE
first syllable alignment when vowel after initial

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#42]
The alignment of first syllable text/neume should be improved when it contains a vowel

Currently, the alignment is made on the first letter after the the first one (which is the initial), in all cases (as was asked at the creation of Gregorio). The following behavior should be implemented:

 * when there is no vowel after the first letter (which is the initial), keep current behavior (alignment on first letter after the initial)
 * if there is a vowel in the letters after the first, align as if it was a regular syllable (ex: initial `C`, other letters `hri`, in this case the alignment is on the `i`)

**Comment by henryso** [comment]
This should be fixed along with #135 in `develop`.
