### ISSUE TITLE
5-line staff

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#429]
Some people requested to be able to work on five lines. It could be an option in TeX.

A difficulty is that in gabc, `o` already means oriscus, so it can't mean the letter above `n`... Maybe `o0` would be acceptable...

**Comment by henryso** [comment]
How about `n` and `p` ?

**Comment by jakubjelinek** [comment]
Yeah, I'd say n and p would be better.

**Comment by eroux** [comment]
ok

**Comment by henryso** [comment]
If we do five lines, may I request the ability to handle two and three lines as well?

**Comment by eroux** [comment]
sure!

**Comment by henryso** [comment]
How do we handle the various bars for 5, 3, or 2 lines?  Create a bunch of glyphs for them?  How do we position the divisio minor for each of the above?  How about the Dominican bars?

**Comment by eroux** [comment]
I think we can create glyphs for divisio maior for the different number of bars, maybe also create a divisio minor for 5 lines. I don't really know the answer for the way divisio minor and dominican bars should look... I think it would look nice if we keep the same distance with top line and bottom line, making the bar taller (for 5 lines), but I'm not 100% sure... For 2 or 3 lines I really don't know...
