### ISSUE TITLE
Last line of Score alignment

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#43]
Currently the last line of a score is always set ragged.  It should be possible to manually override this in either the gabc or TeX so that the last line is justified.  It is possible to get this effect by messing around in the gtex file currently.

1) End your score with just `(z)`.

2) Run the score through gregorio and open the generated gtex file.

3) At the end of the file you'll see something like this (I've removed empty lines to save space):

> \grebarsyllable{}{}{}{1}{\gresetnextsyllable{}{}{}}{}{0}{%
> \grelastofline %
> }{%
> \gredivisiofinalis{}%
> }%
> \grenewline %
> \endgregorioscore %
> \endinput %

Modify this by changing `\grelastofline` to `\grelastofscore` and moving `\grenewline` to be right after `\gredivisiofinalis{}`.  You should end up with something like the following:

> \grebarsyllable{}{}{}{1}{\gresetnextsyllable{}{}{}}{}{0}{%
> \grelastofscore %
> }{%
> \gredivisiofinalis{}%
> \grenewline %
> }%
> \endgregorioscore %
> \endinput %

4) Now typeset the main document that includes this score and you should get the divisio finalis all the way to the right hand side of the score and the neumes spaced to fill the line.

I think that there should either be a TeX switch that adds code to `\grefinaldivisiofinalis{0}` (what you usually get for the last syllable you end your gabc with `(::)`) or gregorio should recognize `(::z)` as requiring that code.

Note: Adding `\grenewline` to between lines 1534 and 1536 of `gregoriotex-signs.tex` has the desired effect.  All that's needed is a switch. 

Also, are there ever occasions when `\grefinaldivisiofianlis{0}` doesn't end the score?  My quick testing didn't reveal any.  If this is true, then `\grelastofline` in this function should be changed to `\grelastofscore` (though it doesn't seem to have any visible effect in my testing).

**Comment by henryso** [comment]
I have a few projects where I break up the longer work into multiple scores.  In some cases, they end with (:), which results in `\grefinaldivisiomaior{0}` rather than `\grefinaldivisiofinalis{0}`.

**Comment by rpspringuel** [comment]
Sorry, what I meant was are there any occasions where there are other elements after `\grefinaldivisiofinalis{0}`?  I fully expect it to not appear at all in scores which don't end with a divisio finalis.  What I'm concerned about are occasions where it might appear in the middle of a score.

**Comment by henryso** [comment]
The gregorio executable is engineered so that no normal elements can occur after `\grefinaldivisiofinalis{0}` or `\grefinaldivisiomaior{0}`.  However, "texverb" items (and faked "texverb" items) can appear afterward, such as a manual custos.
```
%%
(c4) e(e) (::f+)
```
produces
```
% File generated by gregorio 4.0.0-rc1-font-naming-consistency-8f038bb-1736
\gregoriotexapiversion{4.0.0-rc1}%
\begingregorioscore%
\greinitial{e}%
\grebeginnotes %
\gresetinitialclef{c}{4}{a}%
\gresyllable{}{}{}{1}{\gresetnextsyllable{}{}{}}{}{12}{}{%
\greglyph{\grecpPunctum}{e}{g}{0}{}{}%
}%
%
\grefinaldivisiofinalis{0}%
% verbatim text at element level:
\gremanualcusto{f}%
% end of verbatim text
\endgregorioscore %
\endinput %
```

**Comment by henryso** [comment]
Note: in the current develop, this will produce
```
...
\grefinaldivisiofinalis{%
\gremanualcusto{f}%
}%
\endgregorioscore %
\endinput %
```
