### ISSUE TITLE
pilcrow symbol

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#430]
Pilcrows are rarely used but it would be good to have a nice-looking pilcrow symbol with <sp>para</sp>, unicode ¶ should remain the pilcrow symbol of current font... Or maybe the \gresympara macro should just display pilcrow of current font but raised a little?

**Comment by henryso** [comment]
How would this be used (why would the unicode pilcrow need to be raised)?

**Comment by eroux** [comment]
Well, this comes from the old tracker, I admit I've lost the context, and I can't remember who asked this... So question: would that be useful?
