### ISSUE TITLE
Uncoherent file versions gregoriotex.tex/greciliae.ttf

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#437]
Here is what I get with `build-deb.sh` on 5675cc8 : 

    ! LuaTeX error ./../tex/gregoriotex.lua:306: Module gregoriotex error: 
    (gregoriotex)             Uncoherent file versions!
    (gregoriotex)             gregoriotex.tex is version 3.0.1
    (gregoriotex)             while greciliae.ttf is version 3.0.0
    (gregoriotex)             please update file
    (gregoriotex)             ./../fonts/greciliae.ttf
    
    stack traceback:
    	[C]: in function 'error'
    	...re/texlive/texmf-dist/tex/luatex/luatexbase/modutils.lua:26: in function 'mo
    dule_error_int'
    	...re/texlive/texmf-dist/tex/luatex/luatexbase/modutils.lua:49: in function 'er
    r'
    	./../tex/gregoriotex.lua:306: in function 'check_font_version'
    	[\directlua]:1: in main chunk.
    \setgregoriofont ...the \gre@count@temp@three ]])}
                                                      }\relax 
    l.4 \begingregorioscore
                         %
    ?

If I ignore the error and try a second time, it works.

**Comment by henryso** [comment]
This is happening because the fonts Makefile is not depending on something that gets updated when the version number changes.  @eschwab what is the right file to depend upon?

**Comment by henryso** [comment]
@jperon to resolve your immediate problem, you'll have to rebuild the fonts.  Try deleting `fonts/*.ttf` and rebuild.  Once I know what to depend upon, I should be able to fix this systemically.

**Comment by eschwab** [comment]
Depending on `.gregorio-version` is fine, it should only change with version changes.

**Comment by henryso** [comment]
@eschwab Thanks.

The fix is ready for review.
