### ISSUE TITLE
Set lines above initial in the gabc file.

### ISSUE THREAD

**Issue by eschwab** [gregorio-project/gregorio#44]
The `gabc` file should be able to set the two lines above the initial.

I have been looking into adding this feature. Currently there can be two `annotation: :` fields in the `gabc` header but they are associated with `voice_info`. Rather than hijack these, perhaps rename `mode: ;` to `modelineone: ;` and add `modelinetwo: ;` For `\gresetfirstlineaboveinitial` and `\gresetsecondlineaboveinitial` respectively.

What is the intended/future use for `annotation: ;`?

**Comment by eroux** [comment]
The best solution is to make annotation global (and not voice_info dependant), and use it. For nabc, there is also a annotation_nabc that will most certainly appear.

**Comment by rpspringuel** [comment]
I agree that the annotation fields should be fixed.

One thing that might make things easier is a rewrite of the setannotation interface that I've been thinking about.  Right now there are two different annotation boxes, one for the first and one for the second, which are filled by separate commands.  My idea was to create a single annotation box to which lines could be added by successive calls of the same function.  In this fashion there's less to keep track of when writing information from the gabc into the gtex.

The idea came to me some months ago while working on `texrenaming` in gregoriotex.tex and I think I left myself some notes there in the form of a comment labeled TODO.

**Comment by eschwab** [comment]
First there should be an improved annotation setting macro in TeX. See [this idea](https://mail.gna.org/public/gregorio-devel/2014-05/msg00027.html) from @rpspringuel 

Then however that works out, the gabc should be able to set the annotation with full formatting control i.e. `annotation:\color{red}\emph{H}.\color{black}II;`

**Comment by eroux** [comment]
Apart from the fact that `\color{red}H\color{black}` is anti-pattern and should be replaced by `{\color{red}H}`, I admit I'm not particularly keen on having too much TeX in gabc... But I also admit it's just practical, and I don't think it would be reasonable (from a development resource point of view) to have some kind of markdown parsing in the gabc headers, so I don't disagree on this.

**Comment by jperon** [comment]
Just a thought about that : to help one separate style and content, I think that approach should remain optional, and, if `modelineone` and `modelinetwo` are added, `mode` should remain (without any effect on the final output).

**Comment by rpspringuel** [comment]
The revamp to a single annotation function that I talked about is now in #476.  This should make it much easier to implement this carry-over.
