### ISSUE TITLE
unique id of score

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#441]
It would be necessary for #59 (and possible other future features) to have a unique identifier of the score, to write some info in the .aux file. I thought about a few things:

- using lua md5 library (packaged in LuaTeX) to get a md5 hash on the gabc file. The problem is that if you include the same score twice, you'll get twice the same id, which is not always what you want (if you include it in different `\hsize` formats. There could be a check when computing the md5 hash, to know if there was already one though...
- make Gregorio write a random ID in the `.gtex` file, that would change at each compilation. This would be a bit simpler, but wouldn't work if the score is included with the "force compile" option. But that would be more efficient, and we can make #59 not compatible with the force option

What do you think?

**Comment by jperon** [comment]
What about using first option, but adding an optional argument (`id` for example) to \includescore, that would "salt" the md5 ? It would then be possible to have #59 compatible with the force option, while letting users with more advanced needs change `\hsize`.

**Comment by eroux** [comment]
that seems a good idea, thanx!

**Comment by jakubjelinek** [comment]
Wouldn't just a simple counter, bumped at the end of each includescore, be enough for this?
Those should be the same between two consecutive lualatex invocations on the same source.

**Comment by eroux** [comment]
yes, but this would mean you would have to recompute the infos at each pass, whereas with this solution you don't have to... That may look like misplaced optimization, but I'm not sure about the performance penalty of the pass gathering information on scores...

**Comment by rpspringuel** [comment]
@eroux, can you explain in a bit more detail what you mean?  Wouldn't you have to recompute the md5 hash each run in order to match score specific variables in the aux file to their respective scores?

**Comment by jakubjelinek** [comment]
You could use that counter as kind of array index when caching that computation in the *.aux file and again when reading it back from there.  So pretty much the same as the md5/sha or any other hash, or uuid, just it wouldn't be a constant you could put directly into the *.gtex file, but instead you'd use \the\some_counter or what's the exact syntax to query the counter value.

**Comment by eroux** [comment]
No, wouldn't have to recompute the informations on the lowest and highest notes for each line of the score

**Comment by eroux** [comment]
@jakubjelinek : suppose the user compiles a doc with score A then score B, we have score A with counter == 1, score B with counter == 2. Now users inserts score C between scores A and B, we have counter == 1 for A, counter == 2 for C, counter == 3 for B, so all spaces are mixed up... That means each compilation must recompile all infos of each score in order to be consistent...

**Comment by jakubjelinek** [comment]
@eroux : ah, but that is not the same source, but different source, using old *.aux file.  If that needs to be supported, sure, using some uuid plus the counter and using a pair of the uuid of the *.gtex file and counter (either separate counter for each uuid, or global counter, the latter would need to recompute whenever you add any includescore before some existing one) might work.  But will it catch changes like gresetfactor changing, or various other gregorioTeX macros changed from one invocation to another one?

**Comment by eroux** [comment]
You're right, it wouldn't detect that... So maybe there would be an optimistic mode, more efficient (not default) and a pessimistic mode recomputing everything all the time...

Globally, the idea is to save all highest and lowest notes for each glyph (after the parbuilder has passed, so globally after almost everything is ready to be shipped in the pdf), saving it in the .aux file, and then reusing it in the next compilation.

**Comment by rpspringuel** [comment]
I wouldn't mind the more efficient mode being the default, so long as there was some mechanism for detecting a source code change since the last compilation and outputing a warning when such a change has been detected (much like the warning about cross references).  Unfortunately, we've got a more complicated situation since we need to check for changes across several files (both tex and gabc).
