### ISSUE TITLE
LuaLatex hangs while loading gregoriotex.lua

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#442]
This bug appeared today. Here is the output I get : I guess there must be a syntax error within `gregoriotex.lua`, but I don't know where…

    (/usr/share/texmf/tex/luatex/gregoriotex/gregoriotex-main.tex
    (/usr/share/texmf/tex/luatex/gregoriotex/gregoriotex.lua)
    lua>

**Comment by rpspringuel** [comment]
What branch and commit are you at when you see this bug?

If you went through a full installation process, you can get this information from `gregorio --version`.

**Comment by jperon** [comment]
I'm on `develop` branch. Looking further, it seems `gregoriotex-signs.lua` doesn't get included within the debian package when running `build-deb.sh` : after copying it manually in texmf and running `texhash`, it works again.

**Comment by rpspringuel** [comment]
I assume you mean `gregoriotex-signs.tex`.

As for the fix, I'll let @henryso handle that since he's already assigned it to himself.

**Comment by henryso** [comment]
No, he means gregoriotex-signs.lua.  It's missing from the Makefile.

**Comment by rpspringuel** [comment]
Huh.  I hadn't noticed that file before.  When did it get added?

**Comment by henryso** [comment]
I added it last Saturday as part of decoupling the note position offset case numbers from the gregorio executable.

**Comment by rpspringuel** [comment]
Sometimes it's hard to keep up with all the changes.  At least it's a recent addition and I haven't been totally out of it.

Carry on.

**Comment by henryso** [comment]
@jperon 6eb21f688ff4ed240b8d073d8e9c9e76438064de should fix it.  Would you please try it again when you have the chance?

**Comment by jperon** [comment]
Just tried, and it works like a charm. So I close this issue.
