### ISSUE TITLE
Separating PlainTeX and LaTeX definitions.

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#445]
The way things currently work, if the definition of a function should differ in PlainTeX and LaTeX, then the PlainTeX version is defined in `gregoriotex-xxx.tex` (usually `gregoriotex-main.tex`) and `gregoriotex.sty` redefines the function to have it's LaTeX meaning.  This is a legacy of when most of these functions were defined in `gregoriotex.tex`.

Having converted `gregoriotex.tex` to a specifically PlainTeX bootstrap loader, I think it makes more sense to move PlainTeX specific definitions to this file.  In this fashion each function would be defined only once and in the form appropriate to the variety of TeX being used.

Opinions?

Note: if we implement this I'll make the changes as I come across these functions on texrenaming.

**Comment by henryso** [comment]
Can you give a couple of examples of these functions?

**Comment by rpspringuel** [comment]
The most common ones are the font modifiers: `\grebold`, `\greitalic`, `\grecolored`, etc.

Several of the formatting functions also have this happening (in particular those for the initials, the above line text, and the automatic mode insertion.

Look at `gregoriotex.sty` for a complete list of functions which currently have this behavior (they appear below `%% We now redefine some things in a more LaTeX friendly way.`)

**Comment by henryso** [comment]
In that case, I agree with this proposal.

**Comment by eschwab** [comment]
Sounds reasonable enough for me. This should make it clearer on which definition is being used.

**Comment by rpspringuel** [comment]
Addressing as part of #383.
