### ISSUE TITLE
Using numbers for pitch/height

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#447]
I've been thinking about this as of late, and with #59, #429, and #446, it seems that it would be increasingly valuable to pass a number instead of a letter for the pitch or height of a sign, with `a` being passed as `3`.

This way, numbers can be compared more easily for the min/max height determination for #59, adjusted for the sign change computation for #446, and (as a byproduct) `\ifcase`..`\or`..`\or`..`\fi` should be theoretically faster than `\if`..`\fi\if`..`\fi\if`..`\fi`.

For the 5-line staff (#429), we would be skipping `o` in the gabc, and we already hack `z` and `y` to be the two pitches below `a`, so why not just pass numbers instead to eliminate potentially wrong association of letter with pitch?

If we agree to this, I can make the changes, if so desired, but it may disrupt work in progress, especially on #59.

**Comment by eroux** [comment]
Fine for me!

**Comment by rpspringuel** [comment]
Is this a change in gabc, or just in the coded representation?

**Comment by henryso** [comment]
Gabc will not change.

**Comment by rpspringuel** [comment]
Then I have no objection.

**Comment by henryso** [comment]
#448 is ready for review.
