### ISSUE TITLE
Automatically sizing ob/ocb/ocba

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#454]
It would be very nice to extend the [ob:1;6mm], [ocb:1;6mm] and [ocba:1;6mm] constructs so that GregorioTeX automatically determines the length.  I know the hardcoded lengths make it much easier to implement, but e.g. ocba is often used for psalm initials with certain mediations or terminations, which are often generated from the mode and psalm text, so it is hard to compute the length because it heavily depends on the sizes of the syllables and other spacing gregorioTeX inserts in between the syllables.
As for syntax, there is already the 0/1 modifier where to start, so we could use say 2 after that for the start and 3 for end, so instead of
(hr[ocba:1;6mm]) <b>me</b>(hg)us(g.h.)
one could type:
(hr[ocba:12]) <b>me</b>(hg[ocba:03])us(g.h.)
which would mean start the brace on the left of the (hr) and end it on the right of (hg).  Unclosed braces of this kind or mixing them could be a syntax error determined by gregorio.

The question is if this is easily implementable in gregorioTeX, we'd either need to size the corresponding subpart of the score in a non-placed box, or without *.aux info estimate it somehow and record the locations of the start/end in the *.aux file and let next lualaTeX invocation compute the right length.  Then there is a question what to do if there is a line break in between (just for completeness, guess it won't happen all that often), perhaps emit one from the start to the right margin of the score (minus some length) and another one on the next line from the start (plus some length) to the ending note.

**Comment by eroux** [comment]
Putting it in .aux file seems the only way that would work indeed...

The end of line case could be handled in a second time, it would be pretty difficult to do.

**Comment by jakubjelinek** [comment]
Now that @henryso added support for score_id, I'd like to get this resolved.
http://ur1.ca/my7nh
is a (so far untested) patch for the gregorio parsing, which would add uses of two new macros,
\grevarbraces{id,kind}
and
\grevarbracee{id,kind}.
kind is 0 or 1, like in the existing over/under braces, either to the left or right of the current note.
id would be 1 for the first \grevarbraces{id,kind} pair, 2 for second etc., to be internally in lua concatenated with score_id (including the .inclusion) to produce hopefully unique (except for hash collisions) identification of variable length braces.

In the first pass (when score_id.inclusion.id isn't present in the .greaux file), supposedly grevarbraces would expand to 0mm or a very tiny length, plus perhaps set some magic attribute,
grevarbracee would always expand to nothing, and set some attribute.

Now, is it possible (and how) to compute the horizontal distance between two nodes with some attribute in e.g. post_linebreak_filter or some other callback?  Or other thoughts how to compute the distance?

**Comment by henryso** [comment]
My naive thought would be to store the x-position (a la zref-savepos) of the end point into the aux file and then, from the start point in a later pass, compute the difference in the x-positions.

**Comment by jakubjelinek** [comment]
Thanks, I'll try to implement it on top of zref-savepos first; would
\RequirePackage{zref-savepos}
be acceptable in gregorio.sty though, or do we need to reimplement it using \pdfsavepos and \pdflastxpos and saving/restoring it manually somewhere to/from the aux file?

**Comment by eroux** [comment]
Working with `\pdfsavepos` is really straightforward, I tend to prefer low-level primitives instead of LaTeX packages, it tends to be more reliable...

**Comment by jakubjelinek** [comment]
I agree, I just don't know how to save/restore from aux file, and from 10 of minutes grepping/looking through the zref-{base,savepos}.sty it wasn't obvious how it is done.

**Comment by eroux** [comment]
It used to be done in Gregorio for chronomic signs. It's removed in develop, but it should still be in master, or in old releases.

**Comment by henryso** [comment]
I have a suggestion about the syntax. Since it is already nested, why not use angle brackets or curly braces for start and end?  There should be no conflict, and it'd be easier to see what you're bracketing than (as a person) looking for 2 and 3.

**Comment by jakubjelinek** [comment]
So <ocba:[01]> ... </ocba:[01]> ?  Note the numbers might be different between the start and end.

**Comment by henryso** [comment]
no, I meant `ocba:[01]{` to start and +ocba:[01]}` to end (or with angle brackets).  This would still be inside square brackets, inside paretheses, so the gabc would look like:

```
text(gab[ocba:1{]c) text(gabc) text(gab[ocba:0}]c)
```

**Comment by jakubjelinek** [comment]
https://github.com/jakubjelinek/gregorio/commit/4810aef55f45342a4833a586aeb1c87df3784a88
is my current WIP, it seems it can store something into the *.gaux file.  Now, what is the best place to read it back?  In \AtBeginDocument before it is opened for writing?  Shall it be done in Lua?

**Comment by henryso** [comment]
I think `\AtBeginDocument` will probably only work under LaTeX.  Maybe do it at the end of `gregoriotex-main.tex`?  (I'm saying this as someone who *doesn't* fully understand how writing to .aux files work)

**Comment by jakubjelinek** [comment]
Ok, https://github.com/jakubjelinek/gregorio/commit/daa87807e089975cf5acccdc57800da49622cda3
avoids \AtBeginDocument for these purposes, and for some cases already seems to work properly,
but in other cases the ocba brace appears in wrong vertical position.
I guess I should avoid the \kern (both negative and positive, and perhaps either subtract the
length from \number\pdflastxpos (how?) or emit it as number-number and subtract when reading it back in lua.

**Comment by henryso** [comment]
What do you mean by wrong vertical position?  Maybe one of the temp counts is being clobbered?

**Comment by jakubjelinek** [comment]
https://github.com/jakubjelinek/gregorio/commit/0a11f713ac476b8eb8be2e201c74149a157c3c50
is a small fix for the score id computation.

{{{
initial-style: 0;
%%
(c4)
in(j)<b>dú</b>(jr[ocba:1;4mm])tus(ih) est:(j.)
in(j)<b>dú</b>(jr[ocba:0{])tus(ih[ocba:0}]) est:(j.)
in(j)<b>dú</b>(jr[ocba:0{])tus(ih[ocba:1}]) est:(j.)
in(j)<b>dú</b>(jr[ocba:1{])tus(ih[ocba:0}]) est:(j.)
in(j)<b>dú</b>(jr[ocba:1{])tus(ih[ocba:1}]) est:(j.)
(::)
}}}
is my testcase, and it gave:
![test](https://cloud.githubusercontent.com/assets/9370665/8425034/0e157974-1f02-11e5-81e5-e1fba8d4fcae.png)
so yes, overwriting some temporary dimen is a possible explanation.  Are there any safe ones that I could use instead?

As for the get_cur_score_id in lua, I need the .inclusion addition there, so that it works well with multiple scores.  I suppose atScoreBeginning could tex.print(cur_score_id) and the hunk that invokes it could remember it in a TeX macro.

**Comment by jakubjelinek** [comment]
Ah, but trying to move the horizontal position left for [ocba:1{] is undesirable anway, because apparently when it is included as \grebracecommon argument, it is moved to left already anyway.
https://github.com/jakubjelinek/gregorio/commit/b3ba7642e825ea635db911de2f29e404a9debf47
With this I get already the supposedly correct:
![test](https://cloud.githubusercontent.com/assets/9370665/8425235/277778ca-1f04-11e5-9c1b-142cc9302752.png)

**Comment by jakubjelinek** [comment]
>> I suppose atScoreBeginning could tex.print(cur_score_id) and the hunk that invokes it could remember it in a TeX macro.

Tried that, but failed.  Don't know how to set a TeX macro to what \directlua produces immediately, rather than evaluating the \directlua whenever the macro is used (I need the e.g. the make :=
variable assignment behavior rather than = ).

**Comment by jakubjelinek** [comment]
Appart from this, do you have suggestions on macro naming, what should be commented, what else needs to be changed?

I wish the same *.greaux file could be used for the line heights and variable length braces, but couldn't get that to work either with my limited TeX knowledge, \pdflastxpos has been evaluted too early when passed to lua, so it turned out to be 0 always.

**Comment by eroux** [comment]
You should try `\latelua` instead of `\directlua`, it's made for this purpose (though I admit I've never really used it).

**Comment by jakubjelinek** [comment]
I'm getting
! Undefined control sequence
for both
\latelua{}
and
\lualate{}
unfortunately.

**Comment by eroux** [comment]
try `\luatexlatelua`, I forgot they are prefixed in LaTeX...

**Comment by jakubjelinek** [comment]
Indeed, that works.  Will try to rewrite it in the evening to use that.

**Comment by henryso** [comment]
My opinion about your macro naming is that they should be spelled out more. `\grevarbraces` and `\grevarbracee` should be `\grevarbracestart` and `\grevarbraceend`.  I'm not sure of a good name for `\grevarbracer`, perhaps just `\grevarbrace`.

regarding the bit about `atScoreBeginning` doing the `tex.print(cur_score_id)`, why not have `atScoreBeginning` generate the def instead: `tex.print(string.format([[\gdef\macroname{%s}]], cur_score_id))`?
