### ISSUE TITLE
The score starts too close to the clef if initial-style is 0

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#457]
I'm not entirely sure this is a bug, but it seems to me like the first note starts too close to the clef if `initial-style` is set to 0.

Compare...
```
initial-style: 0;
%%
(c3) g(g) g(g)
```
... which produces...
![image](https://cloud.githubusercontent.com/assets/421318/7802759/cfb663a4-030a-11e5-89c3-4f8330f97403.png)
... with ...
```
initial-style:1;
%%
(c3) g(g) g(g)
```
... which produces...
![image](https://cloud.githubusercontent.com/assets/421318/7802763/f97f0b32-030a-11e5-9438-3397b5086d2d.png)

I can work around it by putting a space after the clef like so:
```
initial-style: 0;
%%
(c3 ) g(g) g(g)
```
... which produces...
![image](https://cloud.githubusercontent.com/assets/421318/7802768/25741ee4-030b-11e5-836d-ed8fe1f325be.png)

Is this a bug?  Should I try to fix it?

**Comment by rpspringuel** [comment]
I'd need to check the spacing code to be sure, but it certainly looks like a bug to me, given that the punctum and the clef are touching.

**Comment by eschwab** [comment]
Probably a spacing bug, but it is different behaviour than before (before when, I do not know).

**Comment by henryso** [comment]
I think this has been happening since I created the individual tests from `completetest.gabc`, from the looks of the historical PDFs in gregorio-test.

**Comment by eroux** [comment]
This might be due to the change that aligns notes left (using `\gre@compute@bolshift`)

**Comment by henryso** [comment]
This is not due to `\gre@compute@bolshift`.  It still happens if I take that computation out.

**Comment by henryso** [comment]
The culprit is this code in `\gresetinitialclef` (in `gregoriotex-signs.tex`):
```
  \ifnum\greremoveclefcount=0\relax %
    \ifnum\grelastoflinecount=2\relax % we must not type a space if there is no initial
      \gretypekey{#1}{#2}{0}{0}{#3}%
    \else %
      \gretypekey{#1}{#2}{0}{1}{#3}%
    \fi %
  \fi %
```

This explicitly says "we must not type a space if there is no initial".  Why not?

If I just call `\gretypekey{#1}{#2}{0}{1}{#3}` always, then, to no surprise, I get a nice space between the clef and the first note.

**Comment by henryso** [comment]
Any objections to making that change to add the space?

**Comment by eroux** [comment]
No problem, can't remember what this condition means...

**Comment by henryso** [comment]
In observing the tests that break with this, I can see a negative effect.  Making that change puts a "hard space" after the clef which means that the text starts at the end of this space.  I don't understand the spacing well enough, but I think what needs to be done is to suggest a minimum inter-glyph space after the clef which does not affect the text, similar to how the clefs at the beginning of other lines are kept separate from the first note glyph on the line.  I'd appreciate any hints, but I will continue to look into it.

**Comment by eroux** [comment]
I think you need a constraint system similar to the new one used in syllable end (notes must be at least at xpt, etc.). Maybe you can reuse the existing one, or make a new one, as it will be a bit simpler.

**Comment by eroux** [comment]
I have an idea but I'm affraid it will be shorter to code than to explain... can you give me a mwe showing the problem (tex+gabc)?

**Comment by henryso** [comment]
###### test.tex
```
\documentclass[11pt]{article}
\usepackage{gregoriotex}
\usepackage{libertine}
\gregoriosetnabcfont{gregall}{8}
\begin{document}
\includescore[f]{test1}

\includescore[f]{test2}
\end{document}
```
###### test1.gabc
```
name: test;
initial-style: 0;
%%
(c3) dgad(g) g(g)
```
###### test2.gabc
```
name: test;
initial-style: 0;
%%
(c3) g(g) g(g)
```

**Comment by eroux** [comment]
Can you test

diff --git a/tex/gregoriotex-signs.tex b/tex/gregoriotex-signs.tex
    index 5ac2aba..507c5eb 100644
    --- a/tex/gregoriotex-signs.tex
    +++ b/tex/gregoriotex-signs.tex
    @@ -191,11 +191,7 @@
     \def\gresetinitialclef#1#2#3{%
       \grecalculateclefnum{#1}{#2}{#3}%
       \ifnum\greremoveclefcount=0\relax %
    -    \ifnum\grelastoflinecount=2\relax % we must not type a space if there is no initial
    -      \gretypekey{#1}{#2}{0}{0}{#3}%
    -    \else %
    -      \gretypekey{#1}{#2}{0}{1}{#3}%
    -    \fi %
    +    \gretypekey{#1}{#2}{0}{1}{#3}%
       \fi %
       \gresetlinesclef{#1}{#2}{1}{#3}%
       % if the initial is big, then we adjust the second line
    diff --git a/tex/gregoriotex-syllable.tex b/tex/gregoriotex-syllable.tex
    index b8b888d..62af1c9 100644
    --- a/tex/gregoriotex-syllable.tex
    +++ b/tex/gregoriotex-syllable.tex
    @@ -453,7 +453,6 @@
         \gdef\gre@middlesyllablepart{#2}%
         \gdef\gre@endsyllablepart{#3}%
       \fi %
    -  \grefirstglyph=1\relax %
       \gre@calculate@textaligncenter{\gre@firstsyllablepart}{\gre@middlesyllablepart}{0}% we first get the width between the alignment point and the end of the syllable
       \gresyllablenotes{#9}% we put the notes in a box, so that we have the width of it
       % now we calculate the begin difference, that is to say \gre@dimen@notesaligncenter - \gre@dimen@textaligncenter
    @@ -472,8 +471,10 @@
       % took me years to find it!
       \ifnum\gredisableeolshifts=0\relax%
         \gre@compute@bolshift{\gre@dimen@begindifference}{1}%
    -    \kern -\gre@dimen@bolshift %
    -    \grenobreak %
    +    \ifnum\grelastoflinecount=2\else %
    +      \kern -\gre@dimen@bolshift %
    +      \grenobreak %
    +    \fi %
         \hbox to 0pt{}%
         \grenobreak %
         \kern\gre@dimen@bolshift %

?

**Comment by henryso** [comment]
This certainly fixes the problem I mentioned earlier.  There's one more bit I need to track down, I guess.  The clef (apparently) still applies an offset on the first line, so the first note (if it has a short syllable) on the first line will be the clef's width further to the right than the first note (if it also has a short syllable) on the second line.

**Comment by eroux** [comment]
That's a problem indeed... Can you try removing the patch on `tex/gregoriotex-signs.tex`?

**Comment by henryso** [comment]
If I remove that patch, the note on the first line is too close to the clef by about a punctum's width (though not touching, like before).

**Comment by eroux** [comment]
Hmm ok, can you send me another example please?

**Comment by henryso** [comment]
###### test.tex
```
\documentclass[11pt]{article}
\usepackage{gregoriotex}
\usepackage{libertine}
\gregoriosetnabcfont{gregall}{8}
\begin{document}
\includescore[f]{test}
\end{document}
```
##### test.gabc
```
name: test;
initial-style: 0;
%%
(c3)
g(g) g(g) g(g) g(g) g(g)
g(g) g(g) g(g) g(g) g(g)
g(g) g(g) g(g) g(g) g(g)
g(g) g(g) g(g) g(g) g(g)
g(g) g(g) g(g) g(g) g(g)
g(g) g(g) g(g) g(g) g(g) (::)
```

**Comment by eroux** [comment]
Hmm, I cannot see any problem with your example... can you be more specific?

**Comment by eroux** [comment]
Edit: at least with my first patch

**Comment by henryso** [comment]
My test doesn't break with your original patch.  Try with this test.gabc:
```
name: test;
initial-style: 0;
%%
(c3)
g(g) (:Z)
g(g) (:Z)
g(g) (::)
```

**Comment by eroux** [comment]
This seems to fix it:

    diff --git a/tex/gregoriotex-signs.tex b/tex/gregoriotex-signs.tex
    index 5ac2aba..507c5eb 100644
    --- a/tex/gregoriotex-signs.tex
    +++ b/tex/gregoriotex-signs.tex
    @@ -191,11 +191,7 @@
     \def\gresetinitialclef#1#2#3{%
       \grecalculateclefnum{#1}{#2}{#3}%
       \ifnum\greremoveclefcount=0\relax %
    -    \ifnum\grelastoflinecount=2\relax % we must not type a space if there is no initial
    -      \gretypekey{#1}{#2}{0}{0}{#3}%
    -    \else %
    -      \gretypekey{#1}{#2}{0}{1}{#3}%
    -    \fi %
    +    \gretypekey{#1}{#2}{0}{1}{#3}%
       \fi %
       \gresetlinesclef{#1}{#2}{1}{#3}%
       % if the initial is big, then we adjust the second line
    diff --git a/tex/gregoriotex-spaces.tex b/tex/gregoriotex-spaces.tex
    index 0612037..b8dee7f 100644
    --- a/tex/gregoriotex-spaces.tex
    +++ b/tex/gregoriotex-spaces.tex
    @@ -393,8 +393,7 @@
     %%       TODO for details.
     %%
     %% @arg#1 \gre@dimen@begindifference of the first syllable of the line
    -%% @arg#2 not sure about it... to be removed?
    -\def\gre@compute@bolshift#1#2{%
    +\def\gre@compute@bolshift#1{%
       % as the \gre@dimen@bolshift is computed from skips, we compute it in a
       % skip temp registry, and then "cast" it into a dimen
       \gre@skip@temp@three=\gre@skip@spaceafterlineclef % TODO: or 0pt?
    @@ -410,14 +409,6 @@
       \ifdim\gre@skip@temp@three < #1%
         \gre@skip@temp@three=\the #1%
       \fi %
    -  % Don't allow kern past the beginning of the first line with no initial
    -  \ifnum#2=1%
    -    \ifdim\gre@dimen@initialwidth = 0pt %
    -      \ifnum\greknownline=1 %
    -        \advance\gre@skip@temp@three by \gre@dimen@clefwidth %
    -      \fi %
    -    \fi %
    -  \fi %
       \ifdim\gre@skip@temp@three > 0pt%
         \global\gre@dimen@bolshift=0pt%
       \else %
    diff --git a/tex/gregoriotex-syllable.tex b/tex/gregoriotex-syllable.tex
    index b8b888d..e66e699 100644
    --- a/tex/gregoriotex-syllable.tex
    +++ b/tex/gregoriotex-syllable.tex
    @@ -453,7 +453,6 @@
         \gdef\gre@middlesyllablepart{#2}%
         \gdef\gre@endsyllablepart{#3}%
       \fi %
    -  \grefirstglyph=1\relax %
       \gre@calculate@textaligncenter{\gre@firstsyllablepart}{\gre@middlesyllablepart}{0}% we first get the width between the alignment point and the end of the syllable
       \gresyllablenotes{#9}% we put the notes in a box, so that we have the width of it
       % now we calculate the begin difference, that is to say \gre@dimen@notesaligncenter - \gre@dimen@textaligncenter
    @@ -471,9 +470,11 @@
       % we will have shifted right and left, thus cancelling... Very easy trick, but
       % took me years to find it!
       \ifnum\gredisableeolshifts=0\relax%
    -    \gre@compute@bolshift{\gre@dimen@begindifference}{1}%
    -    \kern -\gre@dimen@bolshift %
    -    \grenobreak %
    +    \gre@compute@bolshift{\gre@dimen@begindifference}%
    +    \ifnum\grelastoflinecount=2\else %
    +      \kern -\gre@dimen@bolshift %
    +      \grenobreak %
    +    \fi %
         \hbox to 0pt{}%
         \grenobreak %
         \kern\gre@dimen@bolshift %

**Comment by henryso** [comment]
That patch appears to break your first syllable changes when I run the PopulusSion test.  Everything (well, for the four lines of that chant) seems to be aligned on the first letter of the words rather than the notes.

**Comment by eroux** [comment]
What about

    diff --git a/tex/gregoriotex-signs.tex b/tex/gregoriotex-signs.tex
    index 5ac2aba..507c5eb 100644
    --- a/tex/gregoriotex-signs.tex
    +++ b/tex/gregoriotex-signs.tex
    @@ -191,11 +191,7 @@
     \def\gresetinitialclef#1#2#3{%
       \grecalculateclefnum{#1}{#2}{#3}%
       \ifnum\greremoveclefcount=0\relax %
    -    \ifnum\grelastoflinecount=2\relax % we must not type a space if there is no initial
    -      \gretypekey{#1}{#2}{0}{0}{#3}%
    -    \else %
    -      \gretypekey{#1}{#2}{0}{1}{#3}%
    -    \fi %
    +    \gretypekey{#1}{#2}{0}{1}{#3}%
       \fi %
       \gresetlinesclef{#1}{#2}{1}{#3}%
       % if the initial is big, then we adjust the second line
    diff --git a/tex/gregoriotex-spaces.tex b/tex/gregoriotex-spaces.tex
    index 0612037..9f60736 100644
    --- a/tex/gregoriotex-spaces.tex
    +++ b/tex/gregoriotex-spaces.tex
    @@ -397,7 +397,7 @@
     \def\gre@compute@bolshift#1#2{%
       % as the \gre@dimen@bolshift is computed from skips, we compute it in a
       % skip temp registry, and then "cast" it into a dimen
    -  \gre@skip@temp@three=\gre@skip@spaceafterlineclef % TODO: or 0pt?
    +  \gre@skip@temp@three=\gre@skip@spaceafterlineclef %
       \advance\gre@skip@temp@three by #1%
       % a little trick... we don't want to kern more than clefwidth minus minimalspaceatlinebeginning
       \advance\gre@dimen@clefwidth by -\gre@dimen@minimalspaceatlinebeginning %
    @@ -407,22 +407,18 @@
       %% TODO: is following line really safe?
       \advance\gre@dimen@clefwidth by \gre@dimen@minimalspaceatlinebeginning %
       \advance\gre@skip@temp@three by -\gre@skip@spaceafterlineclef %
    -  \ifdim\gre@skip@temp@three < #1%
    -    \gre@skip@temp@three=\the #1%
    +  \ifdim\gre@skip@temp@three < #1\relax %
    +    \gre@skip@temp@three=\the #1\relax %
       \fi %
    -  % Don't allow kern past the beginning of the first line with no initial
    -  \ifnum#2=1%
    -    \ifdim\gre@dimen@initialwidth = 0pt %
    -      \ifnum\greknownline=1 %
    -        \advance\gre@skip@temp@three by \gre@dimen@clefwidth %
    -      \fi %
    -    \fi %
    -  \fi %
    -  \ifdim\gre@skip@temp@three > 0pt%
    -    \global\gre@dimen@bolshift=0pt%
    +  \ifnum#2=1\fi % keep it due to a luatex bug, fixed in TL2015, TODO: remove later
    +  \gre@debugmsg{bolshift}{ temp@three = \the\gre@skip@temp@three}%
    +  \ifdim\gre@skip@temp@three > 0pt\relax %
    +    \global\gre@dimen@bolshift=0pt\relax %
       \else %
         \global\gre@dimen@bolshift=\gre@skip@temp@three %
       \fi %
    +  \gre@debugmsg{bolshift}{ bolshift = \the\gre@dimen@bolshift}%
    +  \relax %
     }
     
     % dimen keeping the shift computed with next function
    diff --git a/tex/gregoriotex-syllable.tex b/tex/gregoriotex-syllable.tex
    index b8b888d..118cad3 100644
    --- a/tex/gregoriotex-syllable.tex
    +++ b/tex/gregoriotex-syllable.tex
    @@ -470,10 +470,12 @@
       % So, at beginning of lines, we will have shifted left, and in middle of lines
       % we will have shifted right and left, thus cancelling... Very easy trick, but
       % took me years to find it!
    -  \ifnum\gredisableeolshifts=0\relax%
    +  \ifnum\gredisableeolshifts=0\relax %
         \gre@compute@bolshift{\gre@dimen@begindifference}{1}%
    -    \kern -\gre@dimen@bolshift %
    -    \grenobreak %
    +    \ifnum\grelastoflinecount=2\else %
    +      \kern -\gre@dimen@bolshift %
    +      \grenobreak %
    +    \fi %
         \hbox to 0pt{}%
         \grenobreak %
         \kern\gre@dimen@bolshift %

?

**Comment by henryso** [comment]
This patch seems to do the trick.  The tests change acceptably, except for `gabc-output/bugs/test98.gabc`, which is still as "bad" as it was before.

**Comment by henryso** [comment]
Thanks for the fix.
