### ISSUE TITLE
"First two" episema computation doesn't work correctly for alternate porrectus/torculus resupinus deminutus glyphs

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#458]
The computation for a "first two" episema of a porrectus (or torculus resupinus) deminutus is based on the length of the stroke of the first ambitus of a normal porrectus.  This is fine as long as the user is not using the alternate glyphs.

By way of example:
###### test.tex
```
\documentclass[11pt]{article}
\usepackage{gregoriotex}
\usepackage{fontspec}
\usepackage{libertine}
\grechangeglyph{Porrectus*}{*}{.alt}
\begin{document}
\includescore[a]{test}
\end{document}
```
###### test.gabc
```
initial-style: 0;
%%
(c3 ) test(h_e_h~)
```
###### output
![image](https://cloud.githubusercontent.com/assets/421318/7802863/a1426614-030d-11e5-9369-af894102edaa.png)

The code, before I started on the alternate glyph solution, already didn't work for this case, and in fact, there was a comment there to that point.

I suppose this should be fixed.  However, the question is, how should this be fixed?  Should a whole new set of cases be created for porrectus (and torculus resupinus) deminutus?  This can also be fixed in the gregorio executable by drawing separate episemae, but then the executable would need to somehow know the alternate glyphs are being used.  Another alternative is to pass an extra argument so that the macro knows if the episema is for a deminutus glyph.  Maybe there are other, better ways that I haven't thought of.

Any thoughts on this?

**Comment by henryso** [comment]
Thinking about this further, the "first two" episema wouldn't even make too much sense here.  I think it would have to be above the first note and below the second, extending above the third only if all three have the episema.  Therefore the solution would have to be in C, I think, unless someone can think of a better way.

If C is the way to go, then the next question is, how do we let C know that the alternate porrectus deminutus glyphs are being used?  Another header?

Of course, the alternative is that we don't fix it per se, and people would have to use the new episema flags to get what they want: `(h_e_02h~)`.  This is not perfect, though (for example, `` is rendered with a small episema on the deminutus), so it might require a little work to get things right.

**Comment by eroux** [comment]
That's a difficult issue indeed... Can you post a picture of what `(h_e_02h~_)` looks like?

**Comment by henryso** [comment]
![image](https://cloud.githubusercontent.com/assets/421318/7810029/bc7e7616-036c-11e5-95d8-5dc348acd993.png)

**Comment by eroux** [comment]
I think it's reasonably good...

**Comment by henryso** [comment]
Ok, then I'll close this as won't fix.
