### ISSUE TITLE
Deprecate or remove preamble headers?

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#473]
Should we remove or deprecate the following gabc headers?

- lilypond-preamble
- opustex-preamble
- musixtex-preamble

**Comment by eroux** [comment]
Agreed

**Comment by henryso** [comment]
Deprecate then remove in the future or just remove now (since support for these has already been dropped)?

**Comment by eroux** [comment]
I think it's quite safe to remove them

**Comment by rpspringuel** [comment]
I agree.  Since support for those output types is already dropped it should be safe to simply remove the associated headers.
