### ISSUE TITLE
Use the style system for \gre@writemode.

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#487]
Rather than hard-coding `\GreSmallCaps` and `\GreBold` for `\gre@writemode`, use a new style.

**Comment by eschwab** [comment]
Are you thinking to wrap all annotations (`\greannotation`) with this style or just `\gre@writemode`? Personally I would not wrap all annotations. Doing `\gre@writemode` would be fine, since I think the amount of cases where a user wants the `mode` header to output is fairly slim.

**Comment by henryso** [comment]
Just \gre@writemode.  I should have named the issue differently.
