### ISSUE TITLE
Centering features

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#491]
Continuing the misplaced discussion in #489:

I am not at all familiar with any of the languages mentioned, so I will take everything said there an canon.  I can certainly add all the vowels to the in-built Latin ruleset.  However, they will have to "suffer" Latin's "i" and "u" prefixes.  So if "i" or "u" is followed by a vowel, the "i" or "u" will not be part of the center.

An alternative would be, of course, to create another language in the data file.

Supporting syllabic consonants will not be possible in the current code.  English also has syllabic consonants ("l", "r", "n", probably more), but, in English, there will be a vowel present that is not the center (i.e., c{a}t-t{l}e), so I'm not going to worry about them.  The rule for syllablic consonants proposed by @jakubjelinek is excellent, and can be handled by a second pass if no center is found.  I will add a keyword "secondary" to the vowel file to handle this case.  My reason for choosing "secondary" is that I wanted a single word, and neither "syllabic" nor "consonant" is correct here, and this rule is not general enough to cover all syllabic consonants, anyway, so I named it technically: it will be done in a second pass.

Thoughts?

**Comment by eroux** [comment]
That sounds good! I don't think really know if Polish or Czech have think like ie, ue, uo, etc. I don't think so, but @jakubjelinek will know better!

**Comment by jakubjelinek** [comment]
secondary keyword is fine.  Czech doesn't have ie, ue, uo (for two vowels only au or ou).
Though, do you want to add
secondary lLĺĹmMnNrRŕŔ;
for Latin too (won't that break anything for e.g. Latin itself), or just add Czech (and other Slavic languages that need this) to the vowels data file?

**Comment by henryso** [comment]
Adding the secondaries to Latin will not break it, but it could conceivably break other languages that currently work fine with the Latin rules. The "safe" thing to do would be to add this to the vowel data file, but I will do whatever you tell me to do, since I don't know these languages.

**Comment by eschwab** [comment]
It might be better to have a separate section in the vowal.dat for Slavic languages. If we fill the latin section with characters that don't occur in latin then people who look into the file in the future may be scratching their heads trying to figure out what is going on.

**Comment by jakubjelinek** [comment]
But then it might be useful to have some syntax for language aliases.  Because there is no reason to write a separate section for Czech, another one for Slovak (perhaps the same can be useful also for other Slavic languages).  So perhaps allow:
language [Czech, Slovak];
etc.?

**Comment by henryso** [comment]
Aliases will be in soon. I'm working on that now.  The syntax will be:

`alias [name] to [language];`

**Comment by rpspringuel** [comment]
I'm with @eschwab in that we shouldn't go adding letters to languages that don't exist in that language so that other languages can fall back on that language.  It would be better to create a new language which does actually contain those characters.  Heck, I'd actually favor creating a separate entry for every language we support, just to be explicit about it.

The alias system (which @henryso is working on) would provide for explicit support of several languages which all use the same set of vowel rules.  If the rules differ however, even in minor details (as with, eg, French and Latin) I would have separate entries.  Given that `gregorio-vowels.dat` is a plain text file, I don't think having a large number of entries would lead to a problematic file size.

**Comment by henryso** [comment]
If I create a Slavic language ruleset using the vowels from here and from #489, which language names should I assign to it?  Should I use the English names for these languages or the "in-language" names for the languages?  Both?

**Comment by eroux** [comment]
Maybe it's best to specify languages in ISO 639-2 code?

**Comment by henryso** [comment]
I have certain issues with ISO 639-2 (for example, it doesn't differentiate Cantonese from Mandarin), but if that's what you want, I can do that.

**Comment by eroux** [comment]
If you have a better option for language name standardization, why not...

**Comment by jakubjelinek** [comment]
If there is an alias support, it is quite easy to just use English names of the languages and if the native speakers of some language want to add some alias in their native language, it is just a matter of adding a single extra line into the file.

**Comment by henryso** [comment]
I will take @jakubjelinek's suggestion and use English names for the languages.  We can add anything else later using aliases.

**Comment by henryso** [comment]
@jakubjelinek Would you be able to provide a sentence or two in Czech that are broken up into syllables for me to use in testing?

**Comment by jakubjelinek** [comment]
(c3)
Hos(h)po(i)di(i)ne,(i) po(h)mi(hg)luj(f) ny!(f) (;)
Je(i)zu(i) Kris(i)te,(gf) po(h)mi(hg)luj(fg) ny!(h) (:)
Ty,(h) spa(i)se(i) vše(hg)ho(f) mi(fg)ra,(h) (,)
spa(i)siž(i) ny(h) i(h) u(gh)sly(i)šiž,(i) (;)
Hos(i)po(i)di(h)ne,(hg) hla(fg)sy(h) na(h)šě!(h) (:)
Daj(i) nám(i) všěm,(i) Hos(i)po(i)di(h)ne,(hg) (,)
žizn(f) a(fg) mír(h) v ze(h)mi!(h) (:)
Kr(h)leš!(h) Kr(h)leš!(h) Kr(h)leš!(h) (::)

is an old (10th-11th century) Czech hymn, or

(c4)
Sva(hi)tý(g) Vác(j)la(ig)ve,(h_) (,)
vé(hi)vo(g)do(j) Čes(i)ké(h) ze(f)mě,(e_) (;)
kně(d)že(f) náš,(g.) (,)
pros(f') za(e) ny(e) Bo(d)ha,(g_) (,)
Sva(f')té(e)ho(e) Du(d)cha!(g_)
Ky(f)ri(e')e(d)lei(dc)son.(d.) 2.(:)

Ne(h)bes(h)kéť(h) jest(i) dvor(g)stvo(j) krás(ig)né,(h_) (,)
bla(h)zě(h) to(h)mu,(i) ktož(g) tam(j) pój(ig)de,(h_) (,)
v ži(f)vot(e') věč(d)ný,(g_) (,)
o(f)heň(e') jas(d)ný(g') (,)
Sva(f')té(e)ho(e) Du(d)cha!(g_)
Ky(f)ri(e')e(d)lei(dc)son.(d.) 3.(:)

Po(h)mo(h)ci(i) tvé(g) žá(j)dá(ig)my,(h_) (,)
smi(h)luj(i) se(g) nad(j) ná(ig)mi,(h_) (,)
u(f)těš(e') smut(d)né,(g_) od(f)žeň(e') vše(d) zlé,(g_) (,)
sva(f')tý(e) Vác(e)la(d)ve!(g_)
Ky(f)ri(e')e(d)lei(dc)son.(d.) 4.(:)

Ma(h)ri(h)a,(h) Mat(i)ko(g) žá(j)dú(ig)cie,(h_) (,)
tys(h) krá(h)lov(h)na(i) vše(g)mo(j)hú(ig)cie,(h_) (,)
pro(f)siž(e') za(d) ny,(g_') za(f) křes(e')ťa(d)ny,(g_)
své(f)ho(e') Sy(d)na!(g_) (,)
Kris(f')te(e)lei(dc)son.(d.) 5.(:)

Ty(h) jsi(h) dě(h)dic(i) Čes(g)ké(j) ze(ig)mě,(h_) (,)
rač(h) pom(h)nie(h)ti(i) na(g) své(j) plé(ig)mě,(h_) (,)
ne(f)dajž(f') za(e)hy(e)nú(d)ti,(g_) (,)
nám(f') i(e) bu(e)dú(d)cim,(g_) (,)
sva(f')tý(e) Vác(e)la(d)ve!(g_) (,)
Kris(f')te(e)lei(dc)son.(d.) (::)

is an old Czech hymn (12th century).  Or, an example with contemporary Czech (Libera nos quaesumus):

(c3)
Vys(e)vo(f)boď(f) nás(f) o(f)de(f) vše(f)ho(f) zlé(f)ho,(f) Bo(f)že,(e.) (;)
a(e) dej(f) na(f)šim(f) dnům(e) svůj(e) mír.(f.) (:)
Smi(e)luj(f) se(f) nad(f) ná(f)mi(f) a(f) po(f)moz(e) nám:(e.) (;)
Ať(e) se(f) nik(f)dy(f) ne(f)dos(f)ta(f)ne(f)me(f) do(f) pod(f)ru(f)čí(f) hří(f)chu,(f.) (,)
ať(f) ži(f)je(f)me(f) v(f) bez(f)pe(f)čí(f) před(f) kaž(f)dým(f) zmat(f)kem(e.) (;)
a(e) s na(f)dě(f)jí(f) o(e)če(f)ká(g)vá(f)me(f) po(f)žeh(f)na(f)ný(e) pří(f)chod(f.) (,)
na(f)še(f)ho(f) Spa(f)si(f)te(f)le(f) Je(e)ží(f)še(g) Kris(ee)ta.(c.) (::)
Ne(c)boť(ef) tvé(f) je(e) krá(g)lov(h)ství(gf..) (,)
i(f) moc(f) i(e) slá(f)va(g) na(e)vě(e)ky.(c.) (::)

**Comment by jakubjelinek** [comment]
Note, Hungarian is not a Slavic language (but ugro-finnish) and supposedly does not have any syllabic consonants.
And AFAIK Hungarian (not that I speak more than 3-4 words from it) contains both o with acute, o with with dieresis and o with double acute as separate accented letters (and perhaps similarly for u).

**Comment by eroux** [comment]
Indeed, Hungarian has the same for u, and also has é, á and i with acute. And I don't think they'd like to be put in Slavic languages :)

**Comment by henryso** [comment]
Since no one here really knows Hungarian, maybe I should drop it for now?

**Comment by eroux** [comment]
The best is to make it very simple: no prefix, no suffix, and the vowels `aáéeëiíoóöőuúüű`, if you really want strong confirmation, I can ask some hungarian friends, but this should cover 99% of the cases I believe...
