### ISSUE TITLE
gregorio should treat carriage return/new line as spacing character

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#5]
Currently, for instance if you encode a hymn with new lines after each verses, last word of the line and first of the next one are treated as one word if you don't put a space at the end of the line.

**Comment by eroux** [comment]
Hmm can you give a more precise example? With

```
name: test-issue-5;
%%
(f3) firstword(i!jwkji~)
secondword(gh)
```

the words are distinct...

**Comment by olivierberten** [comment]
Oh right... I had forgotten about that one... it's actually an issue of phpMyAdmin which is "eating" carriage returns...
