### ISSUE TITLE
grefactor initialization

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#50]
Currently `\grefactor` is initialized as `0`, assumed to be `1`, and then changed to `17` when the first score is inserted if the user hasn't manually changed it already.  This change causes all distances to rescale.  For the distances in `gsp-default` this is okay because they are all 1/17th of what actually appears in the default score.  However, for any distance which the user manually changes before inserting the score, the change throws a monkey wrench in the works if they don't have an explicit `\setgrefactor` statement.

If we change those distances so that they don't scale, then if a user tweaks them and then decides they want to change the scale of the score, they have to repeat the tweaking process all over again.  Avoiding this requires a proliferation of `\ifnum\grefactor=0\relax\setgrefactor{17}\fi` code blocks.

I think it might be useful to modify this behavior so that the `grefactor` is initialized as `17`.  This would allow the elimination of the `\ifnum` code blocks but would also require multiplying all the distances in `gsp-default` by 17.  This later change would have the benefit of making the distances more relatable to the user (especially if they were switched out of `sp` and written in `cm` or `mm`).

Finally, `\setgrefactor` could have a built in error check that makes sure it's argument is a positive integer.

Opinions?

**Comment by eroux** [comment]
The idea I have in mind is to make gsp-xxx.tex in a different way. Currently this is like

    \greinterelementspace = 7600 sp plus 200 sp minus 400 sp

but it would be better to have something like

    \gresetlenght{\greinterelementspace}{7600 sp plus 200 sp minus 400 sp}{0}

where the last argument tells gregorio if it needs to scale it according to grefactor or not... It would let the user choose between the old behaviour (scaled with the notes) or make it static (units in mm, pt, etc.) or even scaled with the font (units in em, ex, etc.).

This seems the most flexible solution... what do you think?

**Comment by rpspringuel** [comment]
That would be the more flexible behavior.  Each distance would then have a count associated with it to store the scaling flag and `\grechangedimenfactor` would then need to check the flag before scaling each distance.  I think, however, that this wouldn't correct the specific issue I noticed.  The two fixes don't appear to be incompatible, but I think they address slightly different issues.

Having just [asked on latex-stackexchange] (http://tex.stackexchange.com/questions/229235/how-to-set-a-distance-that-rescales-with-the-font), getting the distances to scale with font requires saving them as text macros rather than actual lengths.  That might complicate things a bit.  Is font scaling behavior critical?

**Comment by eroux** [comment]
Yes, it's something that's been asked, I've already reported it [here](https://github.com/gregorio-project/gregorio/issues/8), so I think it would be best to make this fix for it... 

If I understand correctly, this will mean that spaces can be represented as strings (when they scale according to the font) or as dimen (when they scale with grefactor)... this is a bit annoying, but still possible... Or maybe not all spaces in gsp-xxx.tex should have this option: for instance vertical space between the lines cannot vary according to fonts, and there are certainly others in this case...

What do you think?

**Comment by rpspringuel** [comment]
Hmm... This may not be as difficult as I thought.  The length changing command would need to know which of the text registers are supposed to store dimens and which store skips.  With that that knowledge it could check to make sure that the user isn't trying to store a string representing a skip in a dimen macro, something which would create errors (the other direction is fine).  The other issue seems to be the calculations.  They can only be done on dimen and skip registers, so we'd have to make sure that the string macro gets stored in a temporary skip register, calculations are done on the temporary register, and then the result is stored in the string macro (easily accomplished with a `\def\macro{\the\tempskip}`, perhaps with `\global`).

Beyond that though, it seems that a text macro with a string representation of the distance should function identically to an actual dimen or skip register (and it works the same with both `em`-like and `cm`-like units).  In this case a distance could scale both according to the font (be specified in `em` or `ex`), according to the `grefactor` (have its scaling factor set to `1`), both, or neither.

**Comment by eroux** [comment]
Seems good! By the way, thank you very much for your involvement, it's really helpful!

**Comment by rpspringuel** [comment]
Okay, let me see if I can spec out a task list for this:

1. Change the initialization of `\grefactor` from 0 to 17.
2. Add error check to `\setgrefactor` to make sure its argument is valid (i.e. a positive integer).
3. Change all distances in gsp-default.tex by multiplying them by 17, converting them to cm, and storing them in a text macro.
4. Replace the creation of the dimension and skip registers in gregoriotex-spaces.tex with the creation of the scaling flags for those distances.
5. Modify `\grechangedim` to store distances in text macros rather than dimension and skip registers and add error check to make sure a skip string isn't stored in a macro which needs to represent a dimension.  Also add argument that sets a scaling flag for distance.
6. Modify any other distance changing function so that it pays attention to the scaling flag (and uses `\grechangedim` if it doesn't already).
7. Eliminate the `\ifnum\grefactor=0` code blocks.
8. Check that calculations are being performed on a temporary skip register and that the result gets stored in the appropriate text macro.

Am I missing anything?

**Comment by eroux** [comment]
Hmm, I think \setgrefactor should also be changed quite a lot to take these into account right? It should take all the definitions, put them in a skip register, divide them by 17 (or the current factor), multiply them by the new factor, and overwrite their previous string definition right?

**Comment by rpspringuel** [comment]
Actually, `\setgrefactor` calls `\changedimenfactor` which contains the list of all dimensions needing to be scaled and which calls `\grechangeonedimenfactor` on each to do the the actual scaling.  So `\setgrefactor` itself doesn't need to be modified, but the changes you outlined would need to be applied to the lower level commands.  I think it would be the easiest if `\changedimenfactor` checked the scaling flag, calling `\grechangeonedimenfactor` only on those distances that are supposed to scale, while `\grechangeonedimenfactor` needs the conversion from text macro to skip register and back again.

**Comment by eroux** [comment]
Yes, that's right. Well, it's a go for me!

**Comment by rpspringuel** [comment]
@eroux, do you remember how sensitive the various lengths were to changes when you picked the defaults?  Most of the defaults are specified in `sp` which is the smallest unit TeX understands.  As a result, if I convert them to `cm` there's a potential for a small amount of rounding error to be introduced.  If the distances are really sensitive, then that could be an issue.

I suppose I could just try it, but I thought that if you remembered how futzy picking those defaults was it could save me some work.

**Comment by eroux** [comment]
Well, some are very sensitive, mainly the vertical space between lines. This should stay in sp I believe, but most lengths are just variable horizontal spaces that are not really sensitive... If you have doubts on a type of values, don't hesitate to ask!

**Comment by rpspringuel** [comment]
After some testing, it appears that converting from `sp` introduces errors on the order of 10^-5 in whatever unit I'm converting to, and usually of magnitude 1 or 2.  If I write the distances in `mm` then that's on the order of 10 nm (it's on the order of the size of an airborne virus, according to [Wikipedia] (http://en.wikipedia.org/wiki/10_nanometres)).  If in `cm` that's on the order of 100 nm.  In either case it's probably way smaller than anyone can pick up on visually (at least, anyone not using a microscope).  I'm going to give the conversion a try for all distances as `cm` or even `mm` will be a whole lot more comprehensible to most people.

Sorry fellow Americans, but inches just aren't well understood by most of the rest of the world.  Get with the program and learn metric units.

**Comment by eroux** [comment]
Should be no problem then!

**Comment by rpspringuel** [comment]
@eroux Some questions about lengths:
`\grebraceshift` and `\grecurlybraceaccentusshift` are currently initialized as skips, but defined as having a fixed length (i.e. a dimension).  Based on their descriptions, I think they should be dimensions.  Am I right?

`\grestafflinediff` has a description which suggests that it should be a calculated distance, but it's initialized as if it was a fixed one.  Is it supposed to be calculated or fixed?

**Comment by eroux** [comment]
about `\grebraceshift` and `\grecurlybraceaccentusshift` you're right. About `\grestafflinediff`, it's initalized to 0, but the computation takes place around line 330 of `gregoriotex-spaces.tex`.

**Comment by rpspringuel** [comment]
@eroux, More questions:
I've found what appears to be an orphan distance: `\greclefchangespace`.  It's initialized in `gregoriotex-spaces.tex` but I can't find where it gets set or used.  Am I missing something or can it be eliminated.

Also, the description of `\greminimalspaceatlinebeginning` doesn't appear to be accurate.  So far as I can tell, it has nothing to do with the initial (as the comment describing it indicates) but appears to be related to the space before glyphs relative to the clef.  Can you provide a more accurate description of what it's supposed to be fore?

**Comment by eroux** [comment]
Hmm, I can see several occurences of `\hskip\greclefchangespace` in `gregoriotex-signs.tex`... About `\greminimalspaceatlinebeginning`, the comment is indeed totally wrong. IIRC, it should be the minimal space at beginning of line... I suppose it's for text, but I can't remember exactly. Anyway, I'll change many things in this area for the feature about left alignement on notes and not text, so you can keep it as it is for now, I'll clean things up later.

**Comment by rpspringuel** [comment]
What is the `stafflinefactor` for?  Is this meant to be a way for the user to scale the staff without affecting the size of the notes?  Right now it appears to only affect the thickness of the staff lines (something already controlled by `stafflineheight`.

**Comment by eroux** [comment]
IIRC, if you change stafflineheight directly, you'll have troubles because you need to change it with all the other values in order to keep having something perfectly centered... It may not be really noticeable with naked eye (maybe not even with a lens), but I don't think it's worth removing if you ask my opinion...

**Comment by rpspringuel** [comment]
After doing some testing based on your response, I've found that changes to both `stafflineheight` and `interstafflinespace` create problems with the vertical placement of the glyphs relative to the staff.  Changing the `staflinefactor` affects the `stafflineheight` without messing the spacing.  This implies that `stafflineheight` should not be a user definable parameter, unlike what I originally thought. 

Also, there doesn't appear to be a way to change `interstafflinespace` in a way that affects the placement of the glyphs.  Should there be?

**Comment by rpspringuel** [comment]
Looking at this closer, I've found what appears to be an orphaned comment:
    % primaryglyphraisevalue = interstafflinespace/2 + lineheight/2 + (1500 - lineheight) = 17250 - lineheight 

I can't find any variable named `primaryglyphraisevalue` is this supposed to be referring to `glyphraisevalue`?  Further, the indicated calculations don't appear either directly after the comment or in `\grecalculateglyphraisevalue`.  However, the first value `glyphraisevalue` is set to when it is calculated is 15750sp, the result of the indicated calculation at the default value for `stafflineheight`.  This leads me to think that we've just lost an intermediate variable, but putting it back in leads to spacing problems at `stafflinefactor` other than default.

I'll probably figure this out on my own, but any additional information you have on what's going on here is appreciated.

**Comment by eroux** [comment]
I admit I cannot remember... this code is nearly 7 years old :)

It's of no importance for the current matter, but 15750 is 100 times the values printed in fontforge...

**Comment by rpspringuel** [comment]
Addressed in v2.4.3
