### ISSUE TITLE
Problem centering neumes over small-caps.

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#509]
This comes from Albert Bloomfield on gregorio-user.

See https://gist.github.com/henryso/20bb446cf06444fba061

**Comment by henryso** [comment]
Albert is using 3.0.0-rc2.  The `develop` branch does improve things somewhat, but there is still an alignment error over the small caps:

![example](https://cloud.githubusercontent.com/assets/421318/8245744/37e1b10a-1601-11e5-8e6a-9274abde481e.png)

**Comment by henryso** [comment]
Upon further study, I think this is due to where gregorio (the executable) places the `\GreSetFixedTextFormat` and `\GreSetFixedNextTextFormat` commands.

**Comment by henryso** [comment]
Is this a big enough issue that it should be fixed in 3.0?

**Comment by eroux** [comment]
I don't think so...
