### ISSUE TITLE
Horizontal episema over salicus doesn't render correctly.

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#511]
This comes from Sr. M. Ruth OSB of Abbazia Mater Ecclesiae via the gregorio-user list.

this gabc:
```
name: Salicus episemato;
initial-style: 0;
%%
(c4) fhOj___(fhOj___) (::) f_hOj(f_hOj) (::) fhO__j(fhO__j) (::)
```
in Gregorio 3.0 produces:
![image](https://cloud.githubusercontent.com/assets/421318/8267204/221415d8-1724-11e5-9aac-bd7d734f679f.png)

The `develop` branch produces something slightly different, but still wrong:
![image](https://cloud.githubusercontent.com/assets/421318/8267202/0433c090-1724-11e5-9c25-fd7fd6ae3c46.png)

**Comment by henryso** [comment]
Since the horizontal episema code is very different in `develop`, and this will likely require new positioning cases, this would be two separate fixes (for 3.0 and for `develop`) if we want to fix this in a patch to 3.0.  Should I try to fix this in 3.0 or just in `develop`?

**Comment by eroux** [comment]
I'd say develop in priority, but if it's not overly complex, it would be good to have it backported in 3.0 too, as Gregorio 4.0 might not be out tomorrow...

**Comment by henryso** [comment]
We're pretty close to a 4.0 beta at this point.  Do we still intend to release a 3.0 patch with this fix in it?

**Comment by rpspringuel** [comment]
I would.  Given how the release process for 3.0 went, it will take a couple of months to go from the 4.0-beta to a final release.  Seeing as the fix is already done, I see no reason why we can't merge it into master and make a 3.0 release with it.

**Comment by henryso** [comment]
Since you are the release master (and indeed the only person who can build for MacOS at this time), I'll leave it to you to decide when to do that.
