### ISSUE TITLE
Support generation of lilypond-like textedit links

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#528]
This idea comes from http://www.mail-archive.com/gregorio-users%40gna.org/msg02769.html

The format of the URL is `textedit://{filename}:{line}:{char}:{column}`.  Line and column appear to be 1-based and char is the character-offset from the beginning given line, 0-based.  Column expands tabs.

Links would be created for score glyphs and for syllable text.

This feature would be disabled by default.  You would need to enable it both when calling `gregorio` to generate additional information in the `gtex` files (because this "leaks" filenames into the gtex file) as well as in the TeX code (which is possible to drive strictly based on whether the additional information is in the `gtex` file, but I like the idea of toggling it from TeX as well).

Obviously, it would be disabled if `gregorio` is reading from stdin since it can't know the filename.

https://www.tug.org/pipermail/pdftex/2006-March/006475.html shows how to generate links without LaTeX and hyperref.

**Comment by igneus** [comment]
Wow! I'm afraid I love you :)

**Comment by igneus** [comment]
Oh, sorry, not yet. :) I thought it's already a PR.

**Comment by henryso** [comment]
Good code takes time :)

**Comment by henryso** [comment]
@igneus The pull request is ready.

You will need to set `\gresetpointandclick{on}` to enable this from TeX and compile your scores with '-p' (which is automatic if you are using auto- or forced- compilation, but you might have to delete pre-existing auto-compiled gabc files, as the timestamps would not have changed).
