### ISSUE TITLE
Consider drawing braces using metapost or tikz

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#535]
We currently draw braces by stretching out glyphs in the font.  This is fine as long as the aspect ratio is fairly close to the original, but when it's stretched far, the glyph begins to look funny, being thicker horizontally than vertically.  This is true also when the glyph is compressed, but less obvious since this condition is less likely and less noticeable given the original aspect ratio.

This is a low priority item stemming from a thought in #454, but since that issue is closed, I'm opening this to track it.

**Comment by eroux** [comment]
Note that apart from basic Metapost learning, this is quite straightforward with [luamplib](https://github.com/lualatex/luamplib)

**Comment by henryso** [comment]
TeX Live comes with cmarrows, which looks like it produces pretty good-looking (curly) braces.  Is it too much of a dependency to use that?  We'd still have to implement round braces.

**Comment by eroux** [comment]
Why not, I admit I didn't know the existence of metapost packages, but I think it's a good way to go!

**Comment by eroux** [comment]
(well, I admit I find cmarrows curly braces good-looking for math, but I find them too flat for music)

**Comment by eroux** [comment]
There's a better example page 9 of [metaflow manual](http://www.utdallas.edu/~hamlen/metaflow.pdf)

**Comment by jakubjelinek** [comment]
Yeah, the current gregorioTeX ones are nice if they aren't too stretched.  Would be nice to get similarly looking ones for the non-stretched case.

**Comment by henryso** [comment]
The metaflow braces do look much nicer for music.  However, metaflow does not appear to be part of TeX Live, and metaflow is licensed under the LPPL, which, as far as I know, is not compatible with the GPL.

**Comment by eroux** [comment]
It was mainly an example, I'm sure it's quite easy to draw it by hand...
