### ISSUE TITLE
Files missing from windows/gregorio.iss

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#549]
I'm not entirely sure how this file works, but based on feedback from gregorio-users, I think the following files are missing from this `[Files]` section:

- tex/gregorio-vowels.dat
- tex/gregoriotex-nabc.tex
- tex/gregoriotex-nabc.lua
- tex/gregoriotex-signs.lua
- tex/gregoriotex-main.tex

**Comment by rpspringuel** [comment]
It would help if I tested things before uploading them, wouldn't it?

Turns out those weren't the only files missing, but I'm fairly sure I've gotten them all and have uploaded a working Windows installer.
