### ISSUE TITLE
writemode and setfirstannotation conflict

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#55]
If the user manually indicates an annotation in their TeX file, `\writemode` should not overwrite it with the mode from the gabc file.  This could be accomplished by having `\writemode` check to see if there are contents in the box containing the first annotation before entering the mode (and refraining from doing so if there is some thing there), or by having `\setfirstannotaion` change a flag which controls whether `\writemode` does anything.  In the latter case the flag would need to be reset at the end of the score (to allow for multiple score inclusions).

**Comment by eroux** [comment]
That's right, indeed!
