### ISSUE TITLE
TeXLive integration

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#551]
Putting here everything for TeXLive integration into one issue.

- https://mail.gna.org/public/gregorio-devel/2015-08/msg00005.html
- https://mail.gna.org/public/gregorio-devel/2015-08/msg00004.html

Also, as `fonts/Makefile` is supposed to go in the TDS, `install-gtex.sh` is not usable without running the autotools, `./configure`, etc. which makes no sense in the context of the source tarball. So I think the best solution is to remove `Makefile` from `install-gtex.sh` if it's ok for you.

**Comment by eroux** [comment]
Also, `greg-book.engine` should be executable. @rpspringuel could you also convert the different `.engine` script to posix `sh`? This would allow them to be included in TeXLive directly, thus avoiding user configuration.

**Comment by henryso** [comment]
@eroux When you say "remove `Makefile` it from `install-gtex.sh`", do you mean to stop `install-gtex.sh` from installing `Makefile` or to replace `install-gtex.sh` with `Makefile` functionality?

**Comment by eroux** [comment]
The first option

**Comment by henryso** [comment]
The patches look fine on initial review.  I will apply them tonight or tomorrow night if someone else doesn't beat me to it.

**Comment by rpspringuel** [comment]
Both of the `.engine` files are obsolete, so there is no point in fixing them for TeXLive integration.  We'd be better off moving up the removal time table and just deleting them.

**Comment by rpspringuel** [comment]
Actually, checking the changelog, they should be scheduled for removal in 4.0.0 since they were deprecated in 3.0.0.  I'll submit a pull request to that effect.

**Comment by rpspringuel** [comment]
On the issue of upgrading flex, based on what I can find, flex 2.5.39 won't build on a Mac.  I've seen a couple of different proposed patches (one on the [MacPorts site](https://trac.macports.org/ticket/46378) and one on the [flex site](http://sourceforge.net/p/flex/bugs/182/)), but as of yet, no fix has been implemented.  As a result, I can't upgrade flex on my Mac at the moment (I'm currently running 2.5.37 there, the most recent version which builds on a Mac).

However, I should be able to upgrade it on my Ubuntu VM.  I'll see what I can do about that.

**Comment by rpspringuel** [comment]
Okay, after some further research, I discovered that Homebrew does have flex 2.5.39 available in it's system and so I've been able to install it on my Mac.  I still have to work out the details of forcing the use of that version of flex rather than the MacPorts version.

**Comment by eroux** [comment]
From another mail:

    Elie,
    
    if so you might want to change 'St. Gallen' in GregorioNabcRef.tex into
    either 'St.\ Gallen' or 'St.~Gallen' (and probably more of the same).

**Comment by rpspringuel** [comment]
Okay, I think I've worked out how to build with flex 2.5.39 on my Mac, but I don't know how to tell if the build process is actually using that version of flex or not.  Does anyone know how to tell which version of flex was used for a particular build?

**Comment by henryso** [comment]
Look at the generated *-l.c file for a section like:
```
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif
```
the major/minor/subminor values are the ones you want.

**Comment by rpspringuel** [comment]
Thanks.  Turns out that the first thing I tried wasn't using the more recent version of flex after all.  However, I was able to get it to use it through a different route.  As a result, all future builds I make should make use of flex 2.5.39.

**Comment by henryso** [comment]
I would consider producing another beta release soon.  I'd like to know if the changes we're made pass Peter Breitenlohner's tests.  The patches he sent to @eroux were against the source tarball, and he uses really cutting-edge compilers with aggressive warnings, so it would be good to know that we are clean.  I don't know what the TeXLive inclusion deadlines for 2016 are.

**Comment by eroux** [comment]
Deadlines for TL2016 are something like march or april 2016, so we definitely have time... I just wanted to be sure that the 4.0 we release can be included as is...

**Comment by rpspringuel** [comment]
I'm headed out of town for a week starting tomorrow (it's my last trip of the summer).  If I'm going to build a new beta, it'll have to be either later today or when I get back.  Is there a preference on the timeline, or does someone else want to take charge of building of the next beta?

**Comment by henryso** [comment]
Unless @eroux has some overriding reason, I would wait for your return since we have time to get into TL2016 and we can let the users test a bit more.

**Comment by henryso** [comment]
I'm working on including the latest fixes for TeX Live integration.

**Comment by henryso** [comment]
I suppose since they have actually pulled us into their tree, this issue is done.  We can open new issues if there are integration problems in the future.
