### ISSUE TITLE
/bin/bash: encode_utf8strings : commande introuvable

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#562]
I get this error while launching `make dist` with last commit in develop : a workaround is to drop `src/encode_utf8strings` somewhere in `$PATH`, but I guess there is something missing in Makefile.

**Comment by eroux** [comment]
What error?

**Comment by henryso** [comment]
It's unable to find the built executable.  I'll fix it.

**Comment by eroux** [comment]
Oh sorry, didn't spot it in the title

**Comment by henryso** [comment]
@jperon This should fix it. Please try again.

**Comment by jperon** [comment]
Ok, this works ; closing this issue.
