### ISSUE TITLE
Deprecation in configure.ac

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#57]
When I'm getting the following warning when running autoreconf on my machine:

    configure.ac:25: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
    configure.ac:25: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
    configure.ac:25: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.

I don't know much about this sort of thing, though, so I'm not sure what to do with it without doing some research.

**Comment by eroux** [comment]
I believe it comes from outdated macros in the m4/ directory... This is something done by a friend at the beginning of Gregorio, and I should document and update all that... but as it's just a warning (for now), priority is quite low...
