### ISSUE TITLE
missing GregorioNabcRef.pdf in windows installer

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#572]
The Nabc reference file is missing from the windows installer.

**Comment by rpspringuel** [comment]
Two questions before I fix this:

1. Should this file be incorporated into the main documentation file as a separate section?

2. If not, should this file get tagged with a version number the way GregorioRef is in a distribution?

**Comment by henryso** [comment]
My opinion: I think it should stay separate for now, at least until Nabc is deemed stable.  I think it will evolve along with Gregorio, so I think it should be tagged with a version as is GregorioRef.

**Comment by rpspringuel** [comment]
Looking at the Makefile, I noticed that it actually is tagged with the version number there.  I hadn't noticed that before.

It's too late for me to work on this tonight, but I'll add this in the morning (some 11 or so hours from now).

**Comment by eroux** [comment]
I agree with @henryso
