### ISSUE TITLE
GCC errors in `gabc-score-determination.y`

### ISSUE THREAD

**Issue by eschwab** [gregorio-project/gregorio#577]
Compiling a034929c76fee8a07d4052e9967b62cb6c94be41 and gcc gives the following:

    gcc -DHAVE_CONFIG_H -DBRANCH_VERSION='"develop-a034929-2410"' -I.  -I../src -I../src/gabc  -I../src/dump  -I../src/gregoriotex -D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2   -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=gnu89 -pedantic-errors -fstack-protector-strong -fPIE -Wformat -Werror=format-security -Wstrict-prototypes -Wall -Wextra -MT gabc/gregorio-gabc-score-determination-y.o -MD -MP -MF gabc/.deps/gregorio-gabc-score-determination-y.Tpo -c -o gabc/gregorio-gabc-score-determination-y.o `test -f 'gabc/gabc-score-determination-y.c' || echo './'`gabc/gabc-score-determination-y.c
    gabc/gabc-score-determination.y: In function ‘gabc_score_determination_parse’:
    gabc/gabc-score-determination.y:691:32: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("name", score->name);
				    ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:713:42: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("gabc-copyright", score->gabc_copyright);
					      ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:720:43: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("score_copyright", score->score_copyright);
					       ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:730:44: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("GregorioTeX font", score->gregoriotex_font);
						^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:737:39: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("office part", score->office_part);
					   ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:744:36: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("occasion", score->occasion);
					^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:751:33: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("meter", score->meter);
				     ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:758:38: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("commentary", score->commentary);
					  ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:765:36: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("arranger", score->arranger);
					^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:826:34: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("author", score->si.author);
				      ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:833:32: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("date", score->si.date);
				    ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:840:38: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("manuscript", score->si.manuscript);
					  ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:847:48: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("manuscript-reference", score->si.manuscript_reference);
						    ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:855:17: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
		     score->si.manuscript_storage_place);
		     ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:862:32: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("book", score->si.book);
				    ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:869:39: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("transcriber", score->si.transcriber);
					   ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^
    gabc/gabc-score-determination.y:877:46: error: passing argument 2 of ‘check_multiple’ makes integer from pointer without a cast [-Wint-conversion]
	     check_multiple("transcription date", score->si.transcription_date);
						  ^
    gabc/gabc-score-determination.y:97:22: note: expected ‘bool {aka unsigned int}’ but argument is of type ‘char *’
     static __inline void check_multiple(const char *name, bool exists) {
			  ^

gcc version `5.2.0`

**Comment by henryso** [comment]
In `src/config_.h`, what is HAVE__BOOL defined as?

**Comment by henryso** [comment]
If there is no definition of HAVE__BOOL, could you try re-running `autoreconf -fi` and building again?

**Comment by henryso** [comment]
See #578.

**Comment by eschwab** [comment]
Fixed by #578 

To be complete, I ran `autoreconf -fi` and `src/config_.h` does not define `HAVE_BOOL`
