### ISSUE TITLE
Mode annotation should be suppressed when initial-style is 0

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#592]
From Sr. M. Ruth OSB (Abbazia Mater Ecclesiae):

If a .gabc file with initial-style:0; has the “mode” field filled with something, and this file is included without commenting the "mode" field, that string appears over the first initial letter of the following score.

**Comment by rpspringuel** [comment]
This is probably as simple as making sure the annotation box is empty at the end of a score.  I.e. add `\setbox\gre@box@annotation=\box\voidb@x` to the end of score macro.

**Comment by eschwab** [comment]
I cannot reproduce this bug.

    name: test;
    initial-style: 0;
    mode: 4;
    annotation: 1 Ant.;
    annotation: {\color{red}VII A};

And the pdf looks as expected. I have tried moving the location of `initial-style` but that makes no difference.

**Comment by henryso** [comment]
You need two scores, with the first score with initial-style:0 and mode:whatever, and the second score with initial-style:1.  Then include both.  The mode appears on the second score.

**Comment by eschwab** [comment]
I get it now. Fixed by #593
