### ISSUE TITLE
weird spacing issue in gregorio-v4.0.0beta2

### ISSUE THREAD

**Issue by asbloomf** [gregorio-project/gregorio#595]
I have the same chant included twice, but the text on the line that needs to be lower ("Et Jesum, benedictum fructum" only works the first time.  It seems to have something to do with the first one being in braces.  This was the smallest I could get the code down to still reproduce the issue.  If I remove the first set of braces, both chants work.  Also if I remove the \greannotation from the second one, it works fine.

gist: to clone <https://gist.github.com/f454ddd7ab9baa39954b.git>, to view in a browser <https://gist.github.com/f454ddd7ab9baa39954b>

**Comment by henryso** [comment]
This is a one-line fix that you can apply to your gregoriotex-main.tex to get it working prior to the next release.  Simply add
```
\global\setluatexattribute\gre@attr@glyph@id{0}%
```
to `\GreEndScore` before the final `\relax`.

**Comment by asbloomf** [comment]
Thanks.

**Comment by eschwab** [comment]
Fixed by #596
