### ISSUE TITLE
Joining of ledger lines

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#598]
E.g. in http://gregobase.selapa.net/chant.php?id=2771 one can compare that gregorio does not join adjacent ledger lines on Gloria IX, while Solesmes books join them (Graduale Triplex, Liber Usualis, ...), e.g. on "Qui tollis pec" there is a single ledge line, even across two lower notes (for "cata mun" it is not joined, because the lower notes are higher), or "Tu solus" is joined.
Does or should gregorio have some way to turn on more aggressive ledge line joining?

**Comment by eroux** [comment]
Maybe we should try to make some specifications, but it would certainly requires a few options... do you have something in mind (like join ledger lines that are distant of at most x mm)?

The implementation is not obvious, but now there is the experience and the necessary code to dump some dimension information in an aux file and use it in a second pass, so it shouldn't be too difficult to hook in that.

**Comment by henryso** [comment]
Solesmes is not even consistent.  In that same chant you are looking at, notice that, on the following line, "-cata mundi," the ledger line is not connected from "ca" to "mun," even though the distance between them is less than from "tol" and "pec," so maybe the best thing would be to have a "nlba"-type notation to say "extend ledger lines here"?

**Comment by eroux** [comment]
Why not indeed

**Comment by henryso** [comment]
I actually misspoke slightly, since this is a note-level thing rather than a text-level thing, so my suggestion is more "ocba:{" (inside the parentheses) than "nlba".

**Comment by jakubjelinek** [comment]
Manual control over it would be certainly nice for fine tuning.  Plus I guess detailed investigation is needed to see if we can find an algorithm from the Solesmes books, will try to gather enough snippets to analyse this week.  I bet it isn't related to distance in exact length, but more on how many and what kind of neumes are in between and what pitch they have (plus of course only among notes on the same line).

**Comment by eroux** [comment]
@jakubjelinek did you manage to gather a few example and try to determine an algorithm? In the meantime, I got an example from an Abbey of something they would like to achieve: they would like the ledger line to reach the flat in

![neume4](https://cloud.githubusercontent.com/assets/60868/11632887/1b4c64a6-9d09-11e5-9af4-0377b4a15053.png)

**Comment by jakubjelinek** [comment]
Not yet, sorry, it is in my todo list.

**Comment by eroux** [comment]
Here's a proposal:

`[xll:yz]`

with

- `x` being `o` for ledger line above staff lines, `u` for ledger line below
- `y` being `0` to start the ledger line strictly on the beginning of the note, `1` to start the ledger line further left, with the same length as what we currently do (which is a punctum width or something)
- `z` being on `{` or `;xmm`, with the same meaning as in `ocba`, etc.

What do you think? Do you think the length of the ledger line on the left of the note should be tunable too?

**Comment by eroux** [comment]
thinking back about it, I think it would be useful to control the left width of the ledger line, so `y` could be `0`, `1` or any other value, if it's not 0 or 1, it will be passed to TeX as the left width. Wdyt?

**Comment by henryso** [comment]
If it will be useful to control the left width, I think it would be useful to control the right width as well.  For example, if you are drawing a line from some note until some note, and want to adjust the distance to the left of the first note, it's likely you'll want to adjust the distance to the right of the last note as well.  Probably the `0` and `1` settings even make sense to the right of the last note.

**Comment by eroux** [comment]
You're right indeed... how do you propose to note that? maybe `z` could be `{0` (or `{1`), `{xmm` or `;xmm`?

**Comment by henryso** [comment]
That sounds like a good way to do it.

**Comment by eroux** [comment]
I think this can be closed once #744 is merged, if we come up with new heuristics we can reopen it

**Comment by henryso** [comment]
OK.

**Comment by olivierberten** [comment]
Sorry to revive such an old bug...
Is there a way to have this work across line break?

In this example https://gregobase.selapa.net/chant.php?id=2659 on _suscipe_, I first encoded it as in the original but since a line break happens in the middle, it doesn't work at all.

I'd guess it's, like the flats, something to be adapted once the final layout is done, but if there's a way to make it work better that would be easier ;-)

By the way, is there a list somewhere of the features that get broken or need to be changed when line break happens at a different place?

**Comment by henryso** [comment]
We would need to have a concrete set of rules to follow.  Do you have auggestion?

**Comment by olivierberten** [comment]
If a line break happens between `[oll:1{1]` and `[oll:}]` I would expect the ledger to go until the end of the line and start again at the beginning of next line.
