### ISSUE TITLE
prepare for local discpenalty

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#603]
A change should appear in the next few days (or hours) in LuaTeX for [local disc penalties](http://tracker.luatex.org/view.php?id=928). It will certainly come with LuaTeX of next TeXLive, so I think we should prepare now. The idea is the following:

- we want clef change to have a specific penalty
- clef change are discretionaries
- other things could be discretionaries in the future, with other penalties
- currently all the discretionaries of a paragraph share penalty (which is the value of `\discpenalty` at the end of the paragraph)
- with the future version of LuaTeX, discretionaries' penalty will be the current value of `\discpenalty` when the discretionary is created, so in the same paragraph, discretionaries can have different penalties

To have a discretionary with a speciic penalty, one can do something like

    \begingroup
    \discpenalty mypenalty
    \discretionary{what}{e}{ver}
    \endgroup

What I propose is the following: the `\GreDiscretionary` macro should take an additional argument, which would be a type (it would have only one possible value now, `0` which would mean `clef change`). Then the `\discpenalty` would be set according to the type, inside a group. To be backward compatible, we should keep the current behavior (which is to set `\discpenalty` to the clef change penalty for the whole paragraph), but it could be marked as deprecated, with a removal date of summer 2017.

What do you think?

**Comment by henryso** [comment]
I don't feel qualified to speak to the code behind this, but the logical argument makes sense to me, and doing it in 4.0 sounds like a good idea.  One thing I would change, however, is to relabel this issue as an enhancement rather than a bug.

**Comment by eroux** [comment]
Indeed, the labelling was a mistake (I didn't want to label it that way)

**Comment by henryso** [comment]
Is everything for this issue done?

**Comment by eroux** [comment]
current state is ok yes
