### ISSUE TITLE
bolshift alignment for fa and do clef

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#607]
When a score contains both lines which begin with a do clef and ones which begin with a fa clef the first notes on those lines do not align with each other; the notes on the fa clef lines are indented a bit further than the ones on the do clef lines.  This is likely due to the fact that the calculation for `bolshift` uses the width of the current clef and the fa clef is a bit wider than the do clef.

![page](https://cloud.githubusercontent.com/assets/7671682/9838191/bbc61062-5a24-11e5-83ab-b296c38a074b.png)

It should be possible to adjust the calculation of `bolshift` so that these first notes align.  This may involve getting the executable to pass a command early in the score which indicates if the score has any fa clefs in it.

**Comment by eroux** [comment]
I think there should also be an option to switch from the current behavior (not aligning) and the new one, some might prefer the current one... Does the case appear in Solesme's books?

**Comment by henryso** [comment]
I'm hard-pressed to find a case of switching between do and fa clefs in my Solesmes books.

**Comment by rpspringuel** [comment]
I've also noticed that the issue crops up when switching between a flatted clef and one without.  Though I'm not sure that would be any more common a switch.

**Comment by eschwab** [comment]
Found an example in the Graduale p.456 (Gloriosus Deus). The first notes are _not_ aligned between the fa and do clefs, like the example posted above.

**Comment by rpspringuel** [comment]
Given what @eschwab found, I'm going to mark this as "Won't fix" and close.
