### ISSUE TITLE
\includescore leaves behind outdated gtex files.

### ISSUE THREAD

**Issue by eschwab** [gregorio-project/gregorio#61]
Since #58 `\includescore` now automaticlly generates gtex file if necessary. This behavior now causes old outdated gtex files (with the wrong gregoriotex API version) to remain behind in the filesystem. Those files should be cleaned up.

Need to keep in mind that not all scores are in the same dir as the main.tex file. Also accommodate `/` or `\` for filepaths. `os.remove` does not accept globs and `os.command('rm')` is not portable to Windows.

[This](https://github.com/lualatex/lualibs/blob/master/lualibs-dir.lua) may be of help here.

**Comment by eschwab** [comment]
I put some time into issue and ended up with this code. It works for the most part (don't know about Windows), however there is a problem. Let the tree look like:

    Test/
    - test.tex
    - antiphon.gabc
    - antiphon-10020909.gtex
    |-- subdir/
    |    - ant2.gabc
    |    - ant2-10020909,gtex

When `pwd = Test` and the cmd is `lualatex --shell-escape test` everything works as intended. Both outdated gtex files are deleted, new ones are autocompiled.

When `pwd = Test/subdir` and the cmd is `lualatex --shell-escape ../test` it fails because it is looking for a dir named `subdir` which is the current dir (it wants `Test/subdir/subdir`). Basically the problem is running `lualatex` from a dir different from the location of `test.tex`. I need to get the full or relative path of the `test.tex`. Unfortunately `\jobname` only gives `test`. Other solutions to getting a better path include using more command line options and I don't want to go there.

At this point this code broken and I don't have a solution to fix it.

    local function clean_old_gtex_files(file_withdir)
        local filename = ""
        local dirpath = ""
        local onwindows = os.type == "windows" or
        string.find(os.getenv("PATH"),";",1,true)
        if onwindows then
        dirpath = string.match(file_withdir, '(.*)\\')
        else
        dirpath = string.match(file_withdir, '(.*)/')
        end
        if dirpath then
        filename = '^'..file_withdir:match('.*/'..'(.*)')..'%-[0-9].*%.gtex$'
        for a in lfs.dir(dirpath) do
            if a:match(filename) then os.remove(a) end
        end
        else
        filename = '^'..file_withdir..'%-[0-9].*%.gtex$'
        for a in lfs.dir(lfs.currentdir()) do
            if a:match(filename) then os.remove(a) end
        end
        end
    end

Add `clean_old_gtex_files(file_root)` to `gregoriotex.lua:205`

**Comment by eschwab** [comment]
Upon further testing I found that the `lualatex` command should be from the same directory as the main tex file. Otherwise `\includescore` commands with relative arguments don't work. It seems that tnis fix is possible.

**Comment by eroux** [comment]
Interesting, never thought about that... I guess jobname should be split according to path separator, and all directories before the actual filename should be append before relative path. For instance: if jobname is `../myfile.tex`, then relative path for score inclusion should be prefixed with `../`

**Comment by eroux** [comment]
Forget my previous commentary, I was wrong in my tests... I'll ask about this on stackexchange, I admit I don't know the answer.

**Comment by eroux** [comment]
See [this post](http://tex.stackexchange.com/questions/232358/get-path-of-source-file-when-compiling-from-another-directory?noredirect=1) , the method is basically to check the command line arguments. The example code is not complete and needs some adaptation, but it should not be difficult.

**Comment by eschwab** [comment]
Ok I see that method would work. However after thinking about this some more, trying to get a better path seems contrary to the intended behavior of Tex. It really does assume that it is being run from the same directory as the main.tex. If there is a `\input{myconfig}` Tex cannot find that file if run from a different dir i.e. `lualatex ../main.tex`. It looks for `myconfig.tex` and not `../myconfig.tex`.

So making a more robust way to get a better relative path to our score files does not seem necessary if Tex will still have problem finding other files. To me, now this is more just a point of interest rather than something that we need to find a solution to. I have never run into this before since I have always run `lualatex` from the same dir.

**Comment by eroux** [comment]
Sure, we can leave it like this, it's no emergency
