### ISSUE TITLE
Negative Space 

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#617]
Currently one can introduce extra space into a score with `/`, `//`, and ` `.  Occasionally it would be useful to be able to do the opposite: introduce a negative space which forces thing closer together. I would suggest that the gabc for this should be `\`, `\\`, and `_` (assuming these won't screw up the parser).  Functionally, on the TeX side, I would add an extra argument to `\GreEndOfElement` (which currently handles the forward spaces) which would indicate direction (`r` and `l` for instance). 

Requested by Sr. M. Ruth.

**Comment by eroux** [comment]
I'm not entirely sure it's a very good idea... people would probably use it at beginning of syllable note where it would mess alignment... Do you have an example of a case where this feature would be a good option?

**Comment by henryso** [comment]
Backslashes are probably OK, but underscore would conflict with episema.

**Comment by rpspringuel** [comment]
@eroux, I'm just passing along a request which I thought was technically feasible.  I don't personally have an explicit use case.  Sr. M. Ruth's request ([on the mailing list](http://www.mail-archive.com/gregorio-users@gna.org/msg03006.html)) was related to wanting to bring a single syllable back up to a previous line manually (to prevent a score from ending with a single syllable line).

@henryso, I forgot about the episema, thanks for pointing that out.  Perhaps `-` would be the better choice than.  I think it's still available.

**Comment by henryso** [comment]
Speaking *personally*, I'd probably prefer it to be `\\\`, so as not to take the `-` away --- that is, if this request is approved.

**Comment by eroux** [comment]
I understand, but I'm just concerned that a negative space before the syllable will just make the texts or notes of the syllables melt, or be too close... I think it would be better to reduce general spacing by a tiny amount than moving one syllable of a big amount... But it should be tried, maybe the result will be fine.

**Comment by henryso** [comment]
It *will* mess up alignment and cause syllables to melt and be too close, but I think that's the point.  That said, perhaps it would be better to suggest inserting a negative skip via a macro or texverb if you *really* want to do this rather than institute it as a gabc feature?  Would it be possible to introduce a negative skip via texverb?

**Comment by henryso** [comment]
The workaround of applying kerns via the <v> tag is working for Sr. M. Ruth.  Since this is a dubious feature, perhaps we should just leave it at that and close as "won't fix"?

**Comment by eroux** [comment]
I think that's the best option
