### ISSUE TITLE
Alt text (above lines) and braces not wrapping to new lines

### ISSUE THREAD

**Issue by matthewgonzalez** [gregorio-project/gregorio#618]
Hey all, 

Loving the work done in the recent months! There has been an unfortunate bug introduced with the upgrade to 4.0.0-beta2-develop.

The alt/abovelinestext and braces are causing the ends of lines to not wrap and spill out past the staff lines. See attached pics.
![screen shot 2015-09-22 at 8 45 37 pm](https://cloud.githubusercontent.com/assets/1775184/10036347/e10b0dfc-616b-11e5-83ac-5abd4138dd3e.png)
![screen shot 2015-09-22 at 8 46 13 pm](https://cloud.githubusercontent.com/assets/1775184/10036348/e700bbd0-616b-11e5-8a63-e776c0e89c08.png)

Regards,
Matthew

**Comment by rpspringuel** [comment]
Can you provide a MWE (both gabc and tex files) which demonstrates the bug?  It is easier to diagnose and fix bugs if we don't have to recreate them first.

**Comment by matthewgonzalez** [comment]
Sorry, knew I should've include something in the first place. Here is a paired down snippet of the code in the first example given above.

https://drive.google.com/file/d/0B0HAgIrWw9AUWjZsOVlTOGFzT0U/view?usp=sharing

**Comment by rpspringuel** [comment]
This is not related to the alt text.  If it was then the bug would appear at the end of the first line in the attached example.  Removing all the alt text also does not eliminate the bug.

It also does not appear to be related to the brace, as removing it also preserves the bug.

I've been able to strip the example down considerably and still produce the bug:

```
\documentclass[10pt]{article} % use larger type; default would be 10pt

\usepackage{libertine}
\usepackage[autocompile]{gregoriotex}


\paperwidth = 125mm\relax
\paperheight = 176mm\relax
\oddsidemargin = -1in\relax
\advance\oddsidemargin by 1.5cm\relax
\evensidemargin = \oddsidemargin\relax
\topmargin = \oddsidemargin\relax
\textwidth = \paperwidth\relax
\advance\textwidth by -3cm\relax
\textheight = \paperheight\relax
\advance\textheight by -3cm\relax


\begin{document}
\grechangestaffsize{11}

\gregorioscore{Magn1simp.gabc}

\end{document}
```

and 

```
name: Magnificat-1D;
initial-style:0;
%%
(c4)
Ma(f)gní(gh)fi(h)cat(h.) (:)
á(h)ni(h)ma(h) <i>mé</i>(g)<i>a</i>(f) <b>Dó</b>(gh)mi(gr)num.(gf..) (::)
<b>Dó</b>(gh)mi(gr)num.(g.) (::)
<b>Dó</b>(g)mi(gr)num.(ghg.) (::)
<b>Dó</b>(g)mi(hr)num.(h.) (::)

<b>Dó</b>(g)mi(gr)num.(g.h.) (::)

<b>Dó</b>(gh)mi(gr)num.(g.h.) (::)

<b>Dó</b>(gh)mi(gr)num.(GvFED.) (::)

<b>Dó</b>(g)mi(gr)num.(GvFED.) (::)

<b>Dó</b>(gr)<b>mi</b>(gf)num.(d.) (::)
```

I don't know what's causing the bug, but maybe someone else has some ideas now that I've eliminated several possibilities.

**Comment by henryso** [comment]
Thanks for reducing the example.  I was studying the alt text code and saw nothing so I was really scratching my head there.

I think this is TeX doing its "magic".  Please see http://tex.stackexchange.com/questions/9107.

Put `\sloppy` before `\gregorioscore` and this problem goes away (the word is put on the next line).  We probably want this behavior in general for scores.  What do you think?

**Comment by eroux** [comment]
`\sloppy` can be ok in many cases, but users should be able to fine tune the different parameters assigned by it, see [this answer](http://tex.stackexchange.com/a/241355/33382). Most parameters (tolerance, etc.) can be set for scores only (see gsp-default.tex), you just need to fine-tune them. The default values for scores are very close to those of `\sloppy`, maybe they should be even closer, or maybe some penalties should be diminished...

**Comment by rpspringuel** [comment]
Given @henryso's diagnosis, I would not be in favor of simply applying `\sloppy` to scores.  To me, this is simply an instance where the default values for the penalties and/or spaces don't produce good results and the user should refine those parameters to get something they like better.  I'd be willing to entertain changes to the defaults, but I doubt we could come up with something which is universally "better".  Any set of values is going to have some corner case where they just don't produce good results, in which case the user is going to have to make manual adjustments.  Changing the defaults should require not just a single use case which is better, but should produce better scores more broadly.

**Comment by henryso** [comment]
I'm not advocating the use of `\sloppy`, but rather saying that for scores, we should somehow prevent TeX from attempting to squeeze the word into lines

**Comment by henryso** [comment]
Upon second look, the `\emergencystretch` setting of `\sloppy` messes up alignment of things like two dots after a pes.  So I'm *really* not advocating the use of `\sloppy`.  That said, I cannot intuit the correct settings to make this particular example come out "nice".

**Comment by henryso** [comment]
If there is no good way to make TeX do the right thing here, then perhaps the best suggestion would be to suggest that users either play with the spaces for the given score to make things work out better or force a line break before the offending syllable with `(z)`.  How does that sound?

**Comment by henryso** [comment]
No further comment?  Do we close this as a TeX oddity with `(z)` as workaround?

**Comment by rpspringuel** [comment]
I think so.  I don't think this is something that we can fix, at least not in all cases.

**Comment by henryso** [comment]
@matthewgonzalez This appears to be due to the "fussy" TeX line-breaking algorithm.  After some research, it doesn't appear that there is a way to solve your case without breaking others.  We suggest that you insert a manual line break (using your example, `<b>Dó</b>(g)mi(grz)num.(GvFED.)`) or, alternately, play with the various spacings (see `gsp-default.tex` and the PDF documentation) in order to get a satisfactory result.

Closing this issue as not resolvable.
