### ISSUE TITLE
Documentation discrepancy in grechangestyle

### ISSUE THREAD

**Issue by avbop** [gregorio-project/gregorio#621]
GregorioRef-4_0_0-beta2.pdf lists `initial` and `biginitial`, but [UPGRADE.md](https://github.com/gregorio-project/gregorio/blob/develop/UPGRADE.md#styling-score-elements) lists `greinitial` and `grebiginitial`. In my testing, simply `initial` works.

**Comment by rpspringuel** [comment]
Fixed via fcb648c
