### ISSUE TITLE
Undefined control sequence \GreCPSalicusOneTwoDescendens

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#622]
When typesetting from Nocturnale Romanum 2002, pg. 126, I run into an error with current (but even a month old) gregorio develop:
il(hiOk>)la(hihho~)
With
il(hiOk)la(hihho~)
it is typeset fine, though not the intended shape I need (salicus liquescens, so instead of the upper note note that looks like kv it should look like k>).

**Comment by henryso** [comment]
This is actually a missing shape.

**Comment by jakubjelinek** [comment]
Would it be difficult to add that?

**Comment by henryso** [comment]
No, I can do it.

**Comment by henryso** [comment]
Please see #624.

**Comment by jakubjelinek** [comment]
Verified, thanks a lot.
