### ISSUE TITLE
Distropha and tristropha liquescens

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#623]
If I want a liquescens tristropha, typing (gssgs<) results in all the strophas liquescens, rather than just the last one.  (gss/gs<) works fine, but as I really have no idea when somebody would actually want to write all the 3 (or 2) strophas liquescens rather than the last one, which is pretty common thing when trying to match manuscripts, I wonder if (gssgs<) or perhaps even (gsss<) shouldn't be parsed as liquescence only on the last stropha and if for whatever reason somebody wants all 3 liquescens, write (gs<gs<gs<) or something similar.

**Comment by henryso** [comment]
For what it's worth, I agree.

**Comment by henryso** [comment]
I would even posit that gsss< should result in a tristropha with the last liquescent.  Should I implement this change?

**Comment by henryso** [comment]
If this proposal is accepted, the pull request for the change is #625.

**Comment by jakubjelinek** [comment]
Verified, looks good, thanks.
