### ISSUE TITLE
Neography issue: Salicus with liquescens note after it connected to it

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#631]
In Nocturnale Romanum 2002, p. 17, I ran into a neumatic element that I've tried to type as:
non(efOhf>) (but that has the problem that the liquescens note is not connected with the previous note), or as non(efOh!f>) which looks almost right, except that the stem is too long and thus visible below the liquescens note.  I don't have corresponding St. Gall neumes for this antiphon (maybe
it is in the Bud. 118 codex, but I don't have access to that: http://cantusdatabase.org/id/003697 ), so not sure exactly what is it in the original.  The best shape would be like the non(efOh!f>) up to the top note, and then as if it is e.g. non(fhf>) - the top note and the last one.  Would it be possible to add this?
Shall it be typeset for (efOhf>) ?  If user doesn't want to connect them together, he can always type
(efOh/f>) ...

**Comment by eroux** [comment]
Could you make a scan of the neume in the Nocturnale Romanum?

**Comment by jakubjelinek** [comment]
Sure, here it is (though, I must say I like the ceciliae liquescens note shape much nicer than in this book):
![sal](https://cloud.githubusercontent.com/assets/9370665/10232679/660ab2a8-688a-11e5-9834-51d2fdb2fe4d.png)

**Comment by henryso** [comment]
Interesting.  Salicus flexus I guess.  This will be a whole family of glyphs.  If 4.0 is to be released soon, I would postpone this to after 4.0.  It could introduce a bunch of bugs.

**Comment by jakubjelinek** [comment]
Ok, I think I can live with that efOh!f> for now.  Perhaps it is gabc equivalent of nabc sa!cl> , sa1!cl> , sa1!cl-> or something similar.  And indeed, there is sa!cl too, so another perhaps needed shape will be efOhf connected together.

**Comment by henryso** [comment]
Yes, a family would typically cover all liquescentia at the end.  I would probably exclude initio debilis unless there is an example of such a thing.
