### ISSUE TITLE
VersionManager and CHANGELOG

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#639]
It would be really useful if `VersionManager.py` would update CHANGELOG by inserting the version number and date (and a couple of blank lines) below the `## [Unreleased][unreleased]` line.  I often forget to do this as part of prepping a release and end up having to make a separate commit (and move the version tag) as a result (see 8996797, for example).

I can do this myself, I just don't have the time right this minute to implement it.  I'm posting the issue as a reminder to get this done, or so someone else can beat me to it.

**Comment by henryso** [comment]
Fixed by #646.
