### ISSUE TITLE
Manual custos and automatic custos (on clef change) have inconsistent spacing

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#642]
The manual custos of a figure like `(g+::c3)` has additional space behind it compared to `(z0::c3)`.  It is actually coded this way: `\GreManualCustos` adds the space before calling `\GreCustos`.  As such, it works as coded.

Neither I nor @rpspringuel know whether this is the desired behavior or is just some inconsistency that worked its way into the code (and thus would be considered a bug).

Does anyone know the history here?  Is this a bug?

**Comment by henryso** [comment]
If no one knows the history behind this (probably @eroux would be the best to speak to that), then does anyone have an opinion on the correct behavior?

My not-very-strong opinion is that we should set that space to 0 by default and apply it before both the `g+` and `z0` custos, but not to the end-of-line custos.

**Comment by henryso** [comment]
Sr. Maria Ruth OSB, who brought up this issue on the mailing list, says this:

> My simple thoughts are that all custos should be equally treated, obviously when they are at the end of a line shouldn't be followed by a space.

**Comment by eroux** [comment]
Neither do I have a strong opinion, I guess treating all custos inside a line equally is consistent, and maybe set the space to 0 is good too...

**Comment by henryso** [comment]
I'll work on this and submit a pull request.  Should this be in 4.0.0?

**Comment by henryso** [comment]
It turns out that `spacebeforecustos` is actually applied to the end-of-line custos, so zeroing it out is a bad idea.  However, if I apply it to both the `g+` and `z0` figures, the space is very wide because (I think) the end-of-element space (whichever case it happens to be), which would have been swallowed at the end of the line, is placed before the custos (and `spacebeforecustos`) in the middle of a line.  Can anyone confirm or disprove this finding and, if true, give me a hint on how to combine the end-of-element space with the `spacebeforecustos` so that the space is the maximum of both spaces and not the sum of both spaces?

**Comment by rpspringuel** [comment]
I haven't done any checking to see if what you're getting is true (though it does sound right), but perhaps the easiest thing to do would be to split `spacebeforecustos` into `spacebeforeinlinecustos` and `spacebeforeeolcustos`.  In this scenario one could then zero out the inline value without affecting the end of line value.

**Comment by henryso** [comment]
I tried that, and that does indeed help if there was a note before the custos.  To reduce the "too wide" space in this case, I set `spacebeforeinlinecustos` to be 0.  However, using those settings, if the custos immediately follows a bar (like at the end of `gabc-output/bugs/fix-569.gabc`), the custos touches the bar.  This might be the reason (in the annals of history) that the space was there in the first place.

I tried a few things, but I can't figure out a good way to deal with this in TeX without having the gregorio program detect it and use a different macro at that point.  Can you think of a way to fix this problem in TeX?

**Comment by rpspringuel** [comment]
So you're saying that a bar doesn't surround itself with the appropriate `spacearound...`, at least under some circumstances?  That itself sounds to me like another bug.  Is there some set of circumstances under which `spacearound...` should intentionally not be placed both before and after the corresponding bar?  Maybe @eroux can remember programming that behavior?

**Comment by eroux** [comment]
Well, sorry, I cannot remember anything about this...

**Comment by henryso** [comment]
That's a good clue.  The problem with touching is only on the final divisio finalis.  The final divisio finalis uses the end-of-line finalis macro as opposed to the in-line finalis macro, and changing this might break some edge cases where a final divisio finalis without any custos after it appears at the end of a line.  I don't have any more time to look into it this morning, but I'll most likely use a special macro to handle this case unless someone has a better suggestion.

**Comment by rpspringuel** [comment]
Perhaps the final divisio finalis macro should only be used if the absolutely last element of the score.

**Comment by henryso** [comment]
I tried that but the rubber space after the normal in-line divisio finalis can make things look a bit funny at the end of a line (this is from `tex-output/bugs/fix-43/fix-43.tex`):

![image](https://cloud.githubusercontent.com/assets/421318/10418647/3ce52b18-702f-11e5-960b-365d7b25732e.png).

I personally am not happy with how that looks, but I am willing to accept it if others think it is OK.  Otherwise, I will try to come up with some way to tighten that space with a special `\GreFinalCustos` macro.

**Comment by henryso** [comment]
Any comment on this?  Should I try to tighten that space or is this satisfactory?

**Comment by eroux** [comment]
I think it should be tightened

**Comment by henryso** [comment]
With a final custos macro, I can get it to look like this:
![image](https://cloud.githubusercontent.com/assets/421318/10462968/ad84113c-71af-11e5-8262-4f061096200f.png)
... with the space tuned to be like the one after the dagger in:
![image](https://cloud.githubusercontent.com/assets/421318/10462980/c0b74b8e-71af-11e5-93d1-3be50034e990.png)
Comments?

**Comment by eroux** [comment]
looks good!

**Comment by rpspringuel** [comment]
I agree.

**Comment by eschwab** [comment]
I also agree. It looks much better tightened.

**Comment by henryso** [comment]
The big question: release-4.0 or develop?

**Comment by eroux** [comment]
I don't have a very strong opinion, but I would say 4.0...
