### ISSUE TITLE
Problem with gregorio and multiline scores

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#65]
When I try to compile this score using `lualatex --shell-escape --interaction=nonstopmode mwe.tex`, it fails.  See output below.

###### score.gabc
%%
(c4) Line(c) One(d) (z) Line(c) Two(d)

###### mwe.tex
\documentclass[11pt]{article}
\usepackage{luatextra}
\usepackage{graphicx}
\usepackage{gregoriotex}
\usepackage[utf8]{luainputenc}
\usepackage{times}
\begin{document}
\includescore{score}
\end{document}

###### output
This is LuaTeX, Version beta-0.70.1-2014113017 
 \write18 enabled.
(./mwe.tex
LaTeX2e <2011/06/27>
LuaTeX adaptation of babel <v3.8m-luatex-1.5> and hyphenation patterns for engl
ish, dumylang, nohyphenation, loaded.
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size11.clo))
(/usr/share/texmf-dist/tex/lualatex/luatextra/luatextra.sty
(/usr/share/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texmf-dist/tex/latex/l3kernel/l3names.sty
(/usr/share/texmf-dist/tex/latex/l3kernel/l3bootstrap.sty
(/usr/share/texmf-dist/tex/generic/oberdiek/luatex.sty
(/usr/share/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/share/texmf-dist/tex/latex/etex-pkg/etex.sty)
(/usr/share/texmf-dist/tex/generic/oberdiek/luatex-loader.sty
(/usr/share/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua)))
(/usr/share/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty
(/usr/share/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(/usr/share/texmf-dist/tex/generic/oberdiek/ifpdf.sty))))
(/usr/share/texmf-dist/tex/latex/l3kernel/l3basics.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3expan.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3tl.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3seq.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3int.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3quark.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3prg.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3clist.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3token.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3prop.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3msg.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3file.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3skip.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3keys.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3fp.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3box.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3coffins.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3color.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3luatex.sty)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3candidates.sty))
(/usr/share/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(/usr/share/texmf-dist/tex/luatex/luaotfload/luaotfload.sty
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase-compat.sty)
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase-loader.sty
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase.loader.lua))
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase-regs.sty)
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase-attr.sty
(/usr/share/texmf-dist/tex/luatex/luatexbase/attr.lua))
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase-cctb.sty
(/usr/share/texmf-dist/tex/luatex/luatexbase/cctb.lua))
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase-mcb.sty
(/usr/share/texmf-dist/tex/luatex/luatexbase/luatexbase-modutils.sty
(/usr/share/texmf-dist/tex/luatex/luatexbase/modutils.lua))
(/usr/share/texmf-dist/tex/luatex/luatexbase/mcb.lua)))
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-string.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-lpeg.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-boolean.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-number.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-math.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-table.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-aux.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-io.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-os.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-file.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-md5.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-dir.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-unicode.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-utils.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-dimen.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-url.lua)
(/usr/share/texmf-dist/tex/luatex/lualibs/lualibs-set.lua)
(/usr/share/texmf-dist/tex/luatex/luaotfload/luaotfload.lua)(using cache: /home
/inxi/.texlive/texmf-var/luatex-cache/generic)
Module luatexbase-mcb info: creating 'luaotfload.patch_font' type 4
Module luatexbase-mcb info: inserting 'luaotfload.pre_linebreak_filter'
(luatexbase-mcb)            at position 1 in 'pre_linebreak_filter'
Module luatexbase-mcb info: inserting 'luaotfload.hpack_filter'
(luatexbase-mcb)            at position 1 in 'hpack_filter'
Module luatexbase-mcb info: resetting callback 'define_font'
Module luatexbase-mcb info: inserting 'luaotfload.define_font'
(luatexbase-mcb)            at position 1 in 'define_font'
Module luatexbase-mcb info: inserting 'luaotfload.find_vf_file'
(luatexbase-mcb)            at position 1 in 'find_vf_file'
Module luatexbase-mcb info: inserting 'unicodemath.set_sscale_diments'
(luatexbase-mcb)            at position 1 in 'luaotfload.patch_font'
)
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec.lua)
Module luatexbase-mcb info: inserting 'fontspec.set_capheight'
(luatexbase-mcb)            at position 2 in 'luaotfload.patch_font'
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec-patches.sty
(/usr/share/texmf-dist/tex/latex/base/fixltx2e.sty)
*************************************************
* LaTeX warning: "xparse/redefine-command"
* 
* Redefining document command \oldstylenums with arg. spec. 'm' on line 107.
*************************************************
) (/usr/share/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
(/usr/share/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texmf-dist/tex/latex/euenc/eu2enc.def)
(/usr/share/texmf-dist/tex/latex/euenc/eu2lmr.fd)(load: /home/inxi/.texlive/tex
mf-var/luatex-cache/generic/fonts/otf/temp-lmroman10-regular.lua))
(/usr/share/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(/usr/share/texmf-dist/tex/latex/tipa/t3enc.def(load: /home/inxi/.texlive/texmf
-var/luatex-cache/generic/fonts/otf/temp-lmromanslant10-regular.lua)(load: /hom
e/inxi/.texlive/texmf-var/luatex-cache/generic/fonts/otf/temp-lmroman10-italic.
lua)(load: /home/inxi/.texlive/texmf-var/luatex-cache/generic/fonts/otf/temp-lm
roman10-bold.lua) (/usr/share/texmf-dist/tex/latex/euenc/eu2lmss.fd)(load: /hom
e/inxi/.texlive/texmf-var/luatex-cache/generic/fonts/otf/temp-lmsans10-regular.
lua)) (/usr/share/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/share/texmf-dist/tex/latex/pdftex-def/pdftex.def))))
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/share/texmf-dist/tex/latex/metalogo/metalogo.sty
(/usr/share/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/share/texmf-dist/tex/lualatex/luacode/luacode.sty))
(/home/inxi/texmf/tex/luatex/gregoriotex/gregoriotex.sty
(/usr/share/texmf-site/tex/latex/xcolor/xcolor.sty
(/usr/share/texmf-dist/tex/latex/latexconfig/color.cfg))
(/home/inxi/texmf/tex/luatex/gregoriotex/gregoriotex.tex
(/usr/share/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texmf-dist/tex/generic/xstring/xstring.tex))
(/home/inxi/texmf/tex/luatex/gregoriotex/gregoriotex.lua)
(/home/inxi/texmf/tex/luatex/gregoriotex/gregoriotex-spaces.tex)
(/home/inxi/texmf/tex/luatex/gregoriotex/gregoriotex-chars.tex)
(/home/inxi/texmf/tex/luatex/gregoriotex/gregoriotex-signs.tex)
(/home/inxi/texmf/tex/luatex/gregoriotex/gregoriotex-syllable.tex)
(/home/inxi/texmf/tex/luatex/gregoriotex/gregoriotex-symbols.tex
luaotfload | Font names database loaded: /home/inxi/.texlive/texmf-var/luatex-c
ache/generic/names/otfl-names.lua(load: /home/inxi/.texlive/texmf-var/luatex-ca
che/generic/fonts/otf/temp-gresym.lua))))
(/usr/share/texmf-dist/tex/lualatex/luainputenc/luainputenc.sty
(/usr/share/texmf-dist/tex/lualatex/luainputenc/luainputenc.lua)
(/usr/share/texmf-dist/tex/lualatex/luainputenc/lutf8.def
(/usr/share/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/share/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/share/texmf-dist/tex/latex/base/omsenc.dfu)))
(/usr/share/texmf-dist/tex/latex/psnfss/times.sty) (./mwe.aux)
(/usr/share/texmf-dist/tex/latex/tipa/t3cmr.fd)

LaTeX Font Warning: Font shape `EU2/ptm/m/n' undefined
(Font)              using `EU2/lmr/m/n' instead on input line 7.

 (/usr/share/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/share/texmf-dist/tex/latex/oberdiek/grfext.sty
(/usr/share/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty))
(/usr/share/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texmf-dist/tex/generic/oberdiek/etexcmds.sty)))
(/usr/share/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/home/inxi/texmf/tex/luatex/gregoriotex/gsp-default.tex)
Module gregoriotex info: compiling the score score.gabc...
(./score-20150220.gtex(load: /home/inxi/.texlive/texmf-var/luatex-cache/generic
/fonts/otf/temp-greciliae.lua)
Module luatexbase-mcb info: inserting 'gregoriotex.callback'
(luatexbase-mcb)            at position 1 in 'post_linebreak_filter'
Module luatexbase-mcb info: inserting 'gregoriotex.disable_hyphenation'
(luatexbase-mcb)            at position 1 in 'hyphenate'
(load: /home/inxi/.texlive/texmf-var/luatex-cache/generic/fonts/otf/temp-lmroma
n17-regular.lua)
! Missing = inserted for \ifdim.
<to be read again> 
                   p
l.16 }
      %
! Missing number, treated as zero.
<to be read again> 
                   p
l.16 }
      %
! Illegal unit of measure (pt inserted).
<to be read again> 
                   p
l.16 }
      %
! Missing = inserted for \ifdim.
<to be read again> 
                   p
l.25 }
      %
! Missing number, treated as zero.
<to be read again> 
                   p
l.25 }
      %
! Illegal unit of measure (pt inserted).
<to be read again> 
                   p
l.25 }
      %
! Missing = inserted for \ifdim.
<to be read again> 
                   p
l.25 }
      %
! Missing number, treated as zero.
<to be read again> 
                   p
l.25 }
      %
! Illegal unit of measure (pt inserted).
<to be read again> 
                   p
l.25 }
      %

Underfull \hbox (badness 10000) in paragraph at lines 3--33
[] [] [][][] [][][][] [][][]\EU2/lmr/m/n/10.95 plus -9.07716pt minus -1.81502pt
[][]
Module luatexbase-mcb info: removing 'gregoriotex.callback'
(luatexbase-mcb)            from 'post_linebreak_filter'
Module luatexbase-mcb info: removing 'gregoriotex.disable_hyphenation'
(luatexbase-mcb)            from 'hyphenate'
) [1{/home/inxi/.texlive/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./mwe.aux)

LaTeX Font Warning: Some font shapes were not available, defaults substituted.

 )
(see the transcript file for additional information)
 2947 words of node memory still in use:
   74 hlist, 14 vlist, 53 rule, 125 glue, 54 kern, 27 glyph, 85 attribute, 132 
glue_spec, 43 attribute_list, 1 write, 1 local_par nodes
   avail lists: 1:1,2:249,3:20,4:61,5:35,6:68,7:12,9:29
</usr/share/texmf-dist/fonts/opentype/public/lm/lmroman10-regular.otf></home/in
xi/texmf/fonts/truetype/public/gregoriotex/greciliae.ttf></usr/share/texmf-dist
/fonts/opentype/public/lm/lmroman17-regular.otf>
Output written on mwe.pdf (1 page, 9342 bytes).
Transcript written on mwe.log.

**Comment by rpspringuel** [comment]
This is fixed by pull #67
