### ISSUE TITLE
problem with horizontal episema on first note in a torculus that ends with a liquescent

### ISSUE THREAD

**Issue by asbloomf** [gregorio-project/gregorio#650]
I can't get a neum to like this ![image](https://cloud.githubusercontent.com/assets/3217501/10566626/f9331178-75ba-11e5-9cdf-2858ca48b12b.png)

It comes out like this 
![image](https://cloud.githubusercontent.com/assets/3217501/10566629/0f05a7e0-75bb-11e5-94f8-227d64ed0aa6.png)

when I use `(ixh_ihg~)`

It looks like it has been broken since after version 2.3

**Comment by henryso** [comment]
This is a missing case (T_TORCULUS_LIQUESCENS) in the `advise_positioning` function.  Should I fix this for 4.0.0?

**Comment by rpspringuel** [comment]
This appears (at the user end) to be a bug, so if the fix doesn't require too much coding, then I would say go ahead and fix it for 4.0.0.

Of course if it does require a whole bunch of coding, or has a very difficult to diagnose cause, then it can be saved for later.
