### ISSUE TITLE
Annotating harmonizations, chords?

### ISSUE THREAD

**Issue by michalrus** [gregorio-project/gregorio#654]
I totally aware that this is the worst kind of sin, but it would be great, if we could annotate chords like `III` or `vii°` above certain neumes. Or can it already be done somehow?

**Comment by rpspringuel** [comment]
Does the above lines text (input with `<alt></alt>` in gabc) not work for this for some reason?

**Comment by michalrus** [comment]
@rpspringuel, oh, I’m sorry. I missed the detailed manual, http://gregorio-project.github.io/gabc/details. Maybe it could be exposed a little more?

`<alt/>` is completely sufficient, just what I wanted, thank you. :heart: (However, if there was a non-invasive way of making the text non-italicized, it would be even greater).

**Comment by henryso** [comment]
@michalrus Put something like `\grechangestyle{abovelinestext}{}` in your TeX file.

**Comment by michalrus** [comment]
Thank you!
