### ISSUE TITLE
File Version not applying to Windows executable correctly

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#658]
So, in looking into Albert's problem of 4.0 installers not overwriting and existing 3.0.3 executable, I've discovered that the Windows executable has a File Version property of 1.0.0.0 regardless of the version built (as differentiated from the Product Version which matches the Gregorio version number).  Based on what I can find on line, it would appear that this is what's causing the installation problem because a Windows installer will not overwrite an existing file unless the File Version of the new file is greater (equal doesn't cut it).

Now, looking at `gregorio-resources.rc` it would appear to my untrained eye that the File Version property should be set on the executable during the build process so that it matches the Product Version.  Clearly, though, there is something going on that I don't understand.  @eroux, you're the one that added this at a user's request.  Do you have any idea as to what the problem is and how to fix it?

**Comment by eroux** [comment]
Sorry, no clue... I'll take a look tomorrow if you can't find anything.

**Comment by rpspringuel** [comment]
I believe I've identified the problem and a potential fix (initial tests also look promising), but don't have time to try and implement and fully test it right now.  I'll work on this tomorrow, so don't feel obliged to do anything until I figure out if my potential fix works.

**Comment by rpspringuel** [comment]
See #659
