### ISSUE TITLE
Above line text appears below the line

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#66]
The above line text appears below the line, overlapping with the lyric text.  Example score attached:

###### score.gabc
%%
(c4) <alt>Above Line</alt>Test(cd)

**Comment by rpspringuel** [comment]
Tracked down the problem.  I over inflated the distance that determines the placement of the alt text, thus pushing it below the staff.  Expect a pull request fixing this shortly.

**Comment by rpspringuel** [comment]
Squash.
