### ISSUE TITLE
Add the mailing lists to Gmane

### ISSUE THREAD

**Issue by michalrus** [gregorio-project/gregorio#660]
Gmane is an ML←→NNTP gate, the most convenient interface to a mailing list.

Adding seems easy: http://gmane.org/subscribe.php.

Also, please import the old posts, easy, too: http://gmane.org/import.php

Thank you! :heart:

**Comment by eroux** [comment]
Sounds like a good idea... @henryso @rpspringuel wdyt?

**Comment by henryso** [comment]
As long as it doesn't end up being a spam gateway as well (which has been my experience with such things in the past), I don't mind.  I don't find NNTP particularly convenient.

**Comment by michalrus** [comment]
@henryso, given that it’s used by a great deal of open-source projects, and probably all of the most recognized, it needs to work exceptionally well. They’ve implemented some countermeasures → http://gmane.org/spam-control.php.

For me, NNTP is convenient, because it offers a uniform interface to all MLs I’m interested in, at the same time providing access to archives and spam control (Gmane feature).

Thank you!

**Comment by henryso** [comment]
I accidentally deleted the sentence before "I don't find...", which is: I will still use the mailing list.

So in summary, as long as it doesn't become a spam entry point, I don't mind doing this---but I will still use the mailing list.

**Comment by rpspringuel** [comment]
I'm happy with the interface we have , but don't object to adding another.

**Comment by michalrus** [comment]
Thank you for adding the group.

As for the archive, I see that they are at https://mail.gna.org/public/gregorio-users/. Probably in a format ready for importing to Gmane (gzipped, each message in its own file). However, the last one is updated daily, so probably the import should be carried out tomorrow at the earliest, not to miss any message. Gmane recognizes duplicates, so today’s messages won’t be duplicated.

**Comment by eroux** [comment]
I've asked gmane to import mails from this url, the aswer was:

    To import the archive, I need a Unix mbox file.  Get the archive, put it
    somewhere on the web, and mail me the resulting URL, and I'll do the
    import.

But I don't really have time for this. If you want to take care of this, please send me the mbox file (or upload it somewhere).

**Comment by michalrus** [comment]
@eroux, the way to create the mbox file with all the messages is:

```sh
wget -O - https://mail.gna.org/public/gregorio-users/ \
  | grep -o '....-..\(\.partial\)\?\.mbox\.gz' | sort \
  | while read gz ; do
      wget -O - "https://mail.gna.org/public/gregorio-users/$gz" | zcat
  done | gzip > gregorio.mbox.gz
```

I run this on my server and the link is:

https://michalrus.com/public/gregorio.mbox.gz

Please, feel free to sent it back to Lars for importing. :smiley_cat:

The messages can already be safely imported, because the last one in the daily archive on Gna! is:

```
Message-ID: <562E924B.5090305@domain.hid>
Date: Mon, 26 Oct 2015 16:51:23 -0400
```

And it has already been sent to Gmane.

**Comment by michalrus** [comment]
@eroux, if you want, I can send it to Gmane myself. :smiley:

**Comment by eroux** [comment]
I've sent it, no answer so far, you can do it again if you want.

**Comment by michalrus** [comment]
Ah, sorry! Okay, let’s then wait a bit more.

**Comment by henryso** [comment]
@michalrus Gmane doesn't appear to be working very well at the moment, but the posts back to 2008 appear to be there, although there is a curious set of duplicates of recent posts on the last page.  Perhaps this issue can be closed now?

**Comment by michalrus** [comment]
@henryso, actually, when looked at closely, there are no duplicates.The issue is that messages posted prior to importing are at the bottom. New messages should appear at the top, though. I’ve never seen such situation before, but I’ve also never “took part” in importing.

But I’ll drop a message to Gmane/Lars myself about possible reordering.

@henryso, @eroux, @rpspringuel, thank you, all, this is very appereciated.

Deus vos incolumes custodit! :angel:

**Comment by michalrus** [comment]
Sidenote: the [FAQ](http://gmane.org/faq.php) says:

> **Why are all the articles out of order after doing an import?**
> They aren't on the news server. On the web server they'll remain out of order until weaverd has rethreaded them, which'll happen six months later.
