### ISSUE TITLE
gabc-version header

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#664]
If the command line tool is put into verbose mode when compiling a gabc file, it raises an error about the `gabc-version` header if it is not `0.9.3`.  Either, the command line tool should be updated so that it checks the version number against the current version number (and VersionManager.py changed to keep it up to date) or the `gabc-version` header should be deprecated.

**Comment by henryso** [comment]
I don't know if gabc-version is the version of the "gabc specification" or if it's the version of Gregorio.  Can anyone make a sensible decision on this?

**Comment by rpspringuel** [comment]
My impression was that we had decided that they were all one and the same now.

Additionally, we've made some modifications that involved changes in the gabc entry, so even if the above isn't true, we still need to update that number.

**Comment by rpspringuel** [comment]
Hmm... Checking the issue history, it looks like this wasn't addressed in #87 as I thought it was.  So, discuss.

I think that having a separate version number is cumbersome and not really necessary.  (And that's all I have time to say right now.)

**Comment by henryso** [comment]
I honestly have no opinion at all.  I was actually asking for guidance as to what to do to fix it.

**Comment by eroux** [comment]
Originally there was supposed to be different versions of gabc and gregorio could have compiled them differently, but that's not going to happen, so maybe the best would be to deprecate gabc-version?
