### ISSUE TITLE
Multi-staff polyphony

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#674]
In editing the webpages for the 4.0 release, I came across a proposed notation for multi-staff polyphony.  Since this isn't supported, I'm moving it into a comment in the website code and opening this issue so that if someone feels like working on this, there's a place to discuss it.

The relevant text from the website:

>Polyphonic pieces are different only at the level of the neume; indeed, the text is the same for all the voices (but usually only two). We propose separating the voices using the character <code>&amp;</code>
>
><div class="commandline">
><code>A(g&amp;f)nnua(j/k&amp;dfde/d) gau(j&amp;e)dia(hjhi/g&amp;f/g) (:&amp;:)</code>
></div>

**Comment by henryso** [comment]
Per @eroux (https://mail.gna.org/public/gregorio-devel/2016-05/msg00018.html), closing this:

> #674 - multi-staff polyphony - Do we really want to do this?

Not in short nor middle term, so I think we can close it...
