### ISSUE TITLE
Horizontal episema spacing issue

### ISSUE THREAD

**Issue by ebydj1** [gregorio-project/gregorio#680]
In gregorio version 4.0.0-rc2-release-4.0-d8e147e-2697, the shape f_eg (or similar) places the horizontal episema too high.

![bad_horizontal_episema_over_porrectus](https://cloud.githubusercontent.com/assets/4675370/11455761/4b51543c-963c-11e5-91c1-510499ba94ec.png)

Proper layout would be like this:

![good_horizontal_episema_over_porrectus](https://cloud.githubusercontent.com/assets/4675370/11455767/87925dce-963c-11e5-8626-4421ac36da2b.png)

This seems to have been introduced after version 3.0.3 since I don't remember seeing the problem there.

(FWIW, the screenshots are from the Viderunt omnes gradual for the third Mass of Christmas.)

**Comment by eroux** [comment]
Thanks for the report, it will be fixed in 4.0 release
