### ISSUE TITLE
BOL Shifts interact with invisible clefs

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#683]
I noticed this as I was preparing the revised summary, but when the automatic clefs are set to be invisible, the bolshift causes the text to stick out into the margin.  This should not happen.  There are two ways to implement this:

1. The easy way: when `\gresetclef{invisible}` is called, it automatically calls `\gresetbolshifts{disabled}`.  The problem is that what to do when `\gresetclef{visible}` is called later.
2. The less easy way: Add a flag check to the bolshift calculation that checks to make sure clefs are visible before calculating the bolshift.  If clefs are invisible, then bolshift is automatically 0.

**Comment by henryso** [comment]
It sounds like the less easy way is the way to go.

**Comment by rpspringuel** [comment]
I've run into a problem with fixing this.  It appears that when there is no clef the first line of the score starts immediately while there is a small fixed space before the first element of the subsequent lines.  You can see this in the new test I added on rpspringuel/gregoiro-test@e170fd9.  I don't have time at the moment to track this bug down.  Hopefully I should get to it tomorrow, but I may not have the time.

Should the tracking this down be complicated, or I simply don't have enough time to get to it soon, do we want to postpone the pushing 4.0 out the door until it gets fixed, or should we simply push fixing the bug off.  As far as I can tell, this is the last outstanding issue which remains on 4.0.  If we push this off, we could release 4.0 tomorrow.

**Comment by henryso** [comment]
I could go either way with this.  I don't think this is used enough that it will bother a lot of people as long as it's fixed soon after, in 4.0.1.

**Comment by eroux** [comment]
I Agree with @henryso, 4.0.1 can be released soon after 4.0.0, this bug is small enough to be in the `KNOWN BUGS` category of 4.0.0 in the changelog... What do you think about adding this section?

**Comment by rpspringuel** [comment]
I can add a section like that when prepping the 4.0 release.

Which I'll do on Tuesday (Immaculate Conception is the Patronal Feast of CUA, so no classes), unless there are objections.
