### ISSUE TITLE
Automatic Bracket Sizing doesn't work inside snippet

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#684]
The autosizing braces (`[ob:x{]` and `[ob:x}]` and their relatives) don't work inside a `\gabcsnippet` command.  Should they?  I'm not adverse to saying that some complicated constructs simply will not work inside `\gabcsnippet` and this would be an obvious candidate for that.  However, it does appear to be the only gabc construct that doesn't work inside `\gabcsnippet` currently.

**Comment by henryso** [comment]
It appears to work in 3.0.3.  Perhaps something was broken in 4.0?  What does your snippet look like?

**Comment by rpspringuel** [comment]
```
% !TEX program = LuaLaTeX+se
\documentclass{book}

\usepackage{gregoriotex}
\usepackage{fontspec}
\defaultfontfeatures{Ligatures={NoRequired,NoCommon,NoContextual}}
\setmainfont[Extension=.otf,
		ItalicFont=Inconsolatazi4-Regular,
		BoldFont=Inconsolatazi4-Bold,
		BoldItalicFont=Inconsolatazi4-Bold,
		AutoFakeSlant,
		ItalicFeatures={FakeSlant},
		BoldItalicFeatures={FakeSlant}
		]{Inconsolatazi4-Regular}

\pagestyle{empty}
\begin{document}
\gresetbolshifts{disable}
\greseteolshifts{disable}
\gresetclef{invisible}
\gresetlyriccentering{syllable}
\hsize=3.9in
\gabcsnippet[0]{( ) g<v>[</v>ob:1;6mm<v>]</v>!hgh(g[ob:1;6mm]!hgh) g<v>[</v>obc:1;6mm<v>]</v>!hgh(g[ocb:1;6mm]!hgh) g<v>[</v>ocba:1;6mm<v>]</v>!hgh(g[ocba:x{]!hgh[ocba:x}]) ()}

\end{document}
```
I was modifying the bracket example for the website to provide an example of the new syntax.

**Comment by henryso** [comment]
Did you try `[obca:0{]` and `[ocba:0}]` instead of `[ocba:x{]` and `[ocba:x}]`?

**Comment by rpspringuel** [comment]
No.  Making that change fixes things so that's clearly my problem.  Chances are that if I had this problem, some one else will too.  I should probably try to make the instructions clearer.

**Comment by jakubjelinek** [comment]
The x in there stands for either 0 or 1, the opening and closing part can use the same or different numbers in there., depending on where exactly you want it to start (before/after a note) and end (before/after a note).  The ob vs. ocb vs. ocba strings need to be the same.
BTW, you have above also obc rather than ocb.
