### ISSUE TITLE
Add Windows Metadata to gregorio.exe

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#69]
See [this post](https://www.mail-archive.com/gregorio-users@gna.org/msg02312.html) for the request, and [this](http://stackoverflow.com/questions/708238/how-do-i-add-an-icon-to-a-mingw-gcc-compiled-executable) and [that](http://gnu-automake.7480.n7.nabble.com/correct-windres-use-td4889.html) for hints.

Also, the icon could be added to the main `.exe` file, with the same process.

Low priority.

**Comment by eschwab** [comment]
Addressed by #116
