### ISSUE TITLE
Local installation with --prefix still attempts to install gregoriotex to /usr/local

### ISSUE THREAD

**Issue by igneus** [gregorio-project/gregorio#691]
I am attempting to install fresh gregorio master from source in my home directory:

```
./build.sh --prefix=/home/me/apps
./install.sh
```

The installation runs beautifully until it reaches the point of gregoriotex installation. Then it dies:

```
Installing GregorioTeX
Installing in '/usr/local/share/texmf'.
mkdir: cannot create directory ‘/usr/local/share/texmf/tex’: Permission denied
Failed.
Failed to install GregorioTeX.  Did you forget to run as root?
```

I looked at the other options of `build.sh`, but none seems to suggest it could influence the destionation of the gregoriotex installation. Any hints?

**Comment by henryso** [comment]
Into which TEXMF directory do you want to install GregorioTeX?  You need to pass an argument to install.sh like var:TEXMFHOME or dir:/path/to/other/texmf/directory.

**Comment by igneus** [comment]
I wanted to install to my "home texmf".

`./build.sh var:TEXMFHOME` helped. Thank you very much.
