### ISSUE TITLE
Neography issue: virga cum punctum

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#692]
A quite important Abbey (anonymous for now) wishing to test Gregorio encounters a few limitations, the first one is that they want to be able to typeset this:

![neume1](https://cloud.githubusercontent.com/assets/60868/11631732/bb727fa2-9d03-11e5-9a12-8b618989bdf3.png)

I'm not sure about the way to note this in gabc... what do you think?

**Comment by jakubjelinek** [comment]
I think this is related to issue #687 and issue #679.  At least for this issue and #687, one possibility would be to allow to say in gabc you want a stemless neume (in both cases clivis, but in other cases could be ancus, etc.), then just combine with ! or /.  I've also seen in Nocturnale Romanum 2002 (hghf)
which has not been typeset as a porrectus flexus, but like (h!g!hf) except that the final clivis should not have a stem.  Either it could be done with \ proposed in #679 or something different (some flag on the first note of the neume?).

**Comment by eroux** [comment]
Sounds good! I don't particularly like '\', but it's totally subjective and I have no rational argument against it, so I have no objection to this solution!

**Comment by henryso** [comment]
I don't have my heart set on `\`, but I do think this is a good use for the feature.  Any better suggestions as for which character to use to "glue" two parts of a neume together?

**Comment by eroux** [comment]
In the remaining usual ascii characters, I think `*` or `@` could be candidates too... I kind of like `@`, but I don't have a strong opinion about this, at all...

**Comment by henryso** [comment]
By the way, in case anyone is waiting urgently for this change (i.e., all the issues @jakubjelinek mentioned plus this one), it's not a simple thing.  I have the basics mapped out and am currently working on the algorithm for detecting the shapes and the how the TeX will need to change.  One of my current issues is how to place the signs without defining a huge number of cases for extended shapes.  My current thinking is that I have to "invert" the GreGlyph macro to allow signs to be placed at a sub-glyph level.  It seems that the entire shape needs to be a single glyph for syllable alignment purposes.

**Comment by eroux** [comment]
There's nothing urgent for this issue, but maybe it could be dealt with in an easier way, as I think the current structure could be kept for the neume of this issue?

**Comment by henryso** [comment]
Yes, that is also possible.  Either prefix the first note with something or add a suffix to enforce a shape, and/or treat it as an initial liquescence.  In fact, that was one of the ways I had thought of dealing with the glued neumes, as it can be considered initial and final liquescence-like significations to neume primitives.  Ideas are still in flux, and will take a bit more time to come together.

**Comment by eroux** [comment]
Sounds good, if you think making this feature as a first step is a good idea, that might be a good thing, so that I can make a special build with this feature to the people who need it...

**Comment by jakubjelinek** [comment]
Yeah.  For the (IJ@kh), (h!g@hf) as well as (d!eo<@fd) cases (or whatever other syntax is used in gabc) this could be handled just by defining new stemless clivis glyph(s), and using them in place of the normal clivis, no other changes needed.  For the #679 case that is not sufficient, because you also need to either pick the previous shape with the top note to the left of the stem instead of to the right.

**Comment by henryso** [comment]
I'm having a problem with this figure because the flexus encroaches upon the space of the punctum inclinatum.  It should probably be adjusted according to the distance, no?

**Comment by eroux** [comment]
What I would do here is a new `inclinatumFlexusNoQueue` space, that seems the easiest option... wdyt?

**Comment by henryso** [comment]
It depends on the ambitus, no?

**Comment by eroux** [comment]
hmmm that's a good point, I think it's a good thing to make it depend on the ambitus indeed. Some spaces already do that (the space between puncta inclinata for instance).

**Comment by henryso** [comment]
In my opinion, also, the spacing on ascending puncta inclinata doesn't look as great as descending, especially using the greciliae font, whose punctum inclinatum glyph is not as much of a 45° tilt as the other fonts.

**Comment by eroux** [comment]
Maybe it would be worth creating a new punctum inclinatum forascending, tilted in the opposite way? I'm just affraid it will look awful if they are close to descending punctum inclinatum...

Anyway, don't hesitate to tweak the spacing values of ascending puncta inclinata

**Comment by henryso** [comment]
I don't think an adjustment to the shape is a good idea in this case, so the best course of action is to tweak the spacing, but then it becomes more font-dependent, and is also something that'll take me a bit longer to understand how the TeX currently works.

**Comment by eroux** [comment]
I think the best is to tweak them so that they are good with greciliae, users wanting something very precise with other fonts can use a custom spacing

**Comment by henryso** [comment]
For an ascending figure, without adjusting the space between the punctum inclinatum and the flexus with no bar, I get the following shapes:

![image](https://cloud.githubusercontent.com/assets/421318/11916635/651dfc36-a6ad-11e5-828d-13c5fa696637.png)
(Note: The ascending puncta inclinata spaces *are* tuned)

Any suggestions what I should line up to tune the space?  Should I line up the centers of the puncta inclinata with the corner of the first note of the flexus?  Something else?

**Comment by eroux** [comment]
When I tuned the spaces for descending puncta inclinata, my goal was to have something looking like a straight line, without steps. So I think they could be spaced a bit more, but not much, it's already looking quite good!

**Comment by henryso** [comment]
As for the puncta inclinata, I took a ruler to the descending ones and noticed that the diagonals lined up, so I did the same for these ascending ones.  The problem is that the shape of the first note of the flexus with no bar is not a diamond, so I'm not quite sure the best way (or even a particularly good way) to line that up.

**Comment by henryso** [comment]
Please try out the feature in the develop branch.

**Comment by jakubjelinek** [comment]
Thanks a lot for all your work on this, I'll try to test it out in a few days.  Merry Christmas!
