### ISSUE TITLE
horizontal episemus placement before a space

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#693]
The following example

```
u(ixd!ewg_/hi)
```

gives an awkward horizontal episemus placement (way too high):

![neume3](https://cloud.githubusercontent.com/assets/60868/11632247/72f09a0e-9d06-11e5-9ef4-456cc02a87b3.png)

**Comment by eroux** [comment]
I put it in the 4.0 milestone, but it can be for 4.0.1, @rpspringuel can you add it to the `known bugs` section of the changelog?

**Comment by henryso** [comment]
I can't promise I'll have anything good by tomorrow, but I'll try.

**Comment by henryso** [comment]
I submitted a pull request (#695) with the fix.
