### ISSUE TITLE
develop branch doesn't build

### ISSUE THREAD

**Issue by avbop** [gregorio-project/gregorio#704]
Both within and without the context of `makepkg` on Arch Linux, with gcc just upgraded to v5.3.0, I'm seeing the attached. I copied out the actual error message below. The stable 4.0.0 release works just fine.
[makepkg.txt](https://github.com/gregorio-project/gregorio/files/58583/makepkg.txt)
gabc/gabc-score-determination-l.c: In function ‘gabc_score_determination_ensure_buffer_stack’:
gabc/gabc-score-determination-l.c:2485:21: error: C++ style comments are not allowed in ISO C90
   num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
                     ^
gabc/gabc-score-determination-l.c:2485:21: error: (this will be reported only once per input file)
Makefile:766: recipe for target 'gabc/gregorio-gabc-score-determination-l.o' failed
make[2]: *** [gabc/gregorio-gabc-score-determination-l.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f gabc/.deps/gregorio-gabc-write.Tpo gabc/.deps/gregorio-gabc-write.Po
gabc/gabc-notes-determination-l.c: In function ‘gabc_notes_determination_ensure_buffer_stack’:
gabc/gabc-notes-determination-l.c:9245:21: error: C++ style comments are not allowed in ISO C90
   num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
                     ^
gabc/gabc-notes-determination-l.c:9245:21: error: (this will be reported only once per input file)
Makefile:780: recipe for target 'gabc/gregorio-gabc-notes-determination-l.o' failed

**Comment by henryso** [comment]
As best as I can tell, this is coming from code that was generated by flex.  What version of flex are you using?

**Comment by avbop** [comment]
2.6.0. I didn't notice at the time, but it looks like it was also updated a
few days ago.

**Comment by henryso** [comment]
This is absolutely a bug in Flex 2.6.0.  I have to figure out where to report this bug, but for now, I advise using an earlier version of flex or editing the file to change the BCPL-style comment to a C89-style comment.

**Comment by henryso** [comment]
Hopefully I created the bug in the right place.  See https://sourceforge.net/p/flex/bugs/195/

**Comment by henryso** [comment]
According to the flex developer, this should be fixed in the next release of flex.
