### ISSUE TITLE
Braces on complex neumes

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#707]
There's some cheating happening in the braces example: what looks like a torculus resupinus is actually a punctum sticked to a porrectus... because braces wouldn't work with the actual neume...

I realised this as I was trying to make it work on my own and having it shifted from the beginning of the last "punctum".

I don't know whether there is any point in making it actually work but at least the examples should show real uses of braces (like this one from the Liber Usualis, for instance)

![Liber Usualis p.xxxiv.](http://gregobase.selapa.net/sources/3/33.png)

**Comment by rpspringuel** [comment]
Fixing the examples is the easiest part.  See gregorio-project/gregorio-poroject.github.io#15

I'll leave it up to others to decide if there's a bug that warrants fixing here.

**Comment by eroux** [comment]
@olivierberten can you give us a gabc code that doesn't do what it's supposed to?

**Comment by olivierberten** [comment]
You can use the examples from http://gregorio-project.github.io/gabc/details.html#braces without the `!`

`g[ob:1;6mm]hgh` for instance.

And by the way, `u` (brace under the staff) works only with round braces.

**Comment by henryso** [comment]
I don't think there was ever an intent to support under-curly-braces.

**Comment by rpspringuel** [comment]
Then I better fix the website, as I didn't understand that when I wrote the instructions.

**Comment by henryso** [comment]
So the big question.  Is this a bug?  If it is a bug, it's an old one and looks complicated enough that it probably shouldn't be 4.0.

**Comment by olivierberten** [comment]
Well... let's talk about it when Gregorio is able to typeset this page ;-)

![Antiphonale Monasticum p.1222](http://gregobase.selapa.net/sources/7/1233.png)

**Comment by eroux** [comment]
I think most of the difficulty in this page comes from the alignment of text, but thanks for the example, I've added it in #374. Anyway, AFAICT, Gregorio can typeset the braces of this example, even better than the original (in which they are a bit off on the second and third line), so I don't think it's really relevant... @olivierberten Is there any real-life use case that Gregorio doesn't handle?

**Comment by olivierberten** [comment]
It's actually what I meant: Gregorio does a good job with braces with actual use cases. There are other priorities before "fixing" a feature maybe nobody's using...

**Comment by henryso** [comment]
Is this issue solved by neume fusion, which should allow placing braces anywhere in a fused neume.

**Comment by eroux** [comment]
I think so, please reopen if problem remains
