### ISSUE TITLE
tune spacing between notes of different syllables when second starts by an alteration

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#715]
In the following case:

```
ni(h)et(ixhg/hih) ni(h)et(hg/hih)
```

the spacing between the notes of the different syllables in the first word is too large, there should be a special space for this case, which would be smaller.

**Comment by henryso** [comment]
Sorry, closed the wrong one.

**Comment by henryso** [comment]
Implemented in #725.
