### ISSUE TITLE
horizontal episemus above k with no ledger line

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#716]
In the very simple case

```
k(k_ c_0)
```

the horizontal episemus above `k` is placed too high and the episemus below `c` is too low, to cope with the case where there are ledger lines.

I admit I see no straightforward way to deal with both cases (ledger line, no ledger line). Here are a few options:

- euristics in gabc compilation: trying to see if there are possible ledger lines around the episemus
- an additional option for horizontal episemus in gabc (maybe for vertical episemus too)
- a combination of both: having simple euristics but the ability to correct them when they're wrong

I think the third option would be the best one, with euristics that can be very simple... Also, one should be able to disable this new feature on the TeX side (globally, not episemus by episemus).

What do you think?

**Comment by henryso** [comment]
I agree with the proposal.

**Comment by henryso** [comment]
I should have been more clear.  I agree with the third option as the best solution here.

**Comment by henryso** [comment]
Correcting the heuristic's default choice becomes tricky when you have connected episemata.  Let's say we add another modifier to `_`, like `6`.  Do you have to put `_6` for each episema of the connected set?  There's also an additional complication (straightforward, but more cases to handle) when it comes to short episemata.

**Comment by eroux** [comment]
Having to input `6` at each episemus is not really a problem as these cases won't happen often, but I don't think it's relevant to have `k_j_6` not connected... I tried to write some simple heuristics, but I admit I failed, I'm afraid this is the kind of cases where we cannot avoid difficult code...
