### ISSUE TITLE
Problems with episemae on multiple notes

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#72]
See #40

http://gregobase.selapa.net/chant.php?id=2282

On the 3rd line of LU and 4th of gregobase, on the word "calceamenta": the original scores has 2 distinct episemae, while gregorio puts only a big one.

I just updated gregorio on the gregobase server but unfortunately it doesn't solve the problem... gregorio still draws a line between the 2 episemae...

Strangely enough, it wouldn't do it with `ji__/i_` but it does with `i_/i_` (and by the way, `h!i__` doesn't work, I don't know whether it's related...)

Maybe `i_/i_` and `i/i__` should have a different behaviour...

**Comment by eroux** [comment]
Well, this is not really a bug, but more a feature... Gregorio always tries to make the longest episemus, but there's not control on that behavior... A possiblity I'm thinking about is to change this behavior with a tex option that would simply redefine `grehepisemusbridge` to nothing... Another solution would be to have `_5` to get an episemus without any attempt at linking it to any other... What do you think?

**Comment by eschwab** [comment]
It might be better to have the option in gabc. Some scores may have both linked and individual episemae.
