### ISSUE TITLE
oriscus (& reversus) cavum

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#724]
I recently got a small request from Antiphonale Monasticum project: the possibility to typeset empty oriscus and oriscus reversus, on the same model as the punctum cavum we currently have.

**Comment by henryso** [comment]
I'll give this a shot, but if my font-editing capabilities fall short of my aesthetic sense, I will hand it back.

**Comment by eroux** [comment]
I don't think much aesthetic sense is necessary here. To draw the hole, I usually use uniform scaling transformation, trying a few different values in order to get the lines to have the "normal" width (meaning the width of the joining lines, but it's the same as the lines in punctum cavum)

**Comment by henryso** [comment]
I'm not disagreeing, I'm just saying if I cannot come up with something that (to me) looks nice, then I'll hand this back to someone who is better at editing fonts.

**Comment by eroux** [comment]
fixed in #727
