### ISSUE TITLE
GregorioNabcRef won't compile

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#734]
In preparing the 4.0.1 release I noticed that GregorioNabcRef won't compile.  I'm getting the following error:

```
./veni-4_0_0.gtex:196: Undefined control sequence.
l.1 ...pace\hskip \gre@skip@nabcinterelementspaceERR
                                                  
l.196 }
```
The "ERR" at the end indicates to me a variable that isn't getting resolved correctly when writing the gtex file.  Can some one with more knowledge of the nabc system look into this and figure out what the problem is?

**Comment by henryso** [comment]
Ok, this is related to #717.  I'll see if I can come up with a fix.

**Comment by henryso** [comment]
I won't be able to check this more carefully until tonight, so if you have time, put this line after gregoriotex-nabc.lua:73 (`local fontdata = fonts.hashes.identifiers[font_id]`):
```
local ignored = fontdata.resources.unicodes['_this_is_hopefully_a_nonexisten   t_glyph_']
```
... and see if it works.
