### ISSUE TITLE
segfault on long episemus

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#740]
I get a segfault compiling

```
name: segfault;
%%
pu(g_e_/fh_G_F_/fv_D_C_/fv_D_C_/d_e_d_.)
```

**Comment by henryso** [comment]
This doesn't happen in 4.0, so I'm putting it in the 4.1 milestone.  Minimizing the above example, `
pu(C_/d_e_d_)` generates the segfault.
