### ISSUE TITLE
<eu> tag can result in score not compiling

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#743]
gabc

```
Pó(c3eh/hi) <eu>E(i) e</eu>(fe..) (::)
```

works fine, while

```
Pó(c3eh/hi) <eu>E(i) e(fe..) </eu>(::)
```

results in

```
! Missing number, treated as zero.
<to be read again> 
\relax 
l.39 \GreEndScore
                %
?
```

during TeX compilation

**Comment by henryso** [comment]
I suspect it's a problem in the C code because the broken case doesn't emit `\GreEndEUOUAE`, but I won't be able to look further into it until tonight.
