### ISSUE TITLE
Problem with gregorio and multiline score

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#75]
I am trying out my MWE from the previous multiline score bug (which was fixed) against the latest master from git.  It compiles, but I get output with dimensions printed.

###### score.gabc
%%
(c4) Line(c) One(d) (z) Line(c) Two(d)

###### mwe.tex
\documentclass[11pt]{article}
\usepackage{luatextra}
\usepackage{graphicx}
\usepackage{gregoriotex}
\usepackage[utf8]{luainputenc}
\usepackage{times}
\begin{document}
\includescore{score}
\end{document}

###### output
![mwe](https://cloud.githubusercontent.com/assets/421318/6620616/2cb95a9a-c8a8-11e4-82ba-a99529117075.png)

**Comment by rpspringuel** [comment]
How many times do I have to squash this bug?

Well, I think I've found what's causing it this time.  Hopefully I'll have something that fixes it later today or tomorrow.

**Comment by rpspringuel** [comment]
I just pushed an update (7dff9743da5a4dbf656896e298bdae46f1c0a0a9) which should fix this bug.  I'm going to update CHANGELOG before I pull it into the main repository though.

**Comment by henryso** [comment]
That fixes it for this MWE.  However, if I change score.gabc to:

%%
(c4) Line(c) One(d) (z) Line(c) Two(d) (::)

I get this:

![mwe](https://cloud.githubusercontent.com/assets/421318/6652228/bd0e0d06-ca3e-11e4-8a63-129308b327a1.png)

**Comment by rpspringuel** [comment]
I think I've got it this time.  Any more obscure use cases you can think of?

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)

PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
I think this issue is closed in your repository.  However, I am running into other issues, but it will take me some time to either adjust my code for the new syntax or create MWEs for them.  In either case, I guess this particular issue should not be closed until your fixes are merged into the main repository.

**Comment by eroux** [comment]
By the way, compiling something like

```
name:bars;
%%
(c3) ggi(g/g)ggi(g/g)
```

It seems Gregorio is not hyphenating correctly... Do you confirm? If so, I'll open a separate issue.

**Comment by henryso** [comment]
I also am noticing hyphenation and overlapping text issues, but I have not worked to down to an MWE yet.

**Comment by henryso** [comment]
I don't have an issue with that particular sequence of characters using Br. Samuel's master branch, but I definitely have issues with hyphenation and overlapping characters.  Should I report these here or in Br. Samuel's project?

**Comment by eroux** [comment]
I think it's best to keep all issues here...

**Comment by henryso** [comment]
I found another issue similar to this one; it may be related: https://github.com/gregorio-project/gregorio/issues/78

**Comment by rpspringuel** [comment]
I'll just second what @eroux said.  My repository simply exists to keep my changes separate from the main repository until their finished.  All issues should be reported here.

**Comment by rpspringuel** [comment]
Addressed in #81
