### ISSUE TITLE
strange error message

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#754]
When compiling the example in `fix-662`, I realize I get the message

```
Package GregorioTeX Warning: initial-style gabc header is deprecated.
(GregorioTeX)                Use \gresetinitiallines instead on input line 6.
```

which is weird because the example does not have `initial-style` gabc header...

**Comment by henryso** [comment]
Can you post the breaking example?  I don't see a fix-662 branch in gregorio-test.

**Comment by eroux** [comment]
Sorry, it's the `example/main-lualatex.tex` of the fix-662 branch of the gregorio repo

**Comment by henryso** [comment]
FactusEst.gabc has initial-style in it.

**Comment by eroux** [comment]
Oh sorry, I'll fix that, I was focusing on PopulusSion...

**Comment by eroux** [comment]
I've fixed it in `fix-662`, I don't think it's worth keeping it open
