### ISSUE TITLE
feature: double keys

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#755]
This is a feature that was asked by an abbey to ease transcription: it would be nice to be able to use two keys, stacked one on another. The syntax could be the same as "polyphony", for instance `c4{c1}`. Only the first specified key would be taken into account for the computations, the other one would just be typeset. It should also work for clef changes, and all new lines should contain both keys.

**Comment by henryso** [comment]
Would you want to offset the stack if the keys would overlap (i.e., c3 and c4)?

**Comment by eroux** [comment]
That would be perfect indeed!

**Comment by henryso** [comment]
Right now, curly braces for "polyphony" is implemented using TeX magic.  This double-key feature needs something more carefully handled.  I think adopting the `@` between the clefs (in order to "fuse" the clefs) is more easily lex-ed.  So your example would be `c4@c1`.  What do you think?

**Comment by eroux** [comment]
Sure!

**Comment by eroux** [comment]
I just ran into some images on [musicasacra](http://forum.musicasacra.com/forum/discussion/9137/psalm-tones-besides-the-usual-ones):

![two-clef-1](https://cloud.githubusercontent.com/assets/60868/12259007/f678a498-b912-11e5-94b6-01c03c3f01b5.jpg)
![two-clef-2](https://cloud.githubusercontent.com/assets/60868/12259006/f6730a6a-b912-11e5-9db8-0eb558a98f0b.jpg)

(just for archives)
