### ISSUE TITLE
porrectus cavum

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#758]
Here is an example of a difficult one (not even really handled by the book it's in): a porrectus cavum:

![ferretti001](https://cloud.githubusercontent.com/assets/60868/12165518/ec022748-b51e-11e5-9b13-691360ab3ea6.jpg)

This would be extremely difficult to produce, and I'm quite sure it won't actually be used by anyone, so let's not do it unless there is a real necessity, case by case. I'm just opening (and closing) it so that it's in the archives.

**Comment by henryso** [comment]
That figure (if you mean the porrectus under the 7) actually looks more like a misprint or a loss of toner in a photocopy than anything else.

**Comment by eroux** [comment]
That was reported to me as a such (a cavum) made in a very "manual" way (it would be consistent to have a cavum here), but I'm no specialist, so I'm not sure...
