### ISSUE TITLE
Missing oriscus with left stem

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/gregorio#76]
In Nocturnale Romanum, the standard oriscus like (fo) is often typeset with a left stem like e.g. (fV) has.  This is usually done to typeset virga strata or pressus or salicus.
E.g. in the first snippet I wanted to typeset what was originally virga strata followed by salicus, but
(dxef/e/eoc/co!dv) doesn't do the job (the first snippet - it automatically uses the reverse oriscus), I wonder if e.g. eoVc couldn't be typeset like the second gimp editted snippet.  Or in the third snippet, it is similar, but with just a single pitch difference instead of bigger one, there I've for now used
(f/fo!e) to avoid the reverse oriscus, but it is still missing the stem.
![oriscus](https://cloud.githubusercontent.com/assets/9370665/6625812/b4bc1de8-c8f2-11e4-832f-7ba22a82dd48.png)
Corresponding Nocturnale Romanum pictures:
![nocturnale1](https://cloud.githubusercontent.com/assets/9370665/6626407/b4c0f85a-c8f6-11e4-8d20-2c98b3c45b84.png)
and
![nocturnale2](https://cloud.githubusercontent.com/assets/9370665/6626409/bb6fea58-c8f6-11e4-9b9b-642d95362828.png)

**Comment by eroux** [comment]
This should be relatively easy to add, can you just propose a name for this new glyph (oriscus with stem+punctum after)?

**Comment by jakubjelinek** [comment]
I'm afraid I don't know how it is usually called, and am not good in naming such things.
Semantically it is perhaps pressus (minor, or second/third part of maior), but in the first example
the oriscus with the stem stands for virga strata and the punctum connected to it is already start of the next neume - salicus, with the next oriscus being the oriscus in the salicus and the last virga the upper part of it. Ideally there would be glyphs for different pitch differences of this, so one can use
(foVe) for the second example, (eoVc/codv) for the first one, but say also (hoVf), (hoVe) etc.

**Comment by eroux** [comment]
Sure, that will be done with the same ambitus possibilities as other glyphs

**Comment by eroux** [comment]
By the way, do you plan to reedit the nocturnale romanum or something like that? (that would be great)

**Comment by jakubjelinek** [comment]
No, just typesetting scores for our choir for some feasts and want there complete officium + mass, and Nocturnale Romanum being a useful source for matins:
https://github.com/jakubjelinek/Editio-Sti-Wolfgangi
http://people.redhat.com/jakub/epiphania.pdf
http://people.redhat.com/jakub/feriaiv.pdf
http://people.redhat.com/jakub/pentecostes.pdf
is what I have so far, the latter two work in progress.

**Comment by henryso** [comment]
Right now, Gregorio uses the capital-O for salicus figures that are connected to the first note (i.e., `(egOh)`).  Maybe, if it's not too difficult for the gabc parser, we can adopt capital-O for this feature if its note is not preceded by another note.  The figures in the opening post might then be `(e/eOc/co+dv)` and `(f/fOe)`.

Those figures from the Nocturnale Romanum look like pressus to me.  In the Solesmes books prior to and including the Liber Hymnarium, pressus was notated (to adopt gabc) `(e/ec)`.  As semiology has pointed out, the second note is an oriscus in the non-diastematic neumes.  If you substitute an oriscus for the square head on the second note, you get the figure from the Nocturnale Romanum.

In more recent Solesmes books like the Antiphonale Romanum II, I notice that they depict pressus with the second note as an oriscus, but without a stem, though I am hard-pressed to find an example of a pressus with an ambitus greater than one in that book.

I think, without the trailing note, the virga + oriscus would be called a virga strata, and in fact, in the non-diastematic neumes, a pressus is often depicted as a virga strata followed by a punctum.

@jakubjelinek If you can supply the incipit for these chants, we can try to look for them in the various manuscripts online to confirm whether the neume is a pressus that starts with a virga strata.

**Comment by henryso** [comment]
I found example in Antiphonale Romanum II and Antiphonale Monasticum I (the newer one) with a pressus of ambitus 2, and they still leave out the stem.  Looking at some scans from the Nocturnale Romanum, I am pretty convinced that that figure is actually a pressus, in the style/font chosen by that book's publisher.

**Comment by eroux** [comment]
I think it's more an editing style than really something that cannot be represented in any other way, but I believe gabc is quite graphical and could handle this, and this would be easy to add in the fonts, so I would be in favor of adding it...

**Comment by henryso** [comment]
I'm not against adding it either, but you had asked what that figure was called.

**Comment by jakubjelinek** [comment]
For Antiphonale Romanum II, which indeed is a new book and uses oriscus in lots of cases, I've skimmed a couple dozen pages and attempted to typeset what I found, like:
(ddoc) (c!dwe!fo<) (e!fo<) (kkoj~) (goi) (fog)
and all that looked like in the book.
But (g!hw!ihi~) doesn't, guess, I'll file another issue for that.

**Comment by eroux** [comment]
@henryso @rpspringuel @eschwab , would one of you be interested in this? This would allow you to understand the code in `fonts/`, so that I'm not the only person able to do this kind features... This one is really easy, we can work together on it.

**Comment by henryso** [comment]
I am willing to take this on, but I'm not artistic on the font design side.  Are there guidelines?

**Comment by eroux** [comment]
Don't worry, it's just copy/paste, all the elements are already drawn somewhere, you just have to copy/paste oriscus, stem, etc.

The first thing here is to add the simple oriscus with a stem on the left (we'll do the combined glyphs afterwards): you can just add this glyph in the font, and git it a proper name. The `-base` fonts contain glyphs that will remain in the final font, and also glyphs that are just temporary, to be combined in bigger ones. The first have names like `_0017`, other have names with letters. You can see the numbers already taken in `gregoriotex.h`, just take the first non-taken number. You also have to add it in `squaryze.py`, to the list of the glyphs that will remain in the final font.

Doing this would be a good occasion to document how to add a new glyph, and I believe it's best if you do it with your fresh eyes on this, because it's not obvious and I'm not sure I would make it easy to understand... What do you think?

**Comment by eroux** [comment]
(documentation could be in a md file or in the wiki)

**Comment by henryso** [comment]
I'll give it a try.  Since I am no longer on vacation, please expect it will take longer to accomplish.

**Comment by eroux** [comment]
No problem. The most boring aspect is that the three fonts need to be modified, apart from that, it can take around 10mn if you know how to do it (but I prefer not to, so that I'm not the only one with the key to the fonts).

**Comment by henryso** [comment]
For now, this is in `develop`.  Use capital-O for the stemmed-oriscus.  For your examples: `(e/eOc/co!dv)` and `(f/fOe)`
