### ISSUE TITLE
optional removal of custo before <eu> blocks

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#761]
An abbey asked for the possibility to prevent custo to appear if there is a line break before `<eu>` blocks

**Comment by henryso** [comment]
Markdown ate the `<eu>` in the description.

**Comment by eroux** [comment]
indeed, thanks!

**Comment by henryso** [comment]
I tried the obvious change of putting `\gre@usemanualcustos` at the start of `\GreBeginEUOUAE` (unconditionally, just to see if it would work), but it didn't work.  What am I missing?  Is there some TeX magic going on here?

**Comment by eroux** [comment]
Why not something like `\greblockcustos`? Also, I'm affraid that in some cases, you'll have to tell the syllable before the `<eu>` block not to put some custo, because the `localrightbox` will already typeset at `\greBeginEUOUAE`, but I'm not 100% sure...

**Comment by henryso** [comment]
If I'm reading this correctly, `\gre@usemanualcustos` sets `\ifgre@blockeolcustos` to true and clears the `localrightbox`, so it's probably the prior syllable thing.

**Comment by henryso** [comment]
You were right, `localrightbox` needs to be cleared on the prior syllable.
