### ISSUE TITLE
left alignment before <eu> linebreak?

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#764]
For the Antiphonale Monasticum project, it would be great if the lines were aligned left (and the custos removed as in #761) if a line break occurs before an `<eu>` block. This behavior should be optional too... I'm not entirely sure it's feasible easily (if at all)... The most important is that

```
(::) (Z) <eu>euouae(g) </eu>(::)
```

and

```
(::Z) <eu>euouae(g) </eu>(::)
```

remove the custo

**Comment by henryso** [comment]
What do you mean by "aligned left" here?  Can you post a mock-up?

**Comment by eroux** [comment]
It just means that some blank space can be added to the right of the line before the `<eu>` block (if it's one a new line), as if there was a `Z` in gabc before the `<eu>` block, while now if you have a double bar before, it will be at the very end of the line...

**Comment by henryso** [comment]
As of now, `(::Z)` will get the effect you are describing (ragged line break and suppressed custos).  `(::) (Z)` will neither break the line in a ragged manner nor will it remove the custos.  Should I try to fix this, or is it better to just suggest people use `(::Z)` instead of `(::) (Z)`?

**Comment by eroux** [comment]
That's a bit surprising, `(Z)` should break the line in a ragged manner... I think it's a bug if it doesn't (I cannot test right now, sorry)... But yes `(::) (Z)` should remove the custos too...

**Comment by henryso** [comment]
Any hints on the TeX side as to how to insert a `\hfill` on an automatic linebreak?  I don't think I can put that in a `\discretionary`.

**Comment by eroux** [comment]
No you can't in a discretionary... I really don't have a clue on how to do that simply... maybe in a two-pass system by saving the information that we cut the lines in a particular way in a particular score, as we do for other features...
