### ISSUE TITLE
font scaling factor

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#765]
I'm converting a gregorian font to Gregorio format for an Abbey, but I think it would be wrong to scale the glyphs in the font (as it makes a lot of approximations), so I think it would be best to make Gregorio open the font in a size multiplied by a `gre@fontscalefactor`. In my case this would be *0.173076293*. Gregorio should allow that easily, but I'm not sure about the best way, as `\setgregorianfont` already has an optional parameter...

**Comment by henryso** [comment]
Syntactically, we can either allow a parameter after the command (`\setgregoriofont[#1]{#2}[#3]`) or add a new macro like `\setscaledgregoriofont[#1]{#2}{#3}`.  I'd probably opt for the latter.

**Comment by eroux** [comment]
You're right, `\setscaledgregoriofont[#1]{#2}{#3}` is the best solution!

**Comment by henryso** [comment]
Just a thought: I don't know if this is viable at all, but since the effective font being used is generated by something like `squarize.py`, perhaps there's some place that this scaling factor can be embedded into the font itself.

**Comment by eroux** [comment]
I'm not sure it's a very good idea to have float numbers instead of int in the font... in fact my theory is that this is what causes the small artifacts we see when we look at fused glyphs, but I've never really checked this theory...

**Comment by henryso** [comment]
Well, I meant something like using some text field to store the scale factor as text and using this value to  scaling the font in TeX.

The artifacts in fused glyphs are actually unrelated to this.  They have to do with the way a particular renderer (like Acrobat Reader, for example), positions and anti-aliases the glyph on a (relatively low-dpi) screen.  This is why when zooming in and out, the artifacts shift by a pixel in some direction.  In print, the dpi is so high that the error cannot be seen with the naked eye.

**Comment by eroux** [comment]
Oh, I see, I didn't understand that... There's a problem with that though: we cannot analyze the font (and thus get the factor) before actually opening it, and we must open it with the scale factor... We could open it twice, it's certainly no big deal though... Good idea!
