### ISSUE TITLE
dissociation for space around bars according to presence of text

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#766]
An abbey told me that bars without text should be less stressed than bars with text, and thus need less space around them. Maybe there could be a way to note bars without text that should be stressed in gabc, but I'm not sure it makes much sense...

**Comment by henryso** [comment]
What exactly does "presence of text" mean?  Text on the bar?  Text on either side of the bar?

**Comment by eroux** [comment]
Sorry, text under the bar, like `*(:)`

**Comment by eroux** [comment]
Sorry, text under the bar, like `*(:)`
