### ISSUE TITLE
differenciate some glyphs on lines / between lines

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#773]
The idea never crossed my mind, but it's quite a good one and it's needed for a custom font: the stropha aucta can be very tall and some fonts use a different drawing if the stropha aucta is one a line or not... Maybe there could be an optional `StrophaAucta.interline` in the font that would be automatically used for this purpose? I don't think there another candidate for such a distinction... maybe `Stropha`?

**Comment by henryso** [comment]
I say we just create `StrophaAucta` and `StrophaAuctaLong` (or whatever) in all fonts, but duplicate the same figure (or draw a long one) in the standard fonts.  Then the code would just use them in the same way as it does the longqueue figures.

**Comment by eroux** [comment]
Indeed, that's more in line with the current system

**Comment by henryso** [comment]
I'll work on this tonight.  I take it the longer tail is for the `Stropha Aucta` that's not on a line?

**Comment by eroux** [comment]
Sorry, that's the opposite, the longues tail is for stropha aucta on a line

**Comment by henryso** [comment]
OK, that's what I implemented after looking through the Solesmes books.  I should have updated the earlier comment.
