### ISSUE TITLE
inclinated brace

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#776]
An abbey asked for the ability to do:

![bracecourbe](https://cloud.githubusercontent.com/assets/60868/12221449/f0664baa-b79b-11e5-952d-ed308f1fd434.png)

it should be extremely rare so I'm not really sure it's worth having a gabc notation for this, it could be just something to put in a `<v>` snippet with hardcoded length values, but it should be possible...

If it's possible in 4.1 that would be great, otherwise there's no emergency.

**Comment by henryso** [comment]
I'll work on this, but since this would involve drawing something generically using metapost, I make no promises as to whether it will actually make 4.1.

**Comment by eroux** [comment]
Sure, no problem, thanks a lot!

**Comment by rpspringuel** [comment]
In modern notation that would be called a slur, and I think it would be far more reasonably called that than "inclined brace" here too.
