### ISSUE TITLE
Dimensions leak into text after a flat

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#78]
Compile using lualatex --shell-escape --halt-on-error mwe.tex

###### mwe.tex

\documentclass[11pt]{article}
\usepackage{luatextra}
\usepackage{graphicx}
\usepackage{gregoriotex}
\usepackage[utf8]{luainputenc}
\usepackage{times}
\begin{document}
\includescore{mwe}
\end{document}

###### mwe.gabc

%%
(c4) Test(ixi)

###### output

![mwe](https://cloud.githubusercontent.com/assets/421318/6653299/ce94aebc-ca62-11e4-8a12-005c0e8e86ef.png)

**Comment by rpspringuel** [comment]
Addressed in #81.
