### ISSUE TITLE
Change the names of gsp-default space macros.

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#787]
During some of my recent updates, I've run into a problem differentiating between dimension registers and space macros.  For example, `\gre@dimen@glyphraisevalue` is a dimension register which can be scaled (`15.5\gre@dimen@glyphraisevalue` or `-\gre@dimen@glyphraisevalue`) and whose textual value requires the use of `\the`, but `\gre@dimen@annotationraise` is a textual space macro, which must be scaled using a `\dimexpr` or somesuch, and for which `\the` is illegal.  For a space macro, a leading `-` will work (because it just happens to be in the right place), but a leading number won't.

This is something that was obviously resolvable during testing, but made it a little bit more difficult during development.  Is it worth changing the prefix of spaces to make it more obvious?  For example, using `\grespace@dimen@annotationraise` (or somesuch) instead of `\gre@dimen@annotationraise`?

**Comment by eroux** [comment]
Looks like a good idea!

**Comment by henryso** [comment]
I'll work on this when development has calmed a bit, as this change is likely to cause merge issues.

**Comment by rpspringuel** [comment]
I think it's a reasonable idea but would use something like `\gre@space@dimen@annoationraise` (if you want to emphasize how it is encoded) or `\gre@dimen@space@annotationraise` (if you want to emphasize what is encoded) instead.  The extra `@` makes it more difficult to type, but I find it makes it easier to read and I generally prefer code which is easy to read over that which is easy to type.

**Comment by henryso** [comment]
I have no attachment to `grespace`.  Which would you prefer: `\gre@dimen@space` or `\gre@space@dimen`?

**Comment by rpspringuel** [comment]
As I said, it's a question of emphasis.  To me at least `\gre@space@dimen` emphasizes that a spacing string is being encoded by placing `space` first.  `\gre@dimen@space` emphasizes that the macro represents a dimension (thought in text form).  Given that the problem you're having is based on the fact that spacing strings need to be treated differently in certain contexts, it would make sense to emphasize that aspect (i.e. use `\gre@space@dimen`).
