### ISSUE TITLE
Strange graphy: salicus flexus deminutus

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#789]
Proofreading a custom font, I realize there is a very strange glyph:

![salicusflexusdeminutus](https://cloud.githubusercontent.com/assets/60868/12379293/ceb09b7a-bd57-11e5-8403-8b09c436633d.png)

is it on purpose that the final combination punctum+deminutus doesn't look like the others (like ge~ for instance)?

**Comment by eroux** [comment]
P.S.: the image comes from `greciliae.ttf`

**Comment by henryso** [comment]
You would know better than anyone if there's a reason behind it.  I doubt there's a reason; it's most likely a bug.

**Comment by eroux** [comment]
Ok, let's change it

**Comment by henryso** [comment]
The fusion glyphs should be changed to match.  I can do this once you're done with this change, or you can do it; just let me know.

**Comment by eroux** [comment]
I've fixed it in #788

**Comment by eroux** [comment]
@henryso if you could make the fusion part once #789 is merged, that would be nice, thanks!

**Comment by henryso** [comment]
@eroux I made the changes and merged it into your branch.
