### ISSUE TITLE
Overlapping letters and hyphenation

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#79]
Compile this with lualatex --shell-escape --halt-on-error mwe2.tex

###### mwe2.tex

\documentclass[11pt]{article}
\usepackage{luatextra}
\usepackage{graphicx}
\usepackage{gregoriotex}
\usepackage[utf8]{luainputenc}
\usepackage{times}
\begin{document}
\includescore{mwe2}
\end{document}

###### mwe2.gabc

%%
(c4) Test(c) (:) as(g)sis(gh)tance.(h.) (:) temp(c)ta(de)tion.(d.) (::)

![mwe2](https://cloud.githubusercontent.com/assets/421318/6653344/d2bf4c8e-ca64-11e4-97d7-f1714b4058dc.png)

**Comment by rpspringuel** [comment]
Addressed in #81
