### ISSUE TITLE
new drawing for curly brace

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#797]
An anonymous contributor allowed Gregorio to use the following drawing for curly braces:

[accolade.eps.zip](https://github.com/gregorio-project/gregorio/files/95553/accolade.eps.zip)

Maybe the metapost-drawn curly braces could look more like it?

**Comment by henryso** [comment]
Should this new shape replace the old, or should it be an option along with the old?  Should this be drawn to the same height as the current brace or should it be taller than the current brace?  Are we allowed stretch it non-uniformly, to keep the cusp in the middle sharp as the shape is stretched horizontally?

**Comment by eroux** [comment]
I think it can replace the old one, and non-uniformity seems good indeed. About height I don't really know... I think the best model are old Solesmes books.

**Comment by henryso** [comment]
Here is my spreadsheet for the pathing of the new shape:

[cb-path.xlsx](https://github.com/gregorio-project/gregorio/files/96979/cb-path.xlsx)
