### ISSUE TITLE
z0 and Z0 for line break without custos

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#800]
Original thread [here](https://mail.gna.org/public/gregorio-users/2016-01/msg00007.html). It would be useful to allow line break with no custo with `z0` and `Z0`

**Comment by eroux** [comment]
`1` might be better than `0` which is already taken...

**Comment by rpspringuel** [comment]
Actually, I think `z-` and `Z-` would be better if they won't screw up the parser.  Along similar lines `z+` and `Z+` should force a custos, even in cases where one would not normally be printed.

**Comment by eroux** [comment]
good idea yes

**Comment by henryso** [comment]
`z-` and `Z-` would take precedence over an initio debilis immediately after the line break, with no spaces in between, in the same syllable.  The user could probably override that with a `!`.  I think that's probably acceptable.
