### ISSUE TITLE
build fails on Solaris

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#806]
See [this thread](http://tug.org/pipermail/tlbuild/2016q1/003339.html). This seems caused by the call to `realpath` (see [gnulib's description](https://www.gnu.org/software/gnulib/manual/html_node/realpath.html))

**Comment by henryso** [comment]
Based on @jakubjelinek's presented options, I suggest we try `realpath` with `NULL`, and if it returns `NULL` and `errno` is `EINVAL`, we allocate a buffer of size `PATH_MAX` and try again.  Any objections?

**Comment by jakubjelinek** [comment]
I'm afraid Solaris <= 10 realpath will just segfault instead of returning NULL and setting errno to EINVAL if the last argument is NULL.

**Comment by henryso** [comment]
Ok, then we need to check realpath works in `configure` and call it appropriately depending on the check.

**Comment by henryso** [comment]
I don't have a Solaris box to test this change on.  Any ideas?

**Comment by eroux** [comment]
Good question... @mojca, what would be best for you? import latest sources (`develop` branch) or a patch against texlive sources?

**Comment by mojca** [comment]
Btw: if anyone is interested in having access to Solaris, you can probably request an account at OpenCSW.

I can in principle test the develop branch directly as long as you can explain me how to run the tests. If I patch TL directly, I'll be sure that I would be testing the same thing as I did earlier.

**Comment by eroux** [comment]
Just building (`./build.sh`) and running `make doc` would be enough to trigger the bug. Thanks a lot for the pointer to OpenCSW!

**Comment by mojca** [comment]
However I'm a bit confused at the moment. Do you already have something that I should try and report you back? Or do you plan to apply for an account anyway?

**Comment by eroux** [comment]
Sorry, didn't realize it wasn't ready yet! We'll tell you when it is

**Comment by henryso** [comment]
@eroux I have made changes that I can push for develop; do I need to backport it to some other version?

**Comment by eroux** [comment]
I think develop would be best (as we'll see if 4.1 introduced other bugs)

**Comment by henryso** [comment]
@eroux, I created the pull request.  If you could give a quick look before merge, I'd appreciate it.

**Comment by eroux** [comment]
Done, thanks a lot! @mojca, the `develop` branch should build under Solaris now

**Comment by mojca** [comment]
It looks better now.

**Comment by eroux** [comment]
Closing this, reopen if needed
