### ISSUE TITLE
Colored initial

### ISSUE THREAD

**Issue by liturgy** [gregorio-project/gregorio#807]
Good afternoon everyone,

I noticed a little problem with using coloring tag (`<c>...</c>`). Please, check out this code:
```
% CODE UPDATED
initial-style: 1;
%%
(c3) <c>A</c>(a)b(b)<c>c</c>(c)d(d)e(e)
```
The first and last letter should be red. Instead I have black _A_ and then red dash under first punctum. Tested with v. 4.0.1-develop-0509549-1:
![colored_a](https://cloud.githubusercontent.com/assets/15684548/12513901/a29b5d6e-c120-11e5-8a7c-a5e852846dff.jpg)

**Comment by rpspringuel** [comment]
The code you posted does not correspond to the image.  The code shows 4 syllables (a-d) while the image shows 5 (a-e).

That said I can confirm the first issue (Initial is not red) but not the second (last syllable not getting colored) using latest develop.  Further, when I switch the initial format to `0` the `A` is colored.  Thus it appears that the coloring instructions in the gabc are not being passed on to the initial setting algorithms.

**Comment by henryso** [comment]
The initial style should be set by using the `initial` style (put \grechangestyle{initial}{\fontsize{40}{40}\selectfont\color{gregoriocolor}}{}).  Styles from the gabc are stripped from the initial.

**Comment by henryso** [comment]
Actually, I'm wrong.  Styles are NOT stripped from the initial, so that's a bug, but you can you the above as workaround.

**Comment by liturgy** [comment]
@henryso, you're right - the image was generated using another code:
``
initial-style: 1;
%%
(c3) <c>A</c>(a)b(b)<c>c</c>(c)d(d)e(e)
``
The only problem is with initial.
