### ISSUE TITLE
Gregorio should not generate \GreScoreReference, which is obsolete.

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#813]
See https://github.com/gregorio-project/gregorio/pull/811#discussion-diff-50591095

**Comment by henryso** [comment]
So `\GreScoreReference` was obsoleted, supplanted by `\grescorereference`, which does nothing.

`\GreScoreReference` is called when the user puts a `score-reference` header into gabc.  As of right now, this will cause an error because `\GreScoreReference` is obsolete.  Does it even make sense to keep `\grescorereference` any more?

**Comment by rpspringuel** [comment]
Given that gregoriotex-write.c could produce `\GreScoreReference`, said function should not have been supplanted by `\grescorereference`, which is in the user namespace, not the Gregorio control namespace.  So I think the deprecation (and obselecence) was actually a mistake (probably mine).

That said, given that the function didn't do anything, we were simply reserving it for future use.  Do we really need to do that?  Further, `score-reference` isn't listed in the documentation of the header we weren't even terribly consistent on that reservation.

Finally, with the new customizable headers and header capture system, I don't think it's necessary for us to specifically reserve headers which we don't currently know what to do with.

I would say that `\grescorereference` should be deprecated, `\GreScoreReference` left as obsolete, and the ability of gregoriotex-write.c to produce said macro eliminated.

**Comment by henryso** [comment]
Ok, I'll do that.

**Comment by henryso** [comment]
P.S. The header is actually `manuscript-reference`, not `score-reference`. Apologies.
