### ISSUE TITLE
elisions

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#838]
Solesmes asked for a way to input elisions, syllables that are not sung in order to keep the same syllable number across sentences. These elisions are noted in italic.

A proposal is to use a new text markup `<e>`, for instance `clar<e>a</e>` would ignore the second a in text centering (and `<e>cla</e>ra` would ignore the first), and the second `a` would be in `elisionstye`, which would be italic by default.

What do you think?

**Comment by henryso** [comment]
Would the second `a` be in `elisionstyle` in both cases?

**Comment by eroux** [comment]
no, only the text in `<e>` markups is in `elisionstyle`

**Comment by henryso** [comment]
To answer the question at the top of the issue, I don't have any objections to this feature.  Does this need to be in 4.1?

**Comment by eroux** [comment]
If possible that would be great indeed! Also, by default, `elisionstyle` should use `\small`. Here is a example (here ellisions are not small, but they should):

![magi](https://cloud.githubusercontent.com/assets/60868/12594157/ecd558ce-c474-11e5-9445-6182a3e9bc2d.png)

**Comment by henryso** [comment]
What should happen if the first letter in the score is inside an elision block?  Should the initial be the first letter after the elision (which would make things very complicated)?  Should this be an error?  Something else?

**Comment by eroux** [comment]
I think an error should be just fine
