### ISSUE TITLE
hyphens in margins

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#845]
Hyphens should not be allowed to go far from the right limit of the staff lines. Example of undesired behavior:

![hyphen](https://cloud.githubusercontent.com/assets/60868/12647635/676de7ce-c5d6-11e5-957c-93f9e1b460ba.png)

In a first step, the behavior should be the same as when there is no hyphen, in a second step we would differenciate the case where the syllable ends by an hyphen (automatic or not), and allow it to come closer to the lines (a kind of [character protrusion](http://wiki.contextgarden.net/Protrusion)). 

I'm affraid this is no easy fix, as the hyphen that poses problems is added in lua after the paragraph breaking algorithm, so even in a two-pass system, this wouldn't be easy: the first pass would tell the second to add an hyphen, and in some cases, the second would pass the syllable on the line after (because it would have become too big to stay on the line it was on), and thus we would have an instable system... Maybe the best way to deal with this is with a discretionary?

**Comment by rpspringuel** [comment]
It looks to me like that hyphen is protruding exactly as it should according to the page you linked.

Also, do you have the gabc file that you used to produce the score from which that image was cut?

**Comment by eroux** [comment]
The thing is the protrusion here is a bug, not a feature that was intended, and protrusion should be optional anyway (not all people like the mechanism). You can reproduce it with

```
\documentclass[11pt]{article}
\usepackage{fontspec}
\usepackage{geometry}
\geometry{a5paper}
\usepackage{gregoriotex}
\usepackage{libertine}
\begin{document}
\gabcsnippet{igggg(g)igggg(g) igggg(g)igggg(g) igggg(g)igggg(g) igggg(g)igggg(g) igggg(g)igggg(g)}
\end{document}
```

although here this is a limit case that might be hard to fix...

**Comment by eroux** [comment]
I think it's possible to trick this by adding some kind of space (the size of an hyphen) after the text, this space being removed if not at end of line... might not be easy but that should be the best solution

**Comment by eroux** [comment]
See the example of [this message](https://www.mail-archive.com/gregorio-users@gna.org/msg03349.html) for a realistic case.

**Comment by eroux** [comment]
See #945
