### ISSUE TITLE
more generic system for special characters

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#846]
Solesmes is planning to input special characters not currently handled by Gregorio, like a H with bar, or a custom TQ and TP they'll have in their font. I think a good solution would be to have a macro like `\grespecialcharacter{H/}{\mySpecialHBar}`, and use if to catch all "special characters", and if a special character is not present, it would simply be printed as is (e.g. `H/` in previous case). What do you think?

**Comment by henryso** [comment]
I don't have an issue with this.  Does it need to be in 4.1?
