### ISSUE TITLE
Unintuitive syntax for horizontal episemas

### ISSUE THREAD

**Issue by ebydj1** [gregorio-project/gregorio#847]
Executing the code `(c4) test(efe___3//e_f_e_3)` produces this:
![unexpected_episema_behavior](https://cloud.githubusercontent.com/assets/4675370/12666541/ec57b76a-c60f-11e5-8232-f0ad22256f23.png)

I would expect the same result as the code `(c4) test(e_f_e_3//e_f_e_3)`, namely this:
![expected_episema_behavior](https://cloud.githubusercontent.com/assets/4675370/12666566/2670b316-c610-11e5-93b2-f837f406d0ed.png)

**Comment by henryso** [comment]
When using strings of `_` they apply backwards, so the first `_` is the previous note, the second is the note prior to that, and the third is the note prior to that.  This is a point of perception: some people will see it one way and some people will see it the other.  I brought this up when implementing this feature, and we decided that if you want the precision afforded by the the `2`, `3`, `4`, and `5` modifiers, you should use the latter notation as the former is for backward compatibility only.

**Comment by henryso** [comment]
See discussion in #401.
