### ISSUE TITLE
Greciliae too low?

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#858]
Now that I'm taking a look at greciliae after modifying another font, there is something I'm really puzzled by: I think greciliae is way too low! It's partiularly obvious on porrectus: when one is used to another font, it's hard to read what not a porrectus is in greciliae... Comparing with the original [caeciliae](http://marello.org/caeciliae/downloads/), it's quite obvious to me that there's been a mistake during the import... Before I'm making a few attempts at fixing it (after finishing #803 of course), I'd like to know what you think?

**Comment by henryso** [comment]
Can you post some images?  I'm not entirely sure what you mean by "low".

**Comment by eroux** [comment]
Here is a porrectus in caeciliae:

![porrectus-caeciliae](https://cloud.githubusercontent.com/assets/60868/12722832/0d9b9b22-c907-11e5-8981-0065fcfce579.png)

and the same in greciliae:

![porrectus-greciliae](https://cloud.githubusercontent.com/assets/60868/12722845/15a11f68-c907-11e5-995d-6e7faa201345.png)

in caeciliae, the staff line is around the middle of the left of the stroke, while is greciliae, it's around the third...

**Comment by henryso** [comment]
Thank you.  In that case, I agree, but some people may be used to greciliae...

**Comment by eroux** [comment]
Yes... How do you think we should proceed? Should we ask the user list? Maybe propositing between the two options:

- just change greciliae
- reimport caeciliae and rename the old one greciliae-old

?

**Comment by henryso** [comment]
If we are going to only package one font and make the rest available for download, I think it would be best to have "greciliae-old", "gregorio", "parmesan", and all the "-op" fonts be available that way, with "greciliae" (new) being the one that is distributed.

If we are *not* going to do that, then I would announce this to the list in order to help us decide whether we just replace greciliae or distribute both.

I am open to any other ideas, as well.

**Comment by eroux** [comment]
Making a few calculations, the caeciliae glyphs should be scaled by `1.26` and then shifted down by `391.42`. I don't know what calculations I did during initial import, but it clearly wasn't this one... Maybe what's best is to finish #803 and then I'll work a few hours on this new import, make a sample pdf with simple glyphs, and propose the change to the list... What do you think? Unless someone would like to give it a try? (it's a bit repetitive, but it's also a bit fun!) @eschwab or @rpspringuel would you be interested and have a little time (I hope the merge for #803 can be tonight or tomorrow)?

**Comment by eroux** [comment]
I've made an attempt and sent it to the list, see [this thread](https://mail.gna.org/public/gregorio-users/2016-02/msg00016.html).

**Comment by eroux** [comment]
According to the only answer on the list, I guess it's no big deal to just change it... See branch `fix-858` for an attempt, let's just wait a little more to see if other answers come.

**Comment by henryso** [comment]
I guess they answered you directly, because I haven't seen anything on the list.  But I agree that we should wait a bit longer.

**Comment by eroux** [comment]
I didn't notice, but you're right, the answer was for me alone. There was only one answer, positive.
