### ISSUE TITLE
Heuristics should be glyph-wise

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#863]
See [this comment](https://github.com/gregorio-project/gregorio/issues/803#issuecomment-178758131) and following, if `[ll:0]` or `[ll:1]` are found on any note of the glyph, they should count for the whole glyph, as I cannot imagine a documentation describing on which note to add the `[ll:x]` notation according to the glyph...

**Comment by henryso** [comment]
Does this mean all notes in the glyph should be marked as having a ledger line globally (i.e., it affects sign positioning in TeX), or should this change only affect stem determination?

**Comment by eroux** [comment]
That's a good question... An alternative would be that stem length algorithm looks at `[ll:x]` on the note carrying the stem (this ways the documentation can remain simple)... does it sound feasible?

**Comment by henryso** [comment]
All the listed solutions are feasible without too much effort.  It all rides on which solution is most sensible.  To that end, I think your latest suggestion sounds like the best of these.

**Comment by eroux** [comment]
ok then, let's do it that way
