### ISSUE TITLE
Bug in element determination

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#868]
I found a major and long-standing bug in the code.  In `gabc-elements-determination.c`, there is this code:

```
        if (is_puncta_ascendens(current_glyph->type)) {
            current_glyph_type = G_PUNCTA_ASCENDENS;
        } else {
            if (is_puncta_descendens(current_glyph->type)) {
                current_glyph_type = G_PUNCTA_DESCENDENS;
            } else {
                current_glyph_type = current_glyph->type;
            }
        }
```

The problem is, `current_glyph_type` is being tested against `gregorio_glyph_type` values but `current_glyph->type` is of type `gregorio_type`, and in this case is *always* `GRE_GLYPH` (which has the same numeric value as `G_2_PUNCTA_INCLINATA_DESCENDENS`).

So this code is *unconditionally* setting `current_glyph_type` to `G_PUNCTA_DESCENDENS` before making any further element determination.

If I fix this by changing the code to
```
        if (is_puncta_ascendens(current_glyph->u.notes.glyph_type)) {
            current_glyph_type = G_PUNCTA_ASCENDENS;
        } else {
            if (is_puncta_descendens(current_glyph->u.notes.glyph_type)) {
                current_glyph_type = G_PUNCTA_DESCENDENS;
            } else {
                current_glyph_type = current_glyph->u.notes.glyph_type;
            }
        }
```
... it changes **A LOT** of tests.  Do I fix it?

This code has literally been doing this since *inception* (see https://github.com/gregorio-project/gregorio/blob/588be00ed31072c8d0c2ef14d382718bdd130ecf/plugins/gabc/gabc-elements-determination.c).

**Comment by henryso** [comment]
Note that doing this also completely breaks fusion because fusion was written with the assumptions of how the code was working, so if we decide to fix this, then we would have to make fusion work again.

Alternately, I can distill out the current behavior (as opposed to the original code's intent) and make the intent of the new code the same as the effect of the old code.

**Comment by eroux** [comment]
Interesting finding! Apart from fusion, does fixing change a lot of pdf output? My first thought would be to fix it and the fusion, but I'll take a closer look at the results.

**Comment by eroux** [comment]
I think your change is not enough to make everything work, I have a lot of

```
in function `close_element': assertion:previous element was not closed
```

when I try it

**Comment by henryso** [comment]
I took that bit of code (in `close_element`) to be an assertion because no run was using that code path.  However, this was, of course, because the element determination was not exercising that code.  So, yes, we would have to remove the assertion to allow it to run.  It does change a lot of PDF output, but I didn't check the extent of how it changed PDF output (i.e., only a pixel here and there vs. massive movement).  The biggest change is that a lot of `EndOfGlyph` become `EndOfElement`.

**Comment by eroux** [comment]
Hmm do you think you could paste a working patch for `gabc-element-determination.c`?

**Comment by henryso** [comment]
```
diff -r 5083e7ca8749 src/gabc/gabc-elements-determination.c
--- a/src/gabc/gabc-elements-determination.c	Thu Feb 04 08:26:14 2016 +0100
+++ b/src/gabc/gabc-elements-determination.c	Thu Feb 04 08:43:42 2016 -0500
@@ -36,22 +36,32 @@
  * 
  */
 
-static __inline bool is_puncta_ascendens(char glyph)
+static __inline bool is_puncta_ascendens(gregorio_glyph_type glyph)
 {
-    return glyph == G_2_PUNCTA_INCLINATA_ASCENDENS
-        || glyph == G_3_PUNCTA_INCLINATA_ASCENDENS
-        || glyph == G_4_PUNCTA_INCLINATA_ASCENDENS
-        || glyph == G_5_PUNCTA_INCLINATA_ASCENDENS
-        || glyph == G_PUNCTUM_INCLINATUM;
+    switch (glyph) {
+    case G_2_PUNCTA_INCLINATA_ASCENDENS:
+    case G_3_PUNCTA_INCLINATA_ASCENDENS:
+    case G_4_PUNCTA_INCLINATA_ASCENDENS:
+    case G_5_PUNCTA_INCLINATA_ASCENDENS:
+    case G_PUNCTUM_INCLINATUM:
+        return true;
+    default:
+        return false;
+    }
 }
 
-static __inline bool is_puncta_descendens(char glyph)
+static __inline bool is_puncta_descendens(gregorio_glyph_type glyph)
 {
-    return glyph == G_2_PUNCTA_INCLINATA_DESCENDENS
-        || glyph == G_3_PUNCTA_INCLINATA_DESCENDENS
-        || glyph == G_4_PUNCTA_INCLINATA_DESCENDENS
-        || glyph == G_5_PUNCTA_INCLINATA_DESCENDENS
-        || glyph == G_PUNCTUM_INCLINATUM;
+    switch (glyph) {
+    case G_2_PUNCTA_INCLINATA_DESCENDENS:
+    case G_3_PUNCTA_INCLINATA_DESCENDENS:
+    case G_4_PUNCTA_INCLINATA_DESCENDENS:
+    case G_5_PUNCTA_INCLINATA_DESCENDENS:
+    case G_PUNCTUM_INCLINATUM:
+        return true;
+    default:
+        return false;
+    }
 }
 
 /*
@@ -70,15 +80,9 @@
 {
     gregorio_add_element(current_element, *first_glyph);
     if (*first_glyph && (*first_glyph)->previous) {
-        /* not reachable unless there's a programming error */
-        /* LCOV_EXCL_START */
-        gregorio_fail(close_element, "previous element was not closed");
         (*first_glyph)->previous->next = NULL;
         (*first_glyph)->previous = NULL;
     }
-    /* for some reason (optimization?), the previous line is not counted as
-     * covered even though the start of the condition IS covered */
-    /* LCOV_EXCL_STOP */
     *first_glyph = current_glyph->next;
 }
 
@@ -123,7 +127,7 @@
     /* a char that is necessary to determine some cases */
     bool do_not_cut = false;
     /* a char that is necesarry to determine the type of the current_glyph */
-    char current_glyph_type;
+    gregorio_glyph_type current_glyph_type;
 
     gregorio_not_null(current_glyph, gabc_det_elements_from_glyphs, return NULL);
     /* first we go to the first glyph in the chained list of glyphs (maybe to
@@ -182,13 +186,13 @@
             continue;
         }
 
-        if (is_puncta_ascendens(current_glyph->type)) {
+        if (is_puncta_ascendens(current_glyph->u.notes.glyph_type)) {
             current_glyph_type = G_PUNCTA_ASCENDENS;
         } else {
-            if (is_puncta_descendens(current_glyph->type)) {
+            if (is_puncta_descendens(current_glyph->u.notes.glyph_type)) {
                 current_glyph_type = G_PUNCTA_DESCENDENS;
             } else {
-                current_glyph_type = current_glyph->type;
+                current_glyph_type = current_glyph->u.notes.glyph_type;
             }
         }
         switch (current_glyph_type) {
```

**Comment by henryso** [comment]
I'm reviewing the test results and will report back once I have a better idea.

**Comment by eroux** [comment]
I've reviewed some, it seems quite good to me... better than before actually... Maybe we can keep it for another change, but I think `!/` should correspond to an inter-glyph space, and keep both sides in the same `gre_element`. That's the only space a user cannot input, it shouldn't change anything in the output (the space is almost the same a an unbreakable interelement space), but would make internal representation more coherent... What do you think?

**Comment by henryso** [comment]
I concur.

On PDF, most changes are only a very slight shift (less than one pixel at 100dpi).  The alterations no longer connect to the previous note (which is a better result).  Fusion is of course broken as are notes immediately following a string of ascending puncta inclinata (i.e., `GHiv` has an interelement space after `H`).

On the other tests, besides fusion, it's the effect of breaking the element in different places, so gabc-gabc has '/' interspersed where element break was detected, gabc-gtex has the change from `EndOfGlyph` to `EndOfElement`, and gabc-dump shows a new element.

My only remaining question is whether `GHiv` is interpreted correctly (whether it should be interpreted as `GH/iv`, as it is with this new code, or `GH!iv` as it was before.)

**Comment by eroux** [comment]
The original intent was `GH!iv` (but maybe it was bugged too), I think it's best... Also `GH@ig` should be just one element, as in [this picture](https://cloud.githubusercontent.com/assets/60868/11631732/bb727fa2-9d03-11e5-9a12-8b618989bdf3.png). Generally speaking, puncta inclinata should always be in the same element as what's after (when ascendens) or before (when descendens).

**Comment by henryso** [comment]
OK. I will work on this tonight, after work.

**Comment by henryso** [comment]
If I make `!/` a glyph-level space, the user will not be able to enter a non-breaking element space.  Is that OK?

**Comment by henryso** [comment]
What is the purpose of this code block in gabc-elements-determination.c?
```
        case G_ONE_NOTE:
            if (current_glyph->u.notes.first_note
                && (current_glyph->u.notes.first_note->u.note.shape == S_STROPHA
                    || current_glyph->u.notes.first_note->u.note.shape == S_VIRGA
                    || current_glyph->u.notes.first_note->u.note.shape == S_VIRGA_REVERSA)) {
                /* we determine the last pitch */
                char last_pitch;
                gregorio_note *tmp_note;
                tmp_note = previous_glyph->u.notes.first_note;
                while (tmp_note->next) {
                    tmp_note = tmp_note->next;
                }
                last_pitch = tmp_note->u.note.pitch;
                if (current_glyph->u.notes.first_note->u.note.pitch == last_pitch) {
                    previous_glyph = current_glyph;
                    break;
                }
            }
```

There is currently no way for the glyph type to be `G_ONE_NOTE`, so this code can never be executed.  What is the intention here?  Should I just drop this code?

**Comment by eroux** [comment]
I think the point here was to make a serie of virgas or strophas at the same pitch in the same element. Maybe it's not relevant anymore, but it should be tested... and I think two consecutive isolated punctum sharing the same pitch should also be in the same element. I think it's ok not to be able to input a non-breaking element space... but I'm not 100% sure, I hesitate between this and `/1` for interglyph space... What do you think?

**Comment by henryso** [comment]
Based on that premise, I think I can make the `G_ONE_NOTE` thing work.  The code is definitely buggy as my earlier testing showed that previous_glyph can be any glyph that can come after a GRE_SPACE, including another GRE_SPACE.

How about `/!` for an interglyph space?

**Comment by eroux** [comment]
That's a bit tricky but why not yes
