### ISSUE TITLE
Unified Version Number

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#87]
Given that we're releasing more regularly, @eroux and I have discussed the possibility of eliminating the GregorioTeX API version number and moving to a single version number, 3.0.0 in the case of this release.  This should make it easier on the user to keep track of what's going on.

This will require a couple of modifications to `VersionUpdater.py` and `VERSION` to implement.

VERSION should also probably include some guidelines for when and how incrementation is done.  The ones that @eroux and I discussed are:

> We adopt the Semantic Version numbering scheme of x.y.z and only have the one version number.  The alternate version numbers for other parts of the project would be officially dropped.
> 
> z - This number is incremented for bug fixes.  All the work I did recently correcting glues that were leaking onto the score would qualify.  This resets to 0 when x or y increments.
> 
> y - This number is incremented for enhancements.  The new EUOUAE tags would qualify.  This resets to 0 when x increments.
> 
> x - This number is incremented for interface changes.  The recent change to how distances are set and used would qualify.
> 
> Code refactoring (i.e. changes which do not effect the user's experience in any way) would not qualify for a change in any of the numbers.
> 
> Release Schedule - In any month where we make commits to the repository, on the last day of the month we assess those commits and decide whether they warrant a bump to the version number, and if so to which part of the number.  The goal here is not to say that we should release once each month, but rather that we shouldn't release more often than once each month.  If a month has been somewhat lacking in changes, we're still bug swatting those changes that we did make, or we're still in the process of documenting them, then we simply don't release that month and put things off until the following one.

**Comment by eschwab** [comment]
Couple of things.

The API version checks will remain, just that instead of `yyyymmdd` it will have `3.0.0`? Fine with me.

If it is to be `3.0.0` in 'gregoriotex' can we either drop the .'s or replace them with a different sep char? Reason is that I am opposed to filenames with .'s that don't introduce suffixes. I really would not like seeing `antiphon-3.0.0.gtex` but rather `antiphon-3_0_0.gtex` or `antiphon_3-0-0.gtex`.

Either way, I can edit the versioning files when ready.

**Comment by eroux** [comment]
@eschwab is right here I believe, dots should be avoided in filenames.

**Comment by rpspringuel** [comment]
I agree that dots should be avoided in filenames, but they should probably be used elsewhere as that's the expected separator for the components of the version number.  I would favor the `antiphon-3_0_0.gtex` format for file names (as 3_0_0 is more visually similar to 3.0.0 than 3-0-0 and thus more likely to be recognized for what it is).  It should be fairly simple for a python or lua script to translate back and forth where needed (a simple string substitution).

**Comment by eschwab** [comment]
Ok, so keep `internalversion = 3.0.0` but filenames `antiphon-3_0_0.gtex`. Sound good, I should be able to do this later tonight.
