### ISSUE TITLE
simplifying font by hand?

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#874]
The fontforge script doesn't simplify glyphs even when `.simplify()` is called on each glyph or on a selection including all glyphs. Simplifying by hand gives these results:

- no simplifcation:
  - `greciliae.ttf`: 1047712 bytes
  - a small pdf including two scores : 21848 bytes
- simplified:
  - `greciliae.ttf`: 920228 bytes
  - a small pdf including two scores : 21512 bytes

which is 12% for the font and 1.5% for the pdf. Although the economy is quite small for the pdf, maybe it's still worth doing a simplification by hand for the different fonts we generate? It's fairly simple:

- open into fontforge
- select all glyphs (ctrl+a)
- Element->Simplify->Simplify
- File->Generate Font

What do you think about doing this before releasing the tarballs? Maybe not for betas and rcs (though it would be good to do it once before the final release to see if there is any problem)...

**Comment by henryso** [comment]
Sounds like a really good idea, given the *huge* difference.  I just wish fontforge was better about these things.

**Comment by rpspringuel** [comment]
Is it possible that the settings for the GUI are different from the settings used in our script for simplify?

If they are the same, then it's probably this bug: https://github.com/fontforge/fontforge/issues/1348.  Unfortunately, the fontforge people don't appear to be doing anything to fix it (the bug report is over a year old).  Then again with some 718 open issues, it's not surprising that they don't have time to get to everything.

Practically speaking, doing this by hand would mean that `make dist` no longer creates the distribution, at least not unattended.  We could still use it, but would need to introduce a pause (wait for user prompt) after the fonts are built where the manual step could be inserted before `make dist` continues.  Perhaps that should be a different target for `make`?

**Comment by eroux** [comment]
Right, the `make dist` thing will be quite annoying... Maybe the bug of `simplify` doesn't appear in a fresh script doing only that, so a solution that could be tried is to make `squarize.py` output an `.sfd` file, and add an option to `converttottf.py` to make it simplify the font before converting (who knows!)... I'll try that this week-end. 

Anyway, [fontforge kind of belongs to the past](http://typedrawers.com/discussion/comment/15260/#Comment_15260), the future seems to be to have [UFO](http://unifiedfontobject.org/) files and treat them directly with some [python library](https://github.com/ufo-kit/ufo-core/tree/master/python) directly... That will make things simple, but we have to make high-level functions for squarize.py first...

**Comment by henryso** [comment]
You could run make, then edit/simplify/save, then run make dist.  It won't make the fonts again if it doesn't have to.
