### ISSUE TITLE
ledger line piercing flats

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#882]
In this image, the ledger line in "piercing" the flat:

![bxb](https://cloud.githubusercontent.com/assets/60868/12867351/8a149702-cceb-11e5-979e-a278893e3da5.png)

I admit I hoped nobody would ever used this... but the Antiphonale Monasticum project does!

I don't think it's easily fixable, but there should be a way to fix it by hand, for instance by specifiying 

- first a ledger line embracing all the glyphs
- then all the glyphs, but without the ledger lines

Once there's a way to manually do that (in gabc), then we can think about making the C code output spot this case and output the correct TeX, but I think we can keep that part for later...

**Comment by henryso** [comment]
Would it be possible to save all the positions of the holes and draw them on top on a second pass?

**Comment by eroux** [comment]
That's an idea... It's just not obvious to me how you would do it... In this direction, I'm wondering if it would be possible to do in in the `post_linebreakfilter` callback in lua, by reducing the left advance of the rule of a ledger line following a cavum glyph... That doesn't sounds too difficult... What do you think?

**Comment by eroux** [comment]
Well, in fact no need to do it in the lua callback, it should even be doable on the pure TeX side, it should be enough to save the information that the last seen glyph is a cavum, and the reduce the size of the ledger line accordingly, it seems even easier!

**Comment by henryso** [comment]
I was actually thinking about instrumenting all cavum macros to save the position on the page where the cavum hole glyphs should be drawn, and then draw them at the end of each score (in the second pass, of course).  However, what you say sounds simpler, although I don't know TeX well enough to fully understand what you are describing.
