### ISSUE TITLE
not enough space above the line with l_1

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#883]
In attached picture:

![episemustooclose](https://cloud.githubusercontent.com/assets/60868/12867388/86469160-ccec-11e5-9b1a-41498a776d88.png)

there is not enough space above the line. It might be a suboptimal setting and not a bug, I'll inspect that.

**Comment by henryso** [comment]
@eroux Have you confirmed this is a bug rather than a suboptimal setting?

**Comment by eroux** [comment]
not yet, I'll try to do that this morning
