### ISSUE TITLE
UserManual updates.

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#89]
If you've added (or changed) user functionality to the code recently, please make sure that it is listed in the UserManual (in the doc folder).  This is especially important for stuff which is new to 3.0.  I realize that there is a backlog of documentation updates that are needed, but for the moment I'm just concerned about the new stuff.

**Comment by eschwab** [comment]
I'm working on enhancing `\includescore` documentation. @rpspringuel , I can deal with the things added in #86

**Comment by eroux** [comment]
this could be closed right?

**Comment by eschwab** [comment]
I was just looking through the commit log to check, and everything seems to be taken care of.
