### ISSUE TITLE
--version, suggest --help instead of dumping entire usage

### ISSUE THREAD

**Issue by kberry** [gregorio-project/gregorio#891]
it would be nice if gregorio supported the widespread  --version option along with --help.  Here is some info for it:
https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html

Also, it would be nice if gregorio, when invoked with no arguments, just said something like:
  gregorio: missing file operand
  Try 'gregorio --help' for more information.
instead of dumping the whole usage message.

Similarly, when there is an error in arg parsing, an invocation like "gregorio -o" with no argument, it's nicer to just report the error and give the suggestion instead of dumping the whole usage message.  That is usually too much info.

Also, the spaces before colons ("Usage :", "is :"), while I know are usual in French, are just weirdly wrong in English.  There's also no need for the newline before "Usage", or the newline after the "Usage:", or an extra newline at the end.  Fewer lines is better.

Also, it is highly useful to write a sentence or two about what the program does in the --help message.  Something like "Engrave Gregorian chant scores: convert a gabc file to GregorioTeX." 

Also, it's typical to capitalize metavariables like "FORMAT" and "FILE"  in the help message.

Also, the help message could/should end with a url to the overall project home page.

Also, it is not usual to capitalize "Chant" in "Gregorian chant", as far as I've seen.

See pretty much any GNU --help (and --version) message for examples of all this in action.  "mv --help" is reasonably short and instructive.

Happy helping.

**Comment by eroux** [comment]
Thanks a lot, we'll take care of that in rc1 which should be out next Sunday (beta2 has been released a few minutes ago!)

**Comment by eroux** [comment]
Closed by #892
