### ISSUE TITLE
Liquescent scandicus determination is broken

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#897]
Attempting to create a liquescent scandicus in gregorio 4.1-beta2 will fail with an assertion error.  This is due to an error in the assertion.

**Comment by henryso** [comment]
In adding the assertions, I asserted that liquescent scandicus would be determined properly in glyph determination; it is not and (in the prior code) resulted in a fall back to three individual notes glued together.  There are three ways I can see to fix this:
- remove the assertion and restore this figure falling back to being three notes glued together
- determine it as something else (punctum + podatus, podatus + punctum?)
- draw the missing glyphs and determine it as liquescent scandicus.

Any thoughts or suggestions?

**Comment by eroux** [comment]
What comes to my mind first is the first solution... let's wait for a user request before implementing the third one. About two, I'm pretty sure I've seen figures like `(ghi<)` somewhere, so let's not do it...
