### ISSUE TITLE
bug in centering <sp>ae'</sp>

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#899]
This example:

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{gregoriotex}
\begin{document}
\gabcsnippet{(c4) gr<sp>'ae</sp>(c) grǽ(c)}
\end{document}
```

shows a difference in the notes alignment between `grǽ` and `gr<sp>'ae</sp>` which shouldn't exist

**Comment by eroux** [comment]
Strangely, there is no `center` style in this case:

```
=====================================================================
   type                      0 (GRE_SYLLABLE)
   position                  4 (WORD_ONE_SYLLABLE)
---------------------------------------------------------------------
     character                 g
---------------------------------------------------------------------
     character                 r
---------------------------------------------------------------------
     beginning of style    ST_SPECIAL_CHAR
---------------------------------------------------------------------
     character                 '
---------------------------------------------------------------------
     character                 a
---------------------------------------------------------------------
     character                 e
---------------------------------------------------------------------
     end of style          ST_SPECIAL_CHAR
---------------------------------------------------------------------
     type                    3 (GRE_ELEMENT)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

I'm not sure what the current behavior is supposed to be (I don't think it inspects inside `<sp>` to check if there's a vowel), but I think it could be "if no center has been found and there is a `<sp>` then take the first (or last, doesn't matter) `sp`... What do you think?

**Comment by henryso** [comment]
It assumes the special character is just a character.  In this case, I would suggest either using curly braces (forced center) or allowing the user to somehow indicate that certain `<sp>` sequences should be considered vowels.  I don't think we can make *any* assumptions here.  `<sp>R/</sp>` is a special character, frequently at the beginning of a syllable, which should decidedly not be considered a vowel, and `<sp>+</sp>` is a dagger which would typically be at the end of a syllable, and which should also not be considered a vowel.

**Comment by henryso** [comment]
Alternately, we could add something like a `<vsp>` which acts like `<sp>` but which is considered a vowel.

**Comment by eroux** [comment]
Sure, but in the case of `R/` and `+`, the algorithm I describe is still OK I believe (centering around `<sp>` if not other candidate has been found)... Anyway, asking users to use `{}` is not too much, we can do it this way if you prefer. We should just find a way to document it properly...

**Comment by henryso** [comment]
Closing per #900.
