### ISSUE TITLE
3.0 Upgrade Manual

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#90]
An upgrade manual needs to be added to the doc folder which provides instructions for how to get old projects to work with version 3.0.  This is mostly for me, since it's the distance changes that require the biggest adjustments, but any non-backwards compatible changes should be mentioned here.

**Comment by eroux** [comment]
What about creating `UPGRADE.md` with currently only the migration from 2.x to 3.0?

**Comment by eschwab** [comment]
Manual created in #133
