### ISSUE TITLE
Improve format of gabc output

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#905]
While they don't mean anything to the program, line breaks are extremely useful to making a gabc file more human readable (especially when studying diffs).  I thus propose that when generating gabc output the command line tool insert a few.

Off hand I would say that a line break should be introduced after bar syllables and after a explicit line break indication (i.e. a `z` or `Z`, with its modifiers) in the score.

**Comment by eroux** [comment]
Good idea yes

**Comment by eschwab** [comment]
I tried to do something but ran into a difficulty.

```
diff --git a/src/gabc/gabc-write.c b/src/gabc/gabc-write.c
index 46ac340..65280ad 100644
--- a/src/gabc/gabc-write.c
+++ b/src/gabc/gabc-write.c
@@ -1034,7 +1034,13 @@ static void gabc_write_gregorio_syllable(FILE *f, gregorio_syllable *syllable,
     {
         fprintf(f, ") ");
     } else {
-        fprintf(f, ")");
+        if (syllable->elements[0]->type == GRE_BAR
+            || syllable->elements[0]->type == GRE_END_OF_LINE)
+        {
+            fprintf(f, ")\n");
+        } else {
+            fprintf(f, ")");
+        }
     }
 }
```

The `if` is always returning `false` and I presume that this is a type mismatch between the elements of the comparison. I am not really sure how to fix that. Also this may be too simple of a solution and it possibly would be better to have a function handle writing the `)`. Not sure.

**Comment by henryso** [comment]
You are putting the check in the place which catches the *middle* of syllables.  The chance of there being a bar or end of line there is pretty low.  People don't typically put stuff like `syl(:)lab(z)le(g)`, and, in fact, putting a newline there would be a bad idea, as it would end the syllable in the wrong place.  You want to do the check in the previous clause, that prints `") "`.  You probably also want to check *more* than just the first element in the syllable.  Perhaps `gabc_write_gregorio_elements` can return whether it detected a bar or newline.

**Comment by eschwab** [comment]
I have something that seems to be working for me. I'm fine with holding it until after the feature freeze of 4.1 is made. Unless we want this in 4.1.

**Comment by henryso** [comment]
If this is what you have in 1824d90, I don't object to this being merged now.

**Comment by eroux** [comment]
Ok for me too
