### ISSUE TITLE
compilation of TeX Live state on Debian fails

### ISSUE THREAD

**Issue by norbusan** [gregorio-project/gregorio#908]
Hi all,

I just tried to compile the TeX Live sources on Debian and it failed in Gregorio:
`````
gcc -DHAVE_CONFIG_H -I. -I../../../texk/gregorio  -I../../../texk/gregorio/gregorio-src/src -I../../../texk/gregorio/gregorio-src/src/gabc -I../../../texk/gregorio/gregorio-src/src/dump -I../../../texk/gregorio/gregorio-src/src/gregoriotex -I/src/TeX/debian/git/build-area/texlive-bin-2015.20160211.39663/Work/texk -I/src/TeX/debian/git/build-area/texlive-bin-2015.20160211.39663/texk -D_GNU_SOURCE -DUSE_KPSE -Wdate-time -D_FORTIFY_SOURCE=2 -Wimplicit -Wreturn-type -Wdeclaration-after-statement -Wno-unknown-pragmas -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c -o gregorio-src/src/gregorio-utils.o ../../../texk/gregorio/gregorio-src/src/gregorio-utils.c
In file included from ../../../texk/gregorio/gregorio-src/src/struct.h:38:0,
                 from ../../../texk/gregorio/gregorio-src/src/gregorio-utils.c:40:
../../../texk/gregorio/gregorio-src/src/gregorio-utils.c: In function ‘print_usage’:
../../../texk/gregorio/gregorio-src/src/gregorio-utils.c:213:15: error: expected ‘)’ before ‘FILENAME_VERSION’
 GregorioRef-" FILENAME_VERSION ".pdf and GregorioNabcRef-" FILENAME_VERSION ".pdf for full documentation.\
               ^
../../../texk/gregorio/gregorio-src/src/messages.h:35:16: note: in definition of macro ‘_’
 #define _(str) str
                ^
Makefile:836: recipe for target 'gregorio-src/src/gregorio-utils.o' failed
`````

Would be nice to have this fixes, thanks

Norbert

**Comment by eroux** [comment]
I'm not sure about the current state of the sources in TeXLive (is it beta3?) nor about the building process, but can you try running `autoreconf -fi` and `./configure` again? `FILENAME_VERSION` is defined in `configure.ac`

**Comment by henryso** [comment]
If FILENAME_VERSION is properly defined, then the C-preprocessor is acting differently, so maybe the macros should be defined like
```
#define _(str) (str)
```
for safety.

**Comment by eroux** [comment]
Updating to latest Debian/testing build tools, I don't get this error, so I think the import into TeXLive made `FILENAME_VERSION` undefined

**Comment by norbusan** [comment]
@eroux  yes it is beta3, and I already run autoreconf in the texlive source tree due to (unrelated) changes in the automake files.

**Comment by norbusan** [comment]
I am running Debian/unstable - that is gcc 5.3.1

**Comment by norbusan** [comment]
@henryso  I agree that the _(str) (str) construct is safer!

**Comment by eroux** [comment]
I think I understand: in [TeXlive's custom config_.h.in](https://www.tug.org/svn/texlive/trunk/Build/source/texk/gregorio/config_.h.in?revision=39625&view=markup) you don't define `FILENAME_VERSION`, can you add it?

**Comment by norbusan** [comment]
Hmm, mine tells me 
`````
/* config_.h.in.  Generated from configure.ac by autoheader.  */
`````
so it might get overwritten immediatly.

BTW, I have added parenthesis around all macro definitions in messages.h with lonesome `str` and it seemed to have helped (now hanging in upmendex, though ...)

**Comment by norbusan** [comment]
Ah, no, sorry, did NOT help ...

**Comment by eroux** [comment]
Ok I see, maybe TeXLive's `config_.h.in` is used by Akira for Windows build and should still be updated in the svn?

**Comment by norbusan** [comment]
No idea, I will ask Akira ...

**Comment by eroux** [comment]
(I'm trying to checkout Build/source from svn but my connection makes it very slow, it's gonna take a while)

**Comment by eroux** [comment]
I've finally managed to reproduce the problem. Applying the following patch to `Build/source/` on TeXLive's svn makes the problem go away:

```
--- texk/gregorio/config_.h.in	(révision 39666)
+++ texk/gregorio/config_.h.in	(copie de travail)
@@ -143,6 +143,9 @@
 /* Version number of package */
 #undef VERSION
 
+/* version suitable for file names */
+#undef FILENAME_VERSION
+
 /* Define WORDS_BIGENDIAN to 1 if your processor stores words with the most
    significant byte first (like Motorola and SPARC, unlike Intel). */
 #if defined AC_APPLE_UNIVERSAL_BUILD
```

**Comment by eroux** [comment]
(out of curiosity, I suppose *Norbu* is the Japanese way to say *Norbert*? I got a little confused at the beginning because *Norbu* is also a very common Tibetan name.)

**Comment by norbusan** [comment]
Hi everyone,
Akira fixed it in the sources.
Concerning my ID, in fact it comes from the time studied Tibetan at the university, at that time, more than 20 years ago I was young and stupid and thought this is a good I'd and it somehow remained through the years. Didn't know at that time I will ever end up in Japan ;-)

**Comment by eroux** [comment]
Ok thanks! The mixing between Tibetan and Japanese sounds nice, a bit exotic since the sound *san* is impossible in Tibetan :-)

**Comment by norbusan** [comment]
Yes, as I said, I was young and stupid ...
