### ISSUE TITLE
queue length for fused virga seems wrong

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#913]
Here is the result of `(hV@g@h@gf~)` (which the Antiphonale Monasticum project will actually use):

![queuelength](https://cloud.githubusercontent.com/assets/60868/13027154/2e401e02-d244-11e5-8eed-9940a3148cc4.png)

The queue at the beginning has the wrong length... If the problem lies in the font I can fix it, but I admit I'm quite uncertain about the queue length behavior in fusion (especially since I don't have a very precise idea on how fusion works in the C code)...

Also, I don't think there's currently any way to get the same result with the right queue length?

**Comment by eroux** [comment]
Sorry, I've found `hV!ghgf~` which solves the issue, so no emergency!

**Comment by eroux** [comment]
It seems to be in the C code, the generated glyph is `GreCPVirgaReversaOneDown` instead of `GreCPVirgaReversaLongqueueOneDown`

**Comment by henryso** [comment]
I think the fusion code is not accounting for the correct note.  I'll get to that once I'm done with the other things.
