### ISSUE TITLE
Line breaks within tristropha

### ISSUE THREAD

**Issue by rarty** [gregorio-project/gregorio#928]
I think after the fix for #868, at least some elements like the tristropha `(hhh)` and bistropha `(hh)` will unexpectedly break across lines, unless the new syntax for inter-glyph space is inserted, i.e. `(h/!h/!h)`.

![texshop_image](https://cloud.githubusercontent.com/assets/6454162/13063912/dbf5a1e6-d412-11e5-9e79-b450e7853374.png)

(using `4.1.0-beta3-develop-8968c0f-3305`)

**Comment by henryso** [comment]
Thank you for finding this bug.
