### ISSUE TITLE
Translation pushing up lyrics under bar at end of line

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#930]
When a bar syllable with a translation text assigned to it occurs at the end of a line and is followed by a line which does not have any translation text, then the lyric text for the bar syllable is not raised up above the translation text (note, I've tried varying these conditions and this is the only circumstance I can find where this bug occurs). This bug can be seen in the results of the bar-spacing-new test in db97a16. My suspicion is that textlower (the amount of the raise) is getting reset to zero a bit too soon, but I have not yet dug into the code to determine where that might be happening.

This bug also appears to affect only the new spacing algorithm, though I'm not sure why at this point.  The only difference I can see so far between the way translations are handled in the old algorithm and the new is that in the old algorithm the order was set translation, text, centered translation, notes, while in the new algorithm the notes come first.

For instance:
```
<alt>Translation text</alt>
TU[Thou art Peter, and upon this rock](ig) es(ij) Pe(i)trus,(i) *(,) et(i) su(i)per(g) hanc(hg) pe(e)tram[/](e) <i>etc.</i>[more text](::) (Z)

<alt>Punctum mora too close to bar line</alt>
3(g.) (;) (g) 4(g) (;) (g)
```

Produces:
![temp](https://cloud.githubusercontent.com/assets/7671682/13099228/32777cc4-d4fe-11e5-8d68-c3a60bb6ba68.png)

Note that "etc." and "more text" overlap at the end of the first line.

This example is extracted from tex-output/bar-spacing/bar-spacing-new.tex in rpspringuel/gregorio-test@db97a16

**Comment by eroux** [comment]
in the old algorithm, `#8` is called before `#9`, but in the new one it's the other way around. Couldn't that be the problem?

**Comment by eroux** [comment]
This problem is fixed by https://github.com/gregorio-project/gregorio/commit/b50aa98af399bf0e4091f43bb675c6ecab788622

**Comment by eroux** [comment]
sorry, it's not, I was just testing with one compilation, the bug appears only at the second one

**Comment by eroux** [comment]
I've debugged it to the point where I see that commenting the line

```
\directlua{gregoriotex.adjust_line_height(\gre@insidediscretionary)}%
```

of `\gre@writebar` in `gregoriotex-signs.tex` fixes the bug, but it's certainly not the proper way to do it... The thing is, I'm not sure I really understand what `adjust_line_height` does... @henryso could you explain that a little? 

The idea here is that we the usual call is first translation then text then note, but in the new algorithm, its first notes then translation then text. Maybe the best option here is to just switch to the normal order in the new algorithm? This shouldn't be too difficult... @rpspringuel what do you think?

**Comment by henryso** [comment]
`adjust_line_heights` generates a `\gre@calculate@additionalspaces` passing the low pitch, high pitch, whether the line has a translation, and whether the line as above lines text (see gregoriotex.lua:430).  It takes these values from the values computed on the previous pass and stored in the `.gaux` file..

**Comment by eroux** [comment]
Thanks, I think the best solution to this is to typeset the notes after the text. I've made a few attempts but I'm getting lost in the different spaces... @rpspringuel do you think you could handle this?
