### ISSUE TITLE
protrusion

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#931]
Looking at some tests for the new bar algorithm:

![aligncoma](https://cloud.githubusercontent.com/assets/60868/13106181/36e08be8-d567-11e5-8511-fc569c8f2e74.png)

I thnk the coma after _Petrus_ shouldn't be taken into account when centering the star. This could be specified in gabc with something like `<pr>` (protrusion): `trus<pr>,</pr>(...)`. This may also impact (with options) the distance at the end of a line (like real protrusion), `interwordspacing`, etc. The ideal would be that users can set up protrusion factors for different symbols (like "protrude coma from half its width", etc. so `<pr>` could taken an optional argument for that.

A direction to explore would be to have several characters automatically protruded (with default factor 0), like `,`, `;`, `:`, `.`, and users would change the protrusion factors of each the TeX side. (forced protrusion in gabc would still be useful with this system). This is the protrusion part of #845 at a larger scale.

**Comment by eschwab** [comment]
I would be in favor of the automatic protrusion. The less things to manually put in the gabc file the better.

**Comment by eroux** [comment]
Sure, what I'm thinking of is to have automatic protrusion, plus the possibility to override it in gabc.

**Comment by henryso** [comment]
Is it required to "close" the `<pr>`?  I realize there's no precedent, but everything did require an explicit close, and this one can only really happen at the end of a word and so is closed by the end of the word.  Not closing the `<pr>` would simplify the parsing.

**Comment by eroux** [comment]
For the sake of coherence, I think it's best if both possibilities are available... or does it cancel the gain of not closing it?

**Comment by henryso** [comment]
It just makes it more complex to parse.  We would have to put in checks that the close occurs on the same syllable and only at the end.  The alternative is a new syntax, but I really don't like that idea, so I guess I'll live with the complexity.

**Comment by henryso** [comment]
I think we were divided evenly between `<pr/>` (@eroux, @jakubjelinek) vs `$pr$` (@henryso, @rpspringuel).  We should resolve that before we start on this.

**Comment by henryso** [comment]
In reference to the previous comment, it was decided that we will support both `<pr>` and `<pr/>`, with `</pr>` being forbidden.

**Comment by henryso** [comment]
Can anyone give me a hint as to what to do on the TeX side?  At this point, I have the C code that sends the protrusion and specified factor to a macro.  I'm thinking it should take a measurement of the difference between full size and factor-adjusted protrusion and subtract it from (or maybe add it to?) something.

**Comment by eroux** [comment]
well, to take the example given in the initial request, the idea is just to put the coma in a box and setting the width of the box to `protrusion_factor * normal_width_of_the_box`, that should be it... plus of course having the user interface to set a protrusion factor for the characters handled on the C side. Don't hesitate to ask if it's not clear!

**Comment by henryso** [comment]
I did think of that, but then thought spacing would be weird (especially in the auto-protrusion case) for a normal space, like for `x.(g) y(g)`.  If I don't need to worry about that, then I can take that approach.

**Comment by eroux** [comment]
well, protrusion is weird yes, but it looks nice nonetheless! (some people can't do without it, some people hate it... but it's used quite often)

**Comment by henryso** [comment]
I am unclear whether that means simply boxing it to the appropriate size will be sufficient.

**Comment by eroux** [comment]
basically yes... something like

```
\setbox\protrusionbox\hbox{,}
\newprotrusiondim = \dimexpr(\comaprotrusionfactor * \wd\protrusionbox)\end
\hbox to \newprotrusiondim{,\hss}
```

(certainly contains a lot of mistakes)

**Comment by henryso** [comment]
For `,`, `;`, `:`, and `.`, a default protrusion factor of 1 would be backwards compatible.  Do we want to be backwards compatible or set them to 0, as specified earlier?

**Comment by eroux** [comment]
Usually the protrusion factor is 0 for no protrusion, so I think it's best to keep it this way. I think the most important characters are `.` and `,`, but without any visual test it's quite hard to say anything...

**Comment by henryso** [comment]
Your formula above implied that a factor of 1 meant no protrusion, but if 0 means no protrusion, then I will fully agree with that.

**Comment by henryso** [comment]
I made the changes for this against the fix-1029 branch (because I was hoping that would be merged by now), and because it basically amends the same source files to extend the gabc syntax, it's error-prone to cherry pick the changes into develop.

I see three options:
- I can wait to push these changes until 1029 is completed
- or, I can commit these changes where they are, which would include the fix-1029 branch in the pull request
- or, I can push through the error-prone cherry-pick in order to commit these directly against develop

Thoughts?

**Comment by eroux** [comment]
Thanks! I think the second options looks fine
