### ISSUE TITLE
catcode of @ for custom space files

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#942]
See [this mail](https://www.mail-archive.com/gregorio-users@gna.org/msg03349.html), when copying `gsp-default.tex` into another custom file, the catcode of `@` is problematic for the call to `gre@debugmsg`. I think `\greloadspaceconf` should make `@` a letter and then restore its previous catcode at the end of the `\input`. No emergency, can be post-4.1.

**Comment by henryso** [comment]
Since `gsp-default.tex` serves as both the default and the model for custom files, I think it makes more sense to remove the debugging from this file, but I will defer to any strong opinion.

**Comment by eroux** [comment]
ok for me!

**Comment by rpspringuel** [comment]
I agree with @henryso
