### ISSUE TITLE
first compilation of always seems to break euouae blocks

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#949]
Minimal example

```
\documentclass[12pt, a5paper]{book}
\usepackage{libertine}
\usepackage[autocompile]{gregoriotex}
\begin{document}
\gresetbreakbeforeeuouae{ragged}
\gresetbarspacing{new}
\gregorioscore{a--veni-domine-visitare-MWE}
\end{document}
```

with the gabc file:

```
name: Veni Domine visitare;
%%
(c3) Ve(e)ni,(f) Dó(h)mi(hi)ne,(i!/io> ,) *() vi(h)si(i)tá(j)re(k) nos(l) in(kj~) pa(i.)ce,(i.) (;) ut(kkoj) læ(h_i)té(k)mur(j) co(i)ram(h) te(gf__) (,) cor(e_f)de(g) per(f>)féc(e.)to(e.)  ut(kkoj) læ(h_i)té(k)mur(j) (::) <eu>E(i) u(i) o(j) u(i) a(h) e</eu>(gf) (::)
```

always breaks the score before euouae block during the first compilation (it's fixed in the second one). Commenting `\gresetbreakbeforeeuouae{ragged}` makes this problem go away.

Is it a bug or a feature? If it's a feature, I think it should be documented properly. @henryso would you have time to take a look?

**Comment by henryso** [comment]
That's the way it works, per https://github.com/gregorio-project/gregorio/issues/764#issuecomment-170018292.  Lua will emit the message indicating that a re-run is necessary and something like latexmk will actually do the re-run.  However, I will update the documentation in the user section later today.
