### ISSUE TITLE
C code issues "In" versions of bars when in wrong cases

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#953]
To finish #943 properly, there is a change needed in the C code: `(::z)` outputs `\GreInDivisioFinalis{0}{}` while it should output `\GreDivisioFinalis{0}{}` as with `(::)`. I cannot think of only one case where the current behavior would be right, it would be if there is a manual custo after the bar...

Trying this configuration `(::g+)`, it outputs

```
\GreDivisioFinalis{0}{}%
\GreEndOfElement{1}{1}%
\GreCustos{9}\GreNextCustos{9}%
```

which will certainly have a wrong output with the new bar algorithm... I cannot think about any good option for this case right now, I'll open an issue for that later, let's keep it this way (including the absence of `In`.

Anyway, @henryso would you have some time for this?

**Comment by henryso** [comment]
Should I work in fix-944 or is a new branch satisfactory?

**Comment by eroux** [comment]
it would be easier if it was on fix-944, as I cannot really test on another branch (because of bugs fixed in fix-944)

**Comment by henryso** [comment]
I made the changes and merged them into fix-944.  It seems to do what you want and certainly breaks tests, but I haven't accepted anything since you will be testing it out anyway.

**Comment by eroux** [comment]
Sure, thanks a lot!
