### ISSUE TITLE
Move Metapost code to separate file

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#956]
This is a brain-storming idea, but it occurs to me that if the meta post code was in a separate file, and one which did not have a `.tex` extension, then the `grep` command which looks for malterminated lines would return a lot fewer false positives.

A worst case senario for this would involve using `\input` commands to bring in the code from its own file.  This would, however, require a separate file for each code block (and thus might get unwieldy).

Do others think this might be a good idea?

**Comment by henryso** [comment]
What I'd rather see is a better tool for finding malterminated lines which knows to skip metapost.

**Comment by eroux** [comment]
I don't really have an opinion on this...

**Comment by eroux** [comment]
doesn't seem very important, let's close it, reopen if necessary
