### ISSUE TITLE
Lyrics sticking out into margin

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#957]
In reviewing test results looking for possible bar spacing bugs I noticed that in gabc-output/bugs/fix-928 there are lyrics which stick way out into the right hand margin on lines 3 and 8.  Is this intentional?

**Comment by eroux** [comment]
I think it is yes, at least the original tests were like that IIRC

**Comment by henryso** [comment]
For this test, this is intentional, as the purpose is to space out the neumes, but it may be indicative of a problem that we might want to look at more carefully in the future (definitely after 4.1).
