### ISSUE TITLE
Ledger line length

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#958]
The ledger lines on the first two lines of gabc-output/glyphs/ledger_lines seem to be awfully long, sticking out into the left hand margin and well beyond the notes to the right.  Are they supposed to do that?

**Comment by eroux** [comment]
Looking at the corresponding gabc, it looks perfectly normal yes

**Comment by henryso** [comment]
I confirm that the test is supposed to be doing that, as silly as it seems.
