### ISSUE TITLE
High notes and alt tex overlap

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#960]
When there are high notes (i.e. above the staff lines) and above line text in the same location, they overlap.  See gabc-ouput/heights for an example.

Should we automatically push the above line text up when this happens?  I think we can only do this at a line level right now which might look weird if the above line text and the high notes are at opposite ends of the line (and thus don't really overlap).

Or maybe a mechanism for raising a particular above lines text instance higher than it normally would be?

**Comment by eroux** [comment]
The result is:

![960](https://cloud.githubusercontent.com/assets/60868/13289005/aabc40e6-db0e-11e5-9835-4e8392ffa5f7.png)

Good point... There should be a common solution with #883. But I'm affraid that's too late for 4.1... It should be documented in the know bugs section though

**Comment by eroux** [comment]
I think a mechanism to raise above line text manually is really the best way to deal with this... but I think we can focus on other things before, marking this for 4.2
