### ISSUE TITLE
low Custos overlapping with text (edge case)

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#961]
In gabc-output/lines/2-lines, 3-lines and 5-lines the low notes an the lyrics overlap in the third line.  Is this because of they are custos, or because there's a problem with the line height calculations?

**Comment by eroux** [comment]
The result is

![961](https://cloud.githubusercontent.com/assets/60868/13289118/2e3ec344-db0f-11e5-9e1f-f3a622dd8d01.png)

I don't think it's really serious, it's probably just with custos. Something else to document in the Known bugs section of the changelog for 4.1.

**Comment by rpspringuel** [comment]
Looking at the results further, it does appear to be just with the custos and also occurs with a 2-line staff.

**Comment by henryso** [comment]
Should the height be increased if only the custos at the right of the line might overlap the text?

**Comment by rpspringuel** [comment]
If end of line shifts are enabled, then the height should change, even for an end of line custos, because then the text might overlap with a low custos (the end of line shifts are specifically designed to allow text to go under that custos).

If end of line shifts are disabled, then the text cannot go under the end of line custos, so there is no need for the height to change for it.

**Comment by eroux** [comment]
I don't have a strong opinion on this, I was thinking to consider the custos height in all cases, but it's certainly best to consider it only if it overlaps with the text yes
