### ISSUE TITLE
Glyph charts need to be updated for openqueue glyphs

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#967]

**Comment by henryso** [comment]
@eroux It would be great if you would take a look at the GregorioRef produced by my branch at https://github.com/henryso/gregorio/tree/fix-967 and let me know which new glyph (families) are missing?  For example, I know the ambitus-one longqueue flexus glyphs are missing.  Anything else you remember from #803?

**Comment by eroux** [comment]
I'll take a look tomorrow, thanks

**Comment by henryso** [comment]
@eroux Have you had time to check the charts against release-4.1?

**Comment by eroux** [comment]
A few things missing:

- PorrectusLongqueue
- PorrectusFlexusLongqueue
- Pes*Openqueue
- Flexus*Openqueue

Most of these are only for ambitus of 1

**Comment by henryso** [comment]
Did you check those against release-4.1 (after the merge earlier today)?  I believe those are in.

**Comment by eroux** [comment]
Sorry no, I looked in you "fix-267" branch indicated above. In the release-4.1 branch, I think the `*PesQuassusOpenqueue` are missing, otherwise it seems fine!
