### ISSUE TITLE
Force centering with curly brackets in syllable mode

### ISSUE THREAD

**Issue by SirPL** [gregorio-project/gregorio#968]
I have a problem with centering mode. I am using syllable centering, but in some cases I need to point out specific syllable which sould be taken to center the neume. There's an example taken from polish missal:
![polish-missal](https://cloud.githubusercontent.com/assets/11311649/13373738/21a8494e-dd70-11e5-81ba-a2204e476a42.jpg)
As you can see, all neumes are centered to syllable, but there are prepositions: "w" and "z" which are integral part of syllable (bluish highlight).
When I try to reproduce this, there's the problem: the neumes are centered to space between preposition and syllable:
`(c3) <c><sc>w</sc>.</c> I(h) z du(h)chem(h) two(h.)im.(f.) (::)`
![Syllable centering](https://cloud.githubusercontent.com/assets/11311649/13373789/5b22e7be-dd71-11e5-9bca-cdaa80b4b50f.jpg)

To get what I need I have to change centering to vowel, and use curly brackets almost everywhere. That's very uncomfortable.
`(c3) <c><sc>w</sc>.</c> {I}(h) z {du}(h){chem}(h) {two}(h.){im.}(f.) (::)`
![What I want](https://cloud.githubusercontent.com/assets/11311649/13373813/ea25d94e-dd71-11e5-90de-ba9edd869a94.jpg)

Is there any chance to get curly brackets working in syllable centering, so I would be able to use 
`(c3) <c><sc>w</sc>.</c> {I}(h) z {du}(h)chem(h) two(h.)im.(f.) (::)`
to get the same result? Thank you.

**Comment by henryso** [comment]
What is the objection to doing something like `z() du(h)chem(h)`?

Note: I am not necessarily saying you're doing anything wrong.  I'm just trying to understand the context, since I don't read or speak Polish.

**Comment by SirPL** [comment]
Yes, I forgot to write that. There are two reasons: first - the space between preposition and syllable is much wider (I don't like it, but I can accept). The main reason it that some cases there could be line break between preposition and syllable which is not acceptable (because it's like one syllable in two words).

**Comment by eroux** [comment]
Good point

**Comment by eroux** [comment]
Also, maybe elision should be working too... meaning `<e>z</e> du()` would do the same as `z {du}()`

**Comment by SirPL** [comment]
@eroux Well... <e>z</e> uses italic font, so it looks a bit... odd... :smiley:

**Comment by rpspringuel** [comment]
That behavior can be altered by changing the associated style (`elision`).

**Comment by rpspringuel** [comment]
The issue here, as I see it, is that the center determination code is on the C side but the choice of how to align the syllable and the notes is on the TeX side.  What is probably needed, therefore, is a flag (call it `\ifgre@forcedcentering`.  The C code can then insert a `\gre@forcedcenteringtrue` in a syllable when curly braces were present in the gabc (either at the front end of `#1` or as `#2` which currently isn't used).  `\GreSetThisSyllable` would then consult this flag when deciding how to fill `\gre@firstsyllablepart`, `\gre@middlesyllablepart`, and `\gre@endsyllablepart` and then reset it to `false` (to prepare for the next syllable).

If there are no objections to this strategy, I can make the TeX modifications fairly quickly.  The C mods would take longer (unless someone else wants to take that part on).

**Comment by eroux** [comment]
Sounds like a good idea!

**Comment by eroux** [comment]
There should probably be an option to deactivate this new behavior

**Comment by eroux** [comment]
@henryso how do you evaluate the difficulty of the C changes for this? Would a new boolean pointer argument to `gregorio_write_text` be enough to record the information and print it?

**Comment by henryso** [comment]
I think I should be able to do this one tonight, if @rpspringuel has not already started on it.

**Comment by eroux** [comment]
Ok perfect, thanks!

**Comment by rpspringuel** [comment]
I've done the TeX part and will push it shortly (my computer has frozen and needs to be rebooted). 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by rpspringuel** [comment]
Okay, I've pushed a forced_centering branch to the repository which does the TeX part (and fixes a bug discovered along the way).  What remains is for the C code to insert `\GreGABCForceCenters` and `\GreGABCNextForceCenters` as appropriate before the setting of the syllable text.

**Comment by rpspringuel** [comment]
@henryso, I don't have time to figure out the C part anymore this weekend.  Do you think you could take care of that?

**Comment by henryso** [comment]
I've made the change and merged it into your branch.  It seems to do what you want, but let me know if I missed something.

**Comment by eroux** [comment]
This is the last issue for 4.1.1, I think we could release it afterwards, maybe TeXLive will accept it (which would be good, quite a few bugs fixed!). @rpspringuel would you want me to finish the feature or do you have time to work on it this week-end?

**Comment by henryso** [comment]
From what I saw, this is nearly done.  If my change was correct, then this just needs a test review and perhaps a specific test to highlight the feature.

**Comment by eroux** [comment]
yes, and an little bit of doc

**Comment by henryso** [comment]
If 4.1.1 is a TeX Live candidate, I'd like to rerun coverage, valgrind, and sanitizer checks once everything is merged.

**Comment by rpspringuel** [comment]
I'm checking the existing tests to see if they provide sufficient coverage for this change now.  If they don't, then I'll create a new set of tests to do so.  I'll also work on the documentation and then upload the PR later tonight.

**Comment by rpspringuel** [comment]
@henryso, there is a problem with the change.  `\GreGABCNextForcedCenter` is being inserted into the same call of `\GreSyllable` as `\GreGABCForcedCenter`.  It should be appearing in the previous call, so that it is associated with the same syllable text in both instances.

Example, in gabc-gtex/english.gabc we have the following two syllable excerpt in the expectations:
```
\GreSyllable{\GreSetThisSyllable{n}{ie}{ce's}{n}{iece's}}{}{\GreUnstyled}{1}{\GreSetNextSyllable{q}{ueue}{}{q}{ueue}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
%
\GreSyllable{\GreSetThisSyllable{q}{ueue}{}{q}{ueue}}{}{\GreUnstyled}{1}{\GreSetNextSyllable{}{o}{f}{o}{f}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
```

Currently your change produces:
```
\GreSyllable{\GreSetThisSyllable{n}{ie}{ce's}{n}{iece's}}{}{\GreUnstyled}{1}{\GreSetNextSyllable{q}{ueue}{}{q}{ueue}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
%
\GreSyllable{\GreGABCForceCenters\GreSetThisSyllable{q}{ueue}{}{q}{ueue}}{}{\GreUnstyled}{1}{\GreGABCNextForceCenters\GreSetNextSyllable{}{o}{f}{o}{f}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
```

It should produce:
```
\GreSyllable{\GreSetThisSyllable{n}{ie}{ce's}{n}{iece's}}{}{\GreUnstyled}{1}{\GreGABCNextForceCenters\GreSetNextSyllable{q}{ueue}{}{q}{ueue}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
%
\GreSyllable{\GreGABCForceCenters\GreSetThisSyllable{q}{ueue}{}{q}{ueue}}{}{\GreUnstyled}{1}{\GreSetNextSyllable{}{o}{f}{o}{f}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
```

**Comment by rpspringuel** [comment]
@henryso, there is a problem with the change.  `\GreGABCNextForcedCenter` is being inserted into the same call of `\GreSyllable` as `\GreGABCForcedCenter`.  It should be appearing in the previous call, so that it is associated with the same syllable text in both instances.

Example, in gabc-gtex/english.gabc we have the following two syllable excerpt in the expectations:
```
\GreSyllable{\GreSetThisSyllable{n}{ie}{ce's}{n}{iece's}}{}{\GreUnstyled}{1}{\GreSetNextSyllable{q}{ueue}{}{q}{ueue}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
%
\GreSyllable{\GreSetThisSyllable{q}{ueue}{}{q}{ueue}}{}{\GreUnstyled}{1}{\GreSetNextSyllable{}{o}{f}{o}{f}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
```

Currently your change produces:
```
\GreSyllable{\GreSetThisSyllable{n}{ie}{ce's}{n}{iece's}}{}{\GreUnstyled}{1}{\GreSetNextSyllable{q}{ueue}{}{q}{ueue}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
%
\GreSyllable{\GreGABCForceCenters\GreSetThisSyllable{q}{ueue}{}{q}{ueue}}{}{\GreUnstyled}{1}{\GreGABCNextForceCenters\GreSetNextSyllable{}{o}{f}{o}{f}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
```

It should produce:
```
\GreSyllable{\GreSetThisSyllable{n}{ie}{ce's}{n}{iece's}}{}{\GreUnstyled}{1}{\GreGABCNextForceCenters\GreSetNextSyllable{q}{ueue}{}{q}{ueue}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
%
\GreSyllable{\GreGABCForceCenters\GreSetThisSyllable{q}{ueue}{}{q}{ueue}}{}{\GreUnstyled}{1}{\GreSetNextSyllable{}{o}{f}{o}{f}}{}{0}{}{%
\GreGlyph{\GreCPPunctum}{9}{9}{0}%
{%
\GreGlyphHeights{9}{9}%
}{}{}%
}%
```

**Comment by henryso** [comment]
OK, I misunderstood the change.  I will fix it tonight.

**Comment by henryso** [comment]
Ok, that should be fixed now.
