### ISSUE TITLE
Should "install" from the fonts Makefile depend on the fonts?

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#97]
Currently, the .ttf fonts are built from the .sfd files in the fonts directory and then are committed into the repository.  This is fine because only someone working on the fonts would be modifying them.  That person would then presumably commit the generated fonts.

However, if someone clones the repository from scratch, chances are the time stamps on the .sfd files will be the same or newer than the timestamps on the .ttf files.  Someone running make install just to install the files into their TeX directory will then be forced to rebuild the .ttf files.  It also means that the person installing Gregorio must have python, fontforge, and the python fontforge bindings.

The cleaner solution would be to have two Makefiles.  One in the fonts directory, whose only purpose is to make fonts, and one in some other directory, whose purpose is to install the GregorioTeX files.  This latter Makefile would fail if, for some reason, the .ttf files are missing, but it would not try to rebuild them at that point.

Alternately, we can rejig the current fonts Makefile to have two targets: one for creating fonts and one for installing GregorioTeX.  This gets a bit messy (and is why I say the previous is cleaner) because the "make the fonts" target needs the sfd-to-ttf dependency while the "install" target must not have it lest the fonts be rebuilt unnecessarily.

I suppose there is a third option: add `touch *.ttf` after `cd fonts` in the installation instructions to be sure they have a later timestamp than the .sfd files.

I can make the Makefile changes and submit a pull request once we decide if/how we want to handle this.

**Comment by rpspringuel** [comment]
Could we modify the project root Makefile to have it install the GregorioTeX files (without building the fonts)?  It's always seemed a bit odd to me that I have to do `make install` twice, but I don't know enough about these things to know if it's necessary or not.

If the project root Makefile can install the GregorioTeX files, then as you suggest the Makefile in the fonts directory could be dedicated to building the fonts.

In this option we wouldn't be creating a new Makefile, just moving functionality from one (the fonts) to the other (the root).

**Comment by henryso** [comment]
The Makefile at root is actually a generated Makefile that is created by way of autotools.  Autotools is a set of programs that make it easier to generate the configure script and data files for the configure script.  Upon running the configuration script, the Makefile and various other files may be created.  It's sort of meta-meta-meta programming.  This is why it's autoreconf/configure/make/make install to install from git.

The idea is that the developer uses autotools (autoreconf) to generate a set of source files that they distribute distribute (i.e., as a tarball).  The user takes the source code and runs configure to tailor it to build on their particular system.  This generates things like Makefiles.  Then make uses the Makefiles to build and make install uses the Makefiles to install.

The thing is, autotools was really designed for building software: binaries, libraries, man pages, data files, and documentation -- not so much for installing TeX libraries.  I think this is why it was done this way.  While it may be possible to get autotools to generate the right stuff into the Makefile.in to install TeX, it's probably not worth the effort.  When it comes down to it, installing Gregorio is effectively installing two software packages: the Gregorio application and GregorioTeX.  This is why I didn't included installing GregorioTeX via the "root" Makefile as one of the options.

**Comment by rpspringuel** [comment]
Now that you've explained it that way, things make more sense.

What about doing the install of the GregorioTeX files with a simple shell script rather than a Makefile?  As far as I know, when it comes to installing TeX packages, all that's really necessary is that the files be placed in the right place (a set of copy commands) and that texhash be run afterwards (to update TeX's pointers to account for the new/changed files).  Is there any reason that this couldn't be done with a normal shell script rather than a Makefile?

Developing that idea further, on my own system I've written a shell script which goes through all the steps necessary for an install.  Could this be done in a more universal way so that installation is as easy as running a single shell script?  If it can, then this sort of shell script could be the vehicle for installing the GregorioTeX files.

**Comment by henryso** [comment]
A shell script would work.  Should I put the shell script in the root?  It seems kind of funny to put it in fonts.

**Comment by henryso** [comment]
Regarding the install-everything shell script, I actually wouldn't do that (at least not yet).  Depending on your system, you may want/need to change something.  Not all distributions are set up to let you do "sudo make install", and you may not want to install to /usr.

**Comment by rpspringuel** [comment]
My personal script doesn't use sudo within the script itself (a bad idea because it requires one to be around to enter the root password when that step is reached) but rather relies on me to run the script as a whole with sudo.  Wouldn't that make the script usable by someone who doesn't run the install step as a sudo command?

Also, the configuration options could be handled with optional arguments to the script, couldn't they?  Sure, it would probably make things more complicated as one has to write code which processes the options and passes them to configure, but surely that's possible?

Anyway, even if it's just a script to do the TeX installation steps, I would put it in root.  That eliminates the need to change directory and keeps the process as simple as possible.

**Comment by henryso** [comment]
I think it's generally encouraged that you do no more than necessary when escalating privileges, which is why most build-from-source instructions involve "make; sudo make install".  I happen to be one of those paranoid people who like this practice.

I am going to create the script to install the GregorioTeX portion in root.

In terms of the install-everything script, I think it requires more thought and possibly more discussion.  There are plenty of options including:

* a really fancy script which parses options and passes the appropriate things to the various steps
* a simpler script which takes a more limited set of options
* a really simple script which does takes no options, installing using default options only
* a driver script which clones the repository, builds, and installs
* (of course) no install-everything script

There are pros and cons to each (even "no install-everything script") in terms of how to describe the install process to an end-user.  There are also repercussions as to how the documentation (on the website and elsewhere) needs to describe the script.

The really fancy script would be able to do everything needed for installation, but would require a similar up-front level of documentation so that users unprepared to study how the script works know how to change the options they want changed.

The really simple script is easy to describe and to look at.  If you want the defaults, just use it.  If not, it's easy to modify.  If we use this though, we might still want to include the fully-manual build instructions at the risk of some confusion.

The "simpler" script is somewhere in between, needing a bit more documentation, but hopefully still being readable.  This compromises both the pros and the cons of the either of the previous approaches.

The driver script does everything, not even requiring the repository to be cloned manually.  However this script is likely to be complex (both to code and to use) and probably needs even more thorough documentation than the "really fancy" script.

Finally, for "no install-everything script", the instructions would remain similar to what they are now.  People used to building software themselves would immediately recognize autotools and make.  Users who are not so familiar would use the exact instructions.

If I had to choose an option (other than "no script"), at this point, I'd probably go for the really simple script, which basically does what the instructions say, in order.

**Comment by eroux** [comment]
Just a possibility (not entirely sure it's a good one), there a build.sh script, maybe it could get a --install option? But that would be a bit weird to 

    build.sh
    sudo build.sh --install

so I'm not sure it's the best design...

**Comment by henryso** [comment]
Going down that same route, how about two scripts?

```
build.sh
sudo install.sh
```

build.sh could take arguments for configure.  install.sh could take arguments for GregorioTeX destination directory.  I know that's not exactly consistent, because you are essentially passing build.sh the install directory for Gregorio and install.sh the install directory for GregorioTeX, but that's the way autotools generated builds go.

**Comment by eroux** [comment]
ok, we can go in that direction

**Comment by henryso** [comment]
As I sat down to start this, I noticed that there is already a build.sh file.  Where is this used?  Who or what uses this script?  If it's still in use, I will come up with some other name for the "new" build script per this thread.

**Comment by rpspringuel** [comment]
I know it gets used when building the Windows binaries.  Beyond that, I'm not sure.

**Comment by henryso** [comment]
That's a good enough reason to leave it alone.  Maybe I'll use `git-build.sh` and `git-install.sh`.

**Comment by eroux** [comment]
I'm using build.sh to get the good arguments to configure for cross-compiling to windows, the other thing it does is to run `autoreconf -f -i`, which can be useful. Such a script is quite common, here it's tiny, but if you take a look at LuaTeX build.sh, it does many things. I'm not sure there needs to be a different one, build.sh can perfectly do other things with fonts, etc.

**Comment by henryso** [comment]
I'm not sure if I'm missing something, but the existing build.sh does not appear to run autoreconf.  I think it's probably best for me to create two additional scripts in root as I mentioned "a day ago" (that's what github says...).  I'll keep it simple for now; almost just a list of commands to run when building from git.  We can refine/polish/remove this as time goes on.

**Comment by eroux** [comment]
it doesn't, indeed, but I believe it should...

**Comment by rpspringuel** [comment]
If `build.sh` is meant to build from the repository, then I agree with @eroux.

**Comment by henryso** [comment]
I think we need to be able to pass arbitrary arguments into configure, so I will add that feature and autoreconf to the script.  Then I will get rid of the (newly birthed git-build.sh) and rename git-install.sh to install.sh.

**Comment by henryso** [comment]
I believe I've made all the changes at this point in #110.  However, I am unable to test compiling and cross-compiling for windows using build.sh.  Please let me know if there's anything I messed up and should fix.

**Comment by henryso** [comment]
Made the change suggested by @eroux in #110.

**Comment by henryso** [comment]
Closed since #110 was merged.
