### ISSUE TITLE
interwordspacetext not taken into account for bars

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#978]
With the following example:

```tex
\documentclass[11pt]{article} % use larger type; default would be 10pt
\usepackage{fontspec}
\usepackage{graphicx}
\usepackage{geometry}
\geometry{a4paper}
\usepackage{gregoriotex}
\usepackage{libertine}
\begin{document}
\gresetbarspacing{new}
\gresetlastline{ragged}
\gresetinitiallines{0}
\gabcsnippet{(c3) am<v>\hbox to 0pt{\hss\rule{0.1mm}{3mm}}</v>(g) <v>\hbox to 0pt{\rule{0.1mm}{3mm}\hss}</v>E(g.) am<v>\hbox to 0pt{\hss\rule{0.1mm}{3mm}}</v>(g) (::) <v>\hbox to 0pt{\rule{0.1mm}{3mm}\hss}</v>E(j)}
\end{document}
```

I get

![bugbars](https://cloud.githubusercontent.com/assets/60868/13396735/8ac823cc-def6-11e5-8f8f-1e82bda57b77.png)

in which the space between 'am' and 'E' seems to be less than `interwordspacetext` (between the texts of the syllables around the bar)... @rpspringuel do you have time to inspect that? (this is quite high priority)

**Comment by rpspringuel** [comment]
This behavior is because `interwordspacetext@bars` (0.15cm) is smaller than `interwordspacetext` (0.38cm) to the point that the spacing around the bar is becoming the requirement that has to be met.  Indeed, `interwordspacetext` is not utilized at all in calculating the spacing for a bar syllable.  Do you want me to institute a floor on the require space for the text equal to `interwordspacetext`?

**Comment by eroux** [comment]
Thanks for inspecting! Well, I admit I'm a bit puzzled... In this case, `interwordspacetext` is definitely a better value than `interwordspacetext@bars`, but maybe there should be an even higher value, maybe a new `interwordspacetext@bars@notext`? Looks like the most logical option here...

**Comment by eroux** [comment]
(Just to be clear, this new `interwordspacetext@bars@notext` should be used instead of `interwordspacetext@bars` when there is no text associated with the bar)

**Comment by eroux** [comment]
Thinking back about it, I think `interwordspacetext@bars` and `interwordspacetext@bars@notext` should probably be set on a per-bar-type basis... Does that sound reasonable?

**Comment by eroux** [comment]
Well, the per-bar-type interwordspacetext will be for 5.0 I guess, the change would be too big...

**Comment by rpspringuel** [comment]
I'm working on implementing this and should have something posted in an hour or so.

For 5.0, I would not make this dependent on bar type.  The spacing around the bar itself is already dependent on bar type.  This has to do with the text, not the bar.

**Comment by eroux** [comment]
Thanks a lot! Well, I thought like you at the beginning but if you take (admittedly extreme) cases like `testtttttttttttttttttttttttt(g) (,) g(g)` and `testtttttttttttttttttttttttt(g) (::) g(g)` I think it would be normal that the second case have more space between the text of the two syllables... isn't it?
