### ISSUE TITLE
Overfull line

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#979]
gabc-output/glyphs/clefs, page 8, second to last line runs out into the right hand margin:

![temp](https://cloud.githubusercontent.com/assets/7671682/13399227/3de24658-ded0-11e5-9af6-3a4a41925421.png)

**Comment by eroux** [comment]
I think that's a "feature", it's likely that there is no way for TeX to cut the lines correctly, so I think it can be closed as "wontfix" (or at least be considered super-low priority)
