### ISSUE TITLE
Inconsistent <alt> height

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#98]
Compile this with lualatex --shell-escape --halt-on-error mwe.tex

###### mwe.tex

```
\documentclass[11pt]{article}
\usepackage{luatextra}
\usepackage{graphicx}
\usepackage{gregoriotex}
\usepackage[utf8]{luainputenc}
\usepackage{times}
\begin{document}
\includescore{mwe}
\end{document}
```

###### mwe.gabc

```
initial-style: 0;
%%
(c4) Test(cd) test (cd)
<alt>Alt</alt> (:) Test(cd) test (cd)
<alt>Alt</alt>(:) Test(cd) test (cd)
(:) <alt>Alt</alt>Test(cd) test (cd) (::)
```

###### output

Note that the heights of the "Alt" are different.

![mwe](https://cloud.githubusercontent.com/assets/421318/6702048/bafc04ea-ccfb-11e4-9c4f-da010b496e28.png)

**Comment by rpspringuel** [comment]
@henryso do you happen to know if this bug predates the changes to the spacing modifications or only shows up after them?  If not, I'll do some testing to figure that out, but if you do know that will help narrow down what I have to look at.

**Comment by henryso** [comment]
If I checkout the v2.4.2 tag, all three "Alt" appear all at the same height.

**Comment by rpspringuel** [comment]
Fix being pushed.
