### ISSUE TITLE
There should be a \GreLastOfLine-like macro in the syllable before an EUOUAE

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#988]
See https://github.com/gregorio-project/gregorio/issues/984#issuecomment-190784677

This macro should use the same calculation as to whether the `\gre@newlinecommon{1}` is inserted in `\GreBeginEUOUAE` to determine whether it should call `\GreLastOfLine`

**Comment by eroux** [comment]
I think this could be done easily: the C code could insert a `\GreLastSyllableBeforeEUOUAE` at the place where it inserts `\GreLastOfLine`, and this could transform into `\GreLastOfLine` in appropriate cases...

**Comment by henryso** [comment]
Yes, that's what I was thinking, but I did not have time last night to start working on it.

**Comment by eroux** [comment]
Sure, I'm just trying to evaluate the work needed for 5.0. I think it should be much lighter than 4.1... but I have the feeling I always think that...

**Comment by rpspringuel** [comment]
They always start that way, and then something snowballs into a much more complicated or bigger feature than expected.

**Comment by eroux** [comment]
Indeed... the new bar spacing algorithm was something I wanted to do in 4.0 but didn't have time though, so I knew it would be quite big... I admit i've been surprised by the stem length feature, but I only got positive feedback so far, so chances are that there won't be the need for further work on this... and we get less and less reports... we'll see...

**Comment by henryso** [comment]
This is probably not the best place to discuss this, but since we're on the topic...  There is only one deprecation (initial-style) in 4.1, so it would be possible to make the next release 4.2 as long we hold back the removal of that feature.  Something to consider which would give people more than a month or so to upgrade their scores to cope with this removal.

**Comment by eroux** [comment]
That's probably a good idea yes
