### ISSUE TITLE
Macros in wrong name space?

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#989]
I'm running `doc_check.sh` and `def_check` on the code base to make sure everything is kosher and I've come across a bunch of macros defined in TeX in the `Gre` namespace (i.e. macros expected to appear in gtex files) but which I cannot determine how they get generated by gregoriotex-write.c.  Can some one enlighten me as to how they are possibly generated or confirm they are in the wrong name space?

- GreDrawAdditionalLine
- GreForceBreak
- GreForceHyphen
- GreNoBreak
- GreOverBrace
- GreOverCurlyBrace
- GreSlur
- GreTilde
- GreUnderBrace
- GreVarBraceLength
- GreVarBraceSavePos
- GreZeroHyph

**Comment by henryso** [comment]
GreForceBreak, GreTilde, and GreZeroHyph are not generated (no longer generated?) by the C code.  All the other ones are generated as texverbs during score/note determination.

**Comment by rpspringuel** [comment]
Okay, well since `\GreForceBreak` is a counterpart to `\GreNoBreak` I'll leave it in the `Gre` namespace despite the fact that it currently isn't written into gtex files.

`\GreTilde` is a special character, are there objections to moving it into the user namespace?

`\GreHyph` aliases to `\GreZeroHyph` under some circumstances.  The other options have already been moved into the internal name space, so I'll move this one as well.

**Comment by henryso** [comment]
I'm fine with your decisions.

**Comment by rpspringuel** [comment]
Addressed in #992
