### ISSUE TITLE
New bar spacing algorithm pushes custos into margin

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#990]
I was going through the process of making the new algorithm the default and found this during the test review:

![temp](https://cloud.githubusercontent.com/assets/7671682/13435670/64515c14-dfa9-11e5-90f6-934f5315c93f.png)

The test is tex-output/bugs/fix-43.

**Comment by eroux** [comment]
Interesting... this kind of case shouldn't happen often... but of course, it should be handled correctly, thanks for noticing! I really cannot work more today, I'm not really sure what's best... but if it's the only bug, I think we can still make the new algorithm the default.
