### ISSUE TITLE
C code should write the type of bar in GreBarSyllable

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#995]
This could be done with a `GreSyllableBarType{xxx}` in the `#5` of GreBarSyllable. The values would be the same used in `gsp-default.tex` (`virgula`, `minima`, etc.). This will allow some further tuning of spaces.

**Comment by henryso** [comment]
Should I just create a stub macro for `\GreSyllableBarType`?

**Comment by rpspringuel** [comment]
I'm not sure what @eroux had in mind, but wouldn't it be simpler to simply make `#2` (which is currently unused) of `\GreBarSyllable` be the string name of the bar?  Then we could just put that argument inside of `\csname` when we need to pick a distance based on the bar type.

**Comment by henryso** [comment]
Since this is the most parameter-hungry macro we have, I think @eroux may be suggesting to have `\GreSyllableBarType` define an internal macro with the bar type.  I don't have any particular opinion on how to go forward, but keep in mind that:

1. `\Gre*Syllable` is the most parameter-hungry macro we have
2. The C code that generates these is the same, so using `#2` for `\GreBarSylalble` makes it more difficult to use `#2` for something else in `\GreSyllable`.

**Comment by eroux** [comment]
Agreed, I think `\GreBarSyllableType` is better than `#2` (seems I'm quite predictable!)

**Comment by henryso** [comment]
So, back to my original question: Should I just create a stub macro for `\GreBarSyllableType` until someone can adopt it for tuning spaces?

**Comment by eroux** [comment]
Oh, sorry I didn't realize that was the original question: yes definitely!

**Comment by henryso** [comment]
I'm a little confused. `#5` is for typesetting the text of the *next* syllable.  Should `\GreBarSyllableType` be emitted on the bar syllable itself (and indicate the type of "this" bar syllable) or should it be emitted on the syllable before a bar syllable (and indicate the type of the bar syllable that follows)?

**Comment by eroux** [comment]
Sorry, I was confused, `#5` is definitely not the best place for this... I think it's OK in `#9`, as it will be evaluated at the beginning to compute the width of the notes.

**Comment by henryso** [comment]
Can you confirm that this should be emitted on the `\GreBarSyllable` for the `\GreBarSyllable`'s bar type itself?

**Comment by eroux** [comment]
I'm not entirely sure I understand the question, but I've just realized that there's an obvious way to do it in pure TeX!!! Sorry, it didn't cross my mind earlier...

**Comment by henryso** [comment]
Ok, so I should not push my changes for this, correct?

**Comment by eroux** [comment]
no need, sorry for wasting your time :(

**Comment by henryso** [comment]
You might want to change the title of this issue or close if it no longer applies.
