### ISSUE TITLE
TeXWorks gabc syntax hightlight configuration

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#996]
Adding

```
[Gabc]

# notes
tomato	N	\([^\)]*\)

# headers
darkblue	N	[^\(:]+:.*;

# comments
gray			Y	%.*
```

to `~.TeXworks/configuration/syntax-patterns.txt` adds an entry in the *Format* -> *Syntax Highlighting* menu for gabc file. It's not that useful because users have to select it manually or make it the default, but it might be useful to some, so I think it should be documented somewhere...

**Comment by eschwab** [comment]
Perhaps on the TeXWorks configuration website page?

**Comment by eroux** [comment]
Sure, would you have time to make a pull request for that?

**Comment by rpspringuel** [comment]
Solved in gregorio-project/gregorio-project.github.io#30
