### ISSUE TITLE
Sorting Future Work

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio#997]
Sparked by the comment of @henryso in #988, I've created two new milestones: 4.1.1 and 4.2 so that we can better sort the work we have planned and thus decide what sort of release schedule we want to follow.  I don't have time at the moment to reassess any of the current milestones (which all point to 5.0) but if everyone takes a look at what they're thinking about as they work, we should have things sorted out fairly quickly.

**Comment by henryso** [comment]
Given @eroux's contacts, I think it's probably best for him to decide the priority, which I think should be based on what is needed first and be tempered by the effort necessary.

**Comment by eroux** [comment]
According to my contacts, the most urgent things would be:

- #972 (but I think it's included into #898), that's quite important for Solesmes, certainly the biggest change
- #984
- #960
- #994 would also be very useful to understand and tune spacings, and it's very simple so I think we can do it soon too
- #968 has been asked twice recently so I think it's important too, Br. Innocent will certainly need it for an important project
- we can certainly also fix easy bugs such as #955, #987, #988 and #995, but these should not block the release

I'll put these in the 4.1.1 milestone, and I'll take a few ones.

These are the most urgent, the next ones would be
- #990 
- #959 which is a very big change, so quite risky if we want to release soon
- #961

**Comment by eroux** [comment]
If there are no further comments, maybe we can close this issue?
